### ISSUE TITLE
[extensions] not working after db optimization

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#1075]
```
syndesis-rest-2-jfwd2 syndesis-rest 2018-01-16 09:42:31.815  WARN [-,,,] 1 --- [ool-12-thread-1] io.syndesis.jsondb.impl.SqlJsonDB        : fetchIdsByPropertyValue failed: Index not defined for:  collectionPath: /extensions, property: status
syndesis-rest-2-jfwd2 syndesis-rest Exception in thread "pool-12-thread-1" java.lang.UnsupportedOperationException: Index not defined for:  collectionPath: /extensions, property: status
syndesis-rest-2-jfwd2 syndesis-rest 	at io.syndesis.jsondb.impl.SqlJsonDB.fetchIdsByPropertyValue(SqlJsonDB.java:247)
syndesis-rest-2-jfwd2 syndesis-rest 	at io.syndesis.jsondb.dao.JsonDbDao.fetchIdsByPropertyValue(JsonDbDao.java:88)
syndesis-rest-2-jfwd2 syndesis-rest 	at io.syndesis.dao.manager.DataManager.lambda$fetchIdsByPropertyValue$2(DataManager.java:256)
syndesis-rest-2-jfwd2 syndesis-rest 	at io.syndesis.dao.manager.DataManager.doWithDataAccessObject(DataManager.java:372)
syndesis-rest-2-jfwd2 syndesis-rest 	at io.syndesis.dao.manager.DataManager.fetchIdsByPropertyValue(DataManager.java:246)
syndesis-rest-2-jfwd2 syndesis-rest 	at io.syndesis.dao.extension.ExtensionDataManager.getInstalledPhysicalId(ExtensionDataManager.java:48)
syndesis-rest-2-jfwd2 syndesis-rest 	at io.syndesis.dao.extension.ExtensionDataManager.getExtensionBinaryFile(ExtensionDataManager.java:40)
syndesis-rest-2-jfwd2 syndesis-rest 	at io.syndesis.project.converter.DefaultProjectGenerator.addExtensions(DefaultProjectGenerator.java:221)
syndesis-rest-2-jfwd2 syndesis-rest 	at io.syndesis.project.converter.DefaultProjectGenerator.lambda$generateAddProjectTarEntries$0(DefaultProjectGenerator.java:180)
syndesis-rest-2-jfwd2 syndesis-rest 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
syndesis-rest-2-jfwd2 syndesis-rest 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
syndesis-rest-2-jfwd2 syndesis-rest 	at java.lang.Thread.run(Thread.java:748)
```

found in logs at integration provision time.

@nicolaferraro does this trigger any idea?

**Comment by zregvart** [comment]
@paoloantinori I think you might need to reset your DB if that doesn't help we're probably looking at an issue introduced by #960

**Comment by paoloantinori** [comment]
I have just reprovisioned everything, I don't think it's a db issue.

**Comment by nicolaferraro** [comment]
I don't know what is the actual issue, but the annotation:
```
+@UniqueProperty(value = "extensionId", groups = UniquenessRequired.class)
```

seems wrong to me. Extensions with same `extensionId` are allowed to be present in the DB. It's the basis for doing upgrade and rollback.
