### ISSUE TITLE
 String "Activated": value not one of declared Enum instance names: [Draft, Active, Pending, Error, Inactive, Undeployed]

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#1172]
Got error activating a deployment.

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type io.syndesis.model.integration.IntegrationDeploymentState from String "Activated": value not one of declared Enum instance names: [Draft, Active, Pending, Error, Inactive, Undeployed]
 at [Source: io.undertow.servlet.spec.ServletInputStreamImpl@7fbb3b54; line: 394, column: 20] (through reference chain: io.syndesis.model.integration.Integration$Builder["desiredStatus"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:74) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1410) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:926) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:189) ~[jackson-databind-2.8.10.jar!/:2.8.10]
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:126) ~[jackson-databind-2.8.10.jar!/:2.8.10]
```

**Comment by chirino** [comment]
This seem to help me work around the issue:

```
diff --git a/app/ui/src/app/store/integration/integration.store.ts b/app/ui/src/app/store/integration/integration.store.ts
index 80b817b71..d739def49 100644
--- a/app/ui/src/app/store/integration/integration.store.ts
+++ b/app/ui/src/app/store/integration/integration.store.ts
@@ -24,13 +24,13 @@ export class IntegrationStore extends AbstractStore<
 
   public activate(i: Integration) {
     const _i = JSON.parse(JSON.stringify(i));
-    _i.desiredStatus = 'Activated';
+    _i.desiredStatus = 'Active';
     return this.update(_i);
   }
 
   public deactivate(i: Integration) {
     const _i = JSON.parse(JSON.stringify(i));
-    _i.desiredStatus = 'Deactivated';
+    _i.desiredStatus = 'Inactive';
     return this.update(_i);
   }
```

**Comment by gashcrumb** [comment]
Think @iocanel addressed this, closing...
