### ISSUE TITLE
[UI]  Angular, resolution error in `IntegrationListComponent`

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#1196]
```
ERROR Error: Uncaught (in promise): Error: Can't resolve all parameters for IntegrationListComponent: ([object Object], [object Object], [object Object], [object Object], [object Object], [object Object], ?).
Error: Can't resolve all parameters for IntegrationListComponent: ([object Object], [object Object], [object Object], [object Object], [object Object], [object Object], ?).
    at syntaxError (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:169198:34) [angular]
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver._getDependenciesMetadata (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:183285:35) [angular]
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver._getTypeMetadata (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:183153:26) [angular]
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNonNormalizedDirectiveMetadata (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:182748:24) [angular]
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.loadDirectiveMetadata (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:182610:25) [angular]
    at https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:194337:72 [angular]
    at Array.forEach (<anonymous>) [angular]
    at https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:194336:72 [angular]
    at Array.forEach (<anonymous>) [angular]
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:194333:75) [angular]
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:194303:36) [angular]
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:194232:37) [angular]
    at ModuleBoundCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.ModuleBoundCompiler.compileModuleAsync (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:194632:31) [angular]
    at https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:201049:60 [angular]
    at syntaxError (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:169198:34) [angular]
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver._getDependenciesMetadata (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:183285:35) [angular]
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver._getTypeMetadata (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:183153:26) [angular]
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNonNormalizedDirectiveMetadata (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:182748:24) [angular]
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.loadDirectiveMetadata (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:182610:25) [angular]
    at https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:194337:72 [angular]
    at Array.forEach (<anonymous>) [angular]
    at https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:194336:72 [angular]
    at Array.forEach (<anonymous>) [angular]
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:194333:75) [angular]
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:194303:36) [angular]
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:194232:37) [angular]
    at ModuleBoundCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.ModuleBoundCompiler.compileModuleAsync (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:194632:31) [angular]
    at https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:201049:60 [angular]
    at resolvePromise (https://syndesis.192.168.42.52.xip.io/polyfills.bundle.js:6334:17) [angular]
    at https://syndesis.192.168.42.52.xip.io/polyfills.bundle.js:6411:17 [angular]
    at Object.onInvokeTask (https://syndesis.192.168.42.52.xip.io/vendor.bundle.js:199268:33) [angular]
    at <anonymous> [<root>]
defaultErrorLogger @ core.es5.js:1020
webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ core.es5.js:1080
next @ core.es5.js:4503
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
(anonymous) @ core.es5.js:3912
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:365
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:125
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.runOutsideAngular @ core.es5.js:3844
onHandleError @ core.es5.js:3912
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:369
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runGuarded @ zone.js:141
_loop_1 @ zone.js:604
drainMicroTaskQueue @ zone.js:613
Promise resolved (async)
scheduleQueueDrain @ zone.js:552
scheduleMicroTask @ zone.js:560
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:387
onScheduleTask @ zone.js:274
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:378
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:209
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:229
scheduleResolveOrReject @ zone.js:758
resolvePromise @ zone.js:707
(anonymous) @ zone.js:638
webpackJsonpCallback @ bootstrap cd71ce42da5903f5bd8c:21
(anonymous) @ 1.chunk.js:1
```

in console, in homepage

**Comment by paoloantinori** [comment]
![screenshot from 2018-01-24 12-19-52](https://user-images.githubusercontent.com/1520602/35329647-eda760d8-0100-11e8-925b-9f6a0ea6b7b2.png)


No output
