### ISSUE TITLE
bad SQL grammer on parameterized integer field

### ISSUE THREAD

**Issue by igarashitm** [syndesisio/syndesis#1366]
Possibly the integer value is also single quoted?
#### SQL
```sql
INSERT INTO TODO (TASK, COMPLETED) VALUES (:#TASK, :#COMPLETED)
```
#### Error
```
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: column "completed" is of type integer but expression is of type character varying
--
  | Hint: You will need to rewrite or cast the expression.
  | Position: 48
  | at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:231) ~[spring-jdbc-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
  | at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73) ~[spring-jdbc-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
  | at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649) ~[spring-jdbc-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
  | at org.apache.camel.component.sql.SqlProducer.process(SqlProducer.java:116) ~[camel-sql-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.connector.ConnectorProducer.process(ConnectorProducer.java:45) ~[camel-connector-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:67) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at io.syndesis.integration.runtime.SyndesisLoggingSupport.lambda$null$3(SyndesisLoggingSupport.java:109) ~[integration-runtime-1.2-SNAPSHOT.jar!/:1.2-SNAPSHOT]
  | at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:76) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:67) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at io.syndesis.integration.runtime.OutMessageCaptureInterceptStrategy.lambda$wrapProcessorInInterceptors$0(OutMessageCaptureInterceptStrategy.java:53) ~[integration-runtime-1.2-SNAPSHOT.jar!/:1.2-SNAPSHOT]
  | at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:76) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.twitter.consumer.DefaultTwitterConsumer.poll(DefaultTwitterConsumer.java:98) [camel-twitter-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101) [camel-core-2.20.1.jar!/:2.20.1]
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
  | at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_151]
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
  | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_151]
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
  | at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
  | Caused by: org.postgresql.util.PSQLException: ERROR: column "completed" is of type integer but expression is of type character varying
  | Hint: You will need to rewrite or cast the expression.
  | Position: 48
  | at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455) ~[postgresql-9.4.1212.jre7.jar!/:9.4.1212.jre7]
  | at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155) ~[postgresql-9.4.1212.jre7.jar!/:9.4.1212.jre7]
  | at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288) ~[postgresql-9.4.1212.jre7.jar!/:9.4.1212.jre7]
  | at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430) ~[postgresql-9.4.1212.jre7.jar!/:9.4.1212.jre7]
  | at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356) ~[postgresql-9.4.1212.jre7.jar!/:9.4.1212.jre7]
  | at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168) ~[postgresql-9.4.1212.jre7.jar!/:9.4.1212.jre7]
  | at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:157) ~[postgresql-9.4.1212.jre7.jar!/:9.4.1212.jre7]
  | at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar!/:1.4]
  | at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar!/:1.4]
  | at org.apache.camel.component.sql.SqlProducer$2.doInPreparedStatement(SqlProducer.java:161) ~[camel-sql-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.sql.SqlProducer$2.doInPreparedStatement(SqlProducer.java:116) ~[camel-sql-2.20.1.jar!/:2.20.1]
  | at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633) ~[spring-jdbc-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
  | ... 35 common frames omitted

**Comment by KurtStam** [comment]
@igarashitm - can you the steps to create the integration? I will need to step this through to figure out why the type is changed to varchar.

**Comment by KurtStam** [comment]
@igarashitm The datamapper let's you wire up fields of different type. What will do the casting of these types?

**Comment by KurtStam** [comment]
`{"componentScheme":"sql","connectorCustomizers":["io.syndesis.connector.sql.customizer.SqlConnectorCustomizer"],"inputDataShape":{"kind":"json-schema","type":"SQL_PARAM_IN","specification":"{\"type\":\"object\",\"$schema\":\"http://json-schema.org/schema#\",\"title\":\"SQL_PARAM_IN\",\"properties\":{\"task\":{\"type\":\"string\",\"required\":true},\"COMPLETED\":{\"type\":\"integer\",\"required\":true}}}"},"outputDataShape":{"kind":"json-schema","type":"SQL_PARAM_OUT","specification":"{\"type\":\"object\",\"$schema\":\"http://json-schema.org/schema#\",\"title\":\"SQL_PARAM_OUT\"}"},"propertyDefinitionSteps":[{"description":"Enter a SQL statement that starts with INSERT, SELECT, UPDATE or DELETE.","name":"SQL statement","properties":{"query":{"defaultValue":"INSERT INTO TODO ( task, completed ) VALUES ( :#task, :#COMPLETED)","deprecated":false,"description":"SQL statement to be executed. Can contain input parameters prefixed by ':#' i.e. ':#MYPARAMNAME'","displayName":"SQL statement","group":"common","javaType":"java.lang.String","kind":"path","required":true,"secret":false,"type":"string","enum":[{"label":"query","value":"INSERT INTO TODO ( task, completed ) VALUES ( :#task, :#COMPLETED)"}]}}}]}`

**Comment by KurtStam** [comment]
@igarashitm any update on this?

**Comment by igarashitm** [comment]
Unfortunately I haven't had time to look into again. Hopefully I have this week.
