### ISSUE TITLE
Metrics Collector in unit tests try to access an OpenShift cluster

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#1398]
Happens on `mvn install`: 

```
22:42:03.251 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$52fecfd5] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
22:42:03.759 [main] INFO  o.s.boot.SpringApplication -
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.8.RELEASE)


22:42:05.259 [pool-5-thread-1] ERROR i.s.r.m.collector.MetricsCollector - Error while iterating integration pods.
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Pod]  with name: [null]  in namespace: [myproject]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:585)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:68)
	at io.syndesis.rest.metrics.collector.MetricsCollector.run(MetricsCollector.java:97)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Network is unreachable (connect failed)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:124)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:223)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
```

@KurtStam please fix this and e.g. disable the MetricsCollector for the "unit tests" which spin up a full Spring container.

**Comment by KurtStam** [comment]
I haven't seen this. Do you think it's because your machine is too busy to respond? Kubernetes should be up, and we're only selecting pods that are `ready`. We could start the scheduler later if needed. I don't really want to silence the error logging until we we there is no bigger issue here.

**Comment by KurtStam** [comment]
I refactored the test, but even originally the tests where NOT start a spring container, even when running `man install` in the metrics module. However when running it from the rest module I guess it did start scanning the @Autowired annotations. I can't help to thing that this happens more often in our unit tests.

**Comment by rhuss** [comment]
It's in rest/runtime where the spring container starts and pick up the Metrics Collector. I recommend to switch off the Metrics collector for those test.
