### ISSUE TITLE
DataBuckets exception - Incompatible Source Document 'null'

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#1701]
I created test for data buckets in syndesis-qe repo, but created integration does not work with exception in integrations pod logs:
[exception.txt](https://github.com/syndesisio/syndesis/files/1763726/exception.txt)

My integration is:

Database - database - datamapper - salesforce

You can see feature file of the test here so you can easily reproduce this issue, just follow those steps: 
[feature.txt](https://github.com/syndesisio/syndesis/files/1763741/feature.txt)

I am using output of first database connector in data mapper. Note that if I delete second database step, this integration works as expected so it looks like first database output is not available in data mapper step.

I am not sure if data buckets are already fully implemented as its epic issue https://github.com/syndesisio/syndesis/issues/1110 is still in open state.
If it is the case at least we already have some tests.

**Comment by dsimansk** [comment]
@igarashitm FYI

**Comment by igarashitm** [comment]
It seems like the source document is null there, I'll try to reproduce it.

BTW the error message doesn't make any sense there - atlasmap/atlasmap#314

**Comment by igarashitm** [comment]
It turned out the one of the key of 2 messages in `Syndesis.CAPTURED_OUT_MESSAGES_MAP` is null while mapping definition has a valid docId, then datamapper can't find the corresponding Message from that map.

So the interceptor can't grab right step ID in some case. Not yet have any idea how it happens...

**Comment by igarashitm** [comment]
So `from.getId()` is null here
https://github.com/syndesisio/syndesis/blob/0e0a523d13df47c70d0b7f7b7288d0bf3d4a1ff4/app/integration/runtime/src/main/java/io/syndesis/integration/runtime/OutMessageCaptureInterceptStrategy.java#L52

@syndesisio/backend any idea how it happens?

**Comment by igarashitm** [comment]
Oh so `from` is `Timer` for the periodic SQL connection, not really SQL. I guess it's added behind the scene and the step ID assignment doesn't care about it? No idea how to fix...

**Comment by lburgazzoli** [comment]
@igarashitm will have a look

**Comment by mcada** [comment]
This issue was closed, but maybe it should be reopened. The exception is now better, but I still don't understand why this integration doesn't work. Can you please check it again @igarashitm ?


```
java.lang.IllegalStateException: Got an empty collection
	at io.syndesis.connector.sql.customizer.SqlStartConnectorCustomizer.doAfterProducer(SqlStartConnectorCustomizer.java:49) ~[connector-sql-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
	at io.syndesis.integration.component.proxy.ComponentProxyProducer.process(ComponentProxyProducer.java:44) ~[integration-component-proxy-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:67) ~[camel-core-2.20.1.jar!/:2.20.1]
	at io.syndesis.integration.runtime.logging.IntegrationLoggingInterceptStrategy.lambda$wrapProcessorInInterceptors$0(IntegrationLoggingInterceptStrategy.java:45) ~[integration-runtime-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:76) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) [camel-core-2.20.1.jar!/:2.20.1]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_151]
	at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_151]
```

**Comment by lburgazzoli** [comment]
@mcada can we open a new one ? I this a different issue

**Comment by igarashitm** [comment]
Empty collection means the query didn't return any result I guess?

>

**Comment by lburgazzoli** [comment]
yes

**Comment by mcada** [comment]
Oh my bad, syndesis-db now contains different data and I missed that update. After I changed the query it works as expected, thank you.

**Comment by igarashitm** [comment]
So this is an expected behavior for polling consumer like this, however I
think this error message could be debug level. WDYT?
@mcada Let's continue in new issue if you agree :-)
