### ISSUE TITLE
NPE in DB2StoredProc Integration

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#1713]
Create an integration using Periodic SQL Action with SELECT * FROM CONTACT, and as finish action use the add_lead stored procedure and add a datamapper step.

In the integration logs:

{"exchange":"-L6O07Dn_RcMOI_t54ow","step":"-L6O-7ppxXrDM2Hmb4z1","id":"-L6O07UP_RcMOI_t54oz","duration":11125425,"failure":"java.lang.NullPointerException\n\tat java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)\n\tat org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache.getIfPresent(BoundedLocalCache.java:1525)\n\tat org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache.get(BoundedLocalCache.java:1520)\n\tat org.apache.camel.util.LRUCache.get(LRUCache.java:132)\n\tat org.apache.camel.component.sql.stored.CallableStatementWrapperFactory.getTemplateStoredProcedure(CallableStatementWrapperFactory.java:67)\n\tat org.apache.camel.component.sql.stored.CallableStatementWrapper.populateStatement(CallableStatementWrapper.java:104)\n\tat org.apache.camel.component.sql.stored.SqlStoredProducer$1.execute(SqlStoredProducer.java:69)\n\tat org.apache.camel.component.sql.stored.CallableStatementWrapper.call(CallableStatementWrapper.java:55)\n\tat org.apache.camel.component.sql.stored.SqlStoredProducer.process(SqlStoredProducer.java:43)\n\tat org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat io.syndesis.integration.component.proxy.ComponentProxyProducer.process(ComponentProxyProducer.java:44)\n\tat org.apache.camel.processor.SendProcessor$2.doInAsyncProducer(SendProcessor.java:178)\n\tat org.apache.camel.impl.ProducerCache.doInAsyncProducer(ProducerCache.java:445)\n\tat org.apache.camel.processor.SendProcessor.process(SendProcessor.java:173)\n\tat org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:67)\n\tat io.syndesis.integration.runtime.logging.IntegrationLoggingInterceptStrategy.lambda$wrapProcessorInInterceptors$0(IntegrationLoggingInterceptStrategy.java:45)\n\tat org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)\n\tat org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:76)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:97)\n\tat io.syndesis.integration.runtime.OutMessageCaptureInterceptStrategy.lambda$wrapProcessorInInterceptors$0(OutMessageCaptureInterceptStrategy.java:54)\n\tat org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:701)\n\tat org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:624)\n\tat org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:248)\n\tat org.apache.camel.processor.Splitter.process(Splitter.java:114)\n\tat org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:67)\n\tat io.syndesis.integration.runtime.logging.IntegrationLoggingInterceptStrategy.lambda$wrapProcessorInInterceptors$0(IntegrationLoggingInterceptStrategy.java:45)\n\tat org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)\n\tat org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:76)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:97)\n\tat io.syndesis.integration.runtime.OutMessageCaptureInterceptStrategy.lambda$wrapProcessorInInterceptors$0(OutMessageCaptureInterceptStrategy.java:54)\n\tat org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197)\n\tat org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79)\n\tat java.util.TimerThread.mainLoop(Timer.java:555)\n\tat java.util.TimerThread.run(Timer.java:505)\n"}
2018-02-27 20:46:48.309 ERROR 1 --- [r://integration] o.a.camel.processor.DefaultErrorHandler  : Failed delivery for (MessageId: -L6O07UN_RcMOI_t54oy on ExchangeId: -L6O07Dn_RcMOI_t54ow). Exhausted after delivery attempt: 1 caught: java.lang.NullPointerException

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[-L6O-IF1amUpOJAXmF] [-L6O-IF1amUpOJAXmF] [timer://integration?period=1000                                               ] [      1402]
[-L6O-IF1amUpOJAXmF] [-L6O-9fhxXrDM2Hmb4] [atlas:mapping-step-2.json?sourceMapName=Syndesis.CAPTURED_OUT_MESSAGES_MAP    ] [      1061]
[-L6O-IF1amUpOJAXmF] [-L6O-7ppxXrDM2Hmb4] [sql-stored-3                                                                  ] [        18]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------

java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[na:1.8.0_151]
	at org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache.getIfPresent(BoundedLocalCache.java:1525) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.com.github.benmanes.caffeine.cache.BoundedLocalCache.get(BoundedLocalCache.java:1520) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.util.LRUCache.get(LRUCache.java:132) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.sql.stored.CallableStatementWrapperFactory.getTemplateStoredProcedure(CallableStatementWrapperFactory.java:67) ~[camel-sql-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.sql.stored.CallableStatementWrapper.populateStatement(CallableStatementWrapper.java:104) ~[camel-sql-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.sql.stored.SqlStoredProducer$1.execute(SqlStoredProducer.java:69) ~[camel-sql-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.sql.stored.CallableStatementWrapper.call(CallableStatementWrapper.java:55) ~[camel-sql-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.sql.stored.SqlStoredProducer.process(SqlStoredProducer.java:43) ~[camel-sql-2.20.1.jar!/:2.20.1]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
	at io.syndesis.integration.component.proxy.ComponentProxyProducer.process(ComponentProxyProducer.java:44) ~[integration-component-proxy-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at org.apache.camel.processor.SendProcessor$2.doInAsyncProducer(SendProcessor.java:178) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.impl.ProducerCache.doInAsyncProducer(ProducerCache.java:445) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:173) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:67) [camel-core-2.20.1.jar!/:2.20.1]
	at io.syndesis.integration.runtime.logging.IntegrationLoggingInterceptStrategy.lambda$wrapProcessorInInterceptors$0(IntegrationLoggingInterceptStrategy.java:45) [integration-runtime-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:76) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:97) ~[camel-core-2.20.1.jar!/:2.20.1]
	at io.syndesis.integration.runtime.OutMessageCaptureInterceptStrategy.lambda$wrapProcessorInInterceptors$0(OutMessageCaptureInterceptStrategy.java:54) ~[integration-runtime-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:701) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:624) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:248) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Splitter.process(Splitter.java:114) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:67) [camel-core-2.20.1.jar!/:2.20.1]
	at io.syndesis.integration.runtime.logging.IntegrationLoggingInterceptStrategy.lambda$wrapProcessorInInterceptors$0(IntegrationLoggingInterceptStrategy.java:45) [integration-runtime-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:76) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:97) ~[camel-core-2.20.1.jar!/:2.20.1]
	at io.syndesis.integration.runtime.OutMessageCaptureInterceptStrategy.lambda$wrapProcessorInInterceptors$0(OutMessageCaptureInterceptStrategy.java:54) ~[integration-runtime-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) ~[camel-core-2.20.1.jar!/:2.20.1]
	at java.util.TimerThread.mainLoop(Timer.java:555) ~[na:1.8.0_151]
	at java.util.TimerThread.run(Timer.java:505) ~[na:1.8.0_151]

**Comment by KurtStam** [comment]
@lburgazzoli do you think this is related to the refactoring?

**Comment by lburgazzoli** [comment]
it should not but let me have a look

**Comment by lburgazzoli** [comment]
I think I know were the problem is so, the connector definition for the `sql-stored-connector` action is something like:

```json
{
      "id": "sql-stored-connector",
      "name": "Invoke stored procedure",
      "description": "Periodically invoke a stored procedure.",
      "tags": [
        "dynamic"
      ],
      "pattern": "To",
      "actionType": "connector",
      "descriptor": {
        "componentScheme": "sql-stored",
        "connectorCustomizers": [
          "io.syndesis.connector.sql.customizer.SqlStoredConnectorCustomizer"
        ],
        "inputDataShape": {
          "kind": "json-schema"
        },
        "outputDataShape": {
          "kind": "json-schema"
        },
        "propertyDefinitionSteps": [
          {
            "name": "Procedure name",
            "description": "Select the stored procedure.",
            "properties": {
              "procedureName": {
                "kind": "property",
                "group": "common",
                "displayName": "Procedure name",
                "required": false,
                "type": "string",
                "javaType": "java.lang.String",
                "tags": [],
                "deprecated": false,
                "secret": true,
                "componentProperty": true,
                "description": "Name of the stored procedure."
              },
              "template": {
                "kind": "path",
                "displayName": "Template",
                "group": "producer",
                "required": true,
                "type": "hidden",
                "javaType": "java.lang.String",
                "tags": [],
                "deprecated": false,
                "secret": false,
                "componentProperty": false,
                "defaultValue": "",
                "description": "Stored procedure template to perform."
              }
            }
          }
        ]
      }
    },
```

So there is a property `template` of type `hidden` which gets overridden by the UI so when the runtime process the json bits it looks like:

```json
{
      "action": {
        "id": "sql-stored-connector",
        "name": "Invoke stored procedure",
        "description": "Periodically invoke a stored procedure.",
        "descriptor": {
          "componentScheme": "sql-stored",
          "connectorCustomizers": [
            "io.syndesis.connector.sql.customizer.SqlStoredConnectorCustomizer"
          ],
          "inputDataShape": {
            "name": "add_lead Parameter",
            "description": "Parameters of Stored Procedure 'add_lead'",
            "kind": "json-schema",
            "type": "add_lead_IN",
            "specification": "{\"type\":\"object\",\"$schema\":\"http://json-schema.org/schema#\",\"title\":\"add_lead_IN\",\"properties\":{\"first_and_last_name\":{\"type\":\"string\",\"required\":true},\"company\":{\"type\":\"string\",\"required\":true},\"phone\":{\"type\":\"string\",\"required\":true},\"email\":{\"type\":\"string\",\"required\":true},\"lead_source\":{\"type\":\"string\",\"required\":true},\"lead_status\":{\"type\":\"string\",\"required\":true},\"rating\":{\"type\":\"string\",\"required\":true}}}"
          },
          "outputDataShape": {
            "kind": "none",
            "type": "add_lead_OUT"
          },
          "propertyDefinitionSteps": [
            {
              "description": "Select the stored procedure.",
              "name": "Procedure name",
              "properties": {
                "procedureName": {
                  "componentProperty": true,
                  "deprecated": false,
                  "description": "Name of the stored procedure.",
                  "displayName": "Procedure name",
                  "group": "common",
                  "javaType": "java.lang.String",
                  "kind": "property",
                  "required": false,
                  "secret": true,
                  "type": "string"
                },
                "template": {
                  "componentProperty": false,
                  "defaultValue": "add_lead(VARCHAR ${body[first_and_last_name]}, VARCHAR ${body[company]}, VARCHAR ${body[phone]}, VARCHAR ${body[email]}, VARCHAR ${body[lead_source]}, VARCHAR ${body[lead_status]}, VARCHAR ${body[rating]})",
                  "deprecated": false,
                  "description": "Stored procedure template to perform.",
                  "displayName": "Template",
                  "group": "producer",
                  "javaType": "java.lang.String",
                  "kind": "path",
                  "required": true,
                  "secret": false,
                  "type": "hidden",
                  "enum": [
                    {
                      "label": "template",
                      "value": "add_lead(VARCHAR ${body[first_and_last_name]}, VARCHAR ${body[company]}, VARCHAR ${body[phone]}, VARCHAR ${body[email]}, VARCHAR ${body[lead_source]}, VARCHAR ${body[lead_status]}, VARCHAR ${body[rating]})"
                    }
                  ]
                }
              }
            }
          ]
        },
```

So the `template` property has some new options like `defaultValue` and the `enum` whereas I'd expect such value to be set on step's `configuredProperties`

I can add support for that but it looks wrong to me, @gashcrumb @KurtStam is that the expected behavior on the ui side ?

**Comment by lburgazzoli** [comment]
Mh no sorry this is done by `ConnectionActionHandler` ...

**Comment by KurtStam** [comment]
@lburgazzoli It could be related to https://github.com/syndesisio/syndesis/issues/1718. Working to see if it is.
