### ISSUE TITLE
jsondb's DELETE's using a lot of CPU in postgresql

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#1780]
## This is a...
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I left the integration running for 12 hours and the number of records to jsondb increased to over 500K, with that many rows issuing DELETE SQL statements uses resources significantly.

Notice the CPU TIME of PID 538:

```shell
$ ps auxww
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1000070+     1  0.0  0.1 171452  2776 ?        Ss   Mar01   0:06 postgres
1000070+   107  0.0  0.0  95020   780 ?        Ss   Mar01   0:00 postgres: logger process  
1000070+   109  0.0  3.3 171572 69072 ?        Ss   Mar01   0:07 postgres: checkpointer process  
1000070+   110  0.0  3.3 171452 68712 ?        Ss   Mar01   0:10 postgres: writer process  
1000070+   111  0.0  0.1 171452  2216 ?        Ss   Mar01   0:13 postgres: wal writer process  
1000070+   112  0.0  0.6 171872 12668 ?        Ss   Mar01   0:01 postgres: autovacuum launcher process  
1000070+   113  0.0  0.0  97272  1108 ?        Ss   Mar01   0:08 postgres: stats collector process  
1000070+   532  0.0  0.1 172268  3108 ?        Ss   Mar01   0:00 postgres: syndesis syndesis 172.17.0.2(47648) idle
1000070+   533  0.0  0.0 172268  1424 ?        Ss   Mar01   0:00 postgres: syndesis syndesis 172.17.0.2(47650) idle
1000070+   534  0.0  0.0 172268  1424 ?        Ss   Mar01   0:00 postgres: syndesis syndesis 172.17.0.2(47652) idle
1000070+   535  0.0  0.0 172268  1424 ?        Ss   Mar01   0:00 postgres: syndesis syndesis 172.17.0.2(47654) idle
1000070+   536  0.0  0.0 172268  1424 ?        Ss   Mar01   0:00 postgres: syndesis syndesis 172.17.0.2(47656) idle
1000070+   537  0.0  0.0 172268  1428 ?        Ss   Mar01   0:00 postgres: syndesis syndesis 172.17.0.2(47658) idle
1000070+   538 32.7  3.4 173556 71732 ?        Rs   Mar01 242:36 postgres: syndesis syndesis 172.17.0.2(47660) DELETE
1000070+   539  2.0  3.4 173036 70484 ?        Ss   Mar01  15:23 postgres: syndesis syndesis 172.17.0.2(47662) idle
1000070+   540  0.0  0.3 173148  7500 ?        Ss   Mar01   0:00 postgres: syndesis syndesis 172.17.0.2(47664) idle
1000070+   541  0.7  3.4 173244 71568 ?        Ss   Mar01   5:40 postgres: syndesis syndesis 172.17.0.2(47666) idle
1000070+ 12798  0.0  0.1  11784  2700 ?        Ss   08:15   0:00 /bin/sh
1000070+ 13146  0.0  0.1  47468  3024 ?        R+   08:21   0:00 ps auxww
```

```sql
# select * from pg_stat_activity;
 datid | datname  |  pid  | usesysid | usename  | application_name | client_addr | client_hostname | client_port |         backend_start         |          xact_start           |          query_start          |         state_change          | waiting | state  | backend_xid | backend_xmin |                                                 query                                                  
-------+----------+-------+----------+----------+------------------+-------------+-----------------+-------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+---------+--------+-------------+--------------+--------------------------------------------------------------------------------------------------------
 16385 | syndesis |   532 |    16384 | syndesis |                  | 172.17.0.2  |                 |       47648 | 2018-03-01 20:00:45.265613+00 |                               | 2018-03-01 20:00:45.343247+00 | 2018-03-01 20:00:45.343279+00 | f       | idle   |             |              | SET extra_float_digits = 3
 16385 | syndesis |   533 |    16384 | syndesis |                  | 172.17.0.2  |                 |       47650 | 2018-03-01 20:00:45.379894+00 |                               | 2018-03-01 20:00:45.382083+00 | 2018-03-01 20:00:45.382108+00 | f       | idle   |             |              | SET extra_float_digits = 3
 16385 | syndesis |   534 |    16384 | syndesis |                  | 172.17.0.2  |                 |       47652 | 2018-03-01 20:00:45.386756+00 |                               | 2018-03-01 20:00:45.388448+00 | 2018-03-01 20:00:45.388467+00 | f       | idle   |             |              | SET extra_float_digits = 3
 16385 | syndesis |   535 |    16384 | syndesis |                  | 172.17.0.2  |                 |       47654 | 2018-03-01 20:00:45.392657+00 |                               | 2018-03-01 20:00:45.394147+00 | 2018-03-01 20:00:45.394164+00 | f       | idle   |             |              | SET extra_float_digits = 3
 16385 | syndesis |   536 |    16384 | syndesis |                  | 172.17.0.2  |                 |       47656 | 2018-03-01 20:00:45.398642+00 |                               | 2018-03-01 20:00:45.401067+00 | 2018-03-01 20:00:45.401085+00 | f       | idle   |             |              | SET extra_float_digits = 3
 16385 | syndesis |   537 |    16384 | syndesis |                  | 172.17.0.2  |                 |       47658 | 2018-03-01 20:00:45.405194+00 |                               | 2018-03-01 20:00:45.406874+00 | 2018-03-01 20:00:45.406894+00 | f       | idle   |             |              | SET extra_float_digits = 3
 16385 | syndesis |   538 |    16384 | syndesis |                  | 172.17.0.2  |                 |       47660 | 2018-03-01 20:00:45.41097+00  | 2018-03-02 08:22:59.538506+00 | 2018-03-02 08:23:13.43341+00  | 2018-03-02 08:23:13.433411+00 | f       | active |       29967 |        29967 | DELETE from jsondb where path LIKE $1 OR path in ( $2, $3, $4, $5, $6, $7 )
 16385 | syndesis |   539 |    16384 | syndesis |                  | 172.17.0.2  |                 |       47662 | 2018-03-01 20:00:45.416607+00 |                               | 2018-03-02 07:33:13.565059+00 | 2018-03-02 07:33:13.565213+00 | f       | idle   |             |              | select path,value,ovalue from jsondb where path LIKE $1 order by path ASC
 16385 | syndesis |   540 |    16384 | syndesis |                  | 172.17.0.2  |                 |       47664 | 2018-03-01 20:00:45.423629+00 |                               | 2018-03-01 20:08:30.549945+00 | 2018-03-01 20:08:30.550305+00 | f       | idle   |             |              | select path,value,ovalue from jsondb where path LIKE $1 and path >= $2 and path < $3 order by path ASC
 16385 | syndesis |   541 |    16384 | syndesis |                  | 172.17.0.2  |                 |       47666 | 2018-03-01 20:00:45.429155+00 |                               | 2018-03-02 08:23:13.39786+00  | 2018-03-02 08:23:13.397908+00 | f       | idle   |             |              | select path,value,ovalue from jsondb where path LIKE $1 order by path ASC
 12442 | postgres | 13199 |       10 | postgres | psql             |             |                 |          -1 | 2018-03-02 08:22:17.360923+00 | 2018-03-02 08:23:13.4525+00   | 2018-03-02 08:23:13.4525+00   | 2018-03-02 08:23:13.452502+00 | f       | active |             |        29967 | select * from pg_stat_activity;
(11 rows)
```

Root cause seems to be jsondb's implementation of `update`:

https://github.com/syndesisio/syndesis/blob/9441747dd46ee10df599942105b8ab112f82dfa5/app/rest/jsondb/src/main/java/io/syndesis/jsondb/impl/SqlJsonDB.java#L474

Triggered from:

https://github.com/syndesisio/syndesis/blob/9441747dd46ee10df599942105b8ab112f82dfa5/app/rest/db-logging/src/main/java/io/syndesis/rest/dblogging/controller/ActivityTrackingController.java#L287

Full stack:

```
"Logs Controller" #19 prio=5 os_prio=0 tid=0x00007f8426379800 nid=0x71 runnable [0x00007f84140d8000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:145)
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:114)
	at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:73)
	at org.postgresql.core.PGStream.ReceiveChar(PGStream.java:274)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1661)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
	- locked <0x00000000edccf958> (a org.postgresql.core.v3.QueryExecutorImpl)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:512)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:388)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:381)
	at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy144.execute(Unknown Source)
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1327)
	at org.skife.jdbi.v2.Update.execute(Update.java:56)
	at org.skife.jdbi.v2.BasicHandle.update(BasicHandle.java:305)
	at io.syndesis.jsondb.impl.SqlJsonDB.deleteJsonRecords(SqlJsonDB.java:514)
	at io.syndesis.jsondb.impl.SqlJsonDB.access$100(SqlJsonDB.java:74)
	at io.syndesis.jsondb.impl.SqlJsonDB$BatchManager.deleteRecordsForSet(SqlJsonDB.java:395)
	at io.syndesis.jsondb.impl.SqlJsonDB.lambda$update$18(SqlJsonDB.java:474)
	at io.syndesis.jsondb.impl.SqlJsonDB$$Lambda$240/125309362.accept(Unknown Source)
	at io.syndesis.jsondb.impl.SqlJsonDB.withTransaction(SqlJsonDB.java:550)
	at io.syndesis.jsondb.impl.SqlJsonDB.update(SqlJsonDB.java:451)
	at io.syndesis.jsondb.JsonDB.update(JsonDB.java:141)
	at io.syndesis.rest.dblogging.controller.ActivityTrackingController.processEventQueue(ActivityTrackingController.java:287)
	at io.syndesis.rest.dblogging.controller.ActivityTrackingController$$Lambda$49/522173599.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Expected behavior

Not taking 100% CPU.

## Screenshot

![fine](https://user-images.githubusercontent.com/1306050/36890588-d14c4cd0-1dfe-11e8-80d9-7e1bf30478f9.png)

## Tasks involved / Steps to Reproduce
1. Create an integration
2. Let it run for a while
3. Cook some CPUs

**Comment by rhuss** [comment]
@chirino any clue whats going here (as its possibly related to storing logs into JSONDB) ?

**Comment by rhuss** [comment]
BTW, I add similar performance issues yesterday with minishift running 100% but hadnt much time to dig into it.

**Comment by zregvart** [comment]
> BTW, I had similar performance issues yesterday with minishift running 100% but hadnt much time to dig into it.

I think the easiest way is to run `top` in the minishift VM (`minishift ssh` first). Then one can at least see the process that is using much CPU, and later dig into it. Luckily PostgreSQL has really nice process handling so you can see the statement in `ps`.

**Comment by chirino** [comment]
What was the log ingestion rate?  There should be a limit for it, but we don't enforce it.

**Comment by chirino** [comment]
So today i ran into a slow loading UI issue.  /overviews endpoint was taking a long time to load sometimes timed out.  At first I thought it was related to this issue, bu then I restarted the -sever pod and all became snappy again.

**Comment by chirino** [comment]
Is there a consistent way of reproducing this issue?

**Comment by zregvart** [comment]
Not sure other than trying to leave an integration running over night. With frequent deploys/restarts when developing its hard to notice this I think.

**Comment by paoloantinori** [comment]
we have performance related blocker here: https://github.com/syndesisio/syndesis/issues/2155

I'm cross linking them in case it's a manifestation of the same issue.

**Comment by zregvart** [comment]
With #3337 and #3252 we addressed some of the shortcomings of our current approach. I would opt to close this issue and open a new issue for redesigning the activity logging. Any thoughts?

**Comment by lburgazzoli** [comment]
wasn't @KurtStam looking for some alternatives ? that's what I remember from a tech depth call some time ago.

**Comment by KurtStam** [comment]
@lburgazzoli I wasn't but until we have #4011 I guess we could at least have logs sit in their own table.
