### ISSUE TITLE
Can't publish ANY integration 

### ISSUE THREAD

**Issue by weimeilin79** [syndesisio/syndesis#1844]
Deploy the master branch on OpenShift this morning, but can't seem to publish integration anymore.. 

```
2018-03-06 15:29:01.978 ERROR [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [test]: [ERROR] Activation failure
  | io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://openshift.default.svc/oapi/v1/namespaces/fuseignite/buildconfigs . Message: BuildConfig "test" is invalid: metadata.labels: Invalid value: "-L6vuwf0xU_rKyR4PEAj": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'). Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels, message=Invalid value: "-L6vuwf0xU_rKyR4PEAj": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), reason=FieldValueInvalid, additionalProperties={})], group=null, kind=BuildConfig, name=test, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=BuildConfig "test" is invalid: metadata.labels: Invalid value: "-L6vuwf0xU_rKyR4PEAj": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470) ~[kubernetes-client-2.4.1.jar!/:na]
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409) ~[kubernetes-client-2.4.1.jar!/:na]
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379) ~[kubernetes-client-2.4.1.jar!/:na]
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343) ~[kubernetes-client-2.4.1.jar!/:na]
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226) ~[kubernetes-client-2.4.1.jar!/:na]
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:741) ~[kubernetes-client-2.4.1.jar!/:na]
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:334) ~[kubernetes-client-2.4.1.jar!/:na]
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:403) ~[kubernetes-client-2.4.1.jar!/:na]
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation$2.apply(BaseOperation.java:372) ~[kubernetes-client-2.4.1.jar!/:na]
  | at io.fabric8.openshift.api.model.DoneableBuildConfig.done(DoneableBuildConfig.java:27) ~[kubernetes-model-1.0.74.jar!/:1.0.74]
  | at io.syndesis.server.openshift.OpenShiftServiceImpl.ensureBuildConfig(OpenShiftServiceImpl.java:306) ~[server-openshift-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
  | at io.syndesis.server.openshift.OpenShiftServiceImpl.build(OpenShiftServiceImpl.java:59) ~[server-openshift-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
  | at io.syndesis.server.controller.integration.online.PublishHandler.build(PublishHandler.java:155) ~[server-controller-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
  | at io.syndesis.server.controller.integration.online.PublishHandler$BuildStepPerformer.perform(PublishHandler.java:313) ~[server-controller-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
  | at io.syndesis.server.controller.integration.online.PublishHandler.execute(PublishHandler.java:101) ~[server-controller-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
  | at io.syndesis.server.controller.StateChangeHandler.execute(StateChangeHandler.java:33) [server-controller-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
  | at io.syndesis.server.controller.integration.IntegrationController.lambda$callStateChangeHandler$11(IntegrationController.java:186) [server-controller-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
  | at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
  | 2018-03-06 15:29:01.978  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration -L6vuwf0xU_rKyR4PEAj : Setting status to Pending (Failure executing: POST at: https://openshift.default.svc/oapi/v1/namespaces/fuseignite/buildconfigs . Message: BuildConfig "test" is invalid: metadata.labels: Invalid value: "-L6vuwf0xU_rKyR4PEAj": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'). Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels, message=Invalid value: "-L6vuwf0xU_rKyR4PEAj": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), reason=FieldValueInvalid, additionalProperties={})], group=null, kind=BuildConfig, name=test, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=BuildConfig "test" is invalid: metadata.labels: Invalid value: "-L6vuwf0xU_rKyR4PEAj": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).)

```

**Comment by oscerd** [comment]
Duplicates #1841
