### ISSUE TITLE
Integration fail to start: "EXTENSION_TAG": value not one of declared Enum instance names: [MAVEN, EXTENSION]

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#1859]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Integration fails to deploy

## Screenshot

```
i-paolo2-2-wdbmx i-paolo2 Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
i-paolo2-2-wdbmx i-paolo2 2018-03-06 21:20:45.412 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application startup failed
i-paolo2-2-wdbmx i-paolo2 
i-paolo2-2-wdbmx i-paolo2 org.apache.camel.spring.boot.CamelSpringBootInitializationException: java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type io.syndesis.common.model.Dependency$Type from String "EXTENSION_TAG": value not one of declared Enum instance names: [MAVEN, EXTENSION]
i-paolo2-2-wdbmx i-paolo2  at [Source: org.springframework.boot.loader.jar.ZipInflaterInputStream@289f15e9; line: 313, column: 20] (through reference chain: io.syndesis.common.model.integration.Integration$Builder["steps"]->java.util.ArrayList[0]->io.syndesis.common.model.integration.Step$Builder["connection"]->io.syndesis.common.model.connection.Connection$Builder["connector"]->io.syndesis.common.model.connection.Connector$Builder["dependencies"]->java.util.ArrayList[1]->io.syndesis.common.model.Dependency$Builder["type"])
i-paolo2-2-wdbmx i-paolo2 	at org.apache.camel.spring.boot.RoutesCollector.onApplicationEvent(RoutesCollector.java:250) ~[camel-spring-boot-2.20.1.jar!/:2.20.1]
i-paolo2-2-wdbmx i-paolo2 	at org.apache.camel.spring.boot.RoutesCollector.onApplicationEvent(RoutesCollector.java:57) ~[camel-spring-boot-2.20.1.jar!/:2.20.1]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
i-paolo2-2-wdbmx i-paolo2 	at io.syndesis.example.Application.main(Application.java:13) [classes!/:na]
i-paolo2-2-wdbmx i-paolo2 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
i-paolo2-2-wdbmx i-paolo2 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
i-paolo2-2-wdbmx i-paolo2 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
i-paolo2-2-wdbmx i-paolo2 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [project-0.1-SNAPSHOT.jar:na]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [project-0.1-SNAPSHOT.jar:na]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [project-0.1-SNAPSHOT.jar:na]
i-paolo2-2-wdbmx i-paolo2 	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:587) [project-0.1-SNAPSHOT.jar:na]
i-paolo2-2-wdbmx i-paolo2 Caused by: java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type io.syndesis.common.model.Dependency$Type from String "EXTENSION_TAG": value not one of declared Enum instance names: [MAVEN, EXTENSION]
i-paolo2-2-wdbmx i-paolo2  at [Source: org.springframework.boot.loader.jar.ZipInflaterInputStream@289f15e9; line: 313, column: 20] (through reference chain: io.syndesis.common.model.integration.Integration$Builder["steps"]->java.util.ArrayList[0]->io.syndesis.common.model.integration.Step$Builder["connection"]->io.syndesis.common.model.connection.Connection$Builder["connector"]->io.syndesis.common.model.connection.Connector$Builder["dependencies"]->java.util.ArrayList[1]->io.syndesis.common.model.Dependency$Builder["type"])
i-paolo2-2-wdbmx i-paolo2 	at io.syndesis.integration.runtime.IntegrationRuntimeAutoConfiguration$1.beforeApplicationStart(IntegrationRuntimeAutoConfiguration.java:67) ~[integration-runtime-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
i-paolo2-2-wdbmx i-paolo2 	at org.apache.camel.spring.boot.RoutesCollector.onApplicationEvent(RoutesCollector.java:152) ~[camel-spring-boot-2.20.1.jar!/:2.20.1]
i-paolo2-2-wdbmx i-paolo2 	... 24 common frames omitted
i-paolo2-2-wdbmx i-paolo2 Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type io.syndesis.common.model.Dependency$Type from String "EXTENSION_TAG": value not one of declared Enum instance names: [MAVEN, EXTENSION]
i-paolo2-2-wdbmx i-paolo2  at [Source: org.springframework.boot.loader.jar.ZipInflaterInputStream@289f15e9; line: 313, column: 20] (through reference chain: io.syndesis.common.model.integration.Integration$Builder["steps"]->java.util.ArrayList[0]->io.syndesis.common.model.integration.Step$Builder["connection"]->io.syndesis.common.model.connection.Connection$Builder["connector"]->io.syndesis.common.model.connection.Connector$Builder["dependencies"]->java.util.ArrayList[1]->io.syndesis.common.model.Dependency$Builder["type"])
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:74) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1410) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:926) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:189) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:126) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:116) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:266) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:154) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:116) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:266) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:154) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.datatype.jdk8.OptionalDeserializer.deserialize(OptionalDeserializer.java:100) ~[jackson-datatype-jdk8-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.datatype.jdk8.OptionalDeserializer.deserialize(OptionalDeserializer.java:13) ~[jackson-datatype-jdk8-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:116) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:266) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:154) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.datatype.jdk8.OptionalDeserializer.deserialize(OptionalDeserializer.java:100) ~[jackson-datatype-jdk8-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.datatype.jdk8.OptionalDeserializer.deserialize(OptionalDeserializer.java:13) ~[jackson-datatype-jdk8-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:116) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:266) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:154) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:116) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:266) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:154) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1626) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1186) ~[jackson-databind-2.8.10.jar!/:2.8.10]
i-paolo2-2-wdbmx i-paolo2 	at io.syndesis.integration.runtime.IntegrationRouteBuilder.loadIntegration(IntegrationRouteBuilder.java:95) ~[integration-runtime-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
i-paolo2-2-wdbmx i-paolo2 	at io.syndesis.integration.runtime.IntegrationRouteBuilder.configure(IntegrationRouteBuilder.java:106) ~[integration-runtime-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
i-paolo2-2-wdbmx i-paolo2 	at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:462) ~[camel-core-2.20.1.jar!/:2.20.1]
i-paolo2-2-wdbmx i-paolo2 	at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:402) ~[camel-core-2.20.1.jar!/:2.20.1]
i-paolo2-2-wdbmx i-paolo2 	at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:383) ~[camel-core-2.20.1.jar!/:2.20.1]
i-paolo2-2-wdbmx i-paolo2 	at org.apache.camel.impl.DefaultCamelContext$1.call(DefaultCamelContext.java:1032) ~[camel-core-2.20.1.jar!/:2.20.1]
i-paolo2-2-wdbmx i-paolo2 	at org.apache.camel.impl.DefaultCamelContext$1.call(DefaultCamelContext.java:1029) ~[camel-core-2.20.1.jar!/:2.20.1]
i-paolo2-2-wdbmx i-paolo2 	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3268) ~[camel-core-2.20.1.jar!/:2.20.1]
i-paolo2-2-wdbmx i-paolo2 	at org.apache.camel.impl.DefaultCamelContext.addRoutes(DefaultCamelContext.java:1029) ~[camel-core-2.20.1.jar!/:2.20.1]
i-paolo2-2-wdbmx i-paolo2 	at io.syndesis.integration.runtime.IntegrationRuntimeAutoConfiguration$1.beforeApplicationStart(IntegrationRuntimeAutoConfiguration.java:65) ~[integration-runtime-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
i-paolo2-2-wdbmx i-paolo2 	... 25 common frames omitted
i-paolo2-2-wdbmx i-paolo2 
```

## Tasks involved / Steps to Reproduce

1. just deploy a simple db to db integration
2.
3.
4.

**Comment by paoloantinori** [comment]
Ignore this, I just needed to rebuild and publish `s2i`
