### ISSUE TITLE
Error from the customized swagger API connector. 

### ISSUE THREAD

**Issue by weimeilin79** [syndesisio/syndesis#1884]
Can you please please itake a look at this issue?? 
The swagger worked fine on the build of 2.23, but now it does not work. 
I need to demo to a LARGE audience next week, this is a big event. 

```
---------------------------------------------------------------------------------------------------------------------------------------
--
  | RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
  | [i-L70Hbp3w6m_36vOl] [i-L70Hbp3w6m_36vOl] [sjms-sjms-1://queue:postwitter                                                ] [         4]
  | [i-L70Hbp3w6m_36vOl] [-L70HNDLioNdvYvlnZ] [Processor@0x352e5a82                                                          ] [         1]
  | [i-L70Hbp3w6m_36vOl] [-L70HYxNioNdvYvlnZ] [atlas:mapping-step-2.json?sourceMapName=Syndesis.CAPTURED_OUT_MESSAGES_MAP    ] [         1]
  | [i-L70Hbp3w6m_36vOl] [-L70HYxNioNdvYvlnZ] [Processor@0x2a4e939a                                                          ] [         0]
  | [i-L70Hbp3w6m_36vOl] [-L70HXdJioNdvYvlnZ] [swagger-operation-3?operationId=operation-0                                   ] [         1]
  | Stacktrace
  | ---------------------------------------------------------------------------------------------------------------------------------------
  | java.lang.IllegalArgumentException: Invalid uri: /hireinasia/tweetjob. If you are forwarding/bridging http endpoints, then enable the bridgeEndpoint option on the endpoint: http4://customizetwitter-fuseignite.52.230.124.252.nip.io/twitter/update
  | at org.apache.camel.component.http4.HttpProducer.createMethod(HttpProducer.java:476) ~[camel-http4-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.http4.HttpProducer.process(HttpProducer.java:113) ~[camel-http4-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.rest.RestProducer.process(RestProducer.java:86) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.connector.ConnectorProducer.process(ConnectorProducer.java:45) ~[camel-connector-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:67) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at io.syndesis.integration.runtime.logging.IntegrationLoggingInterceptStrategy.lambda$wrapProcessorInInterceptors$0(IntegrationLoggingInterceptStrategy.java:45) ~[integration-runtime-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
  | at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:76) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.sjms.consumer.InOnlyMessageHandler.handleMessage(InOnlyMessageHandler.java:65) [camel-sjms-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.sjms.consumer.AbstractMessageHandler.onMessage(AbstractMessageHandler.java:86) [camel-sjms-2.20.1.jar!/:2.20.1]
  | at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1401) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.ActiveMQMessageConsumer.iterate(ActiveMQMessageConsumer.java:1572) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:191) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48) [activemq-client-5.14.5.jar!/:5.14.5]
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
  | at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
  | {"exchange":"i-L70K1Yy5BLj4VwAS8z_z","status":"done","failed":true}
  | 2018-03-07 16:38:35.523 ERROR 1 --- [ Session Task-3] o.a.activemq.ActiveMQMessageConsumer     : ID:i-twitterfeed-2-4qsz4-45950-1520440270154-1:1:1:1 Exception while processing message: ID:hireinasia-app-1-jr8sg-34417-1520438705171-1:2:1:1:1
  | org.apache.camel.RuntimeCamelException: java.lang.NullPointerException
  | at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1831) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.sjms.consumer.AbstractMessageHandler.onMessage(AbstractMessageHandler.java:113) ~[camel-sjms-2.20.1.jar!/:2.20.1]
  | at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1401) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.ActiveMQMessageConsumer.iterate(ActiveMQMessageConsumer.java:1572) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:191) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48) [activemq-client-5.14.5.jar!/:5.14.5]
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
  | at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
  | Caused by: java.lang.NullPointerException: null
  | at org.apache.camel.component.sjms.consumer.AbstractMessageHandler.onMessage(AbstractMessageHandler.java:88) ~[camel-sjms-2.20.1.jar!/:2.20.1]
  | ... 8 common frames omitted
```

**Comment by kcbabo** [comment]
Hey @weimeilin79 - can you provide a link/gist to the Swagger definition you're using?

**Comment by weimeilin79** [comment]
I did some test, the problem looks like the problem was cause by the header. if I remove the CamelHTTP header before it got send into the queue, it will show a different error. If I post a pure message through the AMQ console, then it works. 


```

  | RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
  | [i-L70Hbp3w6m_36vOl] [i-L70Hbp3w6m_36vOl] [sjms-sjms-1://queue:postwitter                                                ] [         8]
  | [i-L70Hbp3w6m_36vOl] [-L70HNDLioNdvYvlnZ] [Processor@0x24aedcc5                                                          ] [         3]
  | [i-L70Hbp3w6m_36vOl] [-L70HYxNioNdvYvlnZ] [atlas:mapping-step-2.json?sourceMapName=Syndesis.CAPTURED_OUT_MESSAGES_MAP    ] [         2]
  | [i-L70Hbp3w6m_36vOl] [-L70HYxNioNdvYvlnZ] [Processor@0x261275ae                                                          ] [         0]
  | [i-L70Hbp3w6m_36vOl] [-L70HXdJioNdvYvlnZ] [swagger-operation-3?operationId=operation-0                                   ] [         2]
  | Stacktrace
  | ---------------------------------------------------------------------------------------------------------------------------------------
  | org.apache.http.client.ClientProtocolException: null
  | at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187) ~[httpclient-4.5.3.jar!/:4.5.3]
  | at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.3.jar!/:4.5.3]
  | at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.3.jar!/:4.5.3]
  | at org.apache.camel.component.http4.HttpProducer.executeMethod(HttpProducer.java:334) ~[camel-http4-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.http4.HttpProducer.process(HttpProducer.java:193) ~[camel-http4-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.rest.RestProducer.process(RestProducer.java:86) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.connector.ConnectorProducer.process(ConnectorProducer.java:45) ~[camel-connector-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:67) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at io.syndesis.integration.runtime.logging.IntegrationLoggingInterceptStrategy.lambda$wrapProcessorInInterceptors$0(IntegrationLoggingInterceptStrategy.java:45) ~[integration-runtime-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
  | at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:76) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.sjms.consumer.InOnlyMessageHandler.handleMessage(InOnlyMessageHandler.java:65) [camel-sjms-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.sjms.consumer.AbstractMessageHandler.onMessage(AbstractMessageHandler.java:86) [camel-sjms-2.20.1.jar!/:2.20.1]
  | at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1401) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.ActiveMQMessageConsumer.iterate(ActiveMQMessageConsumer.java:1572) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:191) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48) [activemq-client-5.14.5.jar!/:5.14.5]
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
  | at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
  | Caused by: org.apache.http.ProtocolException: Content-Length header already present
  | at org.apache.http.protocol.RequestContent.process(RequestContent.java:97) ~[httpcore-4.4.8.jar!/:4.4.8]
  | at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133) ~[httpcore-4.4.8.jar!/:4.4.8]
  | at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:183) ~[httpclient-4.5.3.jar!/:4.5.3]
  | at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.3.jar!/:4.5.3]
  | at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.3.jar!/:4.5.3]
  | at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.3.jar!/:4.5.3]
  | ... 34 common frames omitted
  | {"exchange":"i-L70n27d-G3Mmwm0EDymz","status":"done","failed":true}
  | 2018-03-07 18:49:42.194 ERROR 1 --- [Session Task-16] o.a.activemq.ActiveMQMessageConsumer     : ID:i-twitterfeed-10-pt5bq-40023-1520447261168-1:1:1:1 Exception while processing message: ID:hireinasia-app-8-94bjt-36831-1520447819327-1:5:1:1:1
  | org.apache.camel.RuntimeCamelException: java.lang.NullPointerException
  | at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1831) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.sjms.consumer.AbstractMessageHandler.onMessage(AbstractMessageHandler.java:113) ~[camel-sjms-2.20.1.jar!/:2.20.1]
  | at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1401) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.ActiveMQMessageConsumer.iterate(ActiveMQMessageConsumer.java:1572) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:191) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48) [activemq-client-5.14.5.jar!/:5.14.5]
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
  | at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
  | Caused by: java.lang.NullPointerException: null
  | at org.apache.camel.component.sjms.consumer.AbstractMessageHandler.onMessage(AbstractMessageHandler.java:88) ~[camel-sjms-2.20.1.jar!/:2.20.1]
  | ... 8 common frames omitted
```

**Comment by weimeilin79** [comment]
https://github.com/weimeilin79/sko-hireinasia/blob/master/swaggertwitter.yml
https://github.com/weimeilin79/sko-hireinasia/blob/master/Trello-API-New.yml

**Comment by rhuss** [comment]
@weimeilin79 if all fails I can try to publish a release from a well known state (e.g. from 23 february) tomorrow. Unfortunately I'm not of big help for the camel issue at hand ;-(

@dhirajsb (activemq) @zregvart (swagger), any ideas what could have gone wrong ?

**Comment by weimeilin79** [comment]
@rhuss So digging into the problem a little more, comparing to what was on 23rd, I think they are sending more headers into the broker. Unfortunately in Ignite, I was not able to print out logs to see what was in the header on the day. By playing around with the header, I think this is 99% cause by the header.. I am also trying to see which header should be removed before it got send into the broker.

**Comment by rhuss** [comment]
One issue imo is in Camel:

```
Caused by: java.lang.NullPointerException: null
  | at org.apache.camel.component.sjms.consumer.AbstractMessageHandler.onMessage(AbstractMessageHandler.java:88) ~[camel-sjms-2.20.1.jar!/:2.20.1]
```

which is

```java
               if (isTransacted() || isSynchronous()) {
                    log.debug("Handling synchronous message: {}", exchange.getIn().getBody());
                    handleMessage(exchange);
                    if (exchange.isFailed()) {
                        // Sync
                        synchronization.onFailure(exchange); // NPE is here
                    } else {
                        synchronization.onComplete(exchange);
                    }
                }

```

`synchronization` is null when the failure is reported. On a first sight this member can be indeed null, when the constructor withou Synchronization is called.

However, this is only a follow up error as it happens when `exchange.isFailed()` is true. Nevertheless, this should be fixed, too.

just some random observations from a Camel noob.

**Comment by zregvart** [comment]
@rhuss yes that issue needs to be addressed in Camel, the root cause seems to be that the `Content-Length` header is set twice, and that could be an issue that also needs to be fixed in Camel but we can workaround it in the `rest-swagger-connector`.

**Comment by rhuss** [comment]
@weimeilin79 another question: Have you change the log format of the integration logs as I'm missing the timestamp in front of the log messages ?

If so, activity tracking wouldn't work as it expects the ' {' starting in position 30 of each log line with an activity entry (those lines holding only `{...}` like entries) // @chirino (btw, I still believe https://github.com/syndesisio/syndesis/blob/fafebab25faab30969a6403ea21b110de1c50d12/app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/PodLogMonitor.java#L197-L205 is _really_ dirty, much more than prefixed ids ;)

**Comment by weimeilin79** [comment]
@rhuss  I did not change the log format at all. I copy it from the OpenShift log console. Is the timestamp showed somewhere else?

**Comment by zregvart** [comment]
> @weimeilin79 another question: Have you change the log format of the integration logs as I'm missing the timestamp in front of the log messages ?

It's easier to download the log, simply copy-pasting it screws the formatting.

**Comment by weimeilin79** [comment]
@rhuss Will do that next time!

**Comment by rhuss** [comment]
@weimeilin79 then that's no problem of course. just wondered about the missing timestamp, but I guess its still there.

**Comment by davsclaus** [comment]
Logged a ticket about the NPE in camel-sjms
https://issues.apache.org/jira/browse/CAMEL-12335

**Comment by davsclaus** [comment]
The logic of the code in camel-sjms and how you can get that NPE indicate its when you have configured `synchronous=true` on the `sjms` endpoint. Not sure if Syndesis connector does that somewhere. The NPE is fixed in next Camel release.
