### ISSUE TITLE
Exception on empty resultset in sql-connector

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#1894]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

When doing a db-to-db integration with a periodic select `select * from todo` and todo is empty, then the following exception occurs for the integration:

```
2018-03-08 11:02:57.553  WARN 1 --- [r://integration] o.a.camel.component.timer.TimerConsumer  : Error processing exchange. Exchange[i-L74GnoCT_48Vf2Brqaez]. Caused by: [java.lang.IllegalStateException - Got an empty collection]

java.lang.IllegalStateException: Got an empty collection
	at io.syndesis.connector.sql.customizer.SqlStartConnectorCustomizer.doAfterProducer(SqlStartConnectorCustomizer.java:49) ~[connector-sql-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.20.1.jar!/:2.20.1]
	at io.syndesis.integration.component.proxy.ComponentProxyProducer.process(ComponentProxyProducer.java:44) ~[integration-component-proxy-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:67) ~[camel-core-2.20.1.jar!/:2.20.1]
	at io.syndesis.integration.runtime.logging.IntegrationLoggingInterceptStrategy.lambda$wrapProcessorInInterceptors$0(IntegrationLoggingInterceptStrategy.java:45) ~[integration-runtime-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:76) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) [camel-core-2.20.1.jar!/:2.20.1]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_151]
	at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_151]
```

## Expected behavior

Should be a no-op

## Tasks involved / Steps to Reproduce

1. Create a simple integration DB-mapper-DB
2. "select * from todo" for the initial connection
3. Call add_lead as stored procedure for the output connection
4. Add a datamapping from "task" to "last_and_firstname"

**Comment by rhuss** [comment]
@KurtStam any idea ?
