### ISSUE TITLE
Timeout error when Publishing an integration

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#1896]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

On local minishift setup, publishing a simple integration produces this error.

Browser console logs these lines:

```
https://syndesis.192.168.42.228.nip.io/api/v1/metrics/integrations/i-L74XXXEhcQ5XEA1ykevz  500 (Internal Server Error)
https://syndesis.192.168.42.228.nip.io/api/v1/metrics/integrations/i-L74XXXEhcQ5XEA1ykevz 504 (Gateway Time-out)
https://syndesis.192.168.42.228.nip.io/api/v1/metrics/integrations/i-L74XXXEhcQ5XEA1ykevz 504 (Gateway Time-out)
```

But the error is actually non blocking. On my system the build pod took `i-paolo-2-build               0/1	Completed   0          7m` to build. After that the pod is published correctly and the UI page even displays the correct information.

Server logs:
```
syndesis-server-1-fzlmg syndesis-server 2018-03-08 12:16:38.554 ERROR [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [paolo]: [ERROR] Activation failure
syndesis-server-1-fzlmg syndesis-server 
syndesis-server-1-fzlmg syndesis-server io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Build]  with name: [i-paolo-1]  in namespace: [myproject]  failed.
syndesis-server-1-fzlmg syndesis-server 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62) ~[kubernetes-client-2.4.1.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71) ~[kubernetes-client-2.4.1.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:217) ~[kubernetes-client-2.4.1.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:181) ~[kubernetes-client-2.4.1.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at io.syndesis.server.openshift.OpenShiftServiceImpl.waitForBuild(OpenShiftServiceImpl.java:337) ~[server-openshift-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
syndesis-server-1-fzlmg syndesis-server 	at io.syndesis.server.openshift.OpenShiftServiceImpl.build(OpenShiftServiceImpl.java:63) ~[server-openshift-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
syndesis-server-1-fzlmg syndesis-server 	at io.syndesis.server.controller.integration.online.PublishHandler.build(PublishHandler.java:156) ~[server-controller-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
syndesis-server-1-fzlmg syndesis-server 	at io.syndesis.server.controller.integration.online.PublishHandler$BuildStepPerformer.perform(PublishHandler.java:313) ~[server-controller-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
syndesis-server-1-fzlmg syndesis-server 	at io.syndesis.server.controller.integration.online.PublishHandler.execute(PublishHandler.java:101) ~[server-controller-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
syndesis-server-1-fzlmg syndesis-server 	at io.syndesis.server.controller.StateChangeHandler.execute(StateChangeHandler.java:33) [server-controller-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
syndesis-server-1-fzlmg syndesis-server 	at io.syndesis.server.controller.integration.IntegrationController.lambda$callStateChangeHandler$11(IntegrationController.java:186) [server-controller-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
syndesis-server-1-fzlmg syndesis-server 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
syndesis-server-1-fzlmg syndesis-server 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
syndesis-server-1-fzlmg syndesis-server 	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
syndesis-server-1-fzlmg syndesis-server Caused by: java.net.SocketTimeoutException: Read timed out
syndesis-server-1-fzlmg syndesis-server 	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_131]
syndesis-server-1-fzlmg syndesis-server 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_131]
syndesis-server-1-fzlmg syndesis-server 	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[na:1.8.0_131]
syndesis-server-1-fzlmg syndesis-server 	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_131]
syndesis-server-1-fzlmg syndesis-server 	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[na:1.8.0_131]
syndesis-server-1-fzlmg syndesis-server 	at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[na:1.8.0_131]
syndesis-server-1-fzlmg syndesis-server 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983) ~[na:1.8.0_131]
syndesis-server-1-fzlmg syndesis-server 	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940) ~[na:1.8.0_131]
syndesis-server-1-fzlmg syndesis-server 	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[na:1.8.0_131]
syndesis-server-1-fzlmg syndesis-server 	at okio.Okio$2.read(Okio.java:139) ~[okio-1.13.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[okio-1.13.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345) ~[okio-1.13.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217) ~[okio-1.13.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211) ~[okio-1.13.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:64) ~[openshift-client-2.4.1.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at okhttp3.RealCall.execute(RealCall.java:69) ~[okhttp-3.8.0.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:377) ~[kubernetes-client-2.4.1.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343) ~[kubernetes-client-2.4.1.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:312) ~[kubernetes-client-2.4.1.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:295) ~[kubernetes-client-2.4.1.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:753) ~[kubernetes-client-2.4.1.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:206) ~[kubernetes-client-2.4.1.jar!/:na]
syndesis-server-1-fzlmg syndesis-server 	... 11 common frames omitted
syndesis-server-1-fzlmg syndesis-server 
```

## Tasks involved / Steps to Reproduce

1. Simplest db to db integration
2.
3.
4.

**Comment by iocanel** [comment]
Can you reproduce the error consistently?
With a first glance it seems like a random get request failed.

**Comment by iocanel** [comment]
The exception is pretty straight forward, we had a read timeout while polling to check if the deployment is finished.
There is not much to do here, as this can happen when network communications are involved.

The only sideffect that we have is that we won't consider the `deploy` step performed and that we will try to deploy again.

The only thing that can be done here is to have some short of retry policy maybe on IO related errors, or things like http 500.
