### ISSUE TITLE
SQL connector: NPE when mapped field is empty

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#1924]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
There's a NPE for integration `SF on create -> Mapping ->Database` when any of a mapped field isn't provided upon SF's object creation.

```gherkin
#mapping created is counting with e.g. Phone field
When she creates mapping from "Company" to "company"
And she creates mapping from "Email" to "email"
And she creates mapping from "Phone" to "phone"
And she creates mapping from "FirstName" to "first_and_last_name"
And she combines "FirstName" as "1" with "LastName" as "2" to "first_and_last_name" using "Space" separator


#but new Lead is proving just following fields
And create SF lead with first name: "Karol1", last name: "Stieranka1", email: "k1stieranka1@istrochem.sk" and company: "Istrochem"
And validate DB created new lead with first name: "Karol1", last name: "Stieranka1", email: "k1stieranka1@istrochem.sk"

```

```


Message History
--
  | ---------------------------------------------------------------------------------------------------------------------------------------
  | RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
  | [i-L792pr4sF9olezya] [i-L792pr4sF9olezya] [salesforce-salesforce-1://syndesis_Lead_c?notifyForFields=ALL&notifyForOperati] [       787]
  | [i-L792pr4sF9olezya] [-L792nU19GGbI2HZOG] [Processor@0x48106381                                                          ] [         3]
  | [i-L792pr4sF9olezya] [-L792oWX9GGbI2HZOG] [atlas:mapping-step-2.json?sourceMapName=Syndesis.CAPTURED_OUT_MESSAGES_MAP    ] [       757]
  | [i-L792pr4sF9olezya] [-L792oWX9GGbI2HZOG] [Processor@0x18483b8b                                                          ] [         1]
  | [i-L792pr4sF9olezya] [-L792oA49GGbI2HZOG] [sql-stored-3                                                                  ] [        15]
  |  
  | Stacktrace
  | ---------------------------------------------------------------------------------------------------------------------------------------
  |  
  | java.lang.NullPointerException: null
  | at java.util.Hashtable.put(Hashtable.java:460) ~[na:1.8.0_151]
  | at java.util.Hashtable.putAll(Hashtable.java:524) ~[na:1.8.0_151]
  | at io.syndesis.connector.sql.common.JSONBeanUtil.parsePropertiesFromJSONBean(JSONBeanUtil.java:65) ~[connector-sql-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
  | at io.syndesis.connector.sql.customizer.SqlStoredConnectorCustomizer.doBeforeProducer(SqlStoredConnectorCustomizer.java:36) ~[connector-sql-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
  | at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
  | at io.syndesis.integration.component.proxy.ComponentProxyProducer.process(ComponentProxyProducer.java:44) ~[integration-component-proxy-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
  | at org.apache.camel.processor.SendProcessor$2.doInAsyncProducer(SendProcessor.java:178) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.impl.ProducerCache.doInAsyncProducer(ProducerCache.java:445) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:173) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:67) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at io.syndesis.integration.runtime.logging.IntegrationLoggingInterceptStrategy.lambda$wrapProcessorInInterceptors$0(IntegrationLoggingInterceptStrategy.java:45) ~[integration-runtime-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
  | at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.InterceptorToAsyncProcessorBridge.process(InterceptorToAsyncProcessorBridge.java:76) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline.access$100(Pipeline.java:43) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Pipeline$1.done(Pipeline.java:157) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.processor.Enricher$1.done(Enricher.java:237) [camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.salesforce.internal.processor.JsonRestProcessor.processResponse(JsonRestProcessor.java:218) [camel-salesforce-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.salesforce.internal.processor.AbstractRestProcessor$6.onResponse(AbstractRestProcessor.java:381) [camel-salesforce-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.salesforce.internal.client.DefaultRestClient$DelegatingClientCallback.onResponse(DefaultRestClient.java:503) [camel-salesforce-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.salesforce.internal.client.AbstractClientBase$1.onComplete(AbstractClientBase.java:218) [camel-salesforce-2.20.1.jar!/:2.20.1]
  | at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193) [jetty-client-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185) [jetty-client-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:459) [jetty-client-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:405) [jetty-client-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:297) [jetty-client-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1068) [jetty-http-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1393) [jetty-http-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:170) [jetty-client-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:131) [jetty-client-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:70) [jetty-client-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:130) [jetty-client-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:116) [jetty-client-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) [jetty-io-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104) [jetty-io-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:289) [jetty-io-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:149) [jetty-io-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104) [jetty-io-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) [jetty-io-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247) [jetty-util-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140) [jetty-util-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243) [jetty-util-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679) [jetty-util-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597) [jetty-util-9.4.7.v20170914.jar!/:9.4.7.v20170914]
  | at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
  |  
  | {"exchange":"i-L793bDcXbaU6IRwhTGhz","status":"done","failed":true}


```

**Comment by zregvart** [comment]
Fixed with #1923
