### ISSUE TITLE
Validate error for Salesforce connection

### ISSUE THREAD

**Issue by igarashitm** [syndesisio/syndesis#1991]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
When I create a Salesforce connection with filling "Client Id" and "Client Secrent"
 then leave everything else with default value, I got an empty validation error in UI and an Exception in meta pod log
```
2018-03-14 16:07:20.214 ERROR 1 --- [  XNIO-3 task-6] i.s.c.meta.VerifierExceptionMapper       : Exception while handling request: POST /api/v1/connectors/salesforce/actions/io.syndesis.connector:connector-salesforce:salesforce-on-create
--
  |  
  | org.apache.camel.RuntimeCamelException: java.lang.IllegalArgumentException: You must specify parameters aligned with one of the supported authentication methods: for username and password authentication: userName, password, clientSecret; for refresh token authentication: refreshToken, clientSecret; for JWT: userName, keystore. And for every one of those loginUrl and clientId must be specified also.
  | at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1831) ~[camel-core-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.salesforce.SalesforceMetaDataExtension.schemaFor(SalesforceMetaDataExtension.java:73) ~[camel-salesforce-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.salesforce.SalesforceMetaDataExtension.meta(SalesforceMetaDataExtension.java:51) ~[camel-salesforce-2.20.1.jar!/:2.20.1]
  | at io.syndesis.connector.support.verifier.api.ComponentMetadataRetrieval.fetchMetaData(ComponentMetadataRetrieval.java:54) ~[connector-support-verifier-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
...
Caused by: java.lang.IllegalArgumentException: You must specify parameters aligned with one of the supported authentication methods: for username and password authentication: userName, password, clientSecret; for refresh token authentication: refreshToken, clientSecret; for JWT: userName, keystore. And for every one of those loginUrl and clientId must be specified also.
--
  | at org.apache.camel.component.salesforce.SalesforceLoginConfig.getType(SalesforceLoginConfig.java:168) ~[camel-salesforce-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.salesforce.SalesforceLoginConfig.validate(SalesforceLoginConfig.java:217) ~[camel-salesforce-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.salesforce.internal.SalesforceSession.<init>(SalesforceSession.java:94) ~[camel-salesforce-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.salesforce.SalesforceComponent.createRestClient(SalesforceComponent.java:687) ~[camel-salesforce-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.salesforce.SalesforceClientTemplate.lambda$static$0(SalesforceClientTemplate.java:39) ~[camel-salesforce-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.salesforce.SalesforceClientTemplate.invoke(SalesforceClientTemplate.java:48) ~[camel-salesforce-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.salesforce.SalesforceMetaDataExtension.allObjectsSchema(SalesforceMetaDataExtension.java:62) ~[camel-salesforce-2.20.1.jar!/:2.20.1]
  | at org.apache.camel.component.salesforce.SalesforceMetaDataExtension.schemaFor(SalesforceMetaDataExtension.java:71) ~[camel-salesforce-2.20.1.jar!/:2.20.1]
  | ... 80 common frames omitted
```
## Tasks involved / Steps to Reproduce

1. In UI, go to Connections -> Create Connection
2. Choose Salesforce
3. Put "Client Id" and "Client Secrent"
4. Push "Validate"

**Comment by gashcrumb** [comment]
Going by the error message maybe eventually we can add an 'auth method' selector that could then use the `relation` support to (eventually) show only the relevant required fields.  Right now the form service only supports disabling controls until we get #887 completely sorted.
