### ISSUE TITLE
[AtlasMap] Integer Constant is treated as String

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#2051]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Similar to https://github.com/syndesisio/syndesis/issues/2050 but with the constant set to type 'Integer' and value 1.

## Expected behavior
Should be able to insert a value of 1 into the 'completed' field.

Instead the resulting integration throws the following error:

> 
> {"exchange":"i-L7j_ZX37p9Zk4j5no5Uz","status":"begin"}
> 2018-03-16 16:13:20.903 ERROR 1 --- [r://integration] o.a.camel.processor.DefaultErrorHandler  : Failed delivery for (MessageId: i-L7j_ZX57p9Zk4j5no5Vz on ExchangeId: i-L7j_ZX37p9Zk4j5no5Uz). Exhausted after delivery attempt: 1 caught: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
> 
> Message History
> ---------------------------------------------------------------------------------------------------------------------------------------
> RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
> [i-L7jZmiEvIU90a4JF] [i-L7jZmiEvIU90a4JF] [timer://integration?period=1000                                               ] [         3]
> [i-L7jZmiEvIU90a4JF] [-L7jZVXJck98mnwjQ_] [sql-stored-1                                                                  ] [         1]
> [i-L7jZmiEvIU90a4JF] [-L7jZVXJck98mnwjQ_] [Processor@0x633fe06c                                                          ] [         0]
> [i-L7jZmiEvIU90a4JF] [to1               ] [atlas:mapping-step-2.json?sourceMapName=Syndesis.CAPTURED_OUT_MESSAGES_MAP    ] [         1]
> 
> Stacktrace
> ---------------------------------------------------------------------------------------------------------------------------------------
> 
> java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
> 	at io.atlasmap.json.core.JsonFieldWriter.createValueNode(JsonFieldWriter.java:237) ~[atlas-json-core-1.33.5.jar!/:1.33.5]
> 	at io.atlasmap.json.core.JsonFieldWriter.writeValue(JsonFieldWriter.java:127) ~[atlas-json-core-1.33.5.jar!/:1.33.5]
> 	at io.atlasmap.json.core.JsonFieldWriter.write(JsonFieldWriter.java:116) ~[atlas-json-core-1.33.5.jar!/:1.33.5]
> 	at io.atlasmap.json.module.JsonModule.processTargetFieldMapping(JsonModule.java:160) ~[atlas-json-module-1.33.5.jar!/:1.33.5]
> 	at io.atlasmap.core.DefaultAtlasContext.processTargetFieldMappings(DefaultAtlasContext.java:420) ~[atlas-core-1.33.5.jar!/:1.33.5]
> 	at io.atlasmap.core.DefaultAtlasContext.process(DefaultAtlasContext.java:272) ~[atlas-core-1.33.5.jar!/:1.33.5]
> 	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:194) ~[camel-atlasmap-1.33.5.jar!/:na]
> 	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71) ~[camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) [camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) [camel-core-2.20.1.jar!/:2.20.1]
> 	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_151]
> 	at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_151]
> 
> {"exchange":"i-L7j_ZX37p9Zk4j5no5Uz","status":"done","failed":true}
> 2018-03-16 16:13:20.904  WARN 1 --- [r://integration] o.a.camel.component.timer.TimerConsumer  : Error processing exchange. Exchange[i-L7j_ZX37p9Zk4j5no5Uz]. Caused by: [java.lang.ClassCastException - java.lang.String cannot be cast to java.lang.Integer]
> 
> java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
> 	at io.atlasmap.json.core.JsonFieldWriter.createValueNode(JsonFieldWriter.java:237) ~[atlas-json-core-1.33.5.jar!/:1.33.5]
> 	at io.atlasmap.json.core.JsonFieldWriter.writeValue(JsonFieldWriter.java:127) ~[atlas-json-core-1.33.5.jar!/:1.33.5]
> 	at io.atlasmap.json.core.JsonFieldWriter.write(JsonFieldWriter.java:116) ~[atlas-json-core-1.33.5.jar!/:1.33.5]
> 	at io.atlasmap.json.module.JsonModule.processTargetFieldMapping(JsonModule.java:160) ~[atlas-json-module-1.33.5.jar!/:1.33.5]
> 	at io.atlasmap.core.DefaultAtlasContext.processTargetFieldMappings(DefaultAtlasContext.java:420) ~[atlas-core-1.33.5.jar!/:1.33.5]
> 	at io.atlasmap.core.DefaultAtlasContext.process(DefaultAtlasContext.java:272) ~[atlas-core-1.33.5.jar!/:1.33.5]
> 	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:194) ~[camel-atlasmap-1.33.5.jar!/:na]
> 	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71) ~[camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) [camel-core-2.20.1.jar!/:2.20.1]
> 	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) [camel-core-2.20.1.jar!/:2.20.1]
> 	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_151]
> 	at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_151]
> 
> {"exchange":"i-L7j_Zlg7p9Zk4j5no5Wz","status":"begin"}

**Comment by KurtStam** [comment]
Same underlying issue as #1366
