### ISSUE TITLE
StaticEditionTest - Illegal key size or default parameters

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#2302]
On my Mac I see the StaticEditionTest fail. Seems to work ok on our build environment though. 

[ERROR] Failures: 
[ERROR]   StaticEditionTest.shouldCreateEditionWithNonBase64Passwords:104 Unable to utilize encryption key: javax.crypto.spec.SecretKeySpec@17b0b
[INFO] 
[ERROR] Tests run: 67, Failures: 1, Errors: 0, Skipped: 0

java.lang.AssertionError: Unable to utilize encryption key: javax.crypto.spec.SecretKeySpec@15d1e
	at io.syndesis.server.endpoint.v1.state.StaticEditionTest$KeySourceAssert.canBeUsedForCryptography(StaticEditionTest.java:53)
	at io.syndesis.server.endpoint.v1.state.StaticEditionTest.shouldCreateEditionWithNonBase64Passwords(StaticEditionTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.security.InvalidKeyException: Illegal key size or default parameters
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)
	at javax.crypto.Cipher.implInit(Cipher.java:801)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1249)
	at javax.crypto.Cipher.init(Cipher.java:1186)
	at io.syndesis.server.endpoint.v1.state.StaticEditionTest$KeySourceAssert.canBeUsedForCryptography(StaticEditionTest.java:51)
	... 24 more

**Comment by zregvart** [comment]
This is due to the missing [Unlimited Strength Jurisdiction Policy Files](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html), you can:
 - download and install from [there](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html)
 - you can update your JVM to 8u162 that no longer imposes this restriction
 - use OpenJDK

When deployed we run on OpenJDK so that should not be an issue at runtime.

**Comment by paoloantinori** [comment]
@zregvart can we enforce a check at maven build level? at the end this should  affect only contributors, so we can add it to maven build/profile

**Comment by zregvart** [comment]
@KurtStam did installing unlimited JCE policy files help in your case, can we close this?

> @zregvart can we enforce a check at maven build level? at the end this should affect only contributors, so we can add it to maven build/profile

yup, see #2313

**Comment by KurtStam** [comment]
@zregvart I think I'd prefer to change the UnitTest? Seems like a hinderance for contributors.

**Comment by zregvart** [comment]
> @zregvart I think I'd prefer to change the UnitTest? Seems like a hinderance for contributors.

So that's debatable, we require Java 8 ATM (set in stone I), the latest Java 8 update removes that restriction policy, OpenJDK doesn't have that restriction. I'd think that users would like to be at the latest Java version. We run with OpenJDK.

So rather than adding code to handle an edge case (we're not in the 2000's any more), I'd recommend the upgrade or installing the policy files.

To change the test would also mean that we wouldn't be testing how this code is run at runtime. The code checks if 32 random characters can be used to define the encryption/authentication keys, and this is how we configure to run via an environment variable set from the template:

https://github.com/syndesisio/syndesis/blob/12f988aceefcc39c413f776c177cce689c0db6d3/install/generator/01-header.yml.mustache#L131-L142

Now, this generates a 192bit key, we could opt to configure it to use 128bit key at runtime and in the test, but that would complicate things as 128 is not divisible by 3 to be a valid BASE64 string, as expected by the key parser:

https://github.com/syndesisio/syndesis/blob/12f988aceefcc39c413f776c177cce689c0db6d3/app/server/endpoint/src/main/java/io/syndesis/server/endpoint/v1/state/StaticEdition.java#L62-L71

I even thought about removing that fallback to `String::getBytes` and mandate that the input is only BASE64. Hard to get good key entropy with just the A-Z0-9 and then `getBytes`.

**Comment by KurtStam** [comment]
Are you saying JDK8 from Oracle on OSX works? That's what I'm using:

```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```
I think we should not force users into use a particular JDK vendor, and also we should not require them to install extensions. I'm happy to require JDK 9 if that fixes things.
