### ISSUE TITLE
Support more swagger documents

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis#2319]
## This is a...

<pre><code>
[X] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

[kie-server-swagger.json.txt](https://github.com/syndesisio/syndesis/files/1895081/kie-server-swagger.json.txt) fails to import via the API connector

## Expected behavior
We can import that swagger docuemnt

## Screenshot

    2018-04-09 21:52:10.667 ERROR [-,6a9141301d362ec1,6a9141301d362ec1,false] 1 --- [  XNIO-3 task-9] s.e.v.h.e.IllegalArgumentExceptionMapper : Illegal     Argument on Call Only references to schemas are supported
    
    java.lang.IllegalArgumentException: Only references to schemas are supported
    	at io.syndesis.server.connector.generator.swagger.util.JsonSchemaHelper.determineSchemaReference(JsonSchemaHelper.java:51) ~[    server-connector-generator-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
    	at io.syndesis.server.connector.generator.swagger.UnifiedJsonDataShapeGenerator.createShapeFromProperty(UnifiedJsonDataShapeGenerator.java:249) ~[    server-connector-generator-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
    	at io.syndesis.server.connector.generator.swagger.UnifiedJsonDataShapeGenerator.createShapeFromResponse(UnifiedJsonDataShapeGenerator.java:77) ~[    server-connector-generator-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
    	at io.syndesis.server.connector.generator.swagger.UnifiedDataShapeGenerator.createShapeFromResponse(UnifiedDataShapeGenerator.java:50) ~[    server-connector-generator-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
    	at io.syndesis.server.connector.generator.swagger.SwaggerUnifiedShapeConnectorGenerator.createDescriptor(    SwaggerUnifiedShapeConnectorGenerator.java:38) ~[server-connector-generator-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
    	at io.syndesis.server.connector.generator.swagger.BaseSwaggerConnectorGenerator.configureConnector(BaseSwaggerConnectorGenerator.java:195) ~[    server-connector-generator-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
    	at io.syndesis.server.connector.generator.swagger.BaseSwaggerConnectorGenerator.generate(BaseSwaggerConnectorGenerator.java:90) ~[    server-connector-generator-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
    	at io.syndesis.server.endpoint.v1.handler.connection.CustomConnectorHandler.lambda$create$1(CustomConnectorHandler.java:94) ~[    server-endpoint-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
    	at io.syndesis.server.endpoint.v1.handler.connection.BaseConnectorGeneratorHandler.withGeneratorAndTemplate(BaseConnectorGeneratorHandler.java:52) ~[    server-endpoint-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
    	at io.syndesis.server.endpoint.v1.handler.connection.CustomConnectorHandler.create(CustomConnectorHandler.java:93) ~[    server-endpoint-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
    	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
    	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140) ~[resteasy-jaxrs-3.1.4.Final.jar!/:3.1.4.Final]

**Comment by zregvart** [comment]
There were several issues that needed to be addressed to support the provided Swagger file:
 - when parsing we threw exceptions instead of issuing warnings/errors in validation of the Swagger file (fixed in #2307)
 - performance issues with large repetitive definitions (fixed with PR #2366)
 - be more tolerant about duplicate operation IDs in the Swagger (fixed with PR #2366)
