### ISSUE TITLE
WARNING in server logs

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#2328]
2018-04-10 17:11:41.430  WARN [-,,,] 1 --- [           main] org.reflections.Reflections              : could not get type for name io.syndesis.server.endpoint.v1.state.ClientSideStateTest$Data from any class loader

org.reflections.ReflectionsException: could not get type for name io.syndesis.server.endpoint.v1.state.ClientSideStateTest$Data
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390) ~[reflections-0.9.11.jar!/:na]
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:381) [reflections-0.9.11.jar!/:na]
	at org.reflections.Reflections.<init>(Reflections.java:126) [reflections-0.9.11.jar!/:na]
	at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:276) [swagger-jaxrs-1.5.19-SNAPSHOT.jar!/:1.5.19-SNAPSHOT]
	at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:240) [swagger-jaxrs-1.5.19-SNAPSHOT.jar!/:1.5.19-SNAPSHOT]
	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:221) [swagger-jaxrs-1.5.19-SNAPSHOT.jar!/:1.5.19-SNAPSHOT]
	at io.syndesis.server.endpoint.v1.V1Application.<init>(V1Application.java:35) [server-endpoint-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_151]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_151]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_151]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [na:1.8.0_151]
	at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:150) [resteasy-jaxrs-3.1.4.Final.jar!/:3.1.4.Final]
	at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2017) [resteasy-jaxrs-3.1.4.Final.jar!/:3.1.4.Final]
	at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:341) [resteasy-jaxrs-3.1.4.Final.jar!/:3.1.4.Final]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:103) [resteasy-jaxrs-3.1.4.Final.jar!/:3.1.4.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36) [resteasy-jaxrs-3.1.4.Final.jar!/:3.1.4.Final]
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117) [undertow-servlet-1.4.21.Final.jar!/:1.4.21.Final]
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:265) [undertow-servlet-1.4.21.Final.jar!/:1.4.21.Final]
	at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:133) [undertow-servlet-1.4.21.Final.jar!/:1.4.21.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:565) [undertow-servlet-1.4.21.Final.jar!/:1.4.21.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:536) [undertow-servlet-1.4.21.Final.jar!/:1.4.21.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42) [undertow-servlet-1.4.21.Final.jar!/:1.4.21.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-1.4.21.Final.jar!/:1.4.21.Final]
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:578) [undertow-servlet-1.4.21.Final.jar!/:1.4.21.Final]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.createUndertowServer(UndertowEmbeddedServletContainer.java:209) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:155) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) [spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at io.syndesis.server.runtime.Application.main(Application.java:69) [classes!/:1.3-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [runtime.jar:1.3-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [runtime.jar:1.3-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [runtime.jar:1.3-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [runtime.jar:1.3-SNAPSHOT]
Caused by: java.lang.ClassNotFoundException: io.syndesis.server.endpoint.v1.state.ClientSideStateTest$Data
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_151]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[runtime.jar:1.3-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_151]
	at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388) ~[reflections-0.9.11.jar!/:na]
	... 43 common frames omitted

**Comment by zregvart** [comment]
That is a warning that's being displayed only if you build locally. As the reflections library picks up a class from `src/test/java`. Most likely due to Eclipse IDE not having separate source paths for `src/main/java` and `src/test/java`. This is not something that happens when we run a build from the CI.
This has been fixed in the latest Eclipse/m2e builds (not sure if available on non release candidate update sites atm).

**Comment by KurtStam** [comment]
@zregvart thx, good to know.
