### ISSUE TITLE
NPE when accessing `/api/v1/integrations`

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#2364]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

I'm seeing a NullPointerException when switching from any tab to Integrations tab in the UI.

```
java.lang.NullPointerException: null
	at io.syndesis.server.endpoint.v1.handler.integration.IntegrationHandler.toCurrentConnection(IntegrationHandler.java:352) ~[server-endpoint-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_151]
	at io.syndesis.server.endpoint.v1.handler.integration.IntegrationHandler.toCurrentSteps(IntegrationHandler.java:371) ~[server-endpoint-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_151]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_151]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_151]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_151]
	at io.syndesis.server.endpoint.v1.handler.integration.IntegrationHandler.toCurrentIntegrationOverview(IntegrationHandler.java:333) ~[server-endpoint-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_151]
	at java.util.Collections$2.tryAdvance(Collections.java:4717) ~[na:1.8.0_151]
	at java.util.Collections$2.forEachRemaining(Collections.java:4725) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_151]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_151]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_151]
	at io.syndesis.server.endpoint.v1.handler.integration.IntegrationHandler.list(IntegrationHandler.java:149) ~[server-endpoint-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
```

## Expected behavior

No exceptions.

## Screenshot

![screenshot from 2018-04-12 12-35-20](https://user-images.githubusercontent.com/1306050/38672320-1bf4feca-3e4e-11e8-96e7-527b8cdba8df.png)

## Request and Response Data

```http
GET /api/v1/integrations HTTP/1.1
Accept: application/json, text/plain, */*
```

## API Endpoints and Schemas

`GET /api/v1/integrations`

## Tasks involved / Steps to Reproduce

1. Click to Integrations tab, I think also clicking to Home tab that displays integration summary
2.
3.
4.

**Comment by zregvart** [comment]
I've deleted all rows from `jsondb` and restarted the server pod to recreate them, no longer experiencing this. Could be fiddling with jsondb that lead to this. Closing for now.
