### ISSUE TITLE
Dropbox download action, how does the file path relate to the dropbox app

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#2379]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Documentation issue or request
</code></pre>

This is like a question and maybe a bug report?

## The problem

On this screen in the integration editor:

![capture](https://user-images.githubusercontent.com/351660/38742900-b48b9172-3f0b-11e8-8e17-5c485d9413a1.PNG)

How does this path relate to the app I create in dropbox when I obtain my access token?  In my case I opted to limit the app I created (`Syndesis-gashcrumb`) to a folder, which means that Dropbox creates `/App/Syndesis-gashcrumb` in my dropbox.  So I kinda like want to get anything in that folder.  But since this is a required field, I can't leave it blank.  I put a space in which passes the validation :-) but should it be '*'?  Seems like the text could use some improvement here.

**Comment by gashcrumb** [comment]
@TovaCohen is this in the docs and I'm just obtuse? :-)

**Comment by gashcrumb** [comment]
One other question on the dropbox connector, it's currently untyped but like, it's gonna give me a file object of some kind right?  How is that going to work in an integration?

**Comment by TovaCohen** [comment]
Pinging @oscerd who answered my questions about Dropbox. 
The doc does not address this. I think I was assuming that if you specify a folder when you create the Dropbox app then you would specify the same folder when you configure the Dropbox action. Andrea? can you clarify this and I will be happy to update the doc accordingly. Also pinging @mcada who is doing the QE review of the doc.

**Comment by mcada** [comment]
I just tested it, the path is relative to the access of your app. So if you have access only to "/some/folder/" specifying "/" will download all files from "/some/folder/". 

But it looks like it only works for files. When I added folder ("/some/folder/new") the integration failed with error caused by [this line.](https://github.com/apache/camel/blob/b4c0fbbe0bc9643158353c395b3629f02a0a781b/components/camel-dropbox/src/main/java/org/apache/camel/component/dropbox/core/DropboxAPIFacade.java#L372) 
Dropbox api v2 has methods for downloading whole folders as .zip, but no such option is in syndesis dropbox connection. Maybe we should consider implementing this option into Dropbox connector? Let user specify if it is folder to be downloaded or file and act accordingly?

**Comment by oscerd** [comment]
Looking at the doc downloading a folder should work fine. 

https://github.com/apache/camel/blob/master/components/camel-dropbox/src/main/docs/dropbox-component.adoc

Did you try with only "/new" as remotePath to download the folder?

**Comment by oscerd** [comment]
In my opinion, by the way, the connector should do what the camel component does. If we start adding new stuff, new API usage and so on, we'll diverge too much from the camel codebase and we will need to maintain a second version of Camel components. So I'm against adding features that are not in related camel component.

**Comment by mcada** [comment]
@oscerd With "/new" I have an error:

```
WARN 1 --- [- dropbox://get] .c.d.i.c.DropboxScheduledPollGetConsumer : Error processing exchange. Exchange[i-LADHnoeSC-0YKLTEbH6z]. Caused by: [org.apache.camel.component.dropbox.util.DropboxException - option <remotePath> is not valid!]

org.apache.camel.component.dropbox.util.DropboxException: option <remotePath> is not valid!
	at org.apache.camel.component.dropbox.validator.DropboxConfigurationValidator.validateRemotePathForPut(DropboxConfigurationValidator.java:88) ~[camel-dropbox-2.21.0.jar!/:2.21.0]
	at org.apache.camel.component.dropbox.validator.DropboxConfigurationValidator.validatePutOp(DropboxConfigurationValidator.java:48) ~[camel-dropbox-2.21.0.jar!/:2.21.0]
	at org.apache.camel.component.dropbox.integration.producer.DropboxPutProducer.process(DropboxPutProducer.java:47) ~[camel-dropbox-2.21.0.jar!/:2.21.0]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.21.0.jar!/:2.21.0]
	at io.syndesis.integration.component.proxy.ComponentProxyProducer.process(ComponentProxyProducer.java:44) ~[integration-component-proxy-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.component.dropbox.integration.consumer.DropboxScheduledPollGetConsumer.poll(DropboxScheduledPollGetConsumer.java:67) ~[camel-dropbox-2.21.0.jar!/:2.21.0]
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174) [camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101) [camel-core-2.21.0.jar!/:2.21.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
```

with "/new/" it works: it will download files from /myrestrictedaccessfolder/new/* but if I have another folder inside ("/new/asdf") it it throws exception:

```
Caused by: [org.apache.camel.component.dropbox.util.DropboxException - /new/asdf does not exist or cannot obtain metadata]

org.apache.camel.component.dropbox.util.DropboxException: /new/asdf does not exist or cannot obtain metadata
	at org.apache.camel.component.dropbox.core.DropboxAPIFacade.downloadSingleFile(DropboxAPIFacade.java:372) ~[camel-dropbox-2.21.0.jar!/:2.21.0]
	at org.apache.camel.component.dropbox.core.DropboxAPIFacade.downloadFilesInFolder(DropboxAPIFacade.java:339) ~[camel-dropbox-2.21.0.jar!/:2.21.0]
	at org.apache.camel.component.dropbox.core.DropboxAPIFacade.get(DropboxAPIFacade.java:331) ~[camel-dropbox-2.21.0.jar!/:2.21.0]
	at org.apache.camel.component.dropbox.integration.consumer.DropboxScheduledPollGetConsumer.poll(DropboxScheduledPollGetConsumer.java:44) ~[camel-dropbox-2.21.0.jar!/:2.21.0]
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174) [camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101) [camel-core-2.21.0.jar!/:2.21.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: com.dropbox.core.v2.files.DownloadErrorException: Exception in 2/files/download: {".tag":"path","path":"not_file"}
	at com.dropbox.core.v2.files.DbxUserFilesRequests.download(DbxUserFilesRequests.java:906) ~[dropbox-core-sdk-3.0.6.jar!/:na]
	at com.dropbox.core.v2.files.DbxUserFilesRequests.download(DbxUserFilesRequests.java:925) ~[dropbox-core-sdk-3.0.6.jar!/:na]
	at org.apache.camel.component.dropbox.core.DropboxAPIFacade.downloadSingleFile(DropboxAPIFacade.java:363) ~[camel-dropbox-2.21.0.jar!/:2.21.0]
	... 12 common frames omitted
```

You can see that the error is that it expects file, but in fact it is a folder.

**Comment by mcada** [comment]
What is the final decision here? Do we just write in docs that one can work only with files and not folders? Current docs are not correct.

**Comment by TovaCohen** [comment]
For the "Download from Dropbox" action, I have this in the doc:

> To configure the action, in the **Folder or file name path to download** field, specify the filename path or the folder path for the content that you want the integration to obtain. 

For GA, is it enough and correct to remove "or the folder path", so we have this:

> To configure the action, in the **Folder or file name path to download** field, specify the filename path for the content that you want the integration to obtain. 

For GA, can I edit the dropbox.json file to update the field label and the hint to make it clear that you have to specify a file?

**Comment by mcada** [comment]
As download works 100% correctly only with files, we should remove folder path for now.

**Comment by TovaCohen** [comment]
Okay. Thanks. Since the field label indicates that you can enter a folder, I updated the doc to:

To configure the action, in the *Folder or file name path to download* field, specify the filename path for the content that you want the integration to obtain. In this release, the specification of a folder name
might not work correctly.
