### ISSUE TITLE
SIGSEGV on redeploy

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#2428]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Sometimes the integration pod crashes while editing and redeploying an integration:

```
i-db2db2-5-9prjm i-db2db2 Starting the Java application using /opt/run-java/run-java.sh ...
i-db2db2-5-9prjm i-db2db2 exec java -javaagent:/opt/jolokia/jolokia.jar=config=/opt/jolokia/etc/jolokia.properties -javaagent:/opt/prometheus/jmx_prometheus_javaagent.jar=9779:/tmp/src/prometheus-config.yml -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/project-0.1-SNAPSHOT.jar
i-db2db2-5-9prjm i-db2db2 FATAL ERROR in native method: processing of -javaagent failed
i-db2db2-5-9prjm i-db2db2 #
i-db2db2-5-9prjm i-db2db2 # A fatal error has been detected by the Java Runtime Environment:
i-db2db2-5-9prjm i-db2db2 #
i-db2db2-5-9prjm i-db2db2 #  SIGSEGV (0xb) at pc=0x00007f2a6e433a37, pid=1, tid=0x00007f2a6f21b700
i-db2db2-5-9prjm i-db2db2 #
i-db2db2-5-9prjm i-db2db2 # JRE version: OpenJDK Runtime Environment (8.0_151-b12) (build 1.8.0_151-b12)
i-db2db2-5-9prjm i-db2db2 # Java VM: OpenJDK 64-Bit Server VM (25.151-b12 mixed mode linux-amd64 compressed oops)
i-db2db2-5-9prjm i-db2db2 # Problematic frame:
i-db2db2-5-9prjm i-db2db2 # C  [libc.so.6+0x36a37]  abort+0x297
i-db2db2-5-9prjm i-db2db2 #
i-db2db2-5-9prjm i-db2db2 # Core dump written. Default location: /deployments/core or core.1
i-db2db2-5-9prjm i-db2db2 #
i-db2db2-5-9prjm i-db2db2 # An error report file with more information is saved as:
i-db2db2-5-9prjm i-db2db2 # /deployments/hs_err_pid1.log
i-db2db2-5-9prjm i-db2db2 #
i-db2db2-5-9prjm i-db2db2 # If you would like to submit a bug report, please visit:
i-db2db2-5-9prjm i-db2db2 #   http://bugreport.java.com/bugreport/crash.jsp
i-db2db2-5-9prjm i-db2db2 #
i-db2db2-5-9prjm i-db2db2 [error occurred during error reporting , id 0xb]
...
i-db2db2-5-9prjm i-db2db2 [error occurred during error reporting , id 0xb]
i-db2db2-5-9prjm i-db2db2 [Too many errors, abort]
...
i-db2db2-5-9prjm i-db2db2 [Too many errors, abort]
i-db2db2-5-9prjm i-db2db2 	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
i-db2db2-5-9prjm i-db2db2 	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
i-db2db2-5-9prjm i-db2db2 Caused by: java.io.FileNotFoundException: /tmp/src/prometheus-config.yml (No such file or directory)
i-db2db2-5-9prjm i-db2db2 	at java.io.FileInputStream.open0(Native Method)
i-db2db2-5-9prjm i-db2db2 	at java.io.FileInputStream.open(FileInputStream.java:195)
i-db2db2-5-9prjm i-db2db2 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
i-db2db2-5-9prjm i-db2db2 	at java.io.FileReader.<init>(FileReader.java:72)
i-db2db2-5-9prjm i-db2db2 	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<init>(JmxCollector.java:74)
i-db2db2-5-9prjm i-db2db2 	at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:36)
i-db2db2-5-9prjm i-db2db2 	... 6 more
```

## Expected behavior

It should not crash :)

## Env
- minishift v1.16.0+8abe845
- openshift v3.7.1+a8deba5-34
- iso centos

**Comment by paoloantinori** [comment]
The most relevant issue here is: should this phase never occur at all if the whole process failed at a previous step?

**Comment by rhuss** [comment]
Actually when the build fails there should be no image created at all. It the `assemble` script fails but the build doesn't detect this, then there should be still the `/tmp/src/prometheus-config.yml` as has been added in the build input at 
https://github.com/syndesisio/syndesis/blob/fd3cb3a543b7bdaa7e6e88aec6c0306f53432515/app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java#L272
However, in

**Comment by heiko-braun** [comment]
Closing as out of date
