### ISSUE TITLE
[Upgrade] After upgrading, syndesis-server pod uses old secret due to unexpected restart during upgrade process

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#2462]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Background
I'm running update script directly from the repo, not from the syndesis-upgrade docker image.. I'm running penultimate daily release and I want to upgrade to latest daily release - I changed "latest" to "1.3.5-2018XXXX" in install/syndesis.yml and then run the same command as in the docker file:

```
./upgrade.sh --template <PATH_TO_SYNDESIS_REPO>/install/syndesis.yml --migration migration --oc-login "<OC_LOGIN_CMD>"
```
## The problem

When upgrading syndesis infrastructure on my local minishift installation, I see two failure outcomes of the upgrade process (both tied to syndesis-server pod):
- (Less often) the pod does not start because of :

```
"MountVolume.SetUp failed for volume "syndesis-server-token-2bkpt" : secrets "syndesis-server-token-2bkpt" not found"
```

- (More often) the pod does start, but logs this repetitively:

```
2018-04-23 12:48:24.271 ERROR [-,,,] 1 --- [Logs Controller] i.s.s.l.j.c.ActivityTrackingController   : Unexpected Error occurred.
 
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://openshift.default.svc/api/v1/namespaces/myproject/pods?labelSelector=syndesis.io/component%3Dintegration . Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked. Unauthorized
.
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470) ~[kubernetes-client-2.4.1.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:407) ~[kubernetes-client-2.4.1.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379) ~[kubernetes-client-2.4.1.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343) ~[kubernetes-client-2.4.1.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327) ~[kubernetes-client-2.4.1.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:583) ~[kubernetes-client-2.4.1.jar!/:na]
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:68) ~[kubernetes-client-2.4.1.jar!/:na]
        at io.syndesis.server.logging.jsondb.controller.ActivityTrackingController.listPods(ActivityTrackingController.java:217) ~[server-logging-jsondb-1.3.5-20180422.jar!/:1.3.5-20180422]
        at io.syndesis.server.logging.jsondb.controller.ActivityTrackingController.pollPods(ActivityTrackingController.java:162) ~[server-logging-jsondb-1.3.5-20180422.jar!/:1.3.5-20180422]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
```

This is probably related to the fact that `upgrade_40_update_resources` pushes the DeploymentConfig back to openshift and it causes a new deployment automatically due to the image change trigger - so all your pods will start again in this "phase". You can reproduce this easily by adding a sleep 120 before scaling pods to 1 in `upgrade_60_restart_all` and you will see that the pods are already running again even before scaling up.

**If I delete/scale down and up the syndesis-server pod after failed/broken update of this pod, everything work normally**, so I assume it is a timing issue when the deployment config operates with inconsistent secrets

cc @rhuss @paoloantinori @dsimansk 

## Tasks involved / Steps to Reproduce

1. minishift with syndesis 2018-XXX1
2. edit the install/syndesis.yml to use version 2018-XXX2
3. comment out `scale_deployments 1 ${deployments}` from `steps/upgrade_60_restart_all`
4. call upgrade script
4. observe that after upgrading the pods are running even without the last upscale

**Comment by paoloantinori** [comment]
According to the above analysis I have added this quick patch.
Probably not the final solution but it should mitigate the issue.

**Comment by dsimansk** [comment]
@paoloantinori both referenced PRs were closed. Didn't it mitigate the issue?

**Comment by rhuss** [comment]
@avano you are absolutely correct that the patch of the deployment triggres a deployment if changed. I've seen this behaviour, too, but haven't experienced any issues yet. The final scale to 1 is a no-op if the deployment is already up.

It looks more like an issue with service accounts and their update. I wonder, whether we should skip this update or do it first ?

**Comment by avano** [comment]
@rhuss maybe the re-ordering may work, as currently the upgrade takes the folders sorted alphabetically, so in this order: `BuildConfig  ConfigMap  DeploymentConfig  ImageStream  PersistentVolumeClaim  RoleBinding  Route  Secret  Service  ServiceAccount  Template`

**Comment by rhuss** [comment]
Not sure that it is relaly fixed. @avano could you verify whether this helps ? Otherwise I need to check better how to update the ServiceAccounts. Might be that we need a proper ordering.

**Comment by avano** [comment]
@rhuss sorry @rhuss , Zoran was much faster than me :-) With your PR it looks good - upgrade -  5 tries, 5 successes. However I created a new issue for rollback (initially it was affected by the scaling issues as well so I couldn't try)

**Comment by paoloantinori** [comment]
hi @avano do you confirm that the issues is fixed for you? can we close this?

**Comment by avano** [comment]
@paoloantinori sorry, forgot to close this :-) upgrade works ok with #2493
