### ISSUE TITLE
Integration data buckets are not working

### ISSUE THREAD

**Issue by mcada** [syndesisio/syndesis#2489]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Integration with with more data buckets does not work and throws error:

```
2018-04-27 09:24:44.615  WARN 1 --- [r://integration] o.a.camel.component.timer.TimerConsumer  : Error processing exchange. Exchange[i-LB5PoTP8--C4zmSirFYz]. Caused by: [io.atlasmap.api.AtlasException - Errors: [Source document '-LB5Ox45jJWJ_mHtrd3E' doesn't exist: docId='-LB5Ox45jJWJ_mHtrd3E', path='/first_name'], ]

io.atlasmap.api.AtlasException: Errors: [Source document '-LB5Ox45jJWJ_mHtrd3E' doesn't exist: docId='-LB5Ox45jJWJ_mHtrd3E', path='/first_name'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:213) ~[camel-atlasmap-1.34.2.jar!/:na]
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.21.0.jar!/:2.21.0]
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:77) ~[integration-runtime-1.3-SNAPSHOT.jar!/:1.3-SNAPSHOT]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:711) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:634) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:248) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.Splitter.process(Splitter.java:114) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) [camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) [camel-core-2.21.0.jar!/:2.21.0]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_151]
	at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_151]

```

## Expected behavior

Integration should work as expected, all previous data buckets should be available and functional from each data mapper step.

## Tasks involved / Steps to Reproduce

1. Create integration as follows: 
start:    PostgreDB (periodicSQL): _select * from contact limit 1_
            PostgreDB (invokeSQL) : _select * from contact limit 1_
            Data Mapper: map field company **from the first** data bucket to COMPANY
finish:   PostgreDB: _select * from contact where company = :#COMPANY_

2. Publish the integration. Check openshift logs for this integration pod, there you can see mentioned error.

**Comment by dsimansk** [comment]
@igarashitm might this be caused by upgrade to latest Atlasmap release?

**Comment by dsimansk** [comment]
@lburgazzoli or could it be caused by changes introduced in https://github.com/syndesisio/syndesis/pull/2470?

**Comment by dsimansk** [comment]
@lburgazzoli @igarashitm I've tried yesterday's tag `1.3.5-20180426` prior PR #2470 and Databuckers works fine. I'd say that this is most probably a side effect of #2470.

**Comment by igarashitm** [comment]
So this symptom looks very similar to #1701, the link between step ID and captured output message map is out of sync. Was there any change in the internal camel route which break that map @lburgazzoli ?

**Comment by igarashitm** [comment]
Hmm I can't reproduce this. Tried with today's upstream master and working fine.

**Comment by chirino** [comment]
nice catch.

**Comment by igarashitm** [comment]
verified locally that #2502 fixed this.

**Comment by paoloantinori** [comment]
Thanks Tomo!

**Comment by mcada** [comment]
Tests are passing again, good job!
