### ISSUE TITLE
Deleting a connection which is used by an integration leads to inconsistent state

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#2524]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

After an import of integration with a broken connection (because of missing OAuth dance, see #2522), deleting the connection is possible without warning (e.g. "is used in an existing integration"). After the deletion, the following error happens on the integration overview:

![image](https://user-images.githubusercontent.com/99080/39515763-55e79360-4dfb-11e8-8a85-a67e92da40d7.png)

and in the server logs there's a NPE:

```
2018-05-02 09:24:07.765  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Checking integrations for their status.
2018-05-02 09:24:23.529 ERROR [-,bbc75ec8b624358d,bbc75ec8b624358d,false] 1 --- [  XNIO-3 task-8] .s.e.v.h.e.SyndesisServerExceptionMapper : Internal Server Exception. null

java.lang.NullPointerException: null
	at io.syndesis.server.endpoint.v1.handler.integration.IntegrationHandler.toCurrentConnection(IntegrationHandler.java:352) ~[server-endpoint-1.3.5-20180502.jar!/:1.3.5-20180502]
	at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_151]
	at io.syndesis.server.endpoint.v1.handler.integration.IntegrationHandler.toCurrentSteps(IntegrationHandler.java:371) ~[server-endpoint-1.3.5-20180502.jar!/:1.3.5-20180502]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_151]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_151]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_151]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_151]
	at io.syndesis.server.endpoint.v1.handler.integration.IntegrationHandler.toCurrentIntegrationOverview(IntegrationHandler.java:333) ~[server-endpoint-1.3.5-20180502.jar!/:1.3.5-20180502]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_151]
	at java.util.Collections$2.tryAdvance(Collections.java:4717) ~[na:1.8.0_151]
	at java.util.Collections$2.forEachRemaining(Collections.java:4725) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_151]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_151]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_151]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_151]
	at io.syndesis.server.endpoint.v1.handler.integration.IntegrationHandler.list(IntegrationHandler.java:149) ~[server-endpoint-1.3.5-20180502.jar!/:1.3.5-20180502]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
```

**Comment by zregvart** [comment]
Related to #2123, #1827 and  #1442

**Comment by paoloantinori** [comment]
Due to the late moment, I've discussed this with @aileenc and we were thinking to entirely disable the ability to delete a connection if it's identified as in use.

This affects the UX but it should be relatively easy to implement server side and client side.

Any major objection to this?

**Comment by paoloantinori** [comment]
@rhuss @chirino  are you okay with the proposal? I don't think we have time for any other option.

**Comment by rhuss** [comment]
I'm fine with that.

**Comment by mastepan** [comment]
CR1:
1. create a custom connector
2. create a connection from that connector
3. delete the connector.
* there remains the connection that is editable - its good. It wasn't before.
**4. Create an integration using the connection created from the deleted connector - FAILS**

Please take a look at it. Thanks.

**Comment by lburgazzoli** [comment]
@mastepan can you add some logs, screenshot ?

**Comment by mastepan** [comment]
@lburgazzoli 
[server_pod.log](https://github.com/syndesisio/syndesis/files/1987012/server_pod.log)
![connectionclicked](https://user-images.githubusercontent.com/8707251/39804805-5e586e8c-5375-11e8-8467-3df126ee2148.png)

**Comment by lburgazzoli** [comment]
I did try to follow your steps:

1. upload s[yndesis-connector-telegram](https://github.com/syndesisio/syndesis-extensions/tree/master/syndesis-connector-telegram) extension
2. set-up a new connection from the telegram, connector
3. delete the extension
4. open Connections: the connection related to telegram has disappeared
5. create an Integration: the connection related to telegram is not available

Am I doing something wrong ?

**Comment by mastepan** [comment]
@lburgazzoli I'm not sure how it works with extensions.
I just created Petstore custom connector and a connection from that (Customizations - API Client Connectors)
[http://petstore.swagger.io/v2/swagger.json](http://petstore.swagger.io/v2/swagger.json)
![useurl](https://user-images.githubusercontent.com/8707251/39810687-3663154c-5386-11e8-9a71-d4d9f85e474b.png)

![accesstokenurl](https://user-images.githubusercontent.com/8707251/39810708-4c218e36-5386-11e8-8380-bd5e57f1651c.png)

If you need any other info, just ask.

**Comment by lburgazzoli** [comment]
Ah ok, that's different thing. 

Can you open a new issue ?

**Comment by mastepan** [comment]
Sure I can. Different from what? This issue is all I have found so far that - at least I think might have affected behavior of custom connectors deleting. Is it right?

**Comment by lburgazzoli** [comment]
The workflow for custom connectors created via Swagger is different from connectors created via i.e. an extensions so there maybe something missing in that workflow

**Comment by mastepan** [comment]
-
