### ISSUE TITLE
Extensions Maven plugin requires specific Maven version

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#2999]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Documentation issue or request
</code></pre>

## The problem

Seems that the Extensions Maven Plugin requires specific Maven version, it works with 3.5.2, doesn't with 3.3.9. Do we care about this? Should the plugin check for Maven version? Should we make it run on older Maven versions (and how far back)?

**Comment by paoloantinori** [comment]
What's the error?

**Comment by zregvart** [comment]
An ugly one: [error.log](https://github.com/syndesisio/syndesis/files/2241080/error.log)

**Comment by lburgazzoli** [comment]
keep it open

**Comment by lburgazzoli** [comment]
keep it open

**Comment by tadayosi** [comment]
I used Maven 3.6.0 to build the syndesis-extensions project but got this error:
```
[ERROR] Failed to execute goal io.syndesis.extension:extension-maven-plugin:1.3.10:repackage-extension (default) on project syndesis-connector-irc: Execution default of goal io.syndesis.extension:extension-maven-plugin:1.3.10:repackage-extension failed: Unable to invoke onlyOne([Ljava.lang.Class;@6bf0f70a) on object org.jboss.shrinkwrap.resolver.spi.loader.ServiceRegistry with parameters [Ljava.lang.Object;@5310e451: InvocationTargetException: Could not create new service instance: org/eclipse/aether/internal/impl/DefaultDependencyCollector: org.eclipse.aether.internal.impl.DefaultDependencyCollector -> [Help 1]
```
It says version 1.3.10 but I'm sure 1.6-SNAPSHOT has the same problem with Maven 3.6.0.

**Comment by iledarn** [comment]
The same issue I have when trying to build mssql jdbc library extension.
With maven 3.6 I had `Unable to invoke onlyOne([Ljava.lang.Class;@6bf0f70a) on object org.jboss.shrinkwrap.resolver.spi.loader.ServiceRegistry`
But I've BUILD SUCCESS with maven 3.5.4
Here are the steps to install
https://gist.github.com/iledarn/038085951541ef165b70b29642a15184

**Comment by lhein** [comment]
This issue occurs with Maven Versions 3.6.x while 3.5.4 is still working.

**Comment by apupier** [comment]
full stack when activating debug output:

```
[ERROR] Failed to execute goal io.syndesis.extension:extension-maven-plugin:1.3.12.fuse-000001-redhat-2:repackage-extension (default) on project custom-step-camel: Execution default of goal io.syndesis.extension:extension-maven-plugin:1.3.12.fuse-000001-redhat-2:repackage-extension failed: Unable to invoke onlyOne([Ljava.lang.Class;@57151b3a) on object org.jboss.shrinkwrap.resolver.spi.loader.ServiceRegistry with parameters [Ljava.lang.Object;@26457986: InvocationTargetException: Could not create new service instance: org/eclipse/aether/internal/impl/DefaultDependencyCollector: org.eclipse.aether.internal.impl.DefaultDependencyCollector -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.syndesis.extension:extension-maven-plugin:1.3.12.fuse-000001-redhat-2:repackage-extension (default) on project custom-step-camel: Execution default of goal io.syndesis.extension:extension-maven-plugin:1.3.12.fuse-000001-redhat-2:repackage-extension failed: Unable to invoke onlyOne([Ljava.lang.Class;@57151b3a) on object org.jboss.shrinkwrap.resolver.spi.loader.ServiceRegistry with parameters [Ljava.lang.Object;@26457986
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal io.syndesis.extension:extension-maven-plugin:1.3.12.fuse-000001-redhat-2:repackage-extension failed: Unable to invoke onlyOne([Ljava.lang.Class;@57151b3a) on object org.jboss.shrinkwrap.resolver.spi.loader.ServiceRegistry with parameters [Ljava.lang.Object;@26457986
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	... 20 more
Caused by: org.jboss.shrinkwrap.resolver.api.Invokable$InvocationException: Unable to invoke onlyOne([Ljava.lang.Class;@57151b3a) on object org.jboss.shrinkwrap.resolver.spi.loader.ServiceRegistry with parameters [Ljava.lang.Object;@26457986
	at org.jboss.shrinkwrap.resolver.api.Invokable.invokeMethod(Invokable.java:109)
	at org.jboss.shrinkwrap.resolver.api.ResolverSystemFactory.createFromUserView(ResolverSystemFactory.java:93)
	at org.jboss.shrinkwrap.resolver.api.ResolverSystemFactory.createFromUserView(ResolverSystemFactory.java:54)
	at org.jboss.shrinkwrap.resolver.api.Resolvers.use(Resolvers.java:75)
	at org.jboss.shrinkwrap.resolver.api.maven.Maven.resolver(Maven.java:36)
	at io.syndesis.extension.maven.plugin.RepackageExtensionMojo.obtainBomDependencies(RepackageExtensionMojo.java:262)
	at io.syndesis.extension.maven.plugin.RepackageExtensionMojo.addDefaultBOMs(RepackageExtensionMojo.java:218)
	at io.syndesis.extension.maven.plugin.RepackageExtensionMojo.getAdditionalFilters(RepackageExtensionMojo.java:133)
	at io.syndesis.extension.maven.plugin.SupportMojo.filterDependencies(SupportMojo.java:94)
	at org.springframework.boot.maven.RepackageMojo.repackage(RepackageMojo.java:211)
	at org.springframework.boot.maven.RepackageMojo.execute(RepackageMojo.java:204)
	at io.syndesis.extension.maven.plugin.SupportMojo.execute(SupportMojo.java:50)
	at io.syndesis.extension.maven.plugin.RepackageExtensionMojo.execute(RepackageExtensionMojo.java:113)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	... 21 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.shrinkwrap.resolver.api.Invokable.invokeMethod(Invokable.java:100)
	... 34 more
Caused by: java.lang.RuntimeException: Could not create new service instance
	at org.jboss.shrinkwrap.resolver.spi.loader.SpiServiceLoader.createInstance(SpiServiceLoader.java:251)
	at org.jboss.shrinkwrap.resolver.spi.loader.SpiServiceLoader.createInstances(SpiServiceLoader.java:211)
	at org.jboss.shrinkwrap.resolver.spi.loader.SpiServiceLoader.all(SpiServiceLoader.java:79)
	at org.jboss.shrinkwrap.resolver.spi.loader.SpiServiceLoader.onlyOne(SpiServiceLoader.java:85)
	at org.jboss.shrinkwrap.resolver.spi.loader.ServiceRegistry.onlyOne(ServiceRegistry.java:102)
	... 39 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.shrinkwrap.resolver.spi.loader.SpiServiceLoader.createInstance(SpiServiceLoader.java:247)
	... 43 more
Caused by: java.lang.NoClassDefFoundError: org/eclipse/aether/internal/impl/DefaultDependencyCollector
	at org.jboss.shrinkwrap.resolver.impl.maven.bootstrap.ShrinkWrapResolverServiceLocator.<init>(ShrinkWrapResolverServiceLocator.java:157)
	at org.jboss.shrinkwrap.resolver.impl.maven.bootstrap.MavenRepositorySystem.getRepositorySystem(MavenRepositorySystem.java:162)
	at org.jboss.shrinkwrap.resolver.impl.maven.bootstrap.MavenRepositorySystem.<init>(MavenRepositorySystem.java:61)
	at org.jboss.shrinkwrap.resolver.impl.maven.ConfigurableMavenWorkingSessionImpl.<init>(ConfigurableMavenWorkingSessionImpl.java:58)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.<init>(MavenWorkingSessionImpl.java:122)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenResolverSystemImpl.<init>(MavenResolverSystemImpl.java:43)
	... 48 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.internal.impl.DefaultDependencyCollector
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 54 more
```

**Comment by paoloantinori** [comment]
maven 3.6 has changed its api (...)
Shrinkwrap searches for a class that is not found.
We have tried adding the specific library version that contains that class as a plugin dependency, directly in the `<build>` node but that didn't work. I suspect that's because the same package is served from another jar that loads earlier.

The only solution I see is to either patch shrinkwrap (there is no fresh version fixing the bug atm) or repackaging either shrinkwrap or the extension plugin to shade in the missing class.

Probably the second solution is the only one we can work in isolation.

**Comment by apupier** [comment]
reported the issue upstream https://issues.jboss.org/browse/SHRINKWRAP-524

**Comment by apupier** [comment]
> maven 3.6 has changed its api

They have not really changed it. the class which was used was marked as internal ( org.eclipse.aether.internal.impl.DefaultDependencyCollector )

**Comment by lhein** [comment]
yes and the class has been moved into another package.

**Comment by apupier** [comment]
Created https://github.com/syndesisio/syndesis-extensions/issues/81 to drive users until Maven 3.6+ is supported

**Comment by zregvart** [comment]
Should be fixed, we depend on Maven 3.6.x throughout.
