### ISSUE TITLE
Activity shows 'No Errors' even if there are exceptions in pod's log

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#3150]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
I have no errors in activity when I have exeptions in logs: 
![screen shot 2018-07-23 at 11 53 24](https://user-images.githubusercontent.com/6814482/43070090-27634d18-8e6f-11e8-8cdb-4b0da2e55d9a.png)
```

{"exchange":"i-LI5UK7y2B2_hQp5ECQsz","step":"-LHs62QN3UerPfOI7WY5","id":"i-LI5ULMF2B2_hQp5ECQyz","duration":5742271}
--
  | {"exchange":"i-LI5UK7y2B2_hQp5ECQsz","step":"-LHs62QN3UerPfOI7WY5","id":"i-LI5UK832B2_hQp5ECQvz","duration":5010080407}
  | {"exchange":"i-LI5UK7y2B2_hQp5ECQsz","status":"done","failed":false}
  | {"exchange":"i-LI5ULMd2B2_hQp5ECQzz","status":"begin"}
  | {"exchange":"i-LI5ULMd2B2_hQp5ECQzz","step":"-LHs6Abi3UerPfOI7WY5","id":"i-LI5ULMe2B2_hQp5ECR-z","duration":5323750}
  | {"exchange":"i-LI5ULMd2B2_hQp5ECQzz","step":"-LHs5Slz3UerPfOI7WY4","id":"i-LI5UM_s2B2_hQp5ECR2z","duration":8553316}
  | {"exchange":"i-LI5ULMd2B2_hQp5ECQzz","step":"-LHs7t9A3UerPfOI7WY7","id":"i-LI5UMa02B2_hQp5ECR3z","message":"Body: [bigger] Log zo syndesisu"}
  | 2018-07-23 09:34:29.249  INFO 1 --- [ Session Task-2] -LHs5Eft3UerPfOI7WY4                     : Body: [bigger] Log zo syndesisu
  | {"exchange":"i-LI5ULMd2B2_hQp5ECQzz","step":"-LHs7t9A3UerPfOI7WY7","id":"i-LI5UMa02B2_hQp5ECR3z","duration":392309}
  | 2018-07-23 09:34:29.250  WARN 1 --- [ Session Task-2] i.s.i.runtime.util.JsonSimplePredicate   : Unable to apply simple filter to the given payload
  | 2018-07-23 09:34:29.250 DEBUG 1 --- [ Session Task-2] i.s.i.runtime.util.JsonSimplePredicate   : Unable to parse incoming message body as JSON needed for simple filtering
  | com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'bigger': was expecting ('true', 'false' or 'null')
  | at [Source: org.apache.camel.converter.stream.InputStreamCache@1cec5123; line: 1, column: 13]
  | at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3528) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2686) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3850) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2938) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at io.syndesis.integration.runtime.util.JsonSimplePredicate.matches(JsonSimplePredicate.java:91) ~[integration-runtime-1.4-SNAPSHOT.jar!/:1.4-SNAPSHOT]
  | at org.apache.camel.processor.FilterProcessor.matches(FilterProcessor.java:65) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.FilterProcessor.process(FilterProcessor.java:51) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79) [integration-runtime-1.4-SNAPSHOT.jar!/:1.4-SNAPSHOT]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelayProcessorSupport.processDelay(DelayProcessorSupport.java:100) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelayProcessorSupport.process(DelayProcessorSupport.java:168) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79) [integration-runtime-1.4-SNAPSHOT.jar!/:1.4-SNAPSHOT]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.sjms.consumer.InOnlyMessageHandler.handleMessage(InOnlyMessageHandler.java:65) [camel-sjms-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.sjms.consumer.AbstractMessageHandler.onMessage(AbstractMessageHandler.java:86) [camel-sjms-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1401) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.ActiveMQSessionExecutor.dispatch(ActiveMQSessionExecutor.java:131) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:202) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133) [activemq-client-5.14.5.jar!/:5.14.5]
  | at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48) [activemq-client-5.14.5.jar!/:5.14.5]
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
  | at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

```
`

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by heiko-braun** [comment]
@mmelko Can you add the steps that lead to the error in the logs? That would help us to reproduce the issue

**Comment by mmelko** [comment]
@heiko-braun it's actually related to https://github.com/syndesisio/syndesis/issues/3149. After some investigation it looks like mentioned exceptions are harmless and doesn't affect activity.  So I believe we can close this.
