### ISSUE TITLE
Missing info in activities after running integration for couple of hours 

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#3337]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
I have scenario consist of 6 integration with 3messages/s in total. After couple of hours of running (~4 hours 60000 messages)  I'm missing steps infromations in activities:
No steps:
<img width="1228" alt="screen shot 2018-08-07 at 16 39 02" src="https://user-images.githubusercontent.com/6814482/43782945-c7812eb2-9a60-11e8-994e-79722958f0b0.png">
<img width="1211" alt="screen shot 2018-08-07 at 16 42 34" src="https://user-images.githubusercontent.com/6814482/43783000-ecba83d6-9a60-11e8-828f-d64917ffe98d.png">

## Expected behavior

always should be all steps visible: 
<img width="1176" alt="screen shot 2018-08-07 at 16 38 53" src="https://user-images.githubusercontent.com/6814482/43783032-011ab9f4-9a61-11e8-9ae0-2b7a77e373fb.png">

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by heiko-braun** [comment]
@zregvart looks like the one before, does it?

**Comment by mmelko** [comment]
@heiko-braun @zregvart yeah, looks like:
https://github.com/syndesisio/syndesis/issues/2487
https://github.com/syndesisio/syndesis/issues/2579
https://github.com/syndesisio/syndesis/issues/2726 

I didn't notice that.

**Comment by heiko-braun** [comment]
@mmelko What about the log on each pod? Are these consistent?

**Comment by heiko-braun** [comment]
@mmelko I think this info would be helpful to have:

- syndesis logs
- integration pod log
- pg_stat_activity

**Comment by zregvart** [comment]
To help with debugging this I think we need:
 - log from the syndesis-server pod
 - integration pod logs
 - dump of the syndesis postgresql database
 - output of `ps auxwww` in the syndesis-db pod
 - output of `netstat -tunapl` in the syndesis-server and syndesis-db pods
 - output of `jstack 1` in the syndesis-server pod
 - output of `psql -c 'SELECT * FROM pg_stat_activity;'` in the syndesis-db pod

**Comment by heiko-braun** [comment]
Related to #3350 and #2607

**Comment by mmelko** [comment]
here is it:
-  pg_stat_activity [db-output.txt](https://github.com/syndesisio/syndesis/files/2270159/db-output.txt)
 - log from integration [integration_provide-feedback.txt](https://github.com/syndesisio/syndesis/files/2270160/integration_provide-feedback.txt)

- `ps auxwww` [ps-syndesis-db.txt](https://github.com/syndesisio/syndesis/files/2270162/ps-syndesis-db.txt)
- jstack syndesis-server [jstack.txt](https://github.com/syndesisio/syndesis/files/2270163/jstack.txt)
- syndesis server log [syndesis-server.log](https://github.com/syndesisio/syndesis/files/2270194/syndesis-server.log)
- db dump [syndesis_dump.txt](https://github.com/syndesisio/syndesis/files/2270198/syndesis_dump.txt)

**Comment by zregvart** [comment]
I think the `jstack` output is the most helpful here. What I deduce from it is that the {{eventQueue}} {{LinkedBlockingDeque}} is full at 1000 capacity we allocate for events and that the {{ActivityTrackingController::processEventQueue}} is not running.

{{ActivityTrackingController::processEventQueue}} is started on a separate thread here:
https://github.com/syndesisio/syndesis/blob/dd07eddd58b8520a60edb1de182714bae1eeed3e/app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java#L101

And it should be running, until `stopped` flag is set to `true` or an exception is encountered.

From the server-pod logs, it seems that a exception has occurred while processing events:
```
2018-08-07 14:59:36.166 ERROR [-,,,] 1 --- [ntroller [idle]] i.s.s.l.j.c.ActivityTrackingController   : Failure running activity tracking task on thread: Logs Controller [idle]

org.skife.jdbi.v2.exceptions.CallbackFailedException: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: java.sql.BatchUpdateException: Batch entry 513 INSERT into jsondb (path, value, ovalue) values ('/activity/exchanges/i-LJJ0nl6CuuPiXONnP6Wz/i-LJJZ9kfN2_JW-giX2Ofz/', '`{"id":"i-LJJZ9kfN2_JW-giX2Ofz","logts":"2018-08-07T13:25:50.25218068Z","at":1533648350251,"pod":"i-stats-guess-6-lp9zq","ver":"1","status":"done","failed":false,"steps":[{"id":"-LJJ0i_KEr295bPBIeiG","at":1533648350252,"duration":188769}]}', NULL) ON CONFLICT (path) DO UPDATE SET value = '`{"id":"i-LJJZ9kfN2_JW-giX2Ofz","logts":"2018-08-07T13:25:50.25218068Z","at":1533648350251,"pod":"i-stats-guess-6-lp9zq","ver":"1","status":"done","failed":false,"steps":[{"id":"-LJJ0i_KEr295bPBIeiG","at":1533648350252,"duration":188769}]}', ovalue = NULL was aborted: ERROR: could not extend file "base/16385/16424": No space left on device
  Hint: Check free disk space.  Call getNextException to see other errors in the batch. [statement:"INSERT into jsondb (path, value, ovalue) values (:path, :value, :ovalue) ON CONFLICT (path) DO UPDATE SET value = :value, ovalue = :ovalue", located:"null", rewritten:"null", arguments:{ positional:{}, named:{path:'/activity/pods/i-stats-guess-6-lp9zq/time/',ovalue:'null',value:'`2018-08-07T13:42:26.87125854Z'}, finder:[]}]
	at org.skife.jdbi.v2.DBI.withHandle(DBI.java:301) ~[jdbi-2.78.jar!/:2.78]
	at org.skife.jdbi.v2.DBI.inTransaction(DBI.java:346) ~[jdbi-2.78.jar!/:2.78]
	at io.syndesis.server.logging.jsondb.controller.ActivityTrackingController.writeBatch(ActivityTrackingController.java:163) ~[server-logging-jsondb-1.5-SNAPSHOT.jar!/:1.5-SNAPSHOT]
	at io.syndesis.server.logging.jsondb.controller.ActivityTrackingController.processEventQueue(ActivityTrackingController.java:368) ~[server-logging-jsondb-1.5-SNAPSHOT.jar!/:1.5-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
Caused by: org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: java.sql.BatchUpdateException: Batch entry 513 INSERT into jsondb (path, value, ovalue) values ('/activity/exchanges/i-LJJ0nl6CuuPiXONnP6Wz/i-LJJZ9kfN2_JW-giX2Ofz/', '`{"id":"i-LJJZ9kfN2_JW-giX2Ofz","logts":"2018-08-07T13:25:50.25218068Z","at":1533648350251,"pod":"i-stats-guess-6-lp9zq","ver":"1","status":"done","failed":false,"steps":[{"id":"-LJJ0i_KEr295bPBIeiG","at":1533648350252,"duration":188769}]}', NULL) ON CONFLICT (path) DO UPDATE SET value = '`{"id":"i-LJJZ9kfN2_JW-giX2Ofz","logts":"2018-08-07T13:25:50.25218068Z","at":1533648350251,"pod":"i-stats-guess-6-lp9zq","ver":"1","status":"done","failed":false,"steps":[{"id":"-LJJ0i_KEr295bPBIeiG","at":1533648350252,"duration":188769}]}', ovalue = NULL was aborted: ERROR: could not extend file "base/16385/16424": No space left on device
  Hint: Check free disk space.  Call getNextException to see other errors in the batch. [statement:"INSERT into jsondb (path, value, ovalue) values (:path, :value, :ovalue) ON CONFLICT (path) DO UPDATE SET value = :value, ovalue = :ovalue", located:"null", rewritten:"null", arguments:{ positional:{}, named:{path:'/activity/pods/i-stats-guess-6-lp9zq/time/',ovalue:'null',value:'`2018-08-07T13:42:26.87125854Z'}, finder:[]}]
	at org.skife.jdbi.v2.PreparedBatch.internalBatchExecute(PreparedBatch.java:206) ~[jdbi-2.78.jar!/:2.78]
	at org.skife.jdbi.v2.PreparedBatch.execute(PreparedBatch.java:100) ~[jdbi-2.78.jar!/:2.78]
	at io.syndesis.server.logging.jsondb.controller.ActivityTrackingController.lambda$writeBatch$2(ActivityTrackingController.java:191) ~[server-logging-jsondb-1.5-SNAPSHOT.jar!/:1.5-SNAPSHOT]
	at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:183) ~[jdbi-2.78.jar!/:2.78]
	at org.skife.jdbi.v2.BasicHandle.inTransaction(BasicHandle.java:338) ~[jdbi-2.78.jar!/:2.78]
	at org.skife.jdbi.v2.DBI$5.withHandle(DBI.java:350) ~[jdbi-2.78.jar!/:2.78]
	at org.skife.jdbi.v2.DBI.withHandle(DBI.java:298) ~[jdbi-2.78.jar!/:2.78]
	... 6 common frames omitted
Caused by: java.sql.BatchUpdateException: Batch entry 513 INSERT into jsondb (path, value, ovalue) values ('/activity/exchanges/i-LJJ0nl6CuuPiXONnP6Wz/i-LJJZ9kfN2_JW-giX2Ofz/', '`{"id":"i-LJJZ9kfN2_JW-giX2Ofz","logts":"2018-08-07T13:25:50.25218068Z","at":1533648350251,"pod":"i-stats-guess-6-lp9zq","ver":"1","status":"done","failed":false,"steps":[{"id":"-LJJ0i_KEr295bPBIeiG","at":1533648350252,"duration":188769}]}', NULL) ON CONFLICT (path) DO UPDATE SET value = '`{"id":"i-LJJZ9kfN2_JW-giX2Ofz","logts":"2018-08-07T13:25:50.25218068Z","at":1533648350251,"pod":"i-stats-guess-6-lp9zq","ver":"1","status":"done","failed":false,"steps":[{"id":"-LJJ0i_KEr295bPBIeiG","at":1533648350252,"duration":188769}]}', ovalue = NULL was aborted: ERROR: could not extend file "base/16385/16424": No space left on device
  Hint: Check free disk space.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:145) ~[postgresql-9.4.1212.jre7.jar!/:9.4.1212.jre7]
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:50) ~[postgresql-9.4.1212.jre7.jar!/:9.4.1212.jre7]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2156) ~[postgresql-9.4.1212.jre7.jar!/:9.4.1212.jre7]
	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1265) ~[postgresql-9.4.1212.jre7.jar!/:9.4.1212.jre7]
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1290) ~[postgresql-9.4.1212.jre7.jar!/:9.4.1212.jre7]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:446) ~[postgresql-9.4.1212.jre7.jar!/:9.4.1212.jre7]
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:793) ~[postgresql-9.4.1212.jre7.jar!/:9.4.1212.jre7]
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1659) ~[postgresql-9.4.1212.jre7.jar!/:9.4.1212.jre7]
	at sun.reflect.GeneratedMethodAccessor190.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc-8.5.31.jar!/:na]
	at com.sun.proxy.$Proxy159.executeBatch(Unknown Source) ~[na:na]
	at org.skife.jdbi.v2.PreparedBatch.internalBatchExecute(PreparedBatch.java:196) ~[jdbi-2.78.jar!/:2.78]
	... 12 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: could not extend file "base/16385/16424": No space left on device
  Hint: Check free disk space.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455) ~[postgresql-9.4.1212.jre7.jar!/:9.4.1212.jre7]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155) ~[postgresql-9.4.1212.jre7.jar!/:9.4.1212.jre7]
	... 23 common frames omitted
```

This suggest that the PostgreSQL database `data` directory, a persistent volume with 1GB capacity has run out of disk space.

**Comment by heiko-braun** [comment]
Awesome work sherlock! (@zregvart )

**Comment by zregvart** [comment]
This will cause a number of open connections from the server pod to the kubernetes API server, we should probably handle SQL errors in `ActivityTrackingController::processEventQueue` and just drop events from the queue that we can't process. This would help us with poison messages.

**Comment by mmelko** [comment]
@zregvart so in theory after restart of syndesis-server, should it stay in same state? becasue after restart looks it's working fine.( I will see for how long)

**Comment by zregvart** [comment]
@mmelko probably it will be ok until we run out of disk space in the database pod, then processing of events would stop, threads and connections to the API server would pile up
