### ISSUE TITLE
Custom API connector: Camel sends Accept: application/json for XML endpoints

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#3388]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Having a custom API connector with a method that returns application/xml - the integration sends a request with Accept: application/json that results in HTTP 406 exception.

## Expected behavior

To send Accept: application/xml when the endpoint specification says that it returns application/xml

## Request and Response Data

This is the request from the integration:
```
GET /api/getXml HTTP/1.1
--
  | Accept: application/json
  | breadcrumbId: i-LJxezNjcn-m8cLrLkCuz
  | firedTime: Wed Aug 15 13:00:04 UTC 2018
  | Syndesis.STEP_ID: -LJxbTKc6sjAjo81pzTq
  | Syndesis.STEP_TRACKER_ID: i-LJxezNncn-m8cLrLkCwz
  | Host: http-svc:8080
  | Connection: Keep-Alive
  | User-Agent: Apache-HttpClient/4.5.5 (Java/1.8.0_151)
  | Accept-Encoding: gzip,deflate
```

Exception:
```
org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://http-svc:8080/api/getXml  with statusCode: 406
--
  | at org.apache.camel.component.http4.HttpProducer.populateHttpOperationFailedException(HttpProducer.java:312) ~[camel-http4-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.http4.HttpProducer.process(HttpProducer.java:207) ~[camel-http4-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.rest.RestProducer.process(RestProducer.java:86) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.connector.ConnectorProducer.process(ConnectorProducer.java:45) ~[camel-connector-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79) [integration-runtime-1.5-SNAPSHOT.jar!/:1.5-SNAPSHOT]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_151]
  | at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_151]
```

## API Endpoints and Schemas

Swagger:
```
{
  "swagger": "2.0",
  "info": {
    "description": "Endpoints for custom connector tests",
    "version": "1.0",
    "title": "HTTP Endpoints",
    "termsOfService": "https://www.google.com",
    "contact": {
      "name": "John Doe",
      "url": "https://www.google.com",
      "email": "johndoe@acme.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "host": "localhost:8080",
  "basePath": "/",
  "tags": [
    {
      "name": "HTTP Endpoints",
      "description": "Endpoints for custom connector tests"
    },
    {
      "name": "delete-json",
      "description": "Delete Json"
    },
    {
      "name": "delete-xml",
      "description": "Delete Xml"
    },
    {
      "name": "get-json",
      "description": "Get Json"
    },
    {
      "name": "get-xml",
      "description": "Get Xml"
    },
    {
      "name": "post-json",
      "description": "Post Json"
    },
    {
      "name": "post-xml",
      "description": "Post Xml"
    },
    {
      "name": "put-json",
      "description": "Put Json"
    },
    {
      "name": "put-xml",
      "description": "Put Xml"
    }
  ],
  "schemes": [
    "http"
  ],
  "paths": {
    "/api/deleteJson": {
      "delete": {
        "tags": [
          "delete-json"
        ],
        "summary": "deleteJson",
        "operationId": "deleteJsonUsingDELETE",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "204": {
            "description": "No Content"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "deprecated": false
      }
    },
    "/api/deleteXml": {
      "delete": {
        "tags": [
          "delete-xml"
        ],
        "summary": "deleteXml",
        "operationId": "deleteXmlUsingDELETE",
        "produces": [
          "application/xml"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/XmlResponse"
            }
          },
          "204": {
            "description": "No Content"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "deprecated": false
      }
    },
    "/api/getJson": {
      "get": {
        "tags": [
          "get-json"
        ],
        "summary": "getJson",
        "operationId": "getJsonUsingGET",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        },
        "deprecated": false
      }
    },
    "/api/getXml": {
      "get": {
        "tags": [
          "get-xml"
        ],
        "summary": "getXml",
        "operationId": "getXmlUsingGET",
        "produces": [
          "application/xml"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/XmlResponse"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        },
        "deprecated": false
      }
    },
    "/api/postJson": {
      "post": {
        "tags": [
          "post-json"
        ],
        "summary": "postJson",
        "operationId": "postJsonUsingPOST",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "201": {
            "description": "Created"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        },
        "deprecated": false
      }
    },
    "/api/postXml": {
      "post": {
        "tags": [
          "post-xml"
        ],
        "summary": "postXml",
        "operationId": "postXmlUsingPOST",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/xml"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/XmlResponse"
            }
          },
          "201": {
            "description": "Created"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        },
        "deprecated": false
      }
    },
    "/api/putJson": {
      "put": {
        "tags": [
          "put-json"
        ],
        "summary": "putJson",
        "operationId": "putJsonUsingPUT",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "string"
            }
          },
          "201": {
            "description": "Created"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        },
        "deprecated": false
      }
    },
    "/api/putXml": {
      "put": {
        "tags": [
          "put-xml"
        ],
        "summary": "putXml",
        "operationId": "putXmlUsingPUT",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/xml"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/XmlResponse"
            }
          },
          "201": {
            "description": "Created"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not Found"
          }
        },
        "deprecated": false
      }
    }
  },
  "definitions": {
    "XmlResponse": {
      "type": "object",
      "properties": {
        "prop1": {
          "type": "string",
          "xml": {
            "name": "first",
            "attribute": false,
            "wrapped": false
          }
        }
      },
      "title": "XmlResponse",
      "xml": {
        "name": "XmlResponse",
        "attribute": false,
        "wrapped": false
      }
    }
  }
}
```

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by zregvart** [comment]
Just adding a bit of detail @avano feel free to correct me if I misspeak: the custom API connector is configured on the integration to invoke the `get-xml` action `/api/getXml` that by the specification is producing `application/xml` `Content-Type`, making a request with `Accept: application/json` will result in `406` error as the content negotiation fails to find a good match for the client that requests `application/json` and a server that can only produce `application/xml`.

**Comment by avano** [comment]
@zregvart thanks, 100% correct

**Comment by zregvart** [comment]
I'm a bit worried I've changed a setting that made all requests have `Accept: application/json`, so either 11 months ago I knew of a case that needed that, or no one ever tried invoking APIs that produce (only) XML.
