### ISSUE TITLE
ServiceNow connector:  `Unexpected character (']' (code 93)):` when optional fields are empty 

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#3399]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
Currently _Retrieve Record_ action in serviceNow step has two optional parameters _The query used to filter the result set_ and _Limit of elements per page_.  When I try to retrieve records from Incident table (more that 20 000 incidents)with both empty I can see following exception in pod:

```2018-08-17 12:06:28.116 ERROR 1 --- [r://integration] o.a.camel.processor.DefaultErrorHandler  : Failed delivery for (MessageId: i-LK6ltcDQuByAtpu6TsSz on ExchangeId: i-LK6ldyvQuByAtpu6TsRz). Exhausted after delivery attempt: 1 caught: javax.ws.rs.client.ResponseProcessingException: Problem with reading the data, class com.fasterxml.jackson.databind.JsonNode, ContentType: application/json;charset=UTF-8.
--
  | Message History
  | ---------------------------------------------------------------------------------------------------------------------------------------
  | RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
  | [-LK6usU0hqrFaHJ6Vc] [-LK6usU0hqrFaHJ6Vc] [timer://integration?period=60000                                              ] [     64086]
  | [-LK6usU0hqrFaHJ6Vc] [to1               ] [servicenow-1                                                                  ] [     64073]
  | Stacktrace
  | ---------------------------------------------------------------------------------------------------------------------------------------
  | javax.ws.rs.client.ResponseProcessingException: Problem with reading the data, class com.fasterxml.jackson.databind.JsonNode, ContentType: application/json;charset=UTF-8.
  | at org.apache.cxf.jaxrs.impl.ResponseImpl.reportMessageHandlerProblem(ResponseImpl.java:446) ~[cxf-rt-frontend-jaxrs-3.1.11.fuse-000263.jar!/:3.1.11.fuse-000263]
  | at org.apache.cxf.jaxrs.impl.ResponseImpl.doReadEntity(ResponseImpl.java:386) ~[cxf-rt-frontend-jaxrs-3.1.11.fuse-000263.jar!/:3.1.11.fuse-000263]
  | at org.apache.cxf.jaxrs.impl.ResponseImpl.readEntity(ResponseImpl.java:321) ~[cxf-rt-frontend-jaxrs-3.1.11.fuse-000263.jar!/:3.1.11.fuse-000263]
  | at org.apache.cxf.jaxrs.impl.ResponseImpl.readEntity(ResponseImpl.java:311) ~[cxf-rt-frontend-jaxrs-3.1.11.fuse-000263.jar!/:3.1.11.fuse-000263]
  | at org.apache.camel.component.servicenow.AbstractServiceNowProcessor.setBody(AbstractServiceNowProcessor.java:110) ~[camel-servicenow-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.servicenow.AbstractServiceNowProcessor.setBodyAndHeaders(AbstractServiceNowProcessor.java:59) ~[camel-servicenow-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.servicenow.releases.helsinki.HelsinkiServiceNowTableProcessor.retrieveRecord(HelsinkiServiceNowTableProcessor.java:90) ~[camel-servicenow-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.servicenow.ServiceNowDispatcher.process(ServiceNowDispatcher.java:40) ~[camel-servicenow-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.servicenow.AbstractServiceNowProcessor.process(AbstractServiceNowProcessor.java:70) ~[camel-servicenow-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.impl.BaseSelectorProducer.process(BaseSelectorProducer.java:35) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at io.syndesis.integration.component.proxy.ComponentProxyProducer.process(ComponentProxyProducer.java:44) ~[integration-component-proxy-1.4.5.jar!/:1.4.5]
  | at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_151]
  | at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_151]
  | Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character (']' (code 93)): expected a value
  | at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@701f452b; line: 1, column: 12706756]
  | at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2656) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:269) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:232) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1583) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:964) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:815) ~[jackson-jaxrs-base-2.8.11.jar!/:2.8.11]
  | at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBodyReader(JAXRSUtils.java:1354) ~[cxf-rt-frontend-jaxrs-3.1.11.fuse-000263.jar!/:3.1.11.fuse-000263]
  | at org.apache.cxf.jaxrs.impl.ResponseImpl.doReadEntity(ResponseImpl.java:377) ~[cxf-rt-frontend-jaxrs-3.1.11.fuse-000263.jar!/:3.1.11.fuse-000263]
  | ... 23 common frames omitted
  | {"exchange":"i-LK6ldyvQuByAtpu6TsRz","status":"done","failed":true}
  | 2018-08-17 12:06:28.117  WARN 1 --- [r://integration] o.a.camel.component.timer.TimerConsumer  : Error processing exchange. Exchange[i-LK6ldyvQuByAtpu6TsRz]. Caused by: [javax.ws.rs.client.ResponseProcessingException - Problem with reading the data, class com.fasterxml.jackson.databind.JsonNode, ContentType: application/json;charset=UTF-8.]
  | javax.ws.rs.client.ResponseProcessingException: Problem with reading the data, class com.fasterxml.jackson.databind.JsonNode, ContentType: application/json;charset=UTF-8.
  | at org.apache.cxf.jaxrs.impl.ResponseImpl.reportMessageHandlerProblem(ResponseImpl.java:446) ~[cxf-rt-frontend-jaxrs-3.1.11.fuse-000263.jar!/:3.1.11.fuse-000263]
  | at org.apache.cxf.jaxrs.impl.ResponseImpl.doReadEntity(ResponseImpl.java:386) ~[cxf-rt-frontend-jaxrs-3.1.11.fuse-000263.jar!/:3.1.11.fuse-000263]
  | at org.apache.cxf.jaxrs.impl.ResponseImpl.readEntity(ResponseImpl.java:321) ~[cxf-rt-frontend-jaxrs-3.1.11.fuse-000263.jar!/:3.1.11.fuse-000263]
  | at org.apache.cxf.jaxrs.impl.ResponseImpl.readEntity(ResponseImpl.java:311) ~[cxf-rt-frontend-jaxrs-3.1.11.fuse-000263.jar!/:3.1.11.fuse-000263]
  | at org.apache.camel.component.servicenow.AbstractServiceNowProcessor.setBody(AbstractServiceNowProcessor.java:110) ~[camel-servicenow-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.servicenow.AbstractServiceNowProcessor.setBodyAndHeaders(AbstractServiceNowProcessor.java:59) ~[camel-servicenow-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.servicenow.releases.helsinki.HelsinkiServiceNowTableProcessor.retrieveRecord(HelsinkiServiceNowTableProcessor.java:90) ~[camel-servicenow-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.servicenow.ServiceNowDispatcher.process(ServiceNowDispatcher.java:40) ~[camel-servicenow-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.servicenow.AbstractServiceNowProcessor.process(AbstractServiceNowProcessor.java:70) ~[camel-servicenow-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.impl.BaseSelectorProducer.process(BaseSelectorProducer.java:35) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at io.syndesis.integration.component.proxy.ComponentProxyProducer.process(ComponentProxyProducer.java:44) ~[integration-component-proxy-1.4.5.jar!/:1.4.5]
  | at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
  | at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_151]
  | at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_151]
  | Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character (']' (code 93)): expected a value
  | at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@701f452b; line: 1, column: 12706756]
  | at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2656) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772) ~[jackson-core-2.8.11.jar!/:2.8.11]
  | at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:269) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:232) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1583) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:964) ~[jackson-databind-2.8.11.1.jar!/:2.8.11.1]
  | at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:815) ~[jackson-jaxrs-base-2.8.11.jar!/:2.8.11]
  | at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBodyReader(JAXRSUtils.java:1354) ~[cxf-rt-frontend-jaxrs-3.1.11.fuse-000263.jar!/:3.1.11.fuse-000263]
  | at org.apache.cxf.jaxrs.impl.ResponseImpl.doReadEntity(ResponseImpl.java:377) ~[cxf-rt-frontend-jaxrs-3.1.11.fuse-000263.jar!/:3.1.11.fuse-000263]
  | ... 23 common frames omitted
  | {"exchange":"i-LK6ltcLQuByAtpu6TsTz","status":"begin"}
```

According documentation: _Limit of elements per page_ should have default value 1000 which is not true because if I set limit to 1000 manually, integration is working. 

## Tasks involved / Steps to Reproduce

1.
2.
3.
4.

**Comment by lburgazzoli** [comment]
Sorry my fault, the default value is 10000 not 1000.

@TovaCohen we may need to update the document.
@mmelko what is the table you did query ?

**Comment by mmelko** [comment]
@lburgazzoli as I mentioned _Incident_ table.

**Comment by TovaCohen** [comment]
Just checking in about this.  Do I need to update something in the 7.1 user doc?  Please let me know.

**Comment by mmelko** [comment]
So If I set 10000 I'm getting same error. Looks like default value is too big.

**Comment by lburgazzoli** [comment]
It looks like this is because of a time-out happens on ServiceNow (there) and the generated json is corrupted. ServiceNow answers with HTTP code 200 so it is ok to process the body for camel.

Let me see if I can get any support from ServiceNow.

**Comment by heiko-braun** [comment]
It's a problem with servicenow. Closing this as won't fix.
