### ISSUE TITLE
Incorrect path on DropBox file download does not throw error on the UI

### ISSUE THREAD

**Issue by snandakumar87** [syndesisio/syndesis#3486]
When an integration is created with the drop box connector and incorrect path is specified, throws an error saying path is invalid in the logs, but the Syndesis UI does not update the error count or the failed message exchange.

The error count should show the error that happens on file poll.

<img width="1437" alt="activityview" src="https://user-images.githubusercontent.com/39506194/44739100-e3629200-aac4-11e8-8394-9c2b0cb042b8.png">
<img width="1422" alt="syndesis_error" src="https://user-images.githubusercontent.com/39506194/44739101-e3fb2880-aac4-11e8-975a-282d95b4ac18.png">

2018-08-28 00:21:32.371  WARN 1 --- [- dropbox://get] .c.d.i.c.DropboxScheduledPollGetConsumer : Consumer Consumer[dropbox://get?accessToken=xxxxxxx&clientIdentifier=xxxxxx&remotePath=syndesis] failed polling endpoint: dropbox://get?accessToken=xxxxx&clientIdentifier=xxxx&remotePath=syndesis. Will try again at next poll. Caused by: [java.lang.IllegalArgumentException - String 'path' does not match pattern]
java.lang.IllegalArgumentException: String 'path' does not match pattern
	at com.dropbox.core.v2.files.ListFolderArg.<init>(ListFolderArg.java:74) ~[dropbox-core-sdk-3.0.6.jar!/:na]
	at com.dropbox.core.v2.files.ListFolderArg.<init>(ListFolderArg.java:107) ~[dropbox-core-sdk-3.0.6.jar!/:na]
	at com.dropbox.core.v2.files.DbxUserFilesRequests.listFolder(DbxUserFilesRequests.java:1465) ~[dropbox-core-sdk-3.0.6.jar!/:na]
	at org.apache.camel.component.dropbox.core.DropboxAPIFacade.downloadFilesInFolder(DropboxAPIFacade.java:336) ~[camel-dropbox-2.21.0.jar!/:2.21.0]
	at org.apache.camel.component.dropbox.core.DropboxAPIFacade.get(DropboxAPIFacade.java:331) ~[camel-dropbox-2.21.0.jar!/:2.21.0]
	at org.apache.camel.component.dropbox.integration.consumer.DropboxScheduledPollGetConsumer.poll(DropboxScheduledPollGetConsumer.java:44) ~[camel-dropbox-2.21.0.jar!/:2.21.0]
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174) [camel-core-2.21.0.jar!/:2.21.0]
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101) [camel-core-2.21.0.jar!/:2.21.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

1) Created a Drop Box connector and a slack connector.
2) Chose the action Download from Drop Box, but gave the folder name instead of the path (which is wrong)
3) Published the integration

I see that in the open shift console i see the poll failing, but i dont see any feedback on Syndesis UI. How would the user know something went wrong, unless i am monitoring logs continuously.

**Comment by heiko-braun** [comment]
@dhirajsb Do you have this on your radar?

**Comment by dhirajsb** [comment]
I've looked at this before, and it's a tricky one. The consumer fails on polling the bad path, and it's own `errorCounter` is incremented. But we only track failed messages, not failures in consumer beans. 
One option is to catch the API call in the consumer and set it on the exchange, marking the exchange as failed instead. But I'm not 100% sure that's semantically correct. 
@davsclaus what do you think?

**Comment by gashcrumb** [comment]
Just to chime in I'm not sure we even have a general strategy for Syndesis on how to report back errors, so this would be a nice thing to keep in mind when discussing.

> But I'm not 100% sure that's semantically correct.

Might not be right for Camel but it could be something we do specifically in Syndesis as a way to catch the error and eventually report it back to the user in some fashion, I guess via the activity log for starters.

**Comment by dhirajsb** [comment]
AFAIK, the activity log can only see what's in an exchange. So unless an error shows up in a failed exchange, i.e. if it's an exception elsewhere in Camel or an error log message, users will never see it.

**Comment by davsclaus** [comment]
I think you can turn on the bridge error handler option `bridgeErrorHandler=true`
https://github.com/apache/camel/blob/master/components/camel-dropbox/src/main/docs/dropbox-component.adoc

Then any such errors within the consumer itself (before the Camel Exchange can be created) would be caught by the consumer, and then set on a dummy exchange with the exception that the Camel route then routes and reacts upon, and then syndesis should see that error.

Mind that you will get this error on each poll.

**Comment by dhirajsb** [comment]
Should that be something we turn on for all connectors then?

**Comment by gashcrumb** [comment]
@gaughan question on this one, using the `bridgeErrorHandler` setting would probably handle this error condition, in that each time the Dropbox component attempts to poll for files it'll result in an error going to the integration activity log.  Think that'd work?

**Comment by gashcrumb** [comment]
> Should that be something we turn on for all connectors then?

I think yes if PM agrees with the behavior.

**Comment by gaughan** [comment]
Agreed, we definitely want better error handling. 
Eventually, we want to be able to take a different action based on error type too.

**Comment by dhirajsb** [comment]
This has been fixed for DropBox connector, I have created another issue #3985 for the generic error handling issue of not reporting on errors outside routes. 
Maybe we can have a meeting to brainstorm and come up with a solution on how to handle other such errors which manifest as warnings on errors in the log, without an associated message.
