### ISSUE TITLE
Unable to list activities:  504 (Gateway Time-out) in 1.4.7

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#3505]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem
In my long running scenario with 6 integrations (3 of 6 contains more than 4 elements), I'm not able to list activities after couple of hours(~12). 

### Java script console log: 
```
i-LKvs0nhYGDn4JCJzcZDz:1 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
http-error.interceptor.ts:52 Error performing GET request to https://soak.b9ad.pro-us-east-1.openshiftapps.com/api/v1/activity/integrations/i-LKvs0nhYGDn4JCJzcZDz :  HttpErrorResponse {headers: HttpHeaders, status: 504, statusText: "Gateway Time-out", url: "https://soak.b9ad.pro-us-east-1.openshiftapps.com/…i/v1/activity/integrations/i-LKvs0nhYGDn4JCJzcZDz", ok: false, …}
(anonymous) @ http-error.interceptor.ts:52
push../node_modules/rxjs/_esm5/internal/operators/tap.js.TapSubscriber._error @ tap.js:102
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.error @ Subscriber.js:106
onLoad @ http.js:1556
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:3662
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
exception-handler.service.ts:19 Error: Uncaught (in promise): Error: Cannot parse given Error object
Error: Cannot parse given Error object
    at Object.ErrorStackParser$$parse [as parse] (error-stack-parser.js:74)
    at Object.<anonymous> (stacktrace.js:106)
    at new ZoneAwarePromise (zone.js:891)
    at Object.StackTrace$$fromError [as fromError] (stacktrace.js:105)
    at MessageUtils.js:168
    at new ZoneAwarePromise (zone.js:891)
    at Function.push../node_modules/typescript-logging/dist/commonjs/utils/MessageUtils.js.MessageFormatUtils.renderError (MessageUtils.js:166)
    at _loop_1 (AbstractCategoryLogger.js:321)
    at CategoryConsoleLoggerImpl.push../node_modules/typescript-logging/dist/commonjs/log/category/AbstractCategoryLogger.js.AbstractCategoryLogger._logInternal (AbstractCategoryLogger.js:334)
    at CategoryConsoleLoggerImpl.push../node_modules/typescript-logging/dist/commonjs/log/category/AbstractCategoryLogger.js.AbstractCategoryLogger._log (AbstractCategoryLogger.js:274)
    at Object.ErrorStackParser$$parse [as parse] (error-stack-parser.js:74)
    at Object.<anonymous> (stacktrace.js:106)
    at new ZoneAwarePromise (zone.js:891)
    at Object.StackTrace$$fromError [as fromError] (stacktrace.js:105)
    at MessageUtils.js:168
    at new ZoneAwarePromise (zone.js:891)
    at Function.push../node_modules/typescript-logging/dist/commonjs/utils/MessageUtils.js.MessageFormatUtils.renderError (MessageUtils.js:166)
    at _loop_1 (AbstractCategoryLogger.js:321)
    at CategoryConsoleLoggerImpl.push../node_modules/typescript-logging/dist/commonjs/log/category/AbstractCategoryLogger.js.AbstractCategoryLogger._logInternal (AbstractCategoryLogger.js:334)
    at CategoryConsoleLoggerImpl.push../node_modules/typescript-logging/dist/commonjs/log/category/AbstractCategoryLogger.js.AbstractCategoryLogger._log (AbstractCategoryLogger.js:274)
    at resolvePromise (zone.js:814)
    at resolvePromise (zone.js:771)
    at zone.js:873
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3662)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:500)
    at invokeTask (zone.js:1540)
push../src/app/error-handler/exception-handler.service.ts.ExceptionHandlerService.log @ exception-handler.service.ts:19
push../src/app/error-handler/exception-handler.service.ts.ExceptionHandlerService.handleError @ exception-handler.service.ts:12
next @ core.js:4167
schedulerFn @ core.js:3403
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:253
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:191
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:129
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:93
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:53
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:3395
(anonymous) @ core.js:3693
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:3630
onHandleError @ core.js:3693
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:392
push../node_modules/zone.js/dist/zone.js.Zone.runGuarded @ zone.js:154
_loop_1 @ zone.js:677
api.microtaskDrainDone @ zone.js:686
drainMicroTaskQueue @ zone.js:602
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
core.js:1542 ERROR Error: Uncaught (in promise): Error: Cannot parse given Error object
Error: Cannot parse given Error object
    at Object.ErrorStackParser$$parse [as parse] (error-stack-parser.js:74)
    at Object.<anonymous> (stacktrace.js:106)
    at new ZoneAwarePromise (zone.js:891)
    at Object.StackTrace$$fromError [as fromError] (stacktrace.js:105)
    at MessageUtils.js:168
    at new ZoneAwarePromise (zone.js:891)
    at Function.push../node_modules/typescript-logging/dist/commonjs/utils/MessageUtils.js.MessageFormatUtils.renderError (MessageUtils.js:166)
    at _loop_1 (AbstractCategoryLogger.js:321)
    at CategoryConsoleLoggerImpl.push../node_modules/typescript-logging/dist/commonjs/log/category/AbstractCategoryLogger.js.AbstractCategoryLogger._logInternal (AbstractCategoryLogger.js:334)
    at CategoryConsoleLoggerImpl.push../node_modules/typescript-logging/dist/commonjs/log/category/AbstractCategoryLogger.js.AbstractCategoryLogger._log (AbstractCategoryLogger.js:274)
    at Object.ErrorStackParser$$parse [as parse] (error-stack-parser.js:74)
    at Object.<anonymous> (stacktrace.js:106)
    at new ZoneAwarePromise (zone.js:891)
    at Object.StackTrace$$fromError [as fromError] (stacktrace.js:105)
    at MessageUtils.js:168
    at new ZoneAwarePromise (zone.js:891)
    at Function.push../node_modules/typescript-logging/dist/commonjs/utils/MessageUtils.js.MessageFormatUtils.renderError (MessageUtils.js:166)
    at _loop_1 (AbstractCategoryLogger.js:321)
    at CategoryConsoleLoggerImpl.push../node_modules/typescript-logging/dist/commonjs/log/category/AbstractCategoryLogger.js.AbstractCategoryLogger._logInternal (AbstractCategoryLogger.js:334)
    at CategoryConsoleLoggerImpl.push../node_modules/typescript-logging/dist/commonjs/log/category/AbstractCategoryLogger.js.AbstractCategoryLogger._log (AbstractCategoryLogger.js:274)
    at resolvePromise (zone.js:814)
    at resolvePromise (zone.js:771)
    at zone.js:873
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3662)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:500)
    at invokeTask (zone.js:1540)
```

### Server log 
This was only exception in server log (might be not related though):
```
2018-08-27 23:48:55.673 ERROR [-,,,] 1 --- [ning]: pollPods] i.s.s.l.j.c.ActivityTrackingController   : Unexpected Error occurred.

io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Pod]  with name: [null]  in namespace: [soak]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62) ~[kubernetes-client-3.1.4.fuse-710001.jar!/:na]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71) ~[kubernetes-client-3.1.4.fuse-710001.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:609) ~[kubernetes-client-3.1.4.fuse-710001.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70) ~[kubernetes-client-3.1.4.fuse-710001.jar!/:na]
	at io.syndesis.server.logging.jsondb.controller.ActivityTrackingController.listPods(ActivityTrackingController.java:298) ~[server-logging-jsondb-1.4.7.jar!/:1.4.7]
	at io.syndesis.server.logging.jsondb.controller.ActivityTrackingController.pollPods(ActivityTrackingController.java:242) ~[server-logging-jsondb-1.4.7.jar!/:1.4.7]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:230) ~[okio-1.13.0.jar!/:na]
	at okio.AsyncTimeout.exit(AsyncTimeout.java:285) ~[okio-1.13.0.jar!/:na]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241) ~[okio-1.13.0.jar!/:na]
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345) ~[okio-1.13.0.jar!/:na]
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217) ~[okio-1.13.0.jar!/:na]
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211) ~[okio-1.13.0.jar!/:na]
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:na]
	at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:66) ~[openshift-client-3.1.4.fuse-710001.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) ~[okhttp-3.8.1.jar!/:na]
	at okhttp3.RealCall.execute(RealCall.java:69) ~[okhttp-3.8.1.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:377) ~[kubernetes-client-3.1.4.fuse-710001.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343) ~[kubernetes-client-3.1.4.fuse-710001.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327) ~[kubernetes-client-3.1.4.fuse-710001.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:605) ~[kubernetes-client-3.1.4.fuse-710001.jar!/:na]
	... 10 common frames omitted
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204) ~[na:1.8.0_151]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_151]
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[na:1.8.0_151]
	at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[na:1.8.0_151]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983) ~[na:1.8.0_151]
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940) ~[na:1.8.0_151]
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[na:1.8.0_151]
	at okio.Okio$2.read(Okio.java:139) ~[okio-1.13.0.jar!/:na]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[okio-1.13.0.jar!/:na]
	... 36 common frames omitted
```

Oputput of [jstack 1](https://github.com/syndesisio/syndesis/files/2332396/jstack.txt)

## Tasks involved / Steps to Reproduce

Unfortunately I can't reproduce consistently otherwise I'd mark it as a blocker.

**Comment by zregvart** [comment]
Seems that we didn't receive a response form Kubernetes API server within a timeout while listing pods:

https://github.com/syndesisio/syndesis/blob/843c01af957176862a49e7d55c6c9b70582be450/app/server/logging/jsondb/src/main/java/io/syndesis/server/logging/jsondb/controller/ActivityTrackingController.java#L297-L299

I'm guessing this was on minishift? This might happen if the whole machine is overloaded by the test and the API server is starved for CPU/memory.

**Comment by zregvart** [comment]
We could put Hystrix closure around that call and use the latest known pod list to increase our robustness. That would remove the symptoms at least.

**Comment by mmelko** [comment]
@heiko-braun sorry for late response. Unfortunately I haven't found easy way how to reproduce it. 
@zregvart this was on openshift pro. I have feeling that it's somehow related to larger integrations.

**Comment by zregvart** [comment]
@syndesisio/backend on principle should we decorate calls to Kubernetes API server with Hystrix? I think we should as it will increase our overall robustness.

**Comment by heiko-braun** [comment]
@zregvart  I think increased fault-tolerance is a reasonable aim, but I wouldn't encourage to use Hystrix.  It's viable, but dated and not supported anymore. Failsafe (https://github.com/jhalterman/failsafe) might be an alternative,  but better double if any of this is already productised with @janstey before taking a decision.

**Comment by heiko-braun** [comment]
Better address this in a feature sprint, rather than last minute

**Comment by chirino** [comment]
Moving to a more scalable activity tracking implemenation would help with this, We should look into using opentracing to track activities.
