### ISSUE TITLE
Error using API Connectors 

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3531]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Documentation issue or request
</code></pre>

## scope and impact of the issues
**You cannot work with data returned from API's**. This issue affects all connectors created from a swagger upload. 

## description of the behaviour
Lets take concur as an example: "Create a new listitem" action does not return anything in syndesis so I can not save newly created listitem's ID.
My integration created new listitem and then it failed in data mapper where I mapped ID from response it said in logs that /ID does not exist.

## description of the behaviour you expect
I expect that I can use the data which I get from API connector action later in the integration - available data mapper with visible data from previous api connector action. 

## Reproducer A
[Integration_with_concur-export.zip](https://github.com/syndesisio/syndesis/files/2345063/Integration_with_concur-export.zip)
To reproduce, you can import this integration. (correct concur OAuth credentials required) 
Due to constants not working in data mapper, I add those values into our database which runs with syndesis:

insert into CONTACT values ('Anivia' , 'Bird', 'gWnytPb$pHxNJMPz4yL0nosnCQ4r30gRWs4w' , 'some lead', '1999-01-01');

You can see how are those values used from attached integration.
Run the integration and check integration logs - there is an error that /ID does not exist.

## priority
Concur is just technical preview, I don't mind marking it as p1. But as it affects all connectors created via swagger upload, I think this should be marked as blocker as it has no workaround. I (mcada) only pointed on this error that it does not work, @KurtStam investigated it deeper and should state the priority. 

## Reproducer B:

[db_custom_api_db-export.zip](https://github.com/syndesisio/syndesis/files/2349271/db_custom_api_db-export.zip)

Set up:
Add following values into database:
```
insert into CONTACT values ('evelyn' , 'Queen', '1' , 'some lead', '1999-01-01')
insert into TODO values (1, 'malphite' , 0)
```
After the import, perform these steps **before publishing the integration**:

- change the todo connection host name to reflect your minishift host name
- edit the integration name, save it
- delete and recreate the todo connection step in the flow (otherwise the new host name is not pick up)

Swagger for the custom connector I used:
Note that I added .txt to be able to upload it here.
[todo.swagger.yaml.txt](https://github.com/syndesisio/syndesis/files/2349279/todo.swagger.yaml.txt)

I think it may be useful to check gherkin scenario for automated test which reproduces the issue:
https://github.com/mcada/syndesis-qe/commit/5cb8aeb77351bbce0138ddb54186f3d9144fc990#diff-39b1279fe5ee1403b110a680daf591dbR56

**Comment by heiko-braun** [comment]
@mcada @tplevko We need QE classification on this issue. What severity does it have?

**Comment by mcada** [comment]
This issue affects all connectors which a user creates from a swagger upload. If I understand it well, usability of all connectors created this way just decreased by 50 % as you can not get any data from their actions via data mapper (the connectors have no output) and work with them later in the integration. From my pov this is a blocker.

**Comment by heiko-braun** [comment]
@mcada So it's not limited to Concur, but has broader impact?

**Comment by mcada** [comment]
Based on this: https://github.com/syndesisio/syndesis/pull/3532/files I would say so. I will try it manually just to be sure.

**Comment by mcada** [comment]
Error from my reproducer (I will add the reproducer in the description later):

```
io.atlasmap.api.AtlasException: Errors: [Source document '-LL_2gxr3Jq4DC6RiYJQ' doesn't exist: docId='-LL_2gxr3Jq4DC6RiYJQ', path='/task'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:213) ~[camel-atlasmap-1.35.7.jar!/:na]
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79) ~[integration-runtime-1.4.7.fuse-710001-redhat-00001.jar!/:1.4.7.fuse-710001-redhat-00001]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:715) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:638) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:248) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.Splitter.process(Splitter.java:122) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) [camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) [camel-core-2.21.0.fuse-710018-redhat-00001.jar!/:2.21.0.fuse-710018-redhat-00001]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_181]
	at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_181]

{"exchange":"i-LL_3bXudlluvFmkLmvwz","status":"begin"}
{"exchange":"i-LL_3bXudlluvFmkLmvwz","step":"-LL_2hHU3Jq4DC6RiYJR","id":"i-LL_3bXzdlluvFmkLmw-z","duration":1215591}
{"exchange":"i-LL_3bXudlluvFmkLmvwz","step":"-LL_2gxr3Jq4DC6RiYJQ","id":"i-LL_3bY0dlluvFmkLmw1z","duration":14538442}
2018-09-04 14:52:55.888  WARN 1 --- [r://integration] o.a.c.component.atlasmap.AtlasEndpoint   : Null or non-String source document: docId='-LL_2gxr3Jq4DC6RiYJQ': docId='-LL_2gxr3Jq4DC6RiYJQ', path='null'
2018-09-04 14:52:55.890 ERROR 1 --- [r://integration] o.a.camel.processor.DefaultErrorHandler  : Failed delivery for (MessageId: i-LL_3bYEdlluvFmkLmw2z on ExchangeId: i-LL_3bXydlluvFmkLmvyz). Exhausted after delivery attempt: 1 caught: io.atlasmap.api.AtlasException: Errors: [Source document '-LL_2gxr3Jq4DC6RiYJQ' doesn't exist: docId='-LL_2gxr3Jq4DC6RiYJQ', path='/task'],
```

**Comment by heiko-braun** [comment]
From Nicola:

I've not fully understood what is the issue here.

The concur action mentioned in the issue (`create a new listitem`) has a output datashape and I'm able to map it.

![screenshot from 2018-09-04 16-42-08](https://user-images.githubusercontent.com/4151857/45039200-6060af00-b063-11e8-87e4-5255bbe0e74f.png)

So, is this issue appearing only when the integration is running @mcada? It seems something related to the backend runtime or datamapper and not related to the `Pipeline` pattern, that is something UI only.

**Comment by heiko-braun** [comment]
To clarify: @nicolaferraro  scenario (screenshot above) does also run into the error reported by @mcada 

```
Errors: [Source document '-LL_2gxr3Jq4DC6RiYJQ' doesn't exist
```

**Comment by heiko-braun** [comment]
When I edit the integration using reproducer B (see description), and look at the mapping step after the start connector (DB query), I see this:

![screen shot 2018-09-05 at 11 19 04](https://user-images.githubusercontent.com/369380/45084107-ba15b780-b0fd-11e8-95f3-ee12007e8e40.png)

**Comment by heiko-braun** [comment]
I have recreated reproducer B from scratch to exclude error resulting from import/export. 

The first data mapper step is still intact, but the second one after the Todo connection show this:

![screen shot 2018-09-05 at 11 33 31](https://user-images.githubusercontent.com/369380/45084923-b6833000-b0ff-11e8-81d7-bfdb10a171a7.png)

**Comment by heiko-braun** [comment]
My reproducer logs this (adding the message history for completion):
```
Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[-LLd21Ue8mroEs5G-U] [-LLd21Ue8mroEs5G-U] [timer://integration?period=30000                                              ] [        27]
[-LLd21Ue8mroEs5G-U] [setHeader1        ] [setHeader[Syndesis.STEP_ID]                                                   ] [         0]
[-LLd21Ue8mroEs5G-U] [process1          ] [Processor@0x58af97f                                                           ] [         0]
[-LLd21Ue8mroEs5G-U] [step:-LLd377B8mroE] [pipeline                                                                      ] [         1]
[-LLd21Ue8mroEs5G-U] [setHeader2        ] [setHeader[Syndesis.STEP_ID]                                                   ] [         0]
[-LLd21Ue8mroEs5G-U] [to2               ] [atlas:mapping-step-2.json?encoding=UTF-8&sourceMapName=Syndesis.CAPTURED_OUT_M] [         1]
[-LLd21Ue8mroEs5G-U] [process2          ] [Processor@0x2c045bf                                                           ] [         0]
[-LLd21Ue8mroEs5G-U] [step:-LLd2rX58mroE] [pipeline                                                                      ] [        22]
[-LLd21Ue8mroEs5G-U] [setHeader3        ] [setHeader[Syndesis.STEP_ID]                                                   ] [         0]
[-LLd21Ue8mroEs5G-U] [to3               ] [swagger-operation-3?operationId=operation-2                                   ] [        22]
[-LLd21Ue8mroEs5G-U] [process3          ] [Processor@0x2c045bf                                                           ] [         0]
[-LLd21Ue8mroEs5G-U] [step:-LLd377B8mroE] [pipeline                                                                      ] [         0]
[-LLd21Ue8mroEs5G-U] [setHeader4        ] [setHeader[Syndesis.STEP_ID]                                                   ] [         0]
[-LLd21Ue8mroEs5G-U] [to4               ] [atlas:mapping-step-4.json?encoding=UTF-8&sourceMapName=Syndesis.CAPTURED_OUT_M] [         1]
Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
io.atlasmap.api.AtlasException: Errors: [Source document 'DOC.2 - Data Mapper (Request).915482' doesn't exist: docId='DOC.2 - Data Mapper (Request).915482', path='/parameters/id'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:213) ~[camel-atlasmap-1.35.7.jar!/:na]
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79) [integration-runtime-1.4-SNAPSHOT.jar!/:1.4-SNAPSHOT]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:715) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:638) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:248) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.Splitter.process(Splitter.java:122) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) [camel-core-2.21.0.fuse-000094.jar!/:2.21.0.fuse-000094]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_151]
	at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_151]

```

**Comment by heiko-braun** [comment]
The AtlasMapping to my reproducer:
https://gist.github.com/heiko-braun/b630706951c6fc0cb94a741227e24012

**Comment by heiko-braun** [comment]
@igarashitm `mapping-step-4.json` above looks fishy to me

**Comment by igarashitm** [comment]
Yeah really fishy... `DataSource ID` = `Document ID (docId)` must be equal to Syndesis `Step ID`, and it's supposed to be non human readable string like `-LLd2Lh98mroEs5G-U3_`. The following look like a `display name` of the datamapper steps.
`"id": "DOC.2 - Data Mapper (Request).915482"`
`"docId": "DOC.2 - Data Mapper (Request).915482"`

But I think this is yet another problem. You should be able to avoid this by mapping from API connectors output, but not from datamapper output.

**Comment by nicolaferraro** [comment]
After applying https://github.com/syndesisio/syndesis/commit/9aeeb3f86af344375b9f00701c08861312b1416f I see the following:

Runtime sets the following values in the exchange:
-LLd7vbdumiqh_kg_u3x
-LLd7ouGumiqh_kg_u3w


Atlasmap expects the following ones:
-LLd7k3Wumiqh_kg_u3w
DOC.2 - Data Mapper (Request).734626
-LLd7ouGumiqh_kg_u3w


The "DOC.2 .." thing is may be unrelated, but also the first one is not matching.
It may be a import related thing, so I'm creating the integration from scratch.

**Comment by nicolaferraro** [comment]
The issue in my previous message appears only when importing the integration.

**Comment by heiko-braun** [comment]
With https://github.com/syndesisio/syndesis/pull/3555 , reproducer B is working:

![screen shot 2018-09-05 at 16 22 03](https://user-images.githubusercontent.com/369380/45102787-c8c89280-b12e-11e8-9d4c-28c4956ac67d.png)

**Comment by heiko-braun** [comment]
I've moved the meta data problem to another issues. It doesn't seem to be relevant to the issue here.

https://github.com/syndesisio/syndesis/issues/3556

//cc @igarashitm

**Comment by KurtStam** [comment]
@heiko-braun Now that all is working ok, can we close this now?
