### ISSUE TITLE
API Connectors no longer working

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#3543]
## This is a...

<pre><code>
[ ] Feature request
[*] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Connectors created from a swagger.json can no longer be used. Using them results in stack traces the pod like below, and causes the pod to die and restart. This issue happens with the existing concur connector or any connector created from swagger.

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-09-04 20:54:07.769 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application startup failed
org.apache.camel.RuntimeCamelException: org.apache.camel.FailedToCreateRouteException: Failed to create route -LLaLsy_npeu-AsuejRO at: >>> Split[simple{${body}} -> [SetHeader[Syndesis.STEP_ID, constant{-LLaLtNenpeu-AsuejRO}], process[Processor@0x4d4b019e], pipeline -> [[SetHeader[Syndesis.STEP_ID, constant{-LLaM11Tnpeu-AsuejRO}], To[atlas:mapping-flow-0-step-1.json?encoding=UTF-8&sourceMapName=Syndesis.CAPTURED_OUT_MESSAGES_MAP], process[Processor@0x7ed8b44]]], pipeline -> [[SetHeader[Syndesis.STEP_ID, constant{-LLaLupsnpeu-AsuejRO}], To[swagger-operation-2?operationId=operation-67], process[Processor@0x7ed8b44]]]]] <<< in route: Route(-LLaLsy_npeu-AsuejRO)[[From[timer:integration?period=6... because of No endpoint could be found for: swagger-operation-2?operationId=operation-67, please check your classpath contains the needed Camel component jar.
	at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1830) ~[camel-core-2.21.0.fuse-720007.jar!/:2.21.0.fuse-720007]
	at org.apache.camel.spring.SpringCamelContext.start(SpringCamelContext.java:136) ~[camel-spring-2.21.0.fuse-720007.jar!/:2.21.0.fuse-720007]
	at org.apache.camel.spring.SpringCamelContext.onApplicationEvent(SpringCamelContext.java:174) ~[camel-spring-2.21.0.fuse-720007.jar!/:2.21.0.fuse-720007]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) ~[spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883) ~[spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.13.RELEASE.jar!/:1.5.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.17.RELEASE.jar!/:4.3.17.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.13.RELEASE.jar!/:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.13.RELEASE.jar!/:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.13.RELEASE.jar!/:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.13.RELEASE.jar!/:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.13.RELEASE.jar!/:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.13.RELEASE.jar!/:1.5.13.RELEASE]
	at io.syndesis.example.Application.main(Application.java:13) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:595) [project-0.1-SNAPSHOT.jar:na]
Caused by: org.apache.camel.FailedToCreateRouteException: Failed to create route -LLaLsy_npeu-AsuejRO at: >>> Split[simple{${body}} -> [SetHeader[Syndesis.STEP_ID, constant{-LLaLtNenpeu-AsuejRO}], process[Processor@0x4d4b019e], pipeline -> [[SetHeader[Syndesis.STEP_ID, constant{-LLaM11Tnpeu-AsuejRO}], To[atlas:mapping-flow-0-step-1.json?encoding=UTF-8&sourceMapName=Syndesis.CAPTURED_OUT_MESSAGES_MAP], process[Processor@0x7ed8b44]]], pipeline -> [[SetHeader[Syndesis.STEP_ID, constant{-LLaLupsnpeu-AsuejRO}], To[swagger-operation-2?operationId=operation-67], process[Processor@0x7ed8b44]]]]] <<< in route: Route(-LLaLsy_npeu-AsuejRO)[[From

**Comment by KurtStam** [comment]
[todo-api.json.txt](https://github.com/syndesisio/syndesis/files/2350363/todo-api.json.txt)
