### ISSUE TITLE
Remove `Exchange.HTTP_URI` header before HTTP request in rest-swagger connector

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3729]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When chaining WebHook connector with API client connector the `Exchange.HTTP_URI` header is set on the Camel message. This will override any URL configured on the HTTP4 component endpoint we configure via rest-swagger connector making the chaining of WebHook and API client connectors impossible.

**Comment by mastepan** [comment]
@zregvart could you please provide me with the steps needed to check this issue? Thanks.

**Comment by zregvart** [comment]
@mastepan try creating an integration that starts with a WebHook or API provider and ends with one of HTTP based connectors (HTTP(S), custom API client).

**Comment by mastepan** [comment]
@zregvart how can I spot the right/wrong behavior then?

**Comment by zregvart** [comment]
@mastepan the wrong behaviour ends up overriding the URL of the HTTP call, so the custom API provider would invoke REST API with WebHooks path like `/api/webhook/<token>` instead of the path of the operation.

**Comment by mastepan** [comment]
@zregvart I get the same result on an old 1.5.4-20181002 or 1.5.4-20181017 or a newer version.
The integration is Webhook -> Https
where:
![https1](https://user-images.githubusercontent.com/8707251/47298783-f1421880-d618-11e8-9a76-632ecc0b6fae.png)
![https](https://user-images.githubusercontent.com/8707251/47298809-ff903480-d618-11e8-9e5b-4103038b1698.png)

The URL has been taken from [https://resttesttest.com/](https://resttesttest.com/)

```
mastepan@localhost:~/git/syndesis/tools/bin (master)$ curl -k -v https://i-aaa-syndesis.192.168.42.52.nip.io/webhook/KFPa2zSY0JGWPDAijMwGmcgvyG7GOCLW6ANrYtiOHmIZU1qaDr
*   Trying 192.168.42.52...
* TCP_NODELAY set
* Connected to i-aaa-syndesis.192.168.42.52.nip.io (192.168.42.52) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* ALPN/NPN, server did not agree to a protocol
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=*.router.default.svc.cluster.local
* 	start date: Oct 22 08:55:16 2018 GMT
* 	expire date: Oct 21 08:55:17 2020 GMT
* 	common name: *.router.default.svc.cluster.local
* 	issuer: CN=openshift-signer@1540198419
>  GET /webhook/KFPa2zSY0JGWPDAijMwGmcgvyG7GOCLW6ANrYtiOHmIZU1qaDr HTTP/1.1
>  Host: i-aaa-syndesis.192.168.42.52.nip.io
>  User-Agent: curl/7.51.0
>  Accept: */*
 
< HTTP/1.1 500 Internal Server Error
< Transfer-Encoding: chunked
< Content-Type: text/plain;charset=ISO-8859-1
< X-Application-Context: application
< Date: Mon, 22 Oct 2018 14:07:57 GMT
< Set-Cookie: a7366ea67717e30c26f6eeabf44a2baa=5c91ff63776d3f35ff28f52ccd8a6a0a; path=/; HttpOnly; Secure
< 
java.lang.IllegalArgumentException: Invalid uri: /webhook/KFPa2zSY0JGWPDAijMwGmcgvyG7GOCLW6ANrYtiOHmIZU1qaDr. If you are forwarding/bridging http endpoints, then enable the bridgeEndpoint option on the endpoint: https4://httpbin.org/get?httpMethod=GET&httpClient.redirectsEnabled=true
	at org.apache.camel.component.http4.HttpProducer.createMethod(HttpProducer.java:476)
	at org.apache.camel.component.http4.HttpProducer.process(HttpProducer.java:113)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at io.syndesis.integration.component.proxy.ComponentProxyProducer.process(ComponentProxyProducer.java:44)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
	at org.apache.camel.http.common.CamelServlet.doService(CamelServlet.java:214)
	at org.apache.camel.http.common.CamelServlet.service(CamelServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:111)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:64)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
* Curl_http_done: called premature == 0
* Connection #0 to host i-aaa-syndesis.192.168.42.52.nip.io left intact

```

I wonder if this is the issue that should have been already fixed.

**Comment by zregvart** [comment]
> I wonder if this is the issue that should have been already fixed.

@mastepan that looks exactly like the issue this was trying to fix, I'm guessing that you did set a URL on the HTTPS component (the screenshots depict empty)?

Nonetheless we need to remove the `Exchange.HTTP_URI`, perhaps after the WebHook would be a better place to do that. Let me try to fix that quickly.

**Comment by mastepan** [comment]
> @mastepan that looks exactly like the issue this was trying to fix, I'm guessing that you did set a URL on the HTTPS component (the screenshots depict empty)?

Strange. I can see them...

Creating new connection (HTTPS) - **Base URL:** _https://httpbin.org/get_

Integration - setting finish HTTPS connection - 
**URL Path:** I let it empty
**Http Method:** _GET_
