### ISSUE TITLE
Google Calendar Connector - 'Create event' action cannot instantiate DateTime class when using data mapper

### ISSUE THREAD

**Issue by jstastny-cz** [syndesisio/syndesis#3803]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When using 'Create Event' action of Google Calendar Connector in combination with Data Mapper I am getting error. I am mapping to DateTime class, but that cannot be instantiated by data mapper, see following stacktrace.

```
io.atlasmap.api.AtlasException: Errors: [Unexpected exception is thrown while populating target field: Could not instantiate class: com.google.api.client.util.DateTime, segment: /start/date: docId='-LOYCLASsRGI0zByb7R1', path='/start/date/value'], [Unexpected exception is thrown while populating target field: Could not instantiate class: com.google.api.client.util.DateTime, segment: /start/date: docId='-LOYCLASsRGI0zByb7R1', path='/start/date/value'], [Unexpected exception is thrown while populating target field: Could not instantiate class: com.google.api.client.util.DateTime, segment: /start/date: docId='-LOYCLASsRGI0zByb7R1', path='/start/date/value'], [Unexpected exception is thrown while populating target field: Could not instantiate class: com.google.api.client.util.DateTime, segment: /start/date: docId='-LOYCLASsRGI0zByb7R1', path='/start/date/value'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:213)
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:715)
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:638)
	at org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:248)
	at org.apache.camel.processor.Splitter.process(Splitter.java:122)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197)
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by oscerd** [comment]
cc @igarashitm

**Comment by oscerd** [comment]
Possible.

**Comment by jstastny-cz** [comment]
@oscerd is this mapping expected to work?

What I wanted to do is to transfer 'events' from my postgres db (everything is varchar there) to google calendar.
The format of datetime column I am trying to map is rfc3339.

**Comment by oscerd** [comment]
I think it cannot work, the dateTime of event expects a com.google.api.client.util.DateTime;

**Comment by oscerd** [comment]
By the way I think is a problem on the datamapper side.

**Comment by jstastny-cz** [comment]
@oscerd Couldn't we then resort to passing a different 'thing'(JSON, or idk) than the Event instance as an inputdata shape to the action? And let the Create Event action to process the input (which would be the same shape as values user can define in the actual form)?
Or is that a complicated change to do?

**Comment by oscerd** [comment]
No, we can't do that, because the camel component expects an Event object for the underline operation.

**Comment by oscerd** [comment]
So if you want to pass a complete one to one mapping, in the way you're suggesting it won't work. You should be able to get an event (or create it in previous step) and pass it, as is, to the create event action.

**Comment by igarashitm** [comment]
Note that java DataShape in datamapper only supports no-arg constructor instantiation, and can't instantiate interface/abstract field type . atlasmap/atlasmap#48 won't solve all problems.

2 options:
* Use JSON/XML representation and marshal it into domain specific Java object in the connector interceptor
* Implement special module for Google Calendar API objects to handle those instantiation in the field writer.

**Comment by oscerd** [comment]
We can also think about use only a subset of the event fields and create a POJO as input and output datashape like we did for gmail or slack.

**Comment by oscerd** [comment]
That would maybe make life easier for the citizen integrator.

**Comment by oscerd** [comment]
@heiko-braun @paoloantinori @gaughan what do you think about a pojo with a subset of the fields for an event?

**Comment by gaughan** [comment]
As per the triage call, I'm ok with that approach.
