### ISSUE TITLE
Google Calendar Connector: Get a specific Event NPE for event without start/end time specification

### ISSUE THREAD

**Issue by jstastny-cz** [syndesisio/syndesis#3828]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
For an event, that has only start/end date specified (whole day event) the 'Get a specific Event' action fails with NPE:
```
java.lang.NullPointerException
	at io.syndesis.connector.calendar.GoogleCalendarGetEventCustomizer.afterProducer(GoogleCalendarGetEventCustomizer.java:92)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.access$100(Pipeline.java:43)
	at org.apache.camel.processor.Pipeline$1.done(Pipeline.java:157)
	at org.apache.camel.util.component.AbstractApiProducer$1.run(AbstractApiProducer.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tplevko** [comment]
@jstastny-cz please verify the fix

**Comment by jstastny-cz** [comment]
The NPE is resolved. The fix still needs some work in the createGoogleEvent method. The method relies on concatenation of date and time part of the datetime. But the time part can be missing. The resulting stacktrace with more info:
```
java.text.ParseException: Unparseable date: "2018-10-01 null"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at io.syndesis.connector.calendar.GoogleCalendarUpdateEventCustomizer.createGoogleEvent(GoogleCalendarUpdateEventCustomizer.java:174)
	at io.syndesis.connector.calendar.GoogleCalendarUpdateEventCustomizer.beforeProducer(GoogleCalendarUpdateEventCustomizer.java:116)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at io.syndesis.integration.component.proxy.ComponentProxyProducer.process(ComponentProxyProducer.java:44)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.access$100(Pipeline.java:43)
	at org.apache.camel.processor.Pipeline$1.done(Pipeline.java:157)
	at org.apache.camel.processor.CamelInternalProcessor$InternalCallback.done(CamelInternalProcessor.java:262)
	at org.apache.camel.processor.RedeliveryErrorHandler$2.done(RedeliveryErrorHandler.java:560)
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.lambda$process$0(ActivityTrackingInterceptStrategy.java:93)
	at org.apache.camel.processor.Pipeline$1.done(Pipeline.java:166)
	at org.apache.camel.processor.CamelInternalProcessor$InternalCallback.done(CamelInternalProcessor.java:262)
	at org.apache.camel.processor.RedeliveryErrorHandler$2.done(RedeliveryErrorHandler.java:560)
	at org.apache.camel.processor.SendProcessor$1.done(SendProcessor.java:160)
	at org.apache.camel.processor.Pipeline$1.done(Pipeline.java:166)
	at org.apache.camel.util.component.AbstractApiProducer$1.run(AbstractApiProducer.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by oscerd** [comment]
This is part of the getEvent action, your stack trace seems to be in the Update action. Maybe raise a different issue could be better for tracking the activities.

**Comment by jstastny-cz** [comment]
Yep, but it was introduced by fix for this issue, anyway, I am happy to open a new one. Feel free to move this one through the pipeline again.

**Comment by oscerd** [comment]
Once I fix the new one, I'll track this one in the PR, so it will be closed.
