### ISSUE TITLE
Integration fails to start when using custom API client in a API-provider based integration 

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3857]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

The integration fails to start with:
```
Caused by: java.lang.IllegalArgumentException: Component servlet is not a RestProducerFactory
	at org.apache.camel.component.rest.RestEndpoint.createProducer(RestEndpoint.java:312) ~[camel-core-2.21.2.jar:2.21.2]
	at org.apache.camel.component.rest.swagger.RestSwaggerEndpoint.createProducerFor(RestSwaggerEndpoint.java:282) ~[camel-rest-swagger-2.21.2.jar:2.21.2]
	at org.apache.camel.component.rest.swagger.RestSwaggerEndpoint.createProducer(RestSwaggerEndpoint.java:187) ~[camel-rest-swagger-2.21.2.jar:2.21.2]
	at org.apache.camel.component.connector.DefaultConnectorEndpoint.createProducer(DefaultConnectorEndpoint.java:51) ~[camel-connector-2.21.2.jar:2.21.2]
	at org.apache.camel.impl.ProducerCache.doGetProducer(ProducerCache.java:573) ~[camel-core-2.21.2.jar:2.21.2]
	... 91 common frames omitted
```
I think we need to add `componentName` `rest-swagger` connector property and set it to `http4`.

Probably related to #3800, i.e. the above could fix that also. (cc @nicolaferraro)

## Expected behavior

Not to blow up if both are used.

## Tasks involved / Steps to Reproduce

1. Create API client for the TODO app (via TODO OpenAPI spec) at `http://$(minishift ip).nip.io/swagger.json`
2. Create connection for the new TODO connector (using http scheme for the host, and bogus username/password)
3. Create API-provider based integration with arbitrary OpenAPI specification
4. In one of the flows add the TODO connection
5. Publish the integration

**Comment by zregvart** [comment]
Fixed via #3800 the new (delegate) endpoint URI is:

`rest-swagger-swagger-operation-0-1://file:/tmp/swagger-operation-0-11614648131460701732.swagger%23operation-0?componentName=http4&consumes=application%2Fjson`
