### ISSUE TITLE
Can't publish an integration with a dot in the name

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#3925]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I tried to publish an integration with a dot (`.`) in the name, got an error:
```
2018-10-22 10:32:03.355 ERROR [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [test-no-basepath-api.json]: [ERROR] Activation failure
javax.validation.ConstraintViolationException: Constraint Validations: name must match "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$" on bean: Container(args=[], command=[], env=[EnvVar(name=LOADER_HOME, value=${JAVA_DATA_DIR}/syndesis/loader, valueFrom=null, additionalProperties={}), EnvVar(name=AB_JMX_EXPORTER_CONFIG, value=/tmp/src/prometheus-config.yml, valueFrom=null, additionalProperties={})], envFrom=[], image=172.30.1.1:5000/syndesis/i-test-no-basepath-api.json:1, imagePullPolicy=Always, lifecycle=null, livenessProbe=null, name=i-test-no-basepath-api.json, ports=[ContainerPort(containerPort=8778, hostIP=null, hostPort=null, name=jolokia, protocol=null, additionalProperties={})], readinessProbe=null, resources=null, securityContext=null, stdin=null, stdinOnce=null, terminationMessagePath=null, terminationMessagePolicy=null, tty=null, volumeMounts=[VolumeMount(mountPath=/deployments/config, name=secret-volume, readOnly=false, subPath=null, additionalProperties={})], workingDir=null, additionalProperties={})
	at io.fabric8.kubernetes.api.builder.ValidationUtils.validate(ValidationUtils.java:36) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
	at io.fabric8.kubernetes.api.model.ContainerBuilder.build(ContainerBuilder.java:81) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
	at io.fabric8.kubernetes.api.model.PodSpecFluentImpl$ContainersNestedImpl.and(PodSpecFluentImpl.java:1063) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
	at io.fabric8.kubernetes.api.model.PodSpecFluentImpl$ContainersNestedImpl.endContainer(PodSpecFluentImpl.java:1066) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
	at io.syndesis.server.openshift.OpenShiftServiceImpl.ensureDeploymentConfig(OpenShiftServiceImpl.java:253) ~[server-openshift-1.5-SNAPSHOT.jar!/:1.5-SNAPSHOT]
	at io.syndesis.server.openshift.OpenShiftServiceImpl.deploy(OpenShiftServiceImpl.java:87) ~[server-openshift-1.5-SNAPSHOT.jar!/:1.5-SNAPSHOT]
	at io.syndesis.server.controller.integration.online.PublishHandler.deploy(PublishHandler.java:182) ~[server-controller-1.5-SNAPSHOT.jar!/:1.5-SNAPSHOT]
	at io.syndesis.server.controller.integration.online.PublishHandler$BuildStepPerformer.perform(PublishHandler.java:333) ~[server-controller-1.5-SNAPSHOT.jar!/:1.5-SNAPSHOT]
	at io.syndesis.server.controller.integration.online.PublishHandler.execute(PublishHandler.java:115) ~[server-controller-1.5-SNAPSHOT.jar!/:1.5-SNAPSHOT]
	at io.syndesis.server.controller.StateChangeHandler.execute(StateChangeHandler.java:33) [server-controller-1.5-SNAPSHOT.jar!/:1.5-SNAPSHOT]
	at io.syndesis.server.controller.integration.IntegrationController.lambda$callStateChangeHandler$11(IntegrationController.java:199) [server-controller-1.5-SNAPSHOT.jar!/:1.5-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
```

**Comment by mastepan** [comment]
@zregvart I still can't publish an integration with name **aaa.** on 1.5.4-20181024
Log from server pod: 
[syndesis-server-1.log](https://github.com/syndesisio/syndesis/files/2509898/syndesis-server-1.log)

**Comment by zregvart** [comment]
@mastepan thank you for finding this, the key here is this `and must start and end with an alphanumeric character`, you tried `aaa.` and it got sanitized into `i-aaa-` and that's not allowed by the former rule.

I think the easiest thing would be to append a character to the end, we can't simply remove it because that would lead to non-unique names for integrations named `Test `, `Test_` and `Test.`. I think we'll just add an `0` if the sanitized name ends with non alphanumeric`.

**Comment by mastepan** [comment]
verified on 1.5.4-20181025
