### ISSUE TITLE
Build failed but deploying integration continue

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4074]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Friday, we have a problem in the Brno office that https://repo1.maven.org/ was unavailable (Access denied). In this case, my integration (AMQ->RESTapi) failed on building. However, deploying integration continue, and pod status is ImagePullBackOff (because image not found). After that, it tries to create new deploy and integration pod again but the result is the same (ImagePullBackOff). (In the example below, it tries 20 times)

```
i-amq-to-rest-api-sample-integration-1-build     0/1       Error              0          20m
i-amq-to-rest-api-sample-integration-20-deploy   1/1       Running            0          25s
i-amq-to-rest-api-sample-integration-20-l6w87    0/1       ImagePullBackOff   0          23s
```

But why Syndesis continue in deployment when the build failed? I would expect that state of integration is set to failed or error.

integration description (oc describe pod i-amq-to-rest-api-sample-integration-20-l6w87):
```
Events:
  Type     Reason     Age                From                Message
  ----     ------     ----               ----                -------
  Normal   Scheduled  44s                default-scheduler   Successfully assigned i-amq-to-rest-api-sample-integration-18-m2pdb to localhost
  Normal   Pulling    27s (x2 over 43s)  kubelet, localhost  pulling image "172.30.1.1:5000/myproject/i-amq-to-rest-api-sample-integration:1"
  Warning  Failed     27s (x2 over 43s)  kubelet, localhost  Failed to pull image "172.30.1.1:5000/myproject/i-amq-to-rest-api-sample-integration:1": rpc error: code = Unknown desc = Error: image myproject/i-amq-to-rest-api-sample-integration:1 not found
  Warning  Failed     27s (x2 over 43s)  kubelet, localhost  Error: ErrImagePull
  Normal   BackOff    13s (x2 over 42s)  kubelet, localhost  Back-off pulling image "172.30.1.1:5000/myproject/i-amq-to-rest-api-sample-integration:1"
  Warning  Failed     13s (x2 over 42s)  kubelet, localhost  Error: ImagePullBackOff
```

build (oc logs i-amq-to-rest-api-sample-integration-1-build):
```
Preparing to build temp.builder.openshift.io/myproject/i-amq-to-rest-api-sample-integration-1:0a118d1c
Copying sources from "/tmp/build/inputs" to "/tmp/upload/src"
Clean build will be performed
Running "assemble" in "temp.builder.openshift.io/myproject/i-amq-to-rest-api-sample-integration-1:0a118d1c"
==================================================================
Starting S2I Java Build .....
S2I source build for Maven detected
Using custom maven settings from /tmp/src/configuration/settings.xml
Using MAVEN_OPTS '-XX:+UseG1GC -XX:+UseStringDeduplication -Xmx310m'
Found pom.xml ...
Running 'mvn -Dmaven.repo.local=/tmp/artifacts/m2 -s /tmp/src/configuration/settings.xml package -DskipTests -Dmaven.javadoc.skip=true -Dmaven.site.skip=true -Dmaven.source.skip=true -Djacoco.skip=true -Dcheckstyle.skip=true -Dfindbugs.skip=true -Dpmd.skip=true -Dfabric8.skip=true -e -B '
Apache Maven 3.3.9 (Red Hat 3.3.9-2.8)
Maven home: /opt/rh/rh-maven33/root/usr/share/maven
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.10.0-862.14.4.el7.x86_64", arch: "amd64", family: "unix"
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Syndesis Integrations :: AMQ to REST API Sample Integration 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: https://repo1.maven.org/maven2/org/apache/camel/camel-jacksonxml/2.21.0.fuse-720040-redhat-00001/camel-jacksonxml-2.21.0.fuse-720040-redhat-00001.pom
[INFO] Downloading: https://maven.repository.redhat.com/ga/org/apache/camel/camel-jacksonxml/2.21.0.fuse-720040-redhat-00001/camel-jacksonxml-2.21.0.fuse-720040-redhat-00001.pom
[INFO] Downloading: https://repository.jboss.org/nexus/content/groups/ea/org/apache/camel/camel-jacksonxml/2.21.0.fuse-720040-redhat-00001/camel-jacksonxml-2.21.0.fuse-720040-redhat-00001.pom
[INFO] Downloading: https://repo1.maven.org/maven2/org/apache/camel/camel-jacksonxml/2.21.0.fuse-720040-redhat-00001/camel-jacksonxml-2.21.0.fuse-720040-redhat-00001.pom
[INFO] Downloading: https://repository.jboss.org/org/apache/camel/camel-jacksonxml/2.21.0.fuse-720040-redhat-00001/camel-jacksonxml-2.21.0.fuse-720040-redhat-00001.pom
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/camel/camel-jacksonxml/2.21.0.fuse-720040-redhat-00001/camel-jacksonxml-2.21.0.fuse-720040-redhat-00001.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.344 s
[INFO] Finished at: 2018-11-09T13:39:07+00:00
[INFO] Final Memory: 25M/84M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project project: Could not resolve dependencies for project io.syndesis.integrations:project:jar:0.1-SNAPSHOT: Failed to collect dependencies at org.apache.camel:camel-jacksonxml:jar:2.21.0.fuse-720040-redhat-00001: Failed to read artifact descriptor for org.apache.camel:camel-jacksonxml:jar:2.21.0.fuse-720040-redhat-00001: Could not transfer artifact org.apache.camel:camel-jacksonxml:pom:2.21.0.fuse-720040-redhat-00001 from/to maven.central (https://repo1.maven.org/maven2): Access denied to: https://repo1.maven.org/maven2/org/apache/camel/camel-jacksonxml/2.21.0.fuse-720040-redhat-00001/camel-jacksonxml-2.21.0.fuse-720040-redhat-00001.pom , ReasonPhrase:Forbidden. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project project: Could not resolve dependencies for project io.syndesis.integrations:project:jar:0.1-SNAPSHOT: Failed to collect dependencies at org.apache.camel:camel-jacksonxml:jar:2.21.0.fuse-720040-redhat-00001
at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project io.syndesis.integrations:project:jar:0.1-SNAPSHOT: Failed to collect dependencies at org.apache.camel:camel-jacksonxml:jar:2.21.0.fuse-720040-redhat-00001
at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:180)
at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
... 23 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.apache.camel:camel-jacksonxml:jar:2.21.0.fuse-720040-redhat-00001
at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:172)
... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.apache.camel:camel-jacksonxml:jar:2.21.0.fuse-720040-redhat-00001
at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:282)
at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
... 26 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.apache.camel:camel-jacksonxml:pom:2.21.0.fuse-720040-redhat-00001 from/to maven.central (https://repo1.maven.org/maven2): Access denied to: https://repo1.maven.org/maven2/org/apache/camel/camel-jacksonxml/2.21.0.fuse-720040-redhat-00001/camel-jacksonxml-2.21.0.fuse-720040-redhat-00001.pom , ReasonPhrase:Forbidden.
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:267)
... 33 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.apache.camel:camel-jacksonxml:pom:2.21.0.fuse-720040-redhat-00001 from/to maven.central (https://repo1.maven.org/maven2): Access denied to: https://repo1.maven.org/maven2/org/apache/camel/camel-jacksonxml/2.21.0.fuse-720040-redhat-00001/camel-jacksonxml-2.21.0.fuse-720040-redhat-00001.pom , ReasonPhrase:Forbidden.
at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
... 36 more
Caused by: org.apache.maven.wagon.authorization.AuthorizationException: Access denied to: https://repo1.maven.org/maven2/org/apache/camel/camel-jacksonxml/2.21.0.fuse-720040-redhat-00001/camel-jacksonxml-2.21.0.fuse-720040-redhat-00001.pom , ReasonPhrase:Forbidden.
at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1001)
at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:960)
at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
... 41 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
Aborting due to error code 1 for Maven build
assemble failed with rc=1
error: build error: non-zero (13) exit code from brew-pulp-
```

**Comment by zregvart** [comment]
We have the notion of controller, very much like kubernetes does, this controller notices that the integration needs to be published and tries to publish it. If it fails it will retry to publish the integration. This includes building and creating deployment config, service... as needed.

We do check for the status of the build, and fail the deployment if the build ends up in error:

https://github.com/syndesisio/syndesis/blob/903af9fef5d766971932283555e36f25390261ec/app/server/controller/src/main/java/io/syndesis/server/controller/integration/online/PublishHandler.java#L97-L99

https://github.com/syndesisio/syndesis/blob/903af9fef5d766971932283555e36f25390261ec/app/server/openshift/src/main/java/io/syndesis/server/openshift/OpenShiftServiceImpl.java#L158-L169

Not sure why this didn't work out in this case.
