### ISSUE TITLE
Insertion to DB inserts empty strings when a step with another insertion is before

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4182]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I have this integration
![image](https://user-images.githubusercontent.com/16251792/49222702-e0857f00-f3dc-11e8-9ef4-6c2f8d9aecd9.png)
Integration gets data from webhook, inserts to DB static values (e.g. for some logging), maps webhook data to insert and inserts data to DB.

After sending data to webhook,
```
curl -k -v https://i-hook-to-db-with-db-syndesis.192.168.42.27.nip.io/webhook/test-webhook -d '{"first_name":"John","company":"Red Hat"}' -X POST -H "Content-Type: application/json"
```
 DB **should** contain:
```
 first_name | last_name |  company   | lead_source | create_date
------------+-----------+------------+-------------+-------------
 middleSTEP |           | middleStep |             |
 John       |           | Red Hat    |             |
```

but the contact from the last step has only empty strings.
```
 first_name | last_name |  company   | lead_source | create_date
------------+-----------+------------+-------------+-------------
 middleSTEP |           | middleStep |             |
            |           |            |             |
```

When I delete middle step with insertion static data (first PostgesDB step), integraion works and integration inserts data from webhook to DB correctly
```
 first_name | last_name |  company   | lead_source | create_date
------------+-----------+------------+-------------+-------------
 John       |           | Red Hat    |             |
```

I looked to the data maper but the mapping data from webhook to final insert looks correct.
![image](https://user-images.githubusercontent.com/16251792/49223238-7b328d80-f3de-11e8-949f-4da791651118.png)

Integration: 
[hook-to-db-with-db-export.zip](https://github.com/syndesisio/syndesis/files/2629213/hook-to-db-with-db-export.zip)

**Step to reproduce:**

1. Import and publish integration
2. Run command: (update webhook url according to integration)
```
curl -k -v https://i-hook-to-db-with-db-syndesis.192.168.42.27.nip.io/webhook/test-webhook -d '{"first_name":"John","company":"Red Hat"}' -X POST -H "Content-Type: application/json"
```

3. Look to the Syndesis-DB pod. The table should contains row with 'middleSTEP' values and one row which has **all values empty**
```
psql
\connect sampledb
SELECT * FROM contact;
```

4. Delete middle step from integration and republish
5. Run command for webhook again (step 2.)
6. Look to the DB pod again (step 3.)
    The table should contains row with first name John and company RedHat

**Comment by heiko-braun** [comment]
@KurtStam Any update on this?

**Comment by KurtStam** [comment]
Yeah somehow the data mapper doesn't have access to the PersonInfo set by the WebHook:

io.atlasmap.api.AtlasException: Errors: [Unexpected exception is thrown while reading source field: null: docId='-LSUSDc0ffM14KFZg1Ep', path='/company'], [Unexpected exception is thrown while reading source field: null: docId='-LSUSDc0ffM14KFZg1Ep', path='/company'], [Unexpected exception is thrown while reading source field: null: docId='-LSUSDc0ffM14KFZg1Ep', path='/first_name'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:266)

It reads nulls. And thus nulls end up in second row in the DB.

**Comment by KurtStam** [comment]
I actually never see the PersonInfo being set into the body by the Webhook, no matter what scenario.

**Comment by mkralik3** [comment]
When I tried to verify, the "middle" query is run and values are saved to db, however, the exception is thrown and the final query is not run. When I delete "middle" postgresDB step, run final query works.

I am able to reproduce this when I create a new integration or I import integration from the first comment.

Exception:
```
io.atlasmap.api.AtlasException: Errors: [Unexpected exception is thrown while reading source field: null: docId='-LaGMx7bGJ6DFt_2c-yW', path='/company'], [Unexpected exception is thrown while reading source field: null: docId='-LaGMx7bGJ6DFt_2c-yW', path='/company'], [Unexpected exception is thrown while reading source field: null: docId='-LaGMx7bGJ6DFt_2c-yW', path='/first_name'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:266)
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
	at org.apache.camel.http.common.CamelServlet.doService(CamelServlet.java:214)
	at org.apache.camel.http.common.CamelServlet.service(CamelServlet.java:80)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:111)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:64)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by KurtStam** [comment]
@mkralik3 Not sure what's going bc it's working ok for me with a fresh install from master. Can you check you have the latest code, especially 
https://github.com/syndesisio/syndesis/commit/fc7ad4c66d819759e24b3f293de9887e981eb81f

**Comment by mkralik3** [comment]
Correct, my bad, it works. Probably old version of the Syndesis.
