### ISSUE TITLE
Unstable GoogleSheets integration test breaks build

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4266]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

GoogleSheets integration test is unstable failing from time to time with following error:

```
[INFO] Running org.apache.camel.component.google.sheets.stream.SheetsStreamConsumerIntegrationTest
[ERROR] Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 8.897 s <<< FAILURE! - in org.apache.camel.component.google.sheets.stream.SheetsStreamConsumerIntegrationTest
[ERROR] testConsumeValueRange(org.apache.camel.component.google.sheets.stream.SheetsStreamConsumerIntegrationTest)  Time elapsed: 7.586 s  <<< ERROR!
org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[ID-8a10ca970798-1547073284681-14-1]
	at org.apache.camel.component.google.sheets.stream.SheetsStreamConsumerIntegrationTest.testConsumeValueRange(SheetsStreamConsumerIntegrationTest.java:59)
Caused by: org.apache.camel.RuntimeCamelException: java.lang.IllegalArgumentException: no JSON input found
Caused by: java.lang.IllegalArgumentException: no JSON input found

[ERROR] testConsumeValueRange(org.apache.camel.component.google.sheets.stream.SheetsStreamConsumerIntegrationTest)  Time elapsed: 7.586 s  <<< ERROR!
com.consol.citrus.exceptions.TestCaseFailedException: java.lang.NullPointerException
Caused by: com.consol.citrus.exceptions.CitrusRuntimeException: java.lang.NullPointerException
Caused by: java.lang.NullPointerException
```

**Comment by christophd** [comment]
Maybe leave this issue open until we have seen some builds to complete without that error. Maybe one week?

**Comment by christophd** [comment]
Issue seems to be solved. There were no further failing builds with that particular reason

**Comment by christophd** [comment]
We have to further investigate on this as @alexkieling came up with some failing tests locally:

```
[INFO] Running org.apache.camel.component.google.sheets.stream.SheetsStreamConsumerIntegrationTest
[ERROR] Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 6.553 s <<< FAILURE! - in org.apache.camel.component.google.sheets.stream.SheetsStreamConsumerIntegrationTest
[ERROR] testConsumeValueRange(org.apache.camel.component.google.sheets.stream.SheetsStreamConsumerIntegrationTest)  Time elapsed: 5.252 s  <<< ERROR!
org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[ID-localhost-localdomain-1548370740210-50-1]
	at org.apache.camel.component.google.sheets.stream.SheetsStreamConsumerIntegrationTest.testConsumeValueRange(SheetsStreamConsumerIntegrationTest.java:60)
Caused by: org.apache.camel.RuntimeCamelException: java.lang.IllegalArgumentException: no JSON input found
Caused by: java.lang.IllegalArgumentException: no JSON input found

[ERROR] testConsumeValueRange(org.apache.camel.component.google.sheets.stream.SheetsStreamConsumerIntegrationTest)  Time elapsed: 5.252 s  <<< ERROR!
com.consol.citrus.exceptions.TestCaseFailedException: java.lang.NullPointerException
Caused by: com.consol.citrus.exceptions.CitrusRuntimeException: java.lang.NullPointerException
Caused by: java.lang.NullPointerException

[INFO] Running io.syndesis.connector.sheets.GoogleSheetsAddPivotTableCustomizerTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.096 s - in io.syndesis.connector.sheets.GoogleSheetsAddPivotTableCustomizerTest
[INFO] Running org.apache.camel.component.google.sheets.SheetsSpreadsheetsIntegrationTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.579 s - in org.apache.camel.component.google.sheets.SheetsSpreadsheetsIntegrationTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR] org.apache.camel.component.google.sheets.stream.SheetsStreamConsumerIntegrationTest.testConsumeValueRange(org.apache.camel.component.google.sheets.stream.SheetsStreamConsumerIntegrationTest)
[ERROR]   Run 1: SheetsStreamConsumerIntegrationTest.testConsumeValueRange:60->AbstractGoogleSheetsTestSupport.getSpreadsheetWithTestData:190->AbstractGoogleSheetsTestSupport.createTestSpreadsheet:90->AbstractGoogleSheetsTestSupport.requestBody:178 » CamelExecution
[ERROR]   Run 2: SheetsStreamConsumerIntegrationTest>AbstractGoogleSheetsTestSupport.resetServer:70 » TestCaseFailed
[INFO] 
[INFO] 
[ERROR] Tests run: 83, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by christophd** [comment]
still not working very well 👎 

https://circleci.com/gh/syndesisio/syndesis/59104

I have to take another look

**Comment by tplevko** [comment]
QE does not need to verify - tests are passing, closing this.
