### ISSUE TITLE
Stranged default when using a Cron Timer

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#4491]
![grafik](https://user-images.githubusercontent.com/99080/52498505-48c0c000-2bd9-11e9-8623-f9a61573d7c3.png)

The text field is initialized with '+' as separators. Shouldn't this be " " ?

BTW, from an UX point of view it would be far better to allow 5 input fields with labels like "minute" "hour" .... for every column, I never can memorize the order of these columns.

**Comment by rhuss** [comment]
BTW, when pressing "done" i get the same error as in #4490

**Comment by heiko-braun** [comment]
@gashcrumb Here's another low hanging fruit

**Comment by gashcrumb** [comment]
@heiko-braun this is something that's set in the connector definition, not the UI

**Comment by gashcrumb** [comment]
Also I agree that separate fields for the columns would be way easier to deal with, that'd be another connector definition change and probably also require work on the connector itself to combine the separate fields into one string, but I'm only speculating here.

**Comment by zregvart** [comment]
Seems that this needs to change:

https://github.com/syndesisio/syndesis/blob/826c8d829b7b7d688279f42bda5e028a3d6aa4f7/app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json#L64

@oscerd are we not properly URL encoding so `+` is required for ` `?

Change that introduced this: https://github.com/syndesisio/syndesis/commit/ca87203f8928c36bcda2a73068a36a2a1202712a

**Comment by oscerd** [comment]
That was just an example

**Comment by mmuzikar** [comment]
The default value now appears correctly with spaces instead of pluses, but a simple integration using the default Cron value crashes with this log:
```
org.apache.camel.RuntimeCamelException: org.apache.camel.FailedToCreateRouteException: Failed to create route -L_7vQwYcso8HIomNGxM: Route(-L_7vQwYcso8HIomNGxM)[[From[quartz2-0-0]] -> [SetHeade... because of Failed to resolve endpoint: quartz2-0-0 due to: Failed to resolve endpoint: quartz2://syndesis-quartz?cron=0+0%2F1+*+*+*+%3F due to: No component found with scheme: quartz2
	at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1830) ~[camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.spring.SpringCamelContext.start(SpringCamelContext.java:136) ~[camel-spring-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.spring.SpringCamelContext.onApplicationEvent(SpringCamelContext.java:174) ~[camel-spring-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at io.syndesis.example.Application.main(Application.java:13) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:595) [project-0.1-SNAPSHOT.jar:na]
```

**Comment by oscerd** [comment]
It doesn't seem to be related to the cron rule.

**Comment by mmuzikar** [comment]
The default value is set correctly opened another issue reporting that the cron timer doesn't work #4734
