### ISSUE TITLE
Error handling update event ChangeEvent{kind=connection} after upgrade (related to the split step)

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4515]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
this is related to this: https://github.com/syndesisio/syndesis/commit/651e87f5aff91ce59fdb38258d2ae046b848f6aa

I deployed syndesis version `1.6.1-20190115`, created integration `periodic sql invocation (select * from contact) -> log`

Then I upgraded to `1.6.1-20190211` and during the upgrade, the integration was edited to use the new split step. When the server pod starts, it throws this warning:

```
2019-02-11 16:46:12.986  WARN [-,,,] 1 --- [ler (scheduler)] i.s.s.u.c.b.IntegrationUpdateHandler     : Error handling update event ChangeEvent{kind=connection}
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[na:1.8.0_151]
	at io.syndesis.common.model.support.Equivalencer.equivalent(Equivalencer.java:404) ~[common-model-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.common.model.support.Equivalencer.equivalent(Equivalencer.java:339) ~[common-model-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.bulletin.IntegrationUpdateHandler.computeDeploymentDifferences(IntegrationUpdateHandler.java:413) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.bulletin.IntegrationUpdateHandler.compute(IntegrationUpdateHandler.java:370) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.bulletin.AbstractResourceUpdateHandler.process(AbstractResourceUpdateHandler.java:62) ~[server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.bulletin.IntegrationUpdateHandler.process(IntegrationUpdateHandler.java:57) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.ResourceUpdateController.run(ResourceUpdateController.java:107) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
```

When I create a new integration (the same, sql -> log), similar warnings appear in the log:

```
2019-02-11 16:46:22.218  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [qwqe]: Starting deployment
2019-02-11 16:46:32.086  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [qwqe]: Deployment done
2019-02-11 16:46:32.321  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [qwqe]: Build started: false, isRunning: false, Deployment ready: false
2019-02-11 16:46:32.323  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [qwqe]: [PENDING] [{buildv1=172.30.1.1:5000/syndesis/i-qwqe:1, deploy=1}]
2019-02-11 16:46:32.324  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LYSRE95P3Q_r0Eymb11z : Setting status to Pending
2019-02-11 16:46:35.811  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Checking integrations for their status.
2019-02-11 16:47:32.425  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Integration i-LYSRE95P3Q_r0Eymb11z:1 : Desired status "Published" != current status "Unpublished" --> calling status change handler
2019-02-11 16:47:32.425  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LYSRE95P3Q_r0Eymb11z : Start processing integration: i-LYSRE95P3Q_r0Eymb11z, version: 1 with handler:PublishHandler
2019-02-11 16:47:32.486  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [qwqe]: Build started: false, isRunning: false, Deployment ready: false
2019-02-11 16:47:32.487  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [qwqe]: Steps performed so far: {buildv1=172.30.1.1:5000/syndesis/i-qwqe:1}
2019-02-11 16:47:32.791  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [qwqe]: Skipped step buildv1 because already performed
2019-02-11 16:47:32.824  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [qwqe]: Starting deployment
2019-02-11 16:47:33.292  WARN [-,,,] 1 --- [ler (scheduler)] i.s.s.u.c.b.IntegrationUpdateHandler     : Error handling update event ChangeEvent{action=updated, kind=integration, id=i-LYSRE95P3Q_r0Eymb11z}
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[na:1.8.0_151]
	at io.syndesis.common.model.support.Equivalencer.equivalent(Equivalencer.java:404) ~[common-model-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.common.model.support.Equivalencer.equivalent(Equivalencer.java:339) ~[common-model-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.bulletin.IntegrationUpdateHandler.computeDeploymentDifferences(IntegrationUpdateHandler.java:413) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.bulletin.IntegrationUpdateHandler.compute(IntegrationUpdateHandler.java:370) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.bulletin.AbstractResourceUpdateHandler.process(AbstractResourceUpdateHandler.java:62) ~[server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.bulletin.IntegrationUpdateHandler.process(IntegrationUpdateHandler.java:57) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.ResourceUpdateController.run(ResourceUpdateController.java:128) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.ResourceUpdateController.lambda$onEvent$0(ResourceUpdateController.java:90) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
2019-02-11 16:47:35.812  INFO [-,,,] 1 --- [oller Scheduler] i.s.s.c.i.IntegrationController          : Checking integrations for their status.
2019-02-11 16:47:36.489  WARN [-,,,] 1 --- [ler (scheduler)] i.s.s.u.c.b.IntegrationUpdateHandler     : Error handling update event ChangeEvent{action=updated, kind=connection, id=5}
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[na:1.8.0_151]
	at io.syndesis.common.model.support.Equivalencer.equivalent(Equivalencer.java:404) ~[common-model-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.common.model.support.Equivalencer.equivalent(Equivalencer.java:339) ~[common-model-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.bulletin.IntegrationUpdateHandler.computeDeploymentDifferences(IntegrationUpdateHandler.java:413) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.bulletin.IntegrationUpdateHandler.compute(IntegrationUpdateHandler.java:370) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.bulletin.AbstractResourceUpdateHandler.process(AbstractResourceUpdateHandler.java:62) ~[server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.bulletin.IntegrationUpdateHandler.process(IntegrationUpdateHandler.java:57) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.ResourceUpdateController.run(ResourceUpdateController.java:128) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.ResourceUpdateController.lambda$onEvent$0(ResourceUpdateController.java:90) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
2019-02-11 16:47:37.194  WARN [-,,,] 1 --- [ler (scheduler)] i.s.s.u.c.b.IntegrationUpdateHandler     : Error handling update event ChangeEvent{action=updated, kind=connection, id=log}
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[na:1.8.0_151]
	at io.syndesis.common.model.support.Equivalencer.equivalent(Equivalencer.java:404) ~[common-model-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.common.model.support.Equivalencer.equivalent(Equivalencer.java:339) ~[common-model-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.bulletin.IntegrationUpdateHandler.computeDeploymentDifferences(IntegrationUpdateHandler.java:413) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.bulletin.IntegrationUpdateHandler.compute(IntegrationUpdateHandler.java:370) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.bulletin.AbstractResourceUpdateHandler.process(AbstractResourceUpdateHandler.java:62) ~[server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.bulletin.IntegrationUpdateHandler.process(IntegrationUpdateHandler.java:57) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.ResourceUpdateController.run(ResourceUpdateController.java:128) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at io.syndesis.server.update.controller.ResourceUpdateController.lambda$onEvent$0(ResourceUpdateController.java:90) [server-update-controller-1.6.1-20190211.jar!/:1.6.1-20190211]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
2019-02-11 16:47:42.814  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [qwqe]: Deployment done
2019-02-11 16:47:42.889  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [qwqe]: Build started: false, isRunning: false, Deployment ready: false
2019-02-11 16:47:42.890  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.integration.online.BaseHandler   : Integration [qwqe]: [PENDING] [{buildv1=172.30.1.1:5000/syndesis/i-qwqe:1, deploy=2}]
2019-02-11 16:47:42.890  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.IntegrationController          : Integration i-LYSRE95P3Q_r0Eymb11z : Setting status to Pending
```

Otherwise, the integration seems to be working normally

EDIT: the logs are still about the first integration as it is trying to tell me that I should update it after infrastructure upgrade, but it can't because of some missing value

**Comment by avano** [comment]
cc @christophd

**Comment by avano** [comment]
ok, the error goes away after rebuilding the integration, but the problem is that the UI doesn't tell me to rebuild it, because of the mentioned error

**Comment by avano** [comment]
is ok now when upgrading from 1.5.10 to 1.6.1-20190228
