### ISSUE TITLE
[Datamapper][Split] Source fields are shown from both previous steps (SQL, Split)

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4568]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I use the integration `SQL -> Split -> Datamapper -> SQL -> Aggregate`, this is what I see in datamapper:
![rf4v](https://user-images.githubusercontent.com/7081216/52790160-2a8a1280-3066-11e9-8974-d6c0e90df53f.png)

When I map `2- SQL Result` to a task, it fails with the following exception:

```
2019-02-14 13:31:38.310  WARN 1 --- [r://integration] o.a.c.component.atlasmap.AtlasEndpoint   : Null or non-String source document: docId='DOC.2 - SQL Result.572262': docId='DOC.2 - SQL Result.572262', path='null'
2019-02-14 13:31:38.323 ERROR 1 --- [r://integration] o.a.camel.processor.DefaultErrorHandler  : Failed delivery for (MessageId: i-LYgC8gNPNRr_qeWMwQ2z on ExchangeId: i-LYgC8gKPNRr_qeWMwQ1z). Exhausted after delivery attempt: 1 caught: io.atlasmap.api.AtlasException: Errors: [Source document 'DOC.2 - SQL Result.572262' doesn't exist: docId='DOC.2 - SQL Result.572262', path='/first_name'], 
Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[-LYg9zdz6bChFdHo1b] [-LYg9zdz6bChFdHo1b] [timer://integration?period=60000                                              ] [      1413]
[-LYg9zdz6bChFdHo1b] [setHeader2        ] [setHeader[Syndesis.STEP_ID]                                                   ] [         0]
[-LYg9zdz6bChFdHo1b] [process1          ] [Processor@0x61a4d060                                                          ] [         1]
[-LYg9zdz6bChFdHo1b] [step:-LYgBsjE6bChF] [pipeline                                                                      ] [         0]
[-LYg9zdz6bChFdHo1b] [setHeader3        ] [setHeader[Syndesis.STEP_ID]                                                   ] [         0]
[-LYg9zdz6bChFdHo1b] [to2               ] [atlas:mapping-flow-0-step-2.json?encoding=UTF-8&sourceMapName=Syndesis.CAPTURE] [      1190]
Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
io.atlasmap.api.AtlasException: Errors: [Source document 'DOC.2 - SQL Result.572262' doesn't exist: docId='DOC.2 - SQL Result.572262', path='/first_name'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:266) ~[camel-atlasmap-1.39.1.jar!/:na]
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79) [integration-runtime-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:715) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:638) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:248) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.Splitter.process(Splitter.java:122) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_191]
	at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_191]
{"exchange":"i-LYgC8d6PNRr_qeWMwQ-z","step":"-LYgBsjE6bChFdHo1bsq","id":"i-LYgC8gOPNRr_qeWMwQ3z","duration":1210992705,"failure":"io.atlasmap.api.AtlasException: Errors: [Source document 'DOC.2 - SQL Result.572262' doesn't exist: docId='DOC.2 - SQL Result.572262', path='/first_name'], \n\tat org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:266)\n\tat org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71)\n\tat org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)\n\tat org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)\n\tat io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:715)\n\tat org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:638)\n\tat org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:248)\n\tat org.apache.camel.processor.Splitter.process(Splitter.java:122)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197)\n\tat org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79)\n\tat java.util.TimerThread.mainLoop(Timer.java:555)\n\tat java.util.TimerThread.run(Timer.java:505)\n"}
{"exchange":"i-LYgC8d6PNRr_qeWMwQ-z","status":"done","failed":true}
2019-02-14 13:31:38.331  WARN 1 --- [r://integration] o.a.camel.component.timer.TimerConsumer  : Error processing exchange. Exchange[i-LYgC8d6PNRr_qeWMwQ-z]. Caused by: [io.atlasmap.api.AtlasException - Errors: [Source document 'DOC.2 - SQL Result.572262' doesn't exist: docId='DOC.2 - SQL Result.572262', path='/first_name'], ]
io.atlasmap.api.AtlasException: Errors: [Source document 'DOC.2 - SQL Result.572262' doesn't exist: docId='DOC.2 - SQL Result.572262', path='/first_name'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:266) ~[camel-atlasmap-1.39.1.jar!/:na]
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79) ~[integration-runtime-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:715) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:638) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:248) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.Splitter.process(Splitter.java:122) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) [camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_191]
	at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_191]

```

When I map from `1 - SQL Result` it seems to be working (although the ugly warning is still there):
```
2019-02-14 13:36:24.875  WARN 1 --- [r://integration] o.a.c.component.atlasmap.AtlasEndpoint   : Null or non-String source document: docId='-LYgBsjE6bChFdHo1bsp': docId='-LYgBsjE6bChFdHo1bsp', path='null'
{"exchange":"i-LYgDEbw9mPK12cz3-XGz","step":"-LYgBsjE6bChFdHo1bsq","id":"i-LYgDEfh9mPK12cz3-XKz","duration":1088527464}
{"exchange":"i-LYgDEbw9mPK12cz3-XGz","step":"-LYgAGoJ6bChFdHo1bsp","id":"i-LYgDEwk9mPK12cz3-XMz","duration":20447413}
{"exchange":"i-LYgDEbw9mPK12cz3-XGz","status":"done","failed":false}

```

**Comment by christophd** [comment]
Already seen that on my machine. I guess the API provider collection support latest changes do have influence on pure split/aggregate logic causing those errors

**Comment by zregvart** [comment]
Perhaps we need to copy the exchange properties from the original exchange to the individual one created in split. IIRC Atlasmap keeps copies of source documents in an exchange property.

**Comment by gashcrumb** [comment]
Will update the data mapper component to stop looking at the step array once it encounters a split which will at least prevent it from showing up in the UI.  We may also need some additional work to ensure the aggregate step has the correct output data shape and that the data mapper sees it, once I update the host component I'll try the above integration and see how that looks in the editor.  

Thinking about it more now I suspect the way the code is written that the aggregate step probably would be getting the data mappers output data shape, and the data mapper is finding the aggregate step's input data shape as it's output.  Guess it'll take some discovery :-)

**Comment by gashcrumb** [comment]
Linked PR should sort this specific problem.  I also added some text when a step has a collection, for example:

![image](https://user-images.githubusercontent.com/351660/52800464-cd806380-3049-11e9-917d-76b89ba043c4.png)

@christophd Do you have a use case in mind with the aggregate step?  Unfortunately the typical kind of integration I use doesn't technically need an aggregate step :-)

Maybe it'd be good if you could raise an issue with the sequence of steps that we want to support and assign it to me?

**Comment by gashcrumb** [comment]
Ah, I think #4355 is what I'm thinking of @christophd, thanks!

**Comment by avano** [comment]
looks ok now
