### ISSUE TITLE
google-scheets: unable to create chart

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#4583]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Add charts step doesn't work. I have simple spreadsheet with few entries: 
![screenshot_20190215_102503](https://user-images.githubusercontent.com/6814482/52847248-f406d300-310b-11e9-8ebe-3de3ac4248bb.png)
and simple mapping: 
![screenshot_20190215_102654](https://user-images.githubusercontent.com/6814482/52847374-49db7b00-310c-11e9-9b7b-7d30ce266388.png)

 Following exception is thrown in integration: 
```
org.apache.camel.RuntimeCamelException: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Invalid requests[0].addChart: ChartSourceRange ranges require all rows or all columns to have length of 1",
    "reason" : "badRequest"
  } ],
  "message" : "Invalid requests[0].addChart: ChartSourceRange ranges require all rows or all columns to have length of 1",
  "status" : "INVALID_ARGUMENT"
}
	at org.apache.camel.component.google.sheets.GoogleSheetsProducer.doInvokeMethod(GoogleSheetsProducer.java:49)
	at org.apache.camel.util.component.AbstractApiProducer$1.run(AbstractApiProducer.java:86)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Invalid requests[0].addChart: ChartSourceRange ranges require all rows or all columns to have length of 1",
    "reason" : "badRequest"
  } ],
  "message" : "Invalid requests[0].addChart: ChartSourceRange ranges require all rows or all columns to have length of 1",
  "status" : "INVALID_ARGUMENT"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at org.apache.camel.component.google.sheets.GoogleSheetsProducer.doInvokeMethod(GoogleSheetsProducer.java:47)
	... 8 more
```

**Comment by christophd** [comment]
Seems to be related to how Google Sheets API handles the domain and source ranges. If range is changed to `A1:A20` and `B1:B20` it is working fine. So we need to include the row before the actual data range, too.

I guess this goes down to how the grid range is calculated: https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/other#gridrange

When I have a look at the reference example for charts the row before the actual source data is also included in the chart ranges: https://developers.google.com/sheets/api/samples/charts

**Comment by christophd** [comment]
The Google Sheets API documentation says 

> The strings in the first row are labels for the individual columns

I think we have to include a first row providing labels and these labels should not be empty.

**Comment by christophd** [comment]
@mmelko WDYT? can we treat that as a Google Sheets requirement?

**Comment by mmelko** [comment]
I'd say yes. @TovaCohen I guess this should be included in doc.

**Comment by TovaCohen** [comment]
@mmelko , thanks to @christophd , this now in the user doc. You can see it in the Google document:
https://docs.google.com/document/d/1KeBgAP6UU-fTgMp3zysQKIwNW-GmmCADlX5yrOGulw4/edit#heading=h.isoagfy4wd73

I updated the descriptions of domainRange and dataRange for both basic charts and pie charts. Let me know if you think anything in the doc is unclear or needs to change.
