### ISSUE TITLE
Unable to use basic filter with collection (was: Inconsistent behavior with SQL connector and message split)

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#4629]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

I have following integration:

```
1. SQL - Periodic invocation - Select * from contact
2. AMQ - Publish messages to some queue
```

In this scenario, the list from SQL connector is automatically split into multiple messages for some reason even when I didn't specify the `split` step. So when I have 2 contacts in the database, I receive 2 messages in the queue.

Now I want to add a basic filter to the integration - since the split magic is being done, I might not need the explicit "split" step, so I create:

```
1. SQL - Periodic invocation - Select * from contact
2. Basic filter - last_name contains something (now I know something is wrong because I don't have the autocomplete for the field)
3. AMQ - Publish messages to some queue
```  

Obviously, the integration fails with:

```
org.apache.camel.spring.boot.CamelSpringBootInitializationException: java.lang.IllegalArgumentException: java.lang.IllegalStateException: No step properties defined for rule filter step
	at org.apache.camel.spring.boot.RoutesCollector.onApplicationEvent(RoutesCollector.java:250) ~[camel-spring-boot-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.spring.boot.RoutesCollector.onApplicationEvent(RoutesCollector.java:57) ~[camel-spring-boot-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at io.syndesis.example.Application.main(Application.java:13) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:595) [project-0.1-SNAPSHOT.jar:na]
Caused by: java.lang.IllegalArgumentException: java.lang.IllegalStateException: No step properties defined for rule filter step
	at io.syndesis.integration.runtime.sb.IntegrationRuntimeAutoConfiguration$1.beforeApplicationStart(IntegrationRuntimeAutoConfiguration.java:94) ~[integration-runtime-springboot-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
	at org.apache.camel.spring.boot.RoutesCollector.onApplicationEvent(RoutesCollector.java:152) ~[camel-spring-boot-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	... 24 common frames omitted
Caused by: java.lang.IllegalStateException: No step properties defined for rule filter step
	at io.syndesis.integration.runtime.handlers.RuleFilterStepHandler.getFilterExpression(RuleFilterStepHandler.java:51) ~[integration-runtime-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
	at io.syndesis.integration.runtime.handlers.AbstractFilterStepHandler.handle(AbstractFilterStepHandler.java:36) ~[integration-runtime-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
	at io.syndesis.integration.runtime.handlers.RuleFilterStepHandler.handle(RuleFilterStepHandler.java:30) ~[integration-runtime-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
	at io.syndesis.integration.runtime.IntegrationRouteBuilder.configureFlow(IntegrationRouteBuilder.java:174) ~[integration-runtime-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
	at io.syndesis.integration.runtime.IntegrationRouteBuilder.configure(IntegrationRouteBuilder.java:104) ~[integration-runtime-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
	at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:462) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:402) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:383) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.impl.DefaultCamelContext$1.call(DefaultCamelContext.java:1027) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.impl.DefaultCamelContext$1.call(DefaultCamelContext.java:1024) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3270) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at org.apache.camel.impl.DefaultCamelContext.addRoutes(DefaultCamelContext.java:1024) ~[camel-core-2.21.0.fuse-730042.jar!/:2.21.0.fuse-730042]
	at io.syndesis.integration.runtime.sb.IntegrationRuntimeAutoConfiguration$1.beforeApplicationStart(IntegrationRuntimeAutoConfiguration.java:92) ~[integration-runtime-springboot-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
	... 25 common frames omitted

```

Probably the culprit is https://github.com/syndesisio/syndesis/issues/562 , but I think it does not make sense now since we have the dedicated `split`

**Comment by mmelko** [comment]
I believe there is some auto split in amq connection. I have same behaviour from google-sheets (no split) to amq. I have only one activity but multiple messages in queue.

**Comment by KurtStam** [comment]
@christophd So I'm assuming this issue was raised running with the latest code and thus that we implemented support for collections it always return a collection from the SQL connector. Have we looked at updating the filter step yet? I'm guessing this is now broken since it's not an individual message coming in anymore.

**Comment by christophd** [comment]
@KurtStam yes you are right. Filter step is not able to provide the autocomplete fields for the body of type collection. We should fix that. 

My question would be what the filter on the integration should filter in this case. The filter per definition filters complete messages on the route based on an expression that is evaluated against the message body (= the whole collection). So the filter is not able to filter elements on the message body collection but only complete messages on the route. 

We might need something like `split => filter => aggregate` to get this working so that elements in that collection are filtered.

**Comment by gashcrumb** [comment]
Why wouldn't you be able to aggregate the resulting exchanges produced by a filter?  That seems an arbitrary restriction.

**Comment by lburgazzoli** [comment]
I think the filter still make sense i.e. you want to drop the exchnage if the collection has less tha x elements or go ahead only if the collection has a specific elelment.

**Comment by KurtStam** [comment]
> I think the filter still make sense i.e. you want to drop the exchange if the collection has less than x elements or go ahead only if the collection has a specific element.

Also true. So in that case we have to make sure it's obvious to the user that they are working on a collection.

**Comment by avano** [comment]
@christophd 

I have an integration `SQL (Select * from CONTACT) -> LOG (log everything)`, this is the output I get:

```
{"exchange":"i-LZe_LjWb_0Uso1SWyEYz","status":"begin"}
{"exchange":"i-LZe_LjWb_0Uso1SWyEYz","step":"null","id":"i-LZe_Ljrb_0Uso1SWyEZz","message":"Exchange[Id: i-LZe_LjWb_0Uso1SWyEYz, ExchangePattern: InOnly, Properties: {CamelCreatedTimestamp=Tue Feb 26 16:13:49 UTC 2019, CamelExternalRedelivered=false, CamelMessageHistory=[DefaultMessageHistory[routeId=-LZeX9X7BEs6Dn1MIDCn, node=setHeader1], DefaultMessageHistory[routeId=-LZeX9X7BEs6Dn1MIDCn, node=to1], DefaultMessageHistory[routeId=-LZeX9X7BEs6Dn1MIDCn, node=process1], DefaultMessageHistory[routeId=-LZeX9X7BEs6Dn1MIDCn, node=step:-LZeXFP6BEs6Dn1MIDCn], DefaultMessageHistory[routeId=-LZeX9X7BEs6Dn1MIDCn, node=setHeader2], DefaultMessageHistory[routeId=-LZeX9X7BEs6Dn1MIDCn, node=to2]], CamelTimerCounter=2, CamelTimerFiredTime=Tue Feb 26 16:13:49 UTC 2019, CamelTimerName=integration, CamelTimerPeriod=60000, CamelToEndpoint=log-0-1, Syndesis.ACTIVITY_ID=i-LZe_LjWb_0Uso1SWyEYz}, Headers: {breadcrumbId=i-LZe_LjWb_0Uso1SWyEYz, CamelSqlRowCount=2, firedTime=Tue Feb 26 16:13:49 UTC 2019, Syndesis.FLOW_ID=-LZeX9X7BEs6Dn1MIDCn, Syndesis.STEP_ID=-LZeXFP6BEs6Dn1MIDCn, Syndesis.STEP_TRACKER_ID=i-LZe_Ljrb_0Uso1SWyEZz}, BodyType: java.util.ArrayList, Body: {\"last_name\":\"Stieranka_first\",\"company\":\"Syndesis-qe\",\"create_date\":null,\"first_name\":\"Josef_first\",\"lead_source\":\"db\"},{\"last_name\":\"Stieranka_second\",\"company\":\"Syndesis-qe\",\"create_date\":null,\"first_name\":\"Josef_second\",\"lead_source\":\"db\"}, Out: null: ]"}
2019-02-26 16:13:49.450  INFO 1 --- [r://integration] syndesis-log                             : Exchange[Id: i-LZe_LjWb_0Uso1SWyEYz, ExchangePattern: InOnly, Properties: {CamelCreatedTimestamp=Tue Feb 26 16:13:49 UTC 2019, CamelExternalRedelivered=false, CamelMessageHistory=[DefaultMessageHistory[routeId=-LZeX9X7BEs6Dn1MIDCn, node=setHeader1], DefaultMessageHistory[routeId=-LZeX9X7BEs6Dn1MIDCn, node=to1], DefaultMessageHistory[routeId=-LZeX9X7BEs6Dn1MIDCn, node=process1], DefaultMessageHistory[routeId=-LZeX9X7BEs6Dn1MIDCn, node=step:-LZeXFP6BEs6Dn1MIDCn], DefaultMessageHistory[routeId=-LZeX9X7BEs6Dn1MIDCn, node=setHeader2], DefaultMessageHistory[routeId=-LZeX9X7BEs6Dn1MIDCn, node=to2]], CamelTimerCounter=2, CamelTimerFiredTime=Tue Feb 26 16:13:49 UTC 2019, CamelTimerName=integration, CamelTimerPeriod=60000, CamelToEndpoint=log-0-1, Syndesis.ACTIVITY_ID=i-LZe_LjWb_0Uso1SWyEYz}, Headers: {breadcrumbId=i-LZe_LjWb_0Uso1SWyEYz, CamelSqlRowCount=2, firedTime=Tue Feb 26 16:13:49 UTC 2019, Syndesis.FLOW_ID=-LZeX9X7BEs6Dn1MIDCn, Syndesis.STEP_ID=-LZeXFP6BEs6Dn1MIDCn, Syndesis.STEP_TRACKER_ID=i-LZe_Ljrb_0Uso1SWyEZz}, BodyType: java.util.ArrayList, Body: {"last_name":"Stieranka_first","company":"Syndesis-qe","create_date":null,"first_name":"Josef_first","lead_source":"db"},{"last_name":"Stieranka_second","company":"Syndesis-qe","create_date":null,"first_name":"Josef_second","lead_source":"db"}, Out: null: ]
{"exchange":"i-LZe_LjWb_0Uso1SWyEYz","step":"-LZeXFP6BEs6Dn1MIDCn","id":"i-LZe_Ljrb_0Uso1SWyEZz","duration":20237177}
{"exchange":"i-LZe_LjWb_0Uso1SWyEYz","status":"done","failed":false}
```

When I add a basic filter in between with `[].last_name contains second`, this is the output I get:

```
2019-02-26 16:15:21.303  INFO 1 --- [           main] io.syndesis.example.Application          : Started Application in 11.259 seconds (JVM running for 13.123)
{"exchange":"i-LZe_hAARTiq1agkXqeJz","status":"begin"}
{"exchange":"i-LZe_hAARTiq1agkXqeJz","step":"-LZe_Qkj3Egy6W-jEdMf","id":"i-LZe_hDdRTiq1agkXqeKz","duration":86443930}
{"exchange":"i-LZe_hAARTiq1agkXqeJz","status":"done","failed":false}
```

It seems my array completely disappeared.. did I use it correctly?

**Comment by christophd** [comment]
I think you are missing the item index like `[0].last_name contains second`

**Comment by avano** [comment]
thanks, that works. currently the autocomplete suggests me to use `[].last_name` so I didn't know what I should specify the index to check and I assumed that if there is **some** element in the whole collection, that matches the filter, then it would continue with the collection. is it possible to change it to check the whole collection if there is no index in the filter? would that make sense?

**Comment by tplevko** [comment]
The way the basic filter works now for collections seems to get us in QE a bit confused and I'm afraid this could be also the case for our customers. I don't know how to handle this issue, there is probably a room for someone from UX team to provide more insight, or we could document it? @heiko-braun

**Comment by KurtStam** [comment]
@christophd having to specify an index seems weird to me too.. Why do we need that?

**Comment by christophd** [comment]
The filter is provided with the collection (e.g. Json array) as body. So the user needs to give an index which element in that array to evaluate with the filter expression when using model properties in that expression (e.g. contact.first_name).

The filter is evaluated with the whole collection. This means that when the filter does not match the whole collection is denied and processing for the whole collection stops! Also when the filter matches the whole collection is moving on in the integration.

In case you want to filter some entries in that collection you need to split in front of the filter.

I agree that this is more complicated than before but that comes with the collection support as we now can handle both single elements and collections as body in an integration. Before that we exclusively have had single elements.

**Comment by KurtStam** [comment]
@syndesisio/uxd @gaughan Should we maybe hide the filter step on a collection? It seems rather hard to understand understand whats going on here (See @christophd 's explanation above). IOW is there real value in doing a filter on a collection.

**Comment by dongniwang** [comment]
If we just hide it without an explanation, would that be confusing as well? Can we provide some UI guidance when users apply the filter step? 

I'm also wondering if split and aggregate should be treated a little bit different than normal steps visually.

**Comment by dongniwang** [comment]
In that case, can we add this issue to the Collection Enhancement Epic (if there's one?) so we can look at this in 7.4. @christophd @heiko-braun

**Comment by christophd** [comment]
So the only valuable situation for the current filter implementation with collections would be to evaluate the collection size and filter based on that (e.g. filter collections with less than three elements or so).

This filter on the size of a collection is possible at the moment. 

As already mentioned current filter will not be able to reduce some elements in the collection and continue with a subset of the collection. And as long as we work with the filter EIP in Camel we will not be able to do that in the future.

If we want to remove elements from the collection based on the filter criteria we will have to implement a dedicated step doing so. This will be a normal step processing the exchange body but this will not be a filter EIP that we are using at the moment.

**Comment by KurtStam** [comment]
OK I will hide filter for a collection, and add a task to the 'Collection Enhancement Epic' for 7.4.
