### ISSUE TITLE
ClassCastException when inserting static values to DB with a timer

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4682]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I want to add every minute the same todo task to the DB. So I created integration with 1-minute timer and Invoke SQL step with constant:
```
INSERT INTO TODO (task, completed) VALUES('syndesis1', 0)
```
![image](https://user-images.githubusercontent.com/16251792/53413926-c0f6f600-39cd-11e9-8dd6-758880ac78f5.png)

Integration:
[SimpleSyn1-export.zip](https://github.com/syndesisio/syndesis/files/2905578/SimpleSyn1-export.zip)

Every minute integration contains Error in the activity tab / integration pod log:
```
java.lang.ClassCastException: org.apache.camel.impl.DefaultMessage cannot be cast to java.util.Map
	at io.syndesis.connector.sql.common.JSONBeanUtil.toJSONBeans(JSONBeanUtil.java:175)
	at io.syndesis.connector.sql.customizer.SqlConnectorCustomizer.doAfterProducer(SqlConnectorCustomizer.java:60)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at io.syndesis.integration.component.proxy.ComponentProxyProducer.process(ComponentProxyProducer.java:44)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197)
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

However, the values were successfully added to the DB.
![image](https://user-images.githubusercontent.com/16251792/53415262-14b70e80-39d1-11e9-96ab-1b88337c0b67.png)

Step to reproduced:

1. Import integration
2. Wait 3 minutes
3. In the Activity tab / integration log should be exception 
4. However the data should be visible in todo app / sampledb

**Comment by KurtStam** [comment]
@mkralik3 I can no longer reproduce this. I ran your export w.o any issues.

**Comment by mkralik3** [comment]
@KurtStam I am not able to reproduce this either so I will close the issue.
