### ISSUE TITLE
bug: Import endpoint in public API throws a NPE

### ISSUE THREAD

**Issue by dhirajsb** [syndesisio/syndesis#4707]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When importing integrations that were exported using the all query param, the `import` endpoint throws a NullPointerException when imported integrations do have the tag being imported to record the `importedAt` tag property. 

```
java.lang.NullPointerException: null
	at io.syndesis.server.endpoint.v1.handler.external.PublicApiHandler.updateCDEnvironment(PublicApiHandler.java:560) ~[server-endpoint-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
	at io.syndesis.server.endpoint.v1.handler.external.PublicApiHandler.lambda$updateCDEnvironments$15(PublicApiHandler.java:554) ~[server-endpoint-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
	at java.util.ArrayList.forEach(ArrayList.java:1255) ~[na:1.8.0_151]
	at io.syndesis.server.endpoint.v1.handler.external.PublicApiHandler.updateCDEnvironments(PublicApiHandler.java:554) ~[server-endpoint-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
	at io.syndesis.server.endpoint.v1.handler.external.PublicApiHandler.importResources(PublicApiHandler.java:369) ~[server-endpoint-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
```

**Comment by dhirajsb** [comment]
@mkralik3 I created this issue from your reported stack trace.

**Comment by dhirajsb** [comment]
@mkralik3 please close this issue after you have verified the fix.
