### ISSUE TITLE
Problem with privileges during installation

### ISSUE THREAD

**Issue by mkralik3** [syndesisio/syndesis#4717]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I have a clean instance of minishift (full-reset)
```
syndesis minishift --full-reset --install --project syndesis --openshift-version 3.11.0
```
Installation of Syndesis takes so long (20 minutes for me).
During the installation, the pods are been created, terminated and again created. it is repeated several times.
This error is repeated in the operator log:
```
{"level":"error","ts":1551456915.553912,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"syndesis-controller","request":"syndesis/app","error":"roles.rbac.authorization.k8s.io \"camel-k\" is forbidden: attempt to grant extra privileges: [{[*] [camel.apache.org] [*] [] []}] user=&{system:serviceaccount:syndesis:syndesis-operator 8f4e4614-3c3c-11e9-8e73-5254003010a8 [system:serviceaccounts system:serviceaccounts:syndesis system:authenticated] map[]} ownerrules=[{[get] [ user.openshift.io] [users] [~] []} {[list] [ project.openshift.io] [projectrequests] [] []} {[get list] [ authorization.openshift.io] [clusterroles] [] []} {[get list watch] [rbac.authorization.k8s.io] [clusterroles] [] []} {[get list] [storage.k8s.io] [storageclasses] [] []} {[list watch] [ project.openshift.io] [projects] [] []} {[create] [ authorization.openshift.io] [selfsubjectrulesreviews] [] []} {[create] [authorization.k8s.io] [selfsubjectaccessreviews] [] []} {[get] [] [] [] [/healthz /healthz/*]} {[get] [] [] [] [/version /version/* /api /api/* /apis /apis/* /oapi /oapi/* /openapi/v2 /swaggerapi /swaggerapi/* /swagger.json /swagger-2.0.0.pb-v1 /osapi /osapi/ /.well-known /.well-known/* /]} {[create] [ authorization.openshift.io] [selfsubjectrulesreviews] [] []} {[create] [authorization.k8s.io] [selfsubjectaccessreviews] [] []} {[create] [authorization.k8s.io] [selfsubjectaccessreviews selfsubjectrulesreviews] [] []} {[create] [ build.openshift.io] [builds/docker builds/optimizeddocker] [] []} {[create] [ build.openshift.io] [builds/jenkinspipeline] [] []} {[create] [ build.openshift.io] [builds/source] [] []} {[get] [] [] [] [/api /api/* /apis /apis/* /healthz /openapi /openapi/* /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/* /version /version/]} {[delete] [ oauth.openshift.io] [oauthaccesstokens oauthauthorizetokens] [] []} {[get] [] [] [] [/version /version/* /api /api/* /apis /apis/* /oapi /oapi/* /openapi/v2 /swaggerapi /swaggerapi/* /swagger.json /swagger-2.0.0.pb-v1 /osapi /osapi/ /.well-known /.well-known/* /]} {[impersonate] [authentication.k8s.io] [userextras/scopes.authorization.openshift.io] [] []} {[create get] [ build.openshift.io] [buildconfigs/webhooks] [] []} {[create delete deletecollection get list patch update watch] [] [pods pods/attach pods/exec pods/portforward pods/proxy] [] []} {[create delete deletecollection get list patch update watch] [] [configmaps endpoints persistentvolumeclaims replicationcontrollers replicationcontrollers/scale secrets serviceaccounts services services/proxy] [] []} {[get list watch] [] [bindings events limitranges namespaces/status pods/log pods/status replicationcontrollers/status resourcequotas resourcequotas/status] [] []} {[get list watch] [] [namespaces] [] []} {[impersonate] [] [serviceaccounts] [] []} {[create delete deletecollection get list patch update watch] [apps] [daemonsets deployments deployments/rollback deployments/scale replicasets replicasets/scale statefulsets statefulsets/scale] [] []} {[create delete deletecollection get list patch update watch] [autoscaling] [horizontalpodautoscalers] [] []} {[create delete deletecollection get list patch update watch] [batch] [cronjobs jobs] [] []} {[create delete deletecollection get list patch update watch] [extensions] [daemonsets deployments deployments/rollback deployments/scale ingresses networkpolicies replicasets replicasets/scale replicationcontrollers/scale] [] []} {[create delete deletecollection get list patch update watch] [policy] [poddisruptionbudgets] [] []} {[create delete deletecollection get list patch update watch] [networking.k8s.io] [networkpolicies] [] []} {[create delete deletecollection get list patch update watch] [ build.openshift.io] [buildconfigs buildconfigs/webhooks builds] [] []} {[get list watch] [ build.openshift.io] [builds/log] [] []} {[create] [ build.openshift.io] [buildconfigs/instantiate buildconfigs/instantiatebinary builds/clone] [] []} {[update] [ build.openshift.io] [builds/details] [] []} {[edit view] [build.openshift.io] [jenkins] [] []} {[create delete deletecollection get list patch update watch] [ apps.openshift.io] [deploymentconfigs deploymentconfigs/scale] [] []} {[create] [ apps.openshift.io] [deploymentconfigrollbacks deploymentconfigs/instantiate deploymentconfigs/rollback] [] []} {[get list watch] [ apps.openshift.io] [deploymentconfigs/log deploymentconfigs/status] [] []} {[create delete deletecollection get list patch update watch] [ image.openshift.io] [imagestreamimages imagestreammappings imagestreams imagestreams/secrets imagestreamtags] [] []} {[get list watch] [ image.openshift.io] [imagestreams/status] [] []} {[get update] [ image.openshift.io] [imagestreams/layers] [] []} {[create] [ image.openshift.io] [imagestreamimports] [] []} {[get] [ project.openshift.io] [projects] [] []} {[get list watch] [ quota.openshift.io] [appliedclusterresourcequotas] [] []} {[create delete deletecollection get list patch update watch] [ route.openshift.io] [routes] [] []} {[create] [ route.openshift.io] [routes/custom-host] [] []} {[get list watch] [ route.openshift.io] [routes/status] [] []} {[create delete deletecollection get list patch update watch] [ template.openshift.io] [processedtemplates templateconfigs templateinstances templates] [] []} {[create delete deletecollection get list patch update watch] [extensions networking.k8s.io] [networkpolicies] [] []} {[create delete deletecollection get list patch update watch] [ build.openshift.io] [buildlogs] [] []} {[get list watch] [] [resourcequotausages] [] []} {[get list create update delete deletecollection watch] [syndesis.io] [* */finalizers] [] []} {[get list create update delete deletecollection watch] [] [pods services endpoints persistentvolumeclaims configmaps secrets serviceaccounts] [] []} {[get list] [] [events] [] []} {[get list create update delete deletecollection watch] [rbac.authorization.k8s.io] [roles rolebindings] [] []} {[get list create update delete deletecollection watch] [template.openshift.io] [processedtemplates] [] []} {[get list create update delete deletecollection watch] [image.openshift.io] [imagestreams] [] []} {[get list create update delete deletecollection watch] [apps.openshift.io] [deploymentconfigs] [] []} {[get list create update delete deletecollection watch] [build.openshift.io] [buildconfigs] [] []} {[get list create update delete deletecollection watch] [authorization.openshift.io] [rolebindings] [] []} {[get list create update delete deletecollection watch] [route.openshift.io] [routes routes/custom-host] [] []} {[get list create update delete deletecollection watch] [camel.apache.org] [*] [] []} {[get list create update delete deletecollection watch] [monitoring.coreos.com] [alertmanagers prometheuses servicemonitors prometheusrules] [] []} {[get list create update delete deletecollection watch] [integreatly.org] [grafanadashboards] [] []} {[get list watch] [] [configmaps endpoints persistentvolumeclaims pods replicationcontrollers replicationcontrollers/scale serviceaccounts services] [] []} {[get list watch] [] [bindings events limitranges namespaces/status pods/log pods/status replicationcontrollers/status resourcequotas resourcequotas/status] [] []} {[get list watch] [] [namespaces] [] []} {[get list watch] [apps] [daemonsets deployments deployments/scale replicasets replicasets/scale statefulsets statefulsets/scale] [] []} {[get list watch] [autoscaling] [horizontalpodautoscalers] [] []} {[get list watch] [batch] [cronjobs jobs] [] []} {[get list watch] [extensions] [daemonsets deployments deployments/scale ingresses networkpolicies replicasets replicasets/scale replicationcontrollers/scale] [] []} {[get list watch] [policy] [poddisruptionbudgets] [] []} {[get list watch] [networking.k8s.io] [networkpolicies] [] []} {[get list watch] [ build.openshift.io] [buildconfigs buildconfigs/webhooks builds] [] []} {[get list watch] [ build.openshift.io] [builds/log] [] []} {[view] [build.openshift.io] [jenkins] [] []} {[get list watch] [ apps.openshift.io] [deploymentconfigs deploymentconfigs/scale] [] []} {[get list watch] [ apps.openshift.io] [deploymentconfigs/log deploymentconfigs/status] [] []} {[get list watch] [ image.openshift.io] [imagestreamimages imagestreammappings imagestreams imagestreamtags] [] []} {[get list watch] [ image.openshift.io] [imagestreams/status] [] []} {[get] [ project.openshift.io] [projects] [] []} {[get list watch] [ quota.openshift.io] [appliedclusterresourcequotas] [] []} {[get list watch] [ route.openshift.io] [routes] [] []} {[get list watch] [ route.openshift.io] [routes/status] [] []} {[get list watch] [ template.openshift.io] [processedtemplates templateconfigs templateinstances templates] [] []} {[get list watch] [ build.openshift.io] [buildlogs] [] []} {[get list watch] [] [resourcequotausages] [] []} {[get] [ image.openshift.io] [imagestreams/layers] [] []}] ruleResolutionErrors=[]","stacktrace":"github.com/syndesisio/syndesis/install/operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```
After a lot of time (20 minutes for me) the Syndesis is installed.
In the server log is this exception:
```
2019-03-01 16:36:32.731 ERROR [-,,,] 1 --- [ning]: pollPods] i.s.s.l.j.c.ActivityTrackingController   : Unexpected Error occurred.
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://openshift.default.svc/api/v1/namespaces/syndesis/pods?labelSelector=syndesis.io/component%3Dintegration . Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods is forbidden: User "system:serviceaccount:syndesis:syndesis-server" cannot list pods in the namespace "syndesis": no RBAC policy matched.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470) ~[kubernetes-client-3.1.4.fuse-710001.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:407) ~[kubernetes-client-3.1.4.fuse-710001.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379) ~[kubernetes-client-3.1.4.fuse-710001.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343) ~[kubernetes-client-3.1.4.fuse-710001.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327) ~[kubernetes-client-3.1.4.fuse-710001.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:605) ~[kubernetes-client-3.1.4.fuse-710001.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70) ~[kubernetes-client-3.1.4.fuse-710001.jar!/:na]
	at io.syndesis.server.logging.jsondb.controller.ActivityTrackingController.listPods(ActivityTrackingController.java:327) ~[server-logging-jsondb-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
	at io.syndesis.server.logging.jsondb.controller.ActivityTrackingController.pollPods(ActivityTrackingController.java:271) ~[server-logging-jsondb-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]

```
However, after some time (+- 16minutes), the Syndesis is reinstalled again. So all pods except syndesis-operator are deleted and created again.

**Comment by tplevko** [comment]
@heiko-braun QE testing is blocked by this

**Comment by heiko-braun** [comment]
@syndesisio/backend Can someone take a look at this?

**Comment by heiko-braun** [comment]
I my tests, the connection to the cluster dissappears half ways through the install:

```
syndesis-db-1-4jr64   0/1       ContainerCreating   0         3s
syndesis-ui-1-deploy   1/1       Terminating   0         10s
syndesis-ui-1-kzflk   0/1       Terminating   0         6s
syndesis-server-1-4vkk2   0/1       ContainerCreating   0         4s
syndesis-oauthproxy-1-nhc94   0/1       Pending   0         0s
syndesis-meta-1-5scsb   0/1       Pending   0         0s
syndesis-oauthproxy-1-nhc94   0/1       Pending   0         0s
syndesis-db-metrics-1-xft22   0/1       Pending   0         0s
syndesis-meta-1-5scsb   0/1       Pending   0         0s
syndesis-db-metrics-1-xft22   0/1       Pending   0         1s
syndesis-db-metrics-1-deploy   1/1       Running   0         14s
syndesis-ui-1-kzflk   0/1       Terminating   0         15s
syndesis-oauthproxy-1-nhc94   0/1       ContainerCreating   0         10s
syndesis-oauthproxy-1-deploy   1/1       Running   0         33s
syndesis-meta-1-5scsb   0/1       ContainerCreating   0         26s
Sleeping 10s ...
syndesis-meta-1-deploy   1/1       Running   0         39s
syndesis-ui-1-deploy   0/1       Terminating   0         42s
The connection to the server 192.168.64.12:8443 was refused - did you specify the right host or port?
Sleeping 10s ...
Unable to connect to the server: net/http: TLS handshake timeout
Sleeping 10s ...
The connection to the server 192.168.64.12:8443 was refused - did you specify the right host or port?
Sleeping 10s ...

(Here the cluster comes back)

error: You must be logged in to the server (Unauthorized)
Sleeping 10s ...
error: You must be logged in to the server (Unauthorized)
Sleeping 10s ...
error: You must be logged in to the server (Unauthorized)
Sleeping 10s ...
``

**Comment by heiko-braun** [comment]
Maybe an issue with OKD 3.11? 

```
oc login -u admin -p admin
error: dial tcp 192.168.64.12:8443: i/o timeout - verify you have provided the correct host and port and that the server is currently running.
``

**Comment by heiko-braun** [comment]
I have tried different ways to install on 3.11, using oc 3.11, without any success. At the end it always runs to the loop that terminates and retsrats the pods.

**Comment by heiko-braun** [comment]
Have the liveness checks been modified?

**Comment by heiko-braun** [comment]
Have the readiness checks been modified?  On syndesis-server I see:

```
Readiness probe failed: Get http://172.17.0.10:8181/health: dial tcp 172.17.0.10:8181: connect: connection refused
12 times in the last 3 minutes
```

**Comment by heiko-braun** [comment]
Ah, reading @mkralik3 report more carefully, the server fails with:

```
User "system:serviceaccount:syndesis:syndesis-server" cannot list pods in the namespace "syndesis"
```

**Comment by heiko-braun** [comment]
```
oc adm policy who-can get pods
Namespace: myproject
Verb:      get
Resource:  pods

Users:  admin
        system:admin
        system:kube-scheduler
        system:serviceaccount:default:pvinstaller
        system:serviceaccount:kube-system:clusterrole-aggregation-controller
        system:serviceaccount:kube-system:deployment-controller
        system:serviceaccount:kube-system:endpoint-controller
        system:serviceaccount:kube-system:generic-garbage-collector
        system:serviceaccount:kube-system:namespace-controller
        system:serviceaccount:kube-system:persistent-volume-binder
        system:serviceaccount:kube-system:pvc-protection-controller
        system:serviceaccount:kube-system:statefulset-controller
        system:serviceaccount:myproject:deployer
        system:serviceaccount:myproject:syndesis-operator
        system:serviceaccount:openshift-controller-manager:openshift-controller-manager
        system:serviceaccount:openshift-core-operators:openshift-service-cert-signer-operator
        system:serviceaccount:openshift-core-operators:openshift-web-console-operator
        system:serviceaccount:openshift-infra:build-controller
        system:serviceaccount:openshift-infra:default-rolebindings-controller
        system:serviceaccount:openshift-infra:deployer-controller
        system:serviceaccount:openshift-infra:pv-recycler-controller
        system:serviceaccount:openshift-infra:sdn-controller
        system:serviceaccount:openshift-infra:template-instance-controller
        system:serviceaccount:openshift-infra:template-instance-finalizer-controller

Groups: system:cluster-admins
        system:cluster-readers
        system:masters

```

**Comment by avano** [comment]
it seems that the operator expects the camel-k CRDs to be installed, even when you don't use it, @heiko-braun could you please try:

```
./syndesis install --setup --camel-k
./syndesis install --project syndesis -y --test-support
```

problem will be probably somewhere here :-) https://github.com/syndesisio/syndesis/commit/01115355978d2f2d1bfca739a78690d6624e4b2d

**Comment by heiko-braun** [comment]
@mkralik3 @tplevko To work around, and to allow progress for now, you would need to grant perms to the SA:

```
oc adm policy add-role-to-user edit system:serviceaccount:<NAMESPACE>:syndesis-server
```

**Comment by asmigala** [comment]
@heiko-braun even after doing that, I still get random pod redeployments after a while. Also, the todo app pod is not deployed at all.

**Comment by heiko-braun** [comment]
yes, I see the random redeploymenys as well.

**Comment by heiko-braun** [comment]
@asmigala It seems syndesis-prometheus is missing as well.

**Comment by zregvart** [comment]
I got it to work by doing:

```shell
$ syndesis minishift --full-reset --install --project syndesis --openshift-version 3.11.0
$ oc login -u admin
$ syndesis install --setup --camel-k
$ oc delete $(oc get pods -l syndesis.io/component=syndesis-operator -o name)
```

It's been running for few minutes now, how often do you see these redeployments?

**Comment by asmigala** [comment]
@zregvart after about 15 minutes

**Comment by heiko-braun** [comment]
`--camel-k` should be an optional flag.

**Comment by heiko-braun** [comment]
Looks like `server`, `meta` and `db-metrics` undergo restarts every once in a while

**Comment by zregvart** [comment]
> `--camel-k` should be an optional flag.

Seems that the operator deployment YAML is referencing camel-k resource:

https://github.com/syndesisio/syndesis/blob/d24358f17adcb433853784e42857cad13991eb34/install/operator/deploy/syndesis-operator.yml#L81-L85

**Comment by zregvart** [comment]
Also take note that without `--tag` the image streams point to `_:latest` so any merge to `master` will trigger a push to Docker hub and can trigger the redeployment.

https://github.com/syndesisio/syndesis/blob/3c498a6cb762ca12191a4e04e2f4fa7577f8e1d2/install/syndesis.yml#L171-L187

**Comment by heiko-braun** [comment]
> operator deployment YAML is referencing camel-k resource

that should be fine, even without camel-k present, no?

**Comment by nicolaferraro** [comment]
> > operator deployment YAML is referencing camel-k resource
> 
> that should be fine, even without camel-k present, no?

Yes, I think it's harmless...

**Comment by heiko-braun** [comment]
> the image streams point to _:latest

I think this has been like this for while already

**Comment by zregvart** [comment]
Not seeing any other reference to Camel-K from the operator.

**Comment by zregvart** [comment]
```shell
$ oc get pods
NAME                          READY     STATUS      RESTARTS   AGE
syndesis-db-1-vq6sd           1/1       Running     0          22m
syndesis-db-metrics-1-4zls6   1/1       Running     1          22m
syndesis-meta-1-nmbnt         1/1       Running     0          22m
syndesis-oauthproxy-1-pscdg   1/1       Running     0          22m
syndesis-operator-1-w2scc     1/1       Running     0          23m
syndesis-prometheus-1-gc9jl   1/1       Running     0          22m
syndesis-server-1-z2kvf       1/1       Running     0          22m
syndesis-ui-1-xct4h           1/1       Running     0          22m
todo-1-build                  0/1       Completed   0          22m
todo-1-pd9tp                  1/1       Running     0          21m
```

I've reset my minishift again (wanted `--dev` option as well). The pods are up 20+ minutes without restart.

**Comment by heiko-braun** [comment]
@zregvart Are you on `3.11` as well?

**Comment by asmigala** [comment]
@zregvart yup, seems `syndesis install --setup --camel-k` did it

```
NAME                          READY     STATUS      RESTARTS   AGE
syndesis-db-1-5g6x9           1/1       Running     0          29m
syndesis-db-metrics-1-899kb   1/1       Running     1          29m
syndesis-meta-1-frmnv         1/1       Running     0          29m
syndesis-oauthproxy-1-mnjvr   1/1       Running     0          29m
syndesis-operator-1-f2zrh     1/1       Running     0          29m
syndesis-prometheus-1-dzft5   1/1       Running     0          29m
syndesis-server-1-gst5n       1/1       Running     0          29m
syndesis-ui-1-7gfwc           1/1       Running     0          29m
todo-1-build                  0/1       Completed   0          29m
todo-1-pq5x6                  1/1       Running     0          27m
```

**Comment by zregvart** [comment]
yup

```shell
$ oc version
oc v3.11.0+8de5c34
kubernetes v1.10.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.75:8443
kubernetes v1.11.0+d4cacc0

$ minishift status
Minishift:  Running
Profile:    minishift
OpenShift:  Running (openshift v3.11.0+d0c29df-98)
DiskUsage:  29% of 19G (Mounted On: /mnt/sda1)
CacheUsage: 1.467 GB (used by oc binary, ISO or cached images)
```

**Comment by heiko-braun** [comment]
@nicolaferraro Can it be that the camel-k CRD defintion needs to present at least?

**Comment by heiko-braun** [comment]
@asmigala With `--setup --camel-k` the todo and prometheus pods are also there

**Comment by zregvart** [comment]
I guess this bit needs to be optional in the Syndesis template:

https://github.com/syndesisio/syndesis/blob/212f63f0d9c8bcaccbb142d496fd20504626a878/install/syndesis.yml#L1364-L1396

Perhaps create second template `syndesis-camel-k.yml` that contains those?

**Comment by nicolaferraro** [comment]
Don't know why it's there, but if it's just that role, I think it's safe to leave it there without adding a conditional rule on the operator. API group is just a string.. You can safely add a role like:

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: abcd
  labels:
rules:
- apiGroups:
  - anything.here
  resources:
  - "*"
  verbs: [ get, list, create, update, delete, deletecollection, watch]
```

... also without the CRDs. It will have effect only if needed (iirc).

I think it's not related to the server restart issue...

**Comment by heiko-braun** [comment]
@zregvart @nicolaferraro Not sure which wya to take here, but I think we could install the camel-k CDR by default (and leave make the camel-k operator optional).

**Comment by nicolaferraro** [comment]
> @zregvart @nicolaferraro Not sure which way to take here, but I think we could install the camel-k CRD by default (and leave the actual camel-k operator optional).

So, what you experience is that without installing the CRD, the entire role is ignored?

**Comment by heiko-braun** [comment]
no, it's seem without the CRD we run into the loops described above. Why? I don't know.

**Comment by heiko-braun** [comment]
well, please ignore my previous statement. It seem that even with the CRD pods restart occasionally:

```
NAME                          READY     STATUS      RESTARTS   AGE
syndesis-db-1-svl7j           1/1       Running     0          49m
syndesis-db-metrics-1-mlkbc   1/1       Running     1          49m
syndesis-meta-3-fmv4g         1/1       Running     0          9m
syndesis-oauthproxy-1-fxkvc   1/1       Running     0          49m
syndesis-operator-2-p77cp     1/1       Running     0          31m
syndesis-prometheus-1-flrxg   1/1       Running     0          49m
syndesis-server-3-7n7wd       1/1       Running     0          5m
syndesis-ui-2-xzp58           1/1       Running     0          35m
todo-1-build                  0/1       Completed   0          49m
todo-1-s6q5n                  1/1       Running     0          46m

```

**Comment by avano** [comment]
that one **may** be related to a new commit in the master branch 1 our ago

**Comment by heiko-braun** [comment]
@avano Yes, maybe you are right.

**Comment by nicolaferraro** [comment]
There's a post-install script that runs when installing Syndesis on Minishift. It removes the auto-update part of the imagestreams. I've just installed everything, but I don't see the imagestreams patched (even if logs say so), so I guess there's some timing/sync issues in the script.

If I run that function manually after the installation, I get the IS patched:

```
for is in "syndesis-server" "syndesis-ui" "syndesis-meta" "syndesis-s2i" "syndesis-operator"; do
    echo "Patching imagestream $is"
    replace_kind='{"op": "replace", "path": "/spec/tags/0/from/kind", "value": "ImageStreamTag"}'
    replace_name="{\"op\": \"replace\", \"path\": \"/spec/tags/0/from/name\", \"value\": \"$is:latest\"}"
    remove_import_policy='{"op": "remove", "path": "/spec/tags/0/importPolicy"}'
    oc patch is $is --type json -p="[$replace_kind, $replace_name, $remove_import_policy]"
done
```

**Comment by nicolaferraro** [comment]
I'm experiencing some issues with the deployments re-triggered by the operator.. trying to reproduce and fix

**Comment by nicolaferraro** [comment]
Issue seems to be that the operator gets permissions on specific verbs (https://github.com/syndesisio/syndesis/blob/3bcf4befc7b98d56fd6ff9010e53f00cfcfbc4ec/install/operator/deploy/syndesis-operator.yml#L85), and then tries to assign a "*" (https://github.com/syndesisio/syndesis/blob/3bcf4befc7b98d56fd6ff9010e53f00cfcfbc4ec/install/syndesis.yml#L1332) when creating the syndesis server.

The result is that the role is not applied entirely, the operator never marks the installation as done... And this causes restarts.

I think it's sufficient to change the "*" into the list of verbs, but I've some build issues when trying to rebuild the operator...

**Comment by heiko-braun** [comment]
That's something @rhuss changed recently: https://github.com/syndesisio/syndesis/commit/01115355978d2f2d1bfca739a78690d6624e4b2d

I wonder why? His commit lacks any specifics, but I guess it did relate to the work he did with @avano.

@avano Any ideas?

**Comment by avano** [comment]
it is related to the google chat thread from Ramesh Reddy from friday

**Comment by heiko-braun** [comment]
@rareddy Can you provide some background on the changes @rhuss made?

**Comment by nicolaferraro** [comment]
Looking at the conversation, there were issues at install time, so the change was needed to fix them. But it created issues in the 2nd step of the installation made by the operator. But the issues were not immediately visible..

**Comment by rareddy** [comment]
@heiko-braun I believe I was trying install as
```
enable admin-user
minishift start
oc login -u system:admin
tools/bin/syndesis install --setup --grant developer --cluster
tools/bin/syndesis build -m operator
oc login -u developer
tools/bin/syndesis install 
```

But the second login as `developer` did not have any authorizations to continue with install. so ended up with 
```
Error from server (Forbidden): error when creating "https://raw.githubusercontent.com/syndesisio/syndesis/master/install/operator/deploy/syndesis-operator.yml": roles.rbac.authorization.k8s.io "syndesis-operator" is forbidden: attempt to grant extra privileges: [{[] [syndesis.io] [] [] []} {[] [] [pods] [] []} {[] [] [services] [] []} {[*] [] [endpoints]
```

**Comment by KurtStam** [comment]
Fix did the trick for me, and the PR is merged

**Comment by heiko-braun** [comment]
I still see this error, half way through the install process:

```
The connection to the server 192.168.64.16:8443 was refused - did you specify the right host or port?
```

Has anybody encountered this on 3.11?

**Comment by nicolaferraro** [comment]
Just installed master from scratch.. not seeing it..

**Comment by heiko-braun** [comment]
@mkralik3 Can you verify if  the PR fixes the issue for you?

**Comment by mkralik3** [comment]
Yes, the installation on minishift looks ok, without pods restarting.

**Comment by heiko-braun** [comment]
thanks @mkralik3 and @nicolaferraro !
