### ISSUE TITLE
Unable to delete integration

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#4731]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

I created an integration named `webhook-to-todo` and when I tried to delete it I got an error:

`must match \"^[A-Za-z_][A-Za-z0-9_]*$\"`

```http
DELETE /api/v1/integrations/i-L_7TlnQe8rqSJX5wKkKz HTTP/1.1
Host: syndesis.192.168.42.75.nip.io
Connection: keep-alive
Accept: application/json, text/plain, */*
Origin: https://syndesis.192.168.42.75.nip.io
SYNDESIS-XSRF-TOKEN: awesome
User-Agent: Mozilla/5.0 (X11; Fedora; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Referer: https://syndesis.192.168.42.75.nip.io/integrations
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: _oauth_proxy=...

HTTP/1.1 400 Bad Request
Cache-Control: no-cache, no-store, max-age=0, must-revalidate, proxy-revalidate, s-maxage=0
Content-Length: 91
Content-Type: application/json
Date: Mon, 04 Mar 2019 13:03:19 GMT
Gap-Auth: developer@cluster.local
Gap-Upstream-Address: syndesis-server
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Syndesis-Xsrf-Token: awesome
X-Application-Context: application
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block

[{"error":"Pattern","message":"must match \"^[A-Za-z_][A-Za-z0-9_]*$\"","property":"name"}]
```

**Comment by zregvart** [comment]
Seems to be caused by the environment variable I set on the syndesis-server deployment configuration:

```

javax.validation.ConstraintViolationException: Constraint Validations: name must match "^[A-Za-z_][A-Za-z0-9_]*$" on bean: EnvVar(name=logging.level.org.apache.http.wire, value=DEBUG, valueFrom=null, additionalProperties={})
--
  | at io.fabric8.kubernetes.api.builder.ValidationUtils.validate(ValidationUtils.java:36) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
  | at io.fabric8.kubernetes.api.model.EnvVarBuilder.build(EnvVarBuilder.java:47) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
  | at io.fabric8.kubernetes.api.model.EnvVarBuilder.build(EnvVarBuilder.java:7) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
  | at io.fabric8.kubernetes.api.builder.BaseFluent.build(BaseFluent.java:20) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
  | at io.fabric8.kubernetes.api.model.ContainerFluentImpl.getEnv(ContainerFluentImpl.java:214) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
  | at io.fabric8.kubernetes.api.model.ContainerBuilder.build(ContainerBuilder.java:80) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
  | at io.fabric8.kubernetes.api.model.ContainerBuilder.build(ContainerBuilder.java:7) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
  | at io.fabric8.kubernetes.api.builder.BaseFluent.build(BaseFluent.java:20) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
  | at io.fabric8.kubernetes.api.model.PodSpecFluentImpl.getContainers(PodSpecFluentImpl.java:171) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
  | at io.fabric8.kubernetes.api.model.PodSpecBuilder.build(PodSpecBuilder.java:86) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
  | at io.fabric8.kubernetes.api.model.PodTemplateSpecFluentImpl.getSpec(PodTemplateSpecFluentImpl.java:69) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
  | at io.fabric8.kubernetes.api.model.PodTemplateSpecBuilder.build(PodTemplateSpecBuilder.java:44) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
  | at io.fabric8.openshift.api.model.DeploymentConfigSpecFluentImpl.getTemplate(DeploymentConfigSpecFluentImpl.java:171) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
  | at io.fabric8.openshift.api.model.DeploymentConfigSpecBuilder.build(DeploymentConfigSpecBuilder.java:58) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
  | at io.fabric8.openshift.api.model.DeploymentConfigFluentImpl.getSpec(DeploymentConfigFluentImpl.java:105) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
  | at io.fabric8.openshift.api.model.DeploymentConfigFluentImpl.editSpec(DeploymentConfigFluentImpl.java:130) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
  | at io.syndesis.server.openshift.OpenShiftServiceImpl.lambda$scale$1(OpenShiftServiceImpl.java:134) ~[server-openshift-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
  | at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_151]
  | at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_151]
  | at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1357) ~[na:1.8.0_151]
  | at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_151]
  | at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[na:1.8.0_151]
  | at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:1.8.0_151]
  | at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_151]
  | at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:1.8.0_151]
  | at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_151]
  | at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469) ~[na:1.8.0_151]
  | at io.syndesis.server.openshift.OpenShiftServiceImpl.scale(OpenShiftServiceImpl.java:135) ~[server-openshift-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
  | at io.syndesis.server.controller.integration.online.UnpublishHandler.execute(UnpublishHandler.java:65) ~[server-controller-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
  | at io.syndesis.server.controller.StateChangeHandler.execute(StateChangeHandler.java:33) ~[server-controller-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
  | at io.syndesis.server.controller.integration.IntegrationController.lambda$callStateChangeHandler$11(IntegrationController.java:214) ~[server-controller-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
  | at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
```

I've added `logging.level.org.apache.http.wire=DEBUG` environment variable.

**Comment by zregvart** [comment]
Yeah, removed the environment variable I manually added and the problem doesn't manifest itself. I think we can close this as operator error.
