### ISSUE TITLE
Cron timer can't resolve endpoint quartz2

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#4734]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When creating a simple integration using the cron integration action of timer, leaving the default configuration results in this error:
```
org.apache.camel.RuntimeCamelException: org.apache.camel.FailedToCreateRouteException: Failed to create route -L_7vQwYcso8HIomNGxM: Route(-L_7vQwYcso8HIomNGxM)[[From[quartz2-0-0]] -> [SetHeade... because of Failed to resolve endpoint: quartz2-0-0 due to: Failed to resolve endpoint: quartz2://syndesis-quartz?cron=0+0%2F1+*+*+*+%3F due to: No component found with scheme: quartz2
	at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1830) ~[camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.spring.SpringCamelContext.start(SpringCamelContext.java:136) ~[camel-spring-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.spring.SpringCamelContext.onApplicationEvent(SpringCamelContext.java:174) ~[camel-spring-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.16.RELEASE.jar!/:1.5.16.RELEASE]
	at io.syndesis.example.Application.main(Application.java:13) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [project-0.1-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:595) [project-0.1-SNAPSHOT.jar:na]
```

**Comment by zregvart** [comment]
I think we're missing the `camel-quartz2` jar, this is the content of the fat jar:

```shell
$ jar tvf project-0.1-SNAPSHOT.jar |grep camel-
 19667 Wed Feb 13 18:18:14 UTC 2019 BOOT-INF/lib/camel-atlasmap-1.39.3.jar
4804358 Tue Feb 19 09:39:12 UTC 2019 BOOT-INF/lib/camel-core-2.21.0.fuse-730049.jar
 13246 Tue Feb 19 10:43:12 UTC 2019 BOOT-INF/lib/camel-spring-boot-starter-2.21.0.fuse-730049.jar
160745 Tue Feb 19 09:59:08 UTC 2019 BOOT-INF/lib/camel-spring-boot-2.21.0.fuse-730049.jar
224333 Tue Feb 19 10:43:08 UTC 2019 BOOT-INF/lib/camel-core-starter-2.21.0.fuse-730049.jar
4571471 Tue Feb 19 10:41:06 UTC 2019 BOOT-INF/lib/camel-catalog-2.21.0.fuse-730049.jar
 32796 Tue Feb 19 10:56:34 UTC 2019 BOOT-INF/lib/camel-connector-2.21.0.fuse-730049.jar
353559 Tue Feb 19 09:40:40 UTC 2019 BOOT-INF/lib/camel-spring-2.21.0.fuse-730049.jar
```

The solution could be as simple as adding 

```json
{
  "id": "org.apache.camel:camel-quartz2:@camel.version@",
  "type": "MAVEN"
}
```

here:

https://github.com/syndesisio/syndesis/blob/05aba249dda837520f063d70a0805595180447df/app/connector/timer/src/main/resources/META-INF/syndesis/connector/timer.json#L85-L90

Not exactly sure when we broke this...

**Comment by zregvart** [comment]
@mmuzikar good find, thanks!

**Comment by oscerd** [comment]
It's been a while I think, the behavior is the same on staging too

**Comment by mmuzikar** [comment]
That was quick :smile: great job @zregvart!
