### ISSUE TITLE
Verify Syndesis with Camel 3

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4769]
As a user I want to be able to use Camel 3 with Syndesis to leverage the latest and greatest

**Comment by rkorytkowski** [comment]
> if we could get rid of spring-boot in syndesis meta, then the upgrade to camel 3 is much less problematic
> I think there is already a partial support for discovering meta stuffs using a service loader alike thing but only a few components implement that
> and by getting rid of spring-boot in syndesis meta
> I mean only for the discovery
> syndesis-meta should continue to be packaged as spring-boot
> i.e. https://github.com/syndesisio/syndesis/blob/master/app/meta/src/main/java/io/syndesis/connector/meta/v1/ConnectorEndpoint.java#L53-L73
> this has already a fallback to camel's service loader so it should not be that hard
> 
> on the connector side then we should get rid of things like 
> https://github.com/syndesisio/syndesis/blob/master/app/connector/activemq/src/main/java/io/syndesis/connector/activemq/ActiveMQVerifierAutoConfiguration.java

by @lburgazzoli

**Comment by rkorytkowski** [comment]
@lburgazzoli c38c4aa shows changes I needed to do so far to make the project compile. It currently fails on building the s2i with:

```
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:exec (rest-builder-image-generator) @ s2i ---
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:413)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:392)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:383)
	at org.springframework.boot.SpringApplication.initialize(SpringApplication.java:249)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:225)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at io.syndesis.server.builder.image.generator.Application.main(Application.java:86)
	... 8 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/core/KotlinDetector
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:171)
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:409)
	... 15 more
Caused by: java.lang.ClassNotFoundException: org.springframework.core.KotlinDetector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:39)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:122)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:55)
```
I haven't got rid off the spring stuff yet, which you mentioned... Do you think the above may be fixed after I do that or is it something else? I haven't yet investigated much. Just wanted to share progress so far and hear in case you have any thoughts.

**Comment by rkorytkowski** [comment]
Okay, seems like KotlinDetector is from Spring 5.x+ so I need to force Spring 4.x

**Comment by rkorytkowski** [comment]
364df4b builds fine with `syndesis build -f -c -i` and some quick tests confirm that integrations can be created and use Camel 3 and Spring Boot 2.

`syndesis build -c -i ` has still some failing tests, which I'll continue to work on next week.

Also remaining TODO is to get rid of Spring Configuration in connectors and use Camel discovery instead.

@lburgazzoli you might want to have a look.

**Comment by rkorytkowski** [comment]
Fixed failing tests in https://github.com/rkorytkowski/syndesis/commit/bd5f509725491ed0c550cf66d08e8cfb5e0d931d. 

It depends on updating Atlasmap to Camel 3 as well. See https://github.com/rkorytkowski/atlasmap/commit/ac654d335be242540b7213c6ae02af3a5fbbde07

Remaining TODOs:
1. Examine conflicting dependencies to see, if some should be excluded instead of ignoring
2. Look into getting rid of Spring @Configuration in connectors as suggested by @lburgazzoli. After a bit of investigation I'm not exactly sure how to go about that. Aside from Verifier we also have MetadataRetrieval and some other spring managed beans in connectors. In addition beans are loaded conditionally based on properties so we'd loose that functionality, if we rely solely on Camel context. Using @Configuration doesn't seem to be causing issues at runtime nor in tests, but maybe there are some edge cases we don't have covered. Thoughts?

**Comment by rkorytkowski** [comment]
The 2nd point will be addressed in #5157. I've discussed it with @lburgazzoli and it's essential for quarkus and can be worked on separately from Camel 3 upgrade.

**Comment by Delawen** [comment]
Branch on main repo: https://github.com/syndesisio/syndesis/tree/camel-3.0.x
Branch I am working on: https://github.com/Delawen/syndesis/tree/camel-3.0.x

I am going to merge the above mentioned commits and changes there to have a unique branch with camel 3.

**Comment by Delawen** [comment]
Closing as this is merged and now we create specific issues for specific problems in the now master branch.
