### ISSUE TITLE
Cannot initialize component proxy if the component is not in catalog

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#4807]
Trying to use a `knative` connector but the runtime component proxy refuses it because it's not on the internal catalog.

```
Exception in thread "main" org.apache.camel.RuntimeCamelException: java.lang.IllegalArgumentException: Failed to find component definition for scheme 'knative'. Missing component definition in classpath 'org/apache/camel/catalog/components/knative.json'
        at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1830)
        at org.apache.camel.k.adapter.Exceptions.wrapRuntimeCamelException(Exceptions.java:27)
        at org.apache.camel.k.listener.RoutesConfigurer.load(RoutesConfigurer.java:75)
        at org.apache.camel.k.listener.RoutesConfigurer.accept(RoutesConfigurer.java:45)
        at org.apache.camel.k.listener.AbstractPhaseListener.accept(AbstractPhaseListener.java:31)
        at org.apache.camel.k.jvm.ApplicationRuntime$MainListenerAdapter.lambda$configure$2(ApplicationRuntime.java:156)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.apache.camel.k.jvm.ApplicationRuntime$MainListenerAdapter.configure(ApplicationRuntime.java:156)
        at org.apache.camel.main.MainSupport.postProcessCamelContext(MainSupport.java:618)
        at org.apache.camel.main.MainSupport.postProcessContext(MainSupport.java:550)
        at org.apache.camel.k.jvm.ApplicationRuntime$Main.doStart(ApplicationRuntime.java:126)
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
        at org.apache.camel.main.MainSupport.run(MainSupport.java:170)
        at org.apache.camel.k.jvm.ApplicationRuntime.run(ApplicationRuntime.java:72)
        at org.apache.camel.k.jvm.Application.main(Application.java:52)
Caused by: java.lang.IllegalArgumentException: Failed to find component definition for scheme 'knative'. Missing component definition in classpath 'org/apache/camel/catalog/components/knative.json'
        at io.syndesis.integration.component.proxy.ComponentDefinition.lambda$forScheme$0(ComponentDefinition.java:123)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at io.syndesis.integration.component.proxy.ComponentDefinition.forScheme(ComponentDefinition.java:123)
        at io.syndesis.integration.component.proxy.ComponentProxyComponent.<init>(ComponentProxyComponent.java:75)
        at io.syndesis.connector.knative.KnativeComponentProxyFactory$1.<init>(KnativeComponentProxyFactory.java:18)
        at io.syndesis.connector.knative.KnativeComponentProxyFactory.newInstance(KnativeComponentProxyFactory.java:18)
        at io.syndesis.integration.runtime.handlers.ConnectorStepHandler.resolveComponent(ConnectorStepHandler.java:158)
        at io.syndesis.integration.runtime.handlers.ConnectorStepHandler.handle(ConnectorStepHandler.java:80)
        at io.syndesis.integration.runtime.IntegrationRouteBuilder.configureFlow(IntegrationRouteBuilder.java:174)
        at io.syndesis.integration.runtime.IntegrationRouteBuilder.configure(IntegrationRouteBuilder.java:104)
        at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:462)
        at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:402)
        at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:383)
        at org.apache.camel.impl.DefaultCamelContext$1.call(DefaultCamelContext.java:1027)
        at org.apache.camel.impl.DefaultCamelContext$1.call(DefaultCamelContext.java:1024)
        at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3270)
        at org.apache.camel.impl.DefaultCamelContext.addRoutes(DefaultCamelContext.java:1024)
        at org.apache.camel.k.listener.RoutesConfigurer.load(RoutesConfigurer.java:73)
        ... 12 more
```

**Comment by nicolaferraro** [comment]
See https://github.com/apache/camel-k-runtime/issues/31
