### ISSUE TITLE
ExtensionsITCase::testListExtensionDetails is flaky

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#4827]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

We can either extend the timeout or we can try to address the underlying issue of asynchronous update to the `usage` property.

**Comment by zregvart** [comment]
Seems that increasing the timeout to `30` did not help, it's still flaky:

```
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in io.syndesis.server.runtime.ExtensionsITCase expected:<[1]> but was:<[0]> within 30 seconds.
	at io.syndesis.server.runtime.ExtensionsITCase.testListExtensionDetails(ExtensionsITCase.java:349)
Caused by: org.junit.ComparisonFailure: expected:<[1]> but was:<[0]>
	at io.syndesis.server.runtime.ExtensionsITCase.lambda$testListExtensionDetails$2(ExtensionsITCase.java:355)
```

I wonder if we're actually seeing that the test detects failure in the production code.

**Comment by zregvart** [comment]
Maybe fixed via #5246 5246

**Comment by zregvart** [comment]
Still [flaky](https://circleci.com/gh/syndesisio/syndesis/72021).

**Comment by zregvart** [comment]
I'll just disable the part of the test that's flaky. I'm marking this as `p0` as it slows us down and can fail the release builds
