### ISSUE TITLE
[camel k] cannot find atlas component

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#4834]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Get this when running a integration with mapping.

```
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: atlas://mapping-flow-0-step-1.json?encoding=UTF-8&sourceMapName=Syndesis.CAPTURED_OUT_MESSAGES_MAP due to: No component found with scheme: atlas
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  at org.apache.camel.impl.DefaultCamelContext.getEndpoint(DefaultCamelContext.java:759)
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  at org.apache.camel.util.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:80)
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  at org.apache.camel.model.RouteDefinition.resolveEndpoint(RouteDefinition.java:227)
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  at org.apache.camel.impl.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:116)
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  at org.apache.camel.impl.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:122)
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  at org.apache.camel.model.SendDefinition.resolveEndpoint(SendDefinition.java:62)
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  at org.apache.camel.model.SendDefinition.createProcessor(SendDefinition.java:56)
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  at org.apache.camel.model.ProcessorDefinition.createProcessor(ProcessorDefinition.java:518)
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  at org.apache.camel.model.ProcessorDefinition.createOutputsProcessorImpl(ProcessorDefinition.java:481)
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  at org.apache.camel.model.ProcessorDefinition.createOutputsProcessor(ProcessorDefinition.java:448)
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  at org.apache.camel.model.ProcessorDefinition.createOutputsProcessor(ProcessorDefinition.java:186)
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  at org.apache.camel.model.ProcessorDefinition.createChildProcessor(ProcessorDefinition.java:205)
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  at org.apache.camel.model.PipelineDefinition.createProcessor(PipelineDefinition.java:51)
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  at org.apache.camel.model.ProcessorDefinition.makeProcessorImpl(ProcessorDefinition.java:569)
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  at org.apache.camel.model.ProcessorDefinition.makeProcessor(ProcessorDefinition.java:530)
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  at org.apache.camel.model.ProcessorDefinition.addRoutes(ProcessorDefinition.java:240)
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  at org.apache.camel.model.RouteDefinition.addRoutes(RouteDefinition.java:1349)
i-l-idqznfgqs09i-ddlgz-6cccbb6c46-swqqb i-l-idqznfgqs09i-ddlgz  ... 15 more
```

**Comment by nicolaferraro** [comment]
When adding it manually:

```
i-l-idqznfgqs09i-ddlgz-7db5746b9f-mggjk i-l-idqznfgqs09i-ddlgz {"exchange":"i-L_irH_3VzFCJVtjIxEcz","step":"-L_idR0rPnOnSk66dyI7","id":"i-L_irH_4VzFCJVtjIxEez","duration":3447703,"failure":"java.io.FileNotFoundException: Cannot find resource: mapping-flow-0-step-1.json in classpath for URI: mapping-flow-0-step-1.json\n\tat org.apache.camel.util.ResourceHelper.resolveMandatoryResourceAsInputStream(ResourceHelper.java:196)\n\tat org.apache.camel.component.ResourceEndpoint.loadResource(ResourceEndpoint.java:106)\n\tat org.apache.camel.component.ResourceEndpoint.getResourceAsInputStreamWithoutCache(ResourceEndpoint.java:95)\n\tat org.apache.camel.component.ResourceEndpoint.getResourceAsInputStream(ResourceEndpoint.java:82)\n\tat org.apache.camel.component.atlasmap.AtlasEndpoint.getOrCreateAtlasContext(AtlasEndpoint.java:308)\n\tat org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:241)\n\tat org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71)\n\tat org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)\n\tat org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)\n\tat io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:80)\n\tat org.apache.camel.component.telegram.TelegramConsumer.processUpdates(TelegramConsumer.java:87)\n\tat org.apache.camel.component.telegram.TelegramConsumer.poll(TelegramConsumer.java:73)\n\tat org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174)\n\tat org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n"}
```

We should find a solution that works also with knative serving 0.3 (where you cannot mount configmaps).

**Comment by lburgazzoli** [comment]
> We should find a solution that works also with knative serving 0.3 (where you cannot mount configmaps).

can you open a new issue for this one ?

**Comment by mastepan** [comment]
QE ignore
