### ISSUE TITLE
Lib alignment errors in Camel K mode

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/syndesis#4926]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Standard mode imports the spring-boot bom, that among other things aligns versions of some libraries such as Jackson.

Camel versions should be aligned, but if we mix them with syndesis runtime jar, we get `jackson-annotation` 2.9 and other related libraries in version `2.8` (camel version).

The result is:

```

Exception in thread "main" java.lang.NoSuchFieldError: _valueInstantiator
--
  | at com.fasterxml.jackson.datatype.jdk8.OptionalDeserializer.withResolved(OptionalDeserializer.java:38)
  | at com.fasterxml.jackson.datatype.jdk8.OptionalDeserializer.withResolved(OptionalDeserializer.java:10)
  | at com.fasterxml.jackson.databind.deser.std.ReferenceTypeDeserializer.createContextual(ReferenceTypeDeserializer.java:74)
  | at com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(DeserializationContext.java:650)
  | at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:490)
  | at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
  | at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
  | at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
  | at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:443)
  | at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:206)
  | at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:26)
  | at com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(DeserializationContext.java:650)
  | at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:490)
  | at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
  | at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
  | at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
  | at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:476)
  | at com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:1902)
  | at com.fasterxml.jackson.databind.ObjectReader.forType(ObjectReader.java:676)
  | at com.fasterxml.jackson.databind.ObjectReader.forType(ObjectReader.java:696)
  | at io.syndesis.integration.runtime.IntegrationRouteBuilder.loadIntegration(IntegrationRouteBuilder.java:91)
  | at io.syndesis.integration.runtime.IntegrationRouteBuilder.configure(IntegrationRouteBuilder.java:102)
  | at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:462)
  | at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:402)
  | at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:383)
  | at org.apache.camel.impl.DefaultCamelContext$1.call(DefaultCamelContext.java:1027)
  | at org.apache.camel.impl.DefaultCamelContext$1.call(DefaultCamelContext.java:1024)
  | at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3270)
  | at org.apache.camel.impl.DefaultCamelContext.addRoutes(DefaultCamelContext.java:1024)
  | at org.apache.camel.k.listener.RoutesConfigurer.load(RoutesConfigurer.java:73)
  | at org.apache.camel.k.listener.RoutesConfigurer.accept(RoutesConfigurer.java:45)
  | at org.apache.camel.k.listener.AbstractPhaseListener.accept(AbstractPhaseListener.java:31)
  | at org.apache.camel.k.jvm.ApplicationRuntime$MainListenerAdapter.lambda$configure$2(ApplicationRuntime.java:156)
  | at java.lang.Iterable.forEach(Iterable.java:75)
  | at org.apache.camel.k.jvm.ApplicationRuntime$MainListenerAdapter.configure(ApplicationRuntime.java:156)
  | at org.apache.camel.main.MainSupport.postProcessCamelContext(MainSupport.java:618)
  | at org.apache.camel.main.MainSupport.postProcessContext(MainSupport.java:550)
  | at org.apache.camel.k.jvm.ApplicationRuntime$Main.doStart(ApplicationRuntime.java:126)
  | at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
  | at org.apache.camel.main.MainSupport.run(MainSupport.java:170)
  | at org.apache.camel.k.jvm.ApplicationRuntime.run(ApplicationRuntime.java:72)
  | at org.apache.camel.k.jvm.Application.main(Application.java:52)


```

To reproduce: create an integration from telegram to telegram with datamapper in the middle.
cc: @lburgazzoli

**Comment by lburgazzoli** [comment]
I think we could try to exclude jackson from any of the deps that runtime-camelk brings in and use the one required by atlasmap.

**Comment by valdar** [comment]
this might be related to #2436, let's see if there is a way to workaround it.
