### ISSUE TITLE
[GoogleSheets] data mapper not able to handle split results

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#4994]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When split option on the GoogleSheets connector is enabled the data mapper is not able to process the messages.

This is because the GoogleSheets connection defines a data shape of type json object but provides a Java list of json beans (with one single bean in it).

That used to work but is now causing errors while mapping with data mapper. The connector should provide a json object string instead of a single element list in that case when split is option is enabled. 

Sample exception stack trace:
```
io.atlasmap.api.AtlasException: Errors: [Unexpected exception is thrown while reading source field: null: docId='-LaQ3UP2ZcoAB-YQIrI3', path='/A'], [Unexpected exception is thrown while reading source field: null: docId='-LaQ3UP2ZcoAB-YQIrI3', path='/A'], [Unexpected exception is thrown while reading source field: null: docId='-LaQ3UP2ZcoAB-YQIrI3', path='/B'], [Unexpected exception is thrown while reading source field: null: docId='-LaQ3UP2ZcoAB-YQIrI3', path='/A'], [Unexpected exception is thrown while reading source field: null: docId='-LaQ3UP2ZcoAB-YQIrI3', path='/B'], [Unexpected exception is thrown while reading source field: null: docId='-LaQ3UP2ZcoAB-YQIrI3', path='/C'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:266)
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.component.google.sheets.stream.GoogleSheetsStreamConsumer.processBatch(GoogleSheetsStreamConsumer.java:129)
	at org.apache.camel.component.google.sheets.stream.GoogleSheetsStreamConsumer.poll(GoogleSheetsStreamConsumer.java:111)
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174)
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mmelko** [comment]
should be this also in 1.6.x ? I'm trying in CR1 .. and After split results=yes in connector I can't see Datamapper option at all.

**Comment by heiko-braun** [comment]
CR1 might be to old. @christophd Can you check if this made it to 1.6.x?

**Comment by heiko-braun** [comment]
It's there: https://github.com/syndesisio/syndesis/pull/5005

**Comment by mmelko** [comment]
verified with 1.6.8
