### ISSUE TITLE
OData enum output is wrong

### ISSUE THREAD

**Issue by jsafarik** [syndesisio/syndesis#5060]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

Using OData connector to read and then create/update, it needs Data Mapper in between. I tried to map enum today and it fails with error: `[Failed to convert field value 'Male' into type 'NUMBER': docId='-LatezusaSAYPd8-rHUM', path='/<0>/Gender'], [Unexpected exception is thrown while populating target field: null: docId='-Latf3VcaSAYPd8-rHUM', path='/Gender'], `
it seems that the odata is using number to represent the enum, but it is passing the string representation instead of the actual number, is that right?

## Tasks involved / Steps to Reproduce

1. Create new integration: OData read -> Data Mapper -> OData update (try to use https://services.odata.org/TripPinRESTierService/ as sample service)
2. map enum value (Data Mapper shows the type of the value as NUMBER)
3. run the integration

**Comment by jsafarik** [comment]
When verifying this, it throws error again.
stacktrace from the pod log is:
```

Stacktrace
--
  | ---------------------------------------------------------------------------------------------------------------------------------------
  | org.apache.olingo.client.api.communication.ODataClientErrorException: An error has occurred. [HTTP/1.1 500 Internal Server Error]
  | at org.apache.camel.component.olingo4.api.impl.AbstractFutureCallback.checkStatus(AbstractFutureCallback.java:69) [camel-olingo4-api-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
  | at org.apache.camel.component.olingo4.api.impl.AbstractFutureCallback.completed(AbstractFutureCallback.java:86) [camel-olingo4-api-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
  | at org.apache.camel.component.olingo4.api.impl.AbstractFutureCallback.completed(AbstractFutureCallback.java:46) [camel-olingo4-api-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
  | at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123) [httpcore-4.4.10.jar!/:4.4.10]
  | at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181) [httpasyncclient-4.1.4.jar!/:4.1.4]
  | at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:439) [httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:329) [httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) [httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) [httpasyncclient-4.1.4.jar!/:4.1.4]
  | at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) [httpasyncclient-4.1.4.jar!/:4.1.4]
  | at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121) [httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) [httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) [httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) [httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) [httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) [httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588) [httpcore-nio-4.4.9.jar!/:4.4.9]
  | at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
  | 2019-07-01 14:22:32.055  WARN 1 --- [ngo4-0-0://read] o.a.c.component.olingo4.Olingo4Consumer  : Error processing exchange. Exchange[i-LihubDSMCdL7QunxO_Yz]. Caused by: [org.apache.olingo.client.api.communication.ODataClientErrorException - An error has occurred. [HTTP/1.1 500 Internal Server Error]]
  | org.apache.olingo.client.api.communication.ODataClientErrorException: An error has occurred. [HTTP/1.1 500 Internal Server Error]
  | at org.apache.camel.component.olingo4.api.impl.AbstractFutureCallback.checkStatus(AbstractFutureCallback.java:69) ~[camel-olingo4-api-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
  | at org.apache.camel.component.olingo4.api.impl.AbstractFutureCallback.completed(AbstractFutureCallback.java:86) ~[camel-olingo4-api-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
  | at org.apache.camel.component.olingo4.api.impl.AbstractFutureCallback.completed(AbstractFutureCallback.java:46) ~[camel-olingo4-api-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
  | at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123) ~[httpcore-4.4.10.jar!/:4.4.10]
  | at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
  | at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:439) ~[httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:329) ~[httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
  | at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) ~[httpasyncclient-4.1.4.jar!/:4.1.4]
  | at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121) ~[httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio-4.4.9.jar!/:4.4.9]
  | at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588) ~[httpcore-nio-4.4.9.jar!/:4.4.9]
  | at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]


```

this is the integration I've created:
![image](https://user-images.githubusercontent.com/46523434/60444073-bfa83500-9c1c-11e9-8591-63c9811cdc81.png)

and this is the mapping:
![image](https://user-images.githubusercontent.com/46523434/60444128-dd759a00-9c1c-11e9-914e-f70616e85bac.png)
(taking the gender from someone else, and forcing to update an entity with created constant)

**Comment by heiko-braun** [comment]
@phantomjinx FYI

**Comment by heiko-braun** [comment]
@jsafarik What priority would you assign to this?

**Comment by jsafarik** [comment]
@heiko-braun well, as far as a user doesn't want to create or update an enum type on odata service, it is ok, but it is something that should be working, so I would say it's p1

**Comment by heiko-braun** [comment]
@jsafarik thanks

**Comment by phantomjinx** [comment]
@jsafarik 
This seems to be an issue with the reference odata server than the client request made to it. The following does corretly appear in the route:
- uri : `https://services.odata.org/TripPinRESTierService/(S(4gus0w41xmxedlzbywj2srqo))/People('elainestewart')`
- payload: `{"Gender":"Male"}`

Executing this is a generic RESTClient, also generates the same generic `An error has occurred.`

Now if I do the same with the test [server](https://github.com/syndesisio/syndesis/tree/master/app/connector/odata/src/test/java/io/syndesis/connector/odata/server), things work correctly:
- uri: `http://${IP}:${PORT}/odata4/Products.svc/Products(1)`
- payload: { "Specification": { "PowerType": "240V" } }

So if (big if) I can take the ref server source & dissect the reason then maybe I can/will modify the connector but until then I think its difficult to know if there is anything that can be done.

**Comment by jsafarik** [comment]
@phantomjinx OK, I've just tried to send the REST request and you're right, there is an internal error on their side (on the TripPin service). I'll modify the service I use in automated tests to see how it behaves.

**Comment by jsafarik** [comment]
Just finished manual testing of this bug with syndesis-qe odata service and it is working properly. I've tried mapping odata enum recognized by syndesis as String as well as Int and both were reading and updating correctly.
