### ISSUE TITLE
[1.6.4][regression]google-sheets: Can not deserialize instance of java.util.LinkedHashMap when split involved

### ISSUE THREAD

**Issue by mmelko** [syndesisio/syndesis#5110]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I have simple integration DB -> Split -> DataMapper -> Google-sheets:update (collums).
The expected behavior is that I get couple of records from DB and overwrite values in spreadsheet.

I'm getting following exception on update action: 
```
019-04-02 09:51:43.588 ERROR 1 --- [r://integration] o.a.camel.processor.DefaultErrorHandler  : Failed delivery for (MessageId: i-LbSSXrA4FH1JgLE80W6z on ExchangeId: i-LbSSXlb4FH1JgLE80W3z). Exhausted after delivery attempt: 1 caught: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token
 at [Source: [{"spreadsheetId":"1SXR0Ui5KwS7D_aIKngxGfVeKMMCz3Rb4oeMdY5t4u0I","#1":"Matej","#2":"Foo","#3":"Red Hat","#4":"db"}]; line: 1, column: 1]
Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[-LbSSDoXn5sHKoSiPQ] [-LbSSDoXn5sHKoSiPQ] [timer://integration?period=60000000                                           ] [       621]
[-LbSSDoXn5sHKoSiPQ] [setHeader2        ] [setHeader[Syndesis.STEP_ID]                                                   ] [         1]
[-LbSSDoXn5sHKoSiPQ] [process1          ] [Processor@0x7fc5849e                                                          ] [         0]
[-LbSSDoXn5sHKoSiPQ] [step:-LbSSJSmn5sHK] [pipeline                                                                      ] [       357]
[-LbSSDoXn5sHKoSiPQ] [setHeader3        ] [setHeader[Syndesis.STEP_ID]                                                   ] [         0]
[-LbSSDoXn5sHKoSiPQ] [process2          ] [Processor@0x99b1a4b                                                           ] [         1]
[-LbSSDoXn5sHKoSiPQ] [to2               ] [atlas:mapping-flow-0-step-2.json?encoding=UTF-8&sourceMapName=Syndesis.CAPTURE] [       353]
[-LbSSDoXn5sHKoSiPQ] [process3          ] [Processor@0x76a5bf37                                                          ] [         0]
[-LbSSDoXn5sHKoSiPQ] [process4          ] [Processor@0x7fc5849e                                                          ] [         0]
[-LbSSDoXn5sHKoSiPQ] [step:-LbSSI4Hn5sHK] [pipeline                                                                      ] [         0]
[-LbSSDoXn5sHKoSiPQ] [setHeader4        ] [setHeader[Syndesis.STEP_ID]                                                   ] [         0]
[-LbSSDoXn5sHKoSiPQ] [to3               ] [google-sheets-0-3                                                             ] [        16]
Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token
 at [Source: [{"spreadsheetId":"1SXR0Ui5KwS7D_aIKngxGfVeKMMCz3Rb4oeMdY5t4u0I","#1":"Matej","#2":"Foo","#3":"Red Hat","#4":"db"}]; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270) ~[jackson-databind-2.8.11.2.jar!/:2.8.11.2]
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1247) ~[jackson-databind-2.8.11.2.jar!/:2.8.11.2]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122) ~[jackson-databind-2.8.11.2.jar!/:2.8.11.2]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075) ~[jackson-databind-2.8.11.2.jar!/:2.8.11.2]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromEmpty(StdDeserializer.java:892) ~[jackson-databind-2.8.11.2.jar!/:2.8.11.2]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:358) ~[jackson-databind-2.8.11.2.jar!/:2.8.11.2]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:27) ~[jackson-databind-2.8.11.2.jar!/:2.8.11.2]
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1626) ~[jackson-databind-2.8.11.2.jar!/:2.8.11.2]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1220) ~[jackson-databind-2.8.11.2.jar!/:2.8.11.2]
	at io.syndesis.connector.sheets.GoogleSheetsUpdateValuesCustomizer.beforeProducer(GoogleSheetsUpdateValuesCustomizer.java:97) ~[connector-google-sheets-1.6.4.jar!/:1.6.4]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at io.syndesis.integration.component.proxy.ComponentProxyProducer.process(ComponentProxyProducer.java:44) ~[integration-component-proxy-1.6.4.jar!/:1.6.4]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$EventProcessor.process(ActivityTrackingInterceptStrategy.java:79) [integration-runtime-1.6.4.jar!/:1.6.4]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:715) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:638) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:248) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.Splitter.process(Splitter.java:122) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) [camel-core-2.21.0.fuse-730054.jar!/:2.21.0.fuse-730054]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_191]
	at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_191]
```

This is not working in 1.6.4 and CR1, but it worked with 1.6.2

**Comment by heiko-braun** [comment]
@mmelko What priority would give to this one?

**Comment by mmelko** [comment]
@heiko-braun you basically can't use split with google spreadsheet connector. As this is a regression and it was working before I've set p0.

**Comment by mmelko** [comment]
verified with 1.6.8
