### ISSUE TITLE
[camel-k] NPE thrown by CamelKIntegrationController

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#5219]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

While running syndesis in camel-k mode, I sometimes see the following error:
 
```
java.lang.NullPointerException: id
 at java.util.Objects.requireNonNull(Objects.java:228) ~[na:1.8.0_151]
 at io.syndesis.common.model.ImmutableChangeEvent$Builder.id(ImmutableChangeEvent.java:372) ~[common-model-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
 at io.syndesis.common.model.ChangeEvent.of(ChangeEvent.java:39) ~[common-model-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
 at io.syndesis.server.controller.integration.camelk.CamelKIntegrationController.lambda$start$0(CamelKIntegrationController.java:81) ~[server-controller-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
 at io.syndesis.server.openshift.OpenShiftServiceImpl$1.eventReceived(OpenShiftServiceImpl.java:539) ~[server-openshift-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
 at io.syndesis.server.openshift.OpenShiftServiceImpl$1.eventReceived(OpenShiftServiceImpl.java:536) ~[server-openshift-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
 at io.fabric8.kubernetes.client.utils.WatcherToggle.eventReceived(WatcherToggle.java:49) ~[kubernetes-client-3.1.12.fuse-730022.jar!/:na]
 at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:237) ~[kubernetes-client-3.1.12.fuse-730022.jar!/:na]
 at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:307) ~[okhttp-3.8.1.jar!/:na]
 at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222) ~[okhttp-3.8.1.jar!/:na]
 at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101) ~[okhttp-3.8.1.jar!/:na]
 at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262) ~[okhttp-3.8.1.jar!/:na]
 at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201) ~[okhttp-3.8.1.jar!/:na]
 at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141) [okhttp-3.8.1.jar!/:na]
```

**Comment by valdar** [comment]
The only way I was able to reproduce this was by forcibly removing an annotation from the generated camel-k Integration CR. This, however, can not happen during normal syndesis usage.

Might be it was an error occurred in a spurious environment? 

I will log a warning about dropping the event instead of throwing the exception.
