### ISSUE TITLE
[camel-k] metrics : IllegalStateException thrown by prometheus provider

### ISSUE THREAD

**Issue by lburgazzoli** [syndesisio/syndesis#5253]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

I sometime experience the following error while running an integration using camel-k and then scale it to replicas > 1:

```
 java.lang.IllegalStateException: Duplicate key 19365
 	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133) ~[na:1.8.0_151]
 	at java.util.HashMap.merge(HashMap.java:1254) ~[na:1.8.0_151]
 	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320) ~[na:1.8.0_151]
 	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[na:1.8.0_151]
 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380) ~[na:1.8.0_151]
 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_151]
 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_151]
 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_151]
 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_151]
 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_151]
 	at io.syndesis.server.metrics.prometheus.QueryResult.lambda$getValueMap$5(QueryResult.java:61) ~[server-metrics-prometheus-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
 	at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_151]
 	at io.syndesis.server.metrics.prometheus.QueryResult.getValueMap(QueryResult.java:60) ~[server-metrics-prometheus-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
 	at io.syndesis.server.metrics.prometheus.PrometheusMetricsProviderImpl.getTopIntegrations(PrometheusMetricsProviderImpl.java:255) ~[server-metrics-prometheus-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
 	at io.syndesis.server.metrics.prometheus.PrometheusMetricsProviderImpl.getTotalIntegrationMetricsSummary(PrometheusMetricsProviderImpl.java:212) ~[server-metrics-prometheus-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
 	at io.syndesis.server.endpoint.v1.handler.metrics.IntegrationMetricsHandler.get(IntegrationMetricsHandler.java:65) ~[server-endpoint-1.6-SNAPSHOT.jar!/:1.6-SNAPSHOT]
 	at sun.reflect.GeneratedMethodAccessor632.invoke(Unknown Source) ~[na:na]
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
```

**Comment by lburgazzoli** [comment]
duplicate of #5296
