### ISSUE TITLE
FHIR integration: Transaction->Read: resource Id not mapped by datamapper

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#5338]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
An integration:
**FHIR transaction** -> **Datamapper (id->id)** -> **FHIR read**

throws an exception:
<pre><code>
org.apache.camel.RuntimeCamelException: Error invoking resourceById with {stringId=null, resources=[org.hl7.fhir.dstu3.model.Organization@3ad11c48, org.hl7.fhir.dstu3.model.Patient@2b9a89d7], extraParameters={}, version=null, resourceClass=Patient}: The ID can not be blank
	at org.apache.camel.util.component.ApiMethodHelper.invokeMethod(ApiMethodHelper.java:514)
	at org.apache.camel.util.component.AbstractApiProducer.doInvokeMethod(AbstractApiProducer.java:120)
	at org.apache.camel.util.component.AbstractApiProducer$1.run(AbstractApiProducer.java:86)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: The ID can not be blank
	at org.apache.commons.lang3.Validate.notBlank(Validate.java:451)
	at ca.uhn.fhir.rest.client.impl.GenericClient$ReadInternal.withId(GenericClient.java:1599)
	at org.apache.camel.component.fhir.api.FhirRead.readWithOptionalVersion(FhirRead.java:135)
	at org.apache.camel.component.fhir.api.FhirRead.resourceById(FhirRead.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.camel.util.component.ApiMethodHelper.invokeMethod(ApiMethodHelper.java:506)
	... 9 more
</code></pre>

The read action doesn't get a resource id from the datamapper step.
The exported integration:
[FHIR_transaction-export.zip](https://github.com/syndesisio/syndesis/files/3166458/FHIR_transaction-export.1.zip)

**Comment by rkorytkowski** [comment]
I see that you've mapped from "3 - Data Mapper (Transaction)", whereas you should have mapped from    "4 - io.syndesis:fhir-transaction-connector". 
The 3rd step in Data Mapper refers to what you send in a transaction and the 4th step refers to what you get back, thus the id is only available in the 4th step.
