### ISSUE TITLE
FHIR - datamapper: mapped an URL string as a record ID 

### ISSUE THREAD

**Issue by mastepan** [syndesisio/syndesis#5542]
See also **https://issues.jboss.org/browse/ENTESB-11424**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I have an integration:
[FHIR_delete-export.zip](https://github.com/syndesisio/syndesis/files/3241609/FHIR_delete-export.zip)

DB periodic SQL -> FHIR create -> **datamapper** -> FHIR delete -> log
datamapper should map **id.value** from CREATE action to **id** from DELETE action

But what is mapped is:
<code>http://hapi.fhir.org/baseDstu3/Patient/1948754/_history/1</code>

instead of just 1948754
which causes an exception:
<pre><code>
org.apache.camel.RuntimeCamelException: Error invoking resourceById with {stringId=http://hapi.fhir.org/baseDstu3/Patient/1948754/_history/1, resourceAsString=<?xml version="1.0" encoding="UTF-8" standalone="no"?><tns:Patient xmlns:tns="http://hl7.org/fhir"><name><tns:given value="Joe"/><tns:family value="Jackson"/></name></tns:Patient>, extraParameters={}, type=Patient, version=null, resourceClass=Patient}: LogicalId can not contain '/' (should only be the logical ID portion, not a qualified ID)
	at org.apache.camel.util.component.ApiMethodHelper.invokeMethod(ApiMethodHelper.java:514)
	at org.apache.camel.util.component.AbstractApiProducer.doInvokeMethod(AbstractApiProducer.java:120)
	at org.apache.camel.util.component.AbstractApiProducer$1.run(AbstractApiProducer.java:86)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: LogicalId can not contain '/' (should only be the logical ID portion, not a qualified ID)
	at ca.uhn.fhir.rest.client.impl.GenericClient$DeleteInternal.resourceById(GenericClient.java:671)
	at org.apache.camel.component.fhir.api.FhirDelete.resourceById(FhirDelete.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.camel.util.component.ApiMethodHelper.invokeMethod(ApiMethodHelper.java:506)
	... 9 more
</code></pre>

**Comment by paoloantinori** [comment]
@igarashitm @pleacu can you help triaging this to understand if the issue is with FHIR or with AtlasMap?

**Comment by rkorytkowski** [comment]
I'm back and looking into that.

**Comment by igarashitm** [comment]
Here is the mapping definition I extracted from the syndesis export. It looks OK from AtlasMap POV.
I need to see following two which I can't see from description
1. What is the expected input/output to/from data mapper step
1. What is the actual output from data mapper step

```json
{
  "AtlasMapping": {
    "jsonType": "io.atlasmap.v2.AtlasMapping",
    "dataSource": [
      {
        "jsonType": "io.atlasmap.json.v2.JsonDataSource",
        "id": "-LgD8EqmZwU1BdLWPy36",
        "uri": "atlas:json:-LgD8EqmZwU1BdLWPy36",
        "dataSourceType": "SOURCE"
      },
      {
        "jsonType": "io.atlasmap.xml.v2.XmlDataSource",
        "id": "-LgD8I1HZwU1BdLWPy37",
        "uri": "atlas:xml:-LgD8I1HZwU1BdLWPy37",
        "dataSourceType": "TARGET",
        "template": null,
        "xmlNamespaces": {
          "xmlNamespace": [
            {
              "alias": "tns",
              "uri": "http://hl7.org/fhir"
            }
          ]
        }
      }
    ],
    "mappings": {
      "mapping": [
        {
          "jsonType": "io.atlasmap.v2.Collection",
          "mappingType": "COLLECTION",
          "collectionType": null,
          "mappings": {
            "mapping": [
              {
                "jsonType": "io.atlasmap.v2.Mapping",
                "mappingType": "MAP",
                "id": "mapping.495265",
                "inputField": [
                  {
                    "jsonType": "io.atlasmap.json.v2.JsonField",
                    "name": "first_name",
                    "path": "/<>/first_name",
                    "fieldType": "STRING",
                    "docId": "-LgD8EqmZwU1BdLWPy36",
                    "userCreated": false
                  }
                ],
                "outputField": [
                  {
                    "jsonType": "io.atlasmap.xml.v2.XmlField",
                    "name": "value",
                    "path": "/tns:Patient/tns:name<>/tns:given/@value",
                    "fieldType": "STRING",
                    "docId": "-LgD8I1HZwU1BdLWPy37",
                    "userCreated": false
                  }
                ]
              }
            ]
          }
        },
        {
          "jsonType": "io.atlasmap.v2.Collection",
          "mappingType": "COLLECTION",
          "collectionType": null,
          "mappings": {
            "mapping": [
              {
                "jsonType": "io.atlasmap.v2.Mapping",
                "mappingType": "MAP",
                "id": "mapping.511524",
                "inputField": [
                  {
                    "jsonType": "io.atlasmap.json.v2.JsonField",
                    "name": "last_name",
                    "path": "/<>/last_name",
                    "fieldType": "STRING",
                    "docId": "-LgD8EqmZwU1BdLWPy36",
                    "userCreated": false
                  }
                ],
                "outputField": [
                  {
                    "jsonType": "io.atlasmap.xml.v2.XmlField",
                    "name": "value",
                    "path": "/tns:Patient/tns:name<>/tns:family/@value",
                    "fieldType": "STRING",
                    "docId": "-LgD8I1HZwU1BdLWPy37",
                    "userCreated": false
                  }
                ]
              }
            ]
          }
        }
      ]
    },
    "name": "UI.269561",
    "lookupTables": {
      "lookupTable": []
    },
    "constants": {
      "constant": []
    },
    "properties": {
      "property": []
    }
  }
}
```

**Comment by rkorytkowski** [comment]
@mastepan so the issue is you used the id.value field, but you should have used the id.idPart field. I've requested to mention that in official docs. Id.value holds the URL, but id.idPart holds the logical id.

**Comment by mastepan** [comment]
@rkorytkowski thank you for the explanation. I'd bet my shoes I have always used id.value and it worked but maybe I'm wrong. Thanks anyway :)

**Comment by rkorytkowski** [comment]
@mastepan, your confusion may come from the fact that in other FHIR resources it is indeed id.value, but MethodOutcome is a special return type, which is a bit different.

**Comment by mastepan** [comment]
@rkorytkowski what if this happens?
[qqq-export.zip](https://github.com/syndesisio/syndesis/files/3397754/qqq-export.zip)
It seems there is no idPart...

<pre><code>
io.atlasmap.api.AtlasException: Errors: [Field 'idPart' not found on object 'http://hapi.fhir.org/baseDstu3/Patient/1984617/_history/2': docId='-Ljv9Zr_pw_jJENATYvj', path='/id/idPart'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:262)
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$TrackDoneEventProcessor.process(ActivityTrackingInterceptStrategy.java:121)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.access$100(Pipeline.java:43)
	at org.apache.camel.processor.Pipeline$1.done(Pipeline.java:157)
	at org.apache.camel.processor.CamelInternalProcessor$InternalCallback.done(CamelInternalProcessor.java:262)
	at org.apache.camel.processor.RedeliveryErrorHandler$2.done(RedeliveryErrorHandler.java:560)
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$TrackDoneEventProcessor.lambda$process$0(ActivityTrackingInterceptStrategy.java:134)
	at org.apache.camel.processor.Pipeline$1.done(Pipeline.java:166)
	at org.apache.camel.processor.CamelInternalProcessor$InternalCallback.done(CamelInternalProcessor.java:262)
	at org.apache.camel.processor.RedeliveryErrorHandler$2.done(RedeliveryErrorHandler.java:560)
	at org.apache.camel.processor.SendProcessor$1.done(SendProcessor.java:160)
	at org.apache.camel.processor.Pipeline$1.done(Pipeline.java:166)
	at org.apache.camel.util.component.AbstractApiProducer$1.run(AbstractApiProducer.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</code></pre>

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11424**
