### ISSUE TITLE
Mapping from JSON broke

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#5647]
## This is a...

<pre><code>
[ ] Feature request
[*] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Trying to run this quickstart
https://github.com/syndesisio/syndesis-quickstarts/tree/master/webhook-2-db

 reveals 2 issues:
1. The mapping from task -> task does no longer work

 curl -k --header "Content-Type: application/json" --request POST --data '{ "task":"my new task!"}' $externalURL
org.apache.camel.RuntimeExchangeException: Cannot find key [task] in message body or headers to use when setting named parameter in query [INSERT INTO TODO (task) VALUES (:?task)] on the exchange: Exchange[i-Lgn8J2vEYFPQxsgGnKAz]

2. The externalUrl field no longer shows up after publishing.

**Comment by gashcrumb** [comment]
#2 I just fixed earlier today and I don't think it's been brought over from the syndesis-react repo yet.

**Comment by zregvart** [comment]
I'd double check that Atlasmap receives the POSTed JSON in Camel Message body and that the SQL connector receives JSON out of Atlasmap. I'd usually debug this, but using log connector would work also.
I kinda thought at first that the issue might have something to do with header whitelisting we do for HTTP connectors, but payload is transferred via message body, so that should not be it.

**Comment by christophd** [comment]
I hope this is not a side effect of the new batch insert support for the SQL connector. I will also have a look

**Comment by paoloantinori** [comment]
guys any update on this that can help us to classify it UI or backend?

**Comment by christophd** [comment]
I setup an automated test for the quickstart that loads the export .zip and starts the integration (using Testcontainer) with latest Syndesis S2i runtime. The test invokes the Webhook and checks that the entry is in the DB.

The test was green on my machine so the backend should be fine.

https://github.com/christophd/syndesis-qe/blob/pr/integration-tests/integration-tests/src/test/java/io/syndesis/qe/itest/quickstart/Webhook2DB_IT.java

Someone could double check with local minishfit and latest master though

**Comment by heiko-braun** [comment]
@KurtStam Can you verify @christophd 's change in https://github.com/syndesisio/syndesis/issues/5647#issuecomment-500708504 ?

**Comment by avano** [comment]
@christophd it worked some time after the batch insert change (I was on PTO last week and it doesn't work anymore :grin: )

I tried with latest master on minishift:

`SQL - Select * FROM CONTACT -> Datamapper - last_name to task -> SQL - INSERT INTO TODO (task, completed) VALUES (:#task, 3)`

```
{"exchange":"i-Lh595rOQzNUKAWm5_13z","step":"-Lh58nLr6NK7IgUMgWAs","id":"i-Lh5965PQzNUKAWm5_18z","duration":8060225,"failure":"org.apache.camel.RuntimeExchangeException: Cannot find key [task] in message body or headers to use when setting named parameter in query [INSERT INTO TODO (task, completed) VALUES (:?task, 0)] on the exchange: Exchange[i-Lh595rOQzNUKAWm5_13z]\n\tat org.apache.camel.component.sql.DefaultSqlPrepareStatementStrategy$PopulateIterator.next(DefaultSqlPrepareStatementStrategy.java:355)\n\tat org.apache.camel.component.sql.DefaultSqlPrepareStatementStrategy.populateStatement(DefaultSqlPrepareStatementStrategy.java:180)\n\tat org.apache.camel.component.sql.SqlProducer$2.doInPreparedStatement(SqlProducer.java:146)\n\tat org.apache.camel.component.sql.SqlProducer$2.doInPreparedStatement(SqlProducer.java:116)\n\tat org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:639)\n\tat org.apache.camel.component.sql.SqlProducer.process(SqlProducer.java:116)\n\tat org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat io.syndesis.integration.component.proxy.ComponentProxyProducer.process(ComponentProxyProducer.java:44)\n\tat org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)\n\tat io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$TrackDoneEventProcessor.process(ActivityTrackingInterceptStrategy.java:121)\n\tat org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110)\n\tat org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:138)\n\tat org.apache.camel.processor.Pipeline.process(Pipeline.java:101)\n\tat org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)\n\tat org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197)\n\tat org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79)\n\tat java.util.TimerThread.mainLoop(Timer.java:555)\n\tat java.util.TimerThread.run(Timer.java:505)\n"}
{"exchange":"i-Lh595rOQzNUKAWm5_13z","status":"done","failed":true}
2019-06-11 10:49:44.114  WARN 1 --- [r://integration] o.a.camel.component.timer.TimerConsumer  : Error processing exchange. Exchange[i-Lh595rOQzNUKAWm5_13z]. Caused by: [org.apache.camel.RuntimeExchangeException - Cannot find key [task] in message body or headers to use when setting named parameter in query [INSERT INTO TODO (task, completed) VALUES (:?task, 0)] on the exchange: Exchange[i-Lh595rOQzNUKAWm5_13z]]
org.apache.camel.RuntimeExchangeException: Cannot find key [task] in message body or headers to use when setting named parameter in query [INSERT INTO TODO (task, completed) VALUES (:?task, 0)] on the exchange: Exchange[i-Lh595rOQzNUKAWm5_13z]
	at org.apache.camel.component.sql.DefaultSqlPrepareStatementStrategy$PopulateIterator.next(DefaultSqlPrepareStatementStrategy.java:355) ~[camel-sql-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.component.sql.DefaultSqlPrepareStatementStrategy.populateStatement(DefaultSqlPrepareStatementStrategy.java:180) ~[camel-sql-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.component.sql.SqlProducer$2.doInPreparedStatement(SqlProducer.java:146) ~[camel-sql-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.component.sql.SqlProducer$2.doInPreparedStatement(SqlProducer.java:116) ~[camel-sql-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:639) ~[spring-jdbc-4.3.19.RELEASE.jar!/:4.3.19.RELEASE]
	at org.apache.camel.component.sql.SqlProducer.process(SqlProducer.java:116) ~[camel-sql-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at io.syndesis.integration.component.proxy.ComponentProxyProducer.process(ComponentProxyProducer.java:44) ~[integration-component-proxy-1.7-SNAPSHOT.jar!/:1.7-SNAPSHOT]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$TrackDoneEventProcessor.process(ActivityTrackingInterceptStrategy.java:121) ~[integration-runtime-1.7-SNAPSHOT.jar!/:1.7-SNAPSHOT]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) ~[camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) ~[camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) ~[camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) [camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) [camel-core-2.21.0.fuse-740013.jar!/:2.21.0.fuse-740013]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_191]
	at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_191]

```

**Comment by christophd** [comment]
@avano is your sample integration being imported to Syndesis or created from scratch? Are you using the Angular UI?

**Comment by avano** [comment]
@christophd created from scratch in the react ui

**Comment by christophd** [comment]
cool, thanks

**Comment by avano** [comment]
looks ok now
