### ISSUE TITLE
Flaky SQL test

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#592]
There is a flaky SQL test https://ci.fabric8.io/blue/organizations/jenkins/syndesis-pullreq/detail/PR-586/2/pipeline

```
18:44:51.494 [main           ] DEBUG amel.util.IntrospectionSupport - Clearing cache[size=76, hits=91, misses=76, evicted=48]
18:44:51.495 [main           ] INFO  camel.impl.DefaultCamelContext - Apache Camel 2.20.1 (CamelContext: camel-2) uptime 1.297 seconds
18:44:51.495 [main           ] INFO  camel.impl.DefaultCamelContext - Apache Camel 2.20.1 (CamelContext: camel-2) is shutdown in 0.043 seconds
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.315 sec <<< FAILURE! - in io.syndesis.connector.sql.SqlConnectorComponentTest
camelConnectorTest(io.syndesis.connector.sql.SqlConnectorComponentTest)  Time elapsed: 1.361 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<{ID=[1, FIRSTNAME=Joe, LASTNAME=Jackson]}> but was:<{ID=[2, FIRSTNAME=Roger, LASTNAME=Waters]}>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.syndesis.connector.sql.SqlConnectorComponentTest.camelConnectorTest(SqlConnectorComponentTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)


Results :

Failed tests: 
  SqlConnectorComponentTest.camelConnectorTest:108 expected:<{ID=[1, FIRSTNAME=Joe, LASTNAME=Jackson]}> but was:<{ID=[2, FIRSTNAME=Roger, LASTNAME=Waters]}>

Tests run: 2, Failures: 1, Errors: 0, Skipped: 0

```

**Comment by KurtStam** [comment]
https://github.com/syndesisio/syndesis/pull/595
