### ISSUE TITLE
Anothe SQL Test Error

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#596]
See https://963-105563335-gh.circle-artifacts.com/0/workspace/test_log.txt : 

```
component://SELECT%20\*%20FROM%20NAME%20ORDER%20BY%20id"
06:33:17.862 [main           ] DEBUG agement.DefaultManagementAgent - Unregistered MBean with ObjectName: org.apache.camel:context=camel-2,type=endpoints,name="sql-start-connector://SELECT%20\*%20FROM%20NAME%20ORDER%20BY%20id"
06:33:17.862 [ector-component] WARN  .component.timer.TimerConsumer - Error processing exchange. Exchange[ID-7bcd0c95b122-1512455587207-1-1]. Caused by: [java.util.concurrent.RejectedExecutionException - null]
java.util.concurrent.RejectedExecutionException: null
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:435)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101)
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197)
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
06:33:17.863 [main           ] DEBUG agement.DefaultManagementAgent - Unregistered MBean with ObjectName: org.apache.camel:context=camel-2,type=services,name=DefaultRestRegistry
06:33:17.866 [main           ] DEBUG agement.DefaultManagementAgent - Unregistered MBean with ObjectName: org.apache.camel:context=camel-2,type=services,name=DefaultEndpointRegistry
06:33:17.867 [main           ] DEBUG agement.DefaultManagementAgent - Unregistered MBean with ObjectName: org.apache.camel:context=camel-2,type=components,name="timer"
06:33:17.868 [main           ] DEBUG agement.DefaultManagementAgent - Unregistered MBean with ObjectName: org.apache.camel:context=camel-2,type=endpoints,name="timer://sql-sql-start-connector-component\?period=1000"
06:33:17.869 [main           ] DEBUG agement.DefaultManagementAgent - Unregistered MBean with ObjectName: org.apache.camel:context=camel-2,type=services,name=DefaultTransformerRegistry
06:33:17.870 [main           ] DEBUG agement.DefaultManagementAgent - Unregistered MBean with ObjectName: org.apache.camel:context=camel-2,type=services,name=DefaultAsyncProcessorAwaitManager
06:33:17.871 [main           ] DEBUG agement.DefaultManagementAgent - Unregistered MBean with ObjectName: org.apache.camel:context=camel-2,type=services,name=DefaultValidatorRegistry
06:33:17.872 [main           ] DEBUG agement.DefaultManagementAgent - Unregistered MBean with ObjectName: org.apache.camel:context=camel-2,type=processors,name="to3"
06:33:17.874 [main           ] DEBUG agement.DefaultManagementAgent - Unregistered MBean with ObjectName: org.apache.camel:context=camel-2,type=services,name=DefaultTypeConverter
06:33:17.875 [main           ] DEBUG agement.DefaultManagementAgent - Unregistered MBean with ObjectName: org.apache.camel:context=camel-2,type=tracer,name=BacklogDebugger
06:33:17.876 [main           ] DEBUG agement.DefaultManagementAgent - Unregistered MBean with ObjectName: org.apache.camel:context=camel-2,type=components,name="stream"
06:33:17.877 [main           ] DEBUG agement.DefaultManagementAgent - Unregistered MBean with ObjectName: org.apache.camel:context=camel-2,type=services,name=DefaultInflightRepository
06:33:17.877 [main           ] DEBUG .management.MBeanInfoAssembler - Clearing cache[size=24, hits=10, misses=24, evicted=0]
06:33:17.882 [main           ] DEBUG amel.util.IntrospectionSupport - Clearing cache[size=74, hits=101, misses=74, evicted=1]
06:33:17.886 [main           ] INFO  camel.impl.DefaultCamelContext - Apache Camel 2.20.1 (CamelContext: camel-2) uptime 7.600 seconds
06:33:17.887 [main           ] INFO  camel.impl.DefaultCamelContext - Apache Camel 2.20.1 (CamelContext: camel-2) is shutdown in 2.478 seconds
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 12.983 sec <<< FAILURE! - in io.syndesis.connector.sql.SqlStartConnectorComponentTest
camelConnectorTest(io.syndesis.connector.sql.SqlStartConnectorComponentTest)  Time elapsed: 7.68 sec  <<< FAILURE!
java.lang.AssertionError: expected:<[{"LASTNAME":"Jackson","FIRSTNAME":"Joe","ID":1},{"LASTNAME":"Waters","FIRSTNAME":"Roger","ID":2}]> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.syndesis.connector.sql.SqlStartConnectorComponentTest.camelConnectorTest(SqlStartConnectorComponentTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)


Results :

Failed tests: 
  SqlStartConnectorComponentTest.camelConnectorTest:107 expected:<[{"LASTNAME":"Jackson","FIRSTNAME":"Joe","ID":1},{"LASTNAME":"Waters","FIRSTNAME":"Roger","ID":2}]> but was:<null>
```

**Comment by KurtStam** [comment]
The latch waits 5 seconds, and it seems to take longer for some reason..

06:33:10.409 [main           ] INFO  camel.impl.DefaultCamelContext - Apache Camel 2.20.1 (CamelContext: camel-2) started in 0.122 seconds
06:33:11.408 [ector-component] DEBUG amework.jdbc.core.JdbcTemplate - Executing prepared SQL statement
06:33:15.409 [main           ] INFO  camel.impl.DefaultCamelContext - Apache Camel 2.20.1 (CamelContext: camel-2) is shutting down
06:33:17.814 [ector-component] DEBUG dbc.datasource.DataSourceUtils - Fetching JDBC Connection from DataSource

I will set timeout to 30s. It should be fast if everything goes to plan, so under normal conditions it should not add to the build time.
