### ISSUE TITLE
[Fix] Connection error at startup

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#5965]
```
2019-06-27 14:31:48.008  INFO 1 --- [           main] o.a.c.s.boot.CamelAutoConfiguration      : Using custom InterceptStrategy with id: integrationLoggingInterceptStrategy and implementation: io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy@41a90fa8
2019-06-27 14:31:48.113  INFO 1 --- [           main] o.a.c.i.converter.DefaultTypeConverter   : Type converters loaded (core: 194, classpath: 7)
2019-06-27 14:31:49.162  INFO 1 --- [           main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-06-27 14:31:49.425  INFO 1 --- [localhost:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.connection.SocketStream.open(SocketStream.java:63) ~[mongo-java-driver-3.4.3.jar!/:na]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115) ~[mongo-java-driver-3.4.3.jar!/:na]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:113) ~[mongo-java-driver-3.4.3.jar!/:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_191]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_191]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_191]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_191]
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:57) ~[mongo-java-driver-3.4.3.jar!/:na]
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongo-java-driver-3.4.3.jar!/:na]
	... 3 common frames omitted
2019-06-27 14:31:49.778 INFO 1 --- [ main] o.s.b.a.e.mvc.EndpointHandlerMapping : Mapped "{[/health || /health.json],methods=[GET],produces=[application/vnd.spring-boot.actuator.v1+json || application/json]}" onto public java.lang.Object 
```
As soon as the proxyComponent register a mongoConnection with proper host, then the following is thrown:

```
2019-06-27 14:31:50.908  INFO 1 --- [           main] i.s.i.r.handlers.ConnectorStepHandler    : Got component: io.syndesis.integration.component.proxy.ComponentProxyComponent@54463380, mongodb3-0-1, mongodb3
2019-06-27 14:31:50.937 DEBUG 1 --- [           main] i.s.c.mongo.MongoClientCustomizer        : Creating and registering a client connection to MongoConfiguration [host=172.17.0.9, user=mongo, password=***, port=27017, adminDB=test]
2019-06-27 14:31:50.943  INFO 1 --- [           main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[172.17.0.9:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2019-06-27 14:31:50.955 DEBUG 1 --- [           main] i.s.i.c.proxy.ComponentProxyComponent    : Stopping connector: mongodb3-0-1
2019-06-27 14:31:50.985  INFO 1 --- [           main] utoConfigurationReportLoggingInitializer : 
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2019-06-27 14:31:51.000 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application startup failed
org.apache.camel.spring.boot.CamelSpringBootInitializationException: java.lang.IllegalArgumentException: java.lang.RuntimeException: java.lang.NullPointerException
```

**Comment by squakez** [comment]
Missing Spring autoconfiguration exclusions. Testing in progress...

**Comment by mastepan** [comment]
@squakez please reopen if needed. I'm closing this because of ignore/qe label and Done state
