### ISSUE TITLE
Twitter direct message doesn't work (atlas exception)

### ISSUE THREAD

**Issue by wyvie** [syndesisio/syndesis#6017]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When creating integration with the new twitter direct message feature, I get an error. Deployed integration doesn't receive any new direct messages, and instead prints this into the log:

```
io.atlasmap.api.AtlasException: Errors: [Unexpected exception is thrown while reading source field: java.lang.reflect.InvocationTargetException: docId='-LihpxxpuOg_BQwrUERj', path='/senderScreenName'],
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:262) ~[camel-atlasmap-1.40.0.jar!/:1.40.0]
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71) ~[camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at io.syndesis.integration.runtime.logging.ActivityTrackingInterceptStrategy$TrackDoneEventProcessor.process(ActivityTrackingInterceptStrategy.java:121) [integration-runtime-1.7.6.jar!/:1.7.6]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:110) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.component.twitter.consumer.DefaultTwitterConsumer.poll(DefaultTwitterConsumer.java:98) [camel-twitter-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101) [camel-core-2.21.0.fuse-740028.jar!/:2.21.0.fuse-740028]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
```

The same problem happens when I try to use the `/sender/screenName` instead.
Feature is being developed here: https://github.com/syndesisio/syndesis/issues/3521

**Comment by claudio4j** [comment]
Can you attach the screenshot of the map screen ?

**Comment by wyvie** [comment]
@claudio4j the datamapper one?

**Comment by wyvie** [comment]
![image](https://user-images.githubusercontent.com/3992240/60445602-cf754880-9c1f-11e9-9fb8-6f2494f007fc.png)

**Comment by claudio4j** [comment]
The `senderScreenName` cannot be used as it is deprecated and throws `UnsupportedOperationException`

https://github.com/Twitter4J/Twitter4J/blob/4.0.7/twitter4j-core/src/main/java/twitter4j/DirectMessage.java#L47
https://github.com/Twitter4J/Twitter4J/blob/4.0.7/twitter4j-core/src/internal-json/java/twitter4j/DirectMessageJSONImpl.java#L254

**Comment by wyvie** [comment]
It's all nice, but can we really release the feature like that? Users will be very confused. Do I understand correctly that there is no way to get screen name now? `/sender/screenName` does the same.

**Comment by heiko-braun** [comment]
@igarashitm If the `senderScreenName` is not  supported anymore, but the accessor is still present, can we somehow suppress that attribute in the mapping to avoid the error described above?  @wyvie Would this improve the situation from your point of view?

**Comment by wyvie** [comment]
@heiko-braun of course. if the twitter API doesn't allow us retrieve the screen name, it's fine. problem imo is that attribute is available for our users on the top level of the mapping.
i mean, i don't personally think i will be able to parse twitter user id if it comes on my mail, so i would try to use twitter screen name as soon as i saw one on the mapper, if i were user

**Comment by igarashitm** [comment]
The easiest way is to modify twitter4j.Twitter Java inspection output at Syndesis side manually, i.e. remove unsupported fields. We can investigate to remove fields if it's marked as deprecated programatically, but it's not trivial. If getter is marked as deprecated then it's easy, but there're many of other cases, only some of field/getter/setter have deprecated annotation, one of inheriting intermediate class is marked as deprecated as a whole, if it's marked as `@Deprecated` in the code or just in the javadoc `@deprecated`, etc.
The other option is to support blacklisting fields on inspection. Syndesis would pass a list of field paths to exclude when it requests offline inspection.

**Comment by wyvie** [comment]
also

```
io.atlasmap.api.AtlasException: Errors: [Unexpected exception is thrown while reading source field: io.atlasmap.api.AtlasException: java.lang.reflect.InvocationTargetException: docId='-Lii8eoeahKiNQ9FF49d', path='/sender/id'],
```

`/senderId` does work though.
What I don't like here is that finding a field that works is a process of trial and error... That's really not good.

**Comment by claudio4j** [comment]
Syndesis/Camel-Twitter depends on Twitter4J 4.0.7. The 4.0.6 there was a non -deprecated getSenderScreenName, but somehow the twitter rest api changed and doesn't embedded the sender/recipient screenName. The option to suppress fields by blacklist is a good alternative, is it supported ? 

https://github.com/Twitter4J/Twitter4J/blob/4.0.6/twitter4j-core/src/internal-json/java/twitter4j/DirectMessageJSONImpl.java

https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/guides/message-create-object

**Comment by claudio4j** [comment]
A quick solution is to not use the twitter.DirectMessage as outputDataShape and use a syndesis DirectMessage, I will test this one.

**Comment by wyvie** [comment]
@claudio4j sorry i have one more question
![image](https://user-images.githubusercontent.com/3992240/60450196-9b9f2080-9c29-11e9-8113-90c125498f0b.png)
does this only work across same integration? because after recreating the integration, i seem to receive all of them again

**Comment by claudio4j** [comment]
The valid fields would be: id, text, senderId, recipientId, createdAt.

The ignore option will only work in the same integration in the same execution. If it is restarted, the direct messages will be retrieved all over again.

**Comment by igarashitm** [comment]
I just checked AtlasMap Java inspection and found field blacklist is not yet implemented. Not that big enhancement like handling deprecated, but it's still not trivial and would add regression risk.

**Comment by claudio4j** [comment]
I am working on a custom java object to wrap the DirectMessage.

**Comment by claudio4j** [comment]
@wyvie is this a p0 ? The fix is https://github.com/syndesisio/syndesis/pull/6038

**Comment by heiko-braun** [comment]
It's not a `p0` from my point of view.
