### ISSUE TITLE
[Upgrade] Rebuilding integration after upgrade results in Failure executing: PATCH

### ISSUE THREAD

**Issue by avano** [syndesisio/syndesis#6291]
See also **https://issues.jboss.org/browse/ENTESB-11396**

## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
I've created an integration `SQL (select * from contact) -> log` on 7.3.1 version and then upgraded the infra to 7.4 CR3. When I rebuild the integration, I get this log in the server log every time:

```
2019-07-31 12:42:31.059  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.online.PublishHandler          : Integration [db-log]: Starting deployment
2019-07-31 12:42:35.570 ERROR [-,,,] 1 --- [tion Controller] i.s.s.c.i.online.PublishHandler          : Integration [db-log]: [ERROR] Activation failure
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://kubernetes.default.svc/apis/apps.openshift.io/v1/namespaces/syndesis/deploymentconfigs/i-db-log. Message: This request caused apiserver to panic. Look in the logs for details.
.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:472) ~[kubernetes-client-3.1.12.fuse-740022-redhat-00001.jar!/:3.1.12.fuse-740022-redhat-00001]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:411) ~[kubernetes-client-3.1.12.fuse-740022-redhat-00001.jar!/:3.1.12.fuse-740022-redhat-00001]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381) ~[kubernetes-client-3.1.12.fuse-740022-redhat-00001.jar!/:3.1.12.fuse-740022-redhat-00001]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344) ~[kubernetes-client-3.1.12.fuse-740022-redhat-00001.jar!/:3.1.12.fuse-740022-redhat-00001]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handlePatch(OperationSupport.java:280) ~[kubernetes-client-3.1.12.fuse-740022-redhat-00001.jar!/:3.1.12.fuse-740022-redhat-00001]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handlePatch(BaseOperation.java:776) ~[kubernetes-client-3.1.12.fuse-740022-redhat-00001.jar!/:3.1.12.fuse-740022-redhat-00001]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$3.apply(HasMetadataOperation.java:156) ~[kubernetes-client-3.1.12.fuse-740022-redhat-00001.jar!/:3.1.12.fuse-740022-redhat-00001]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$3.apply(HasMetadataOperation.java:152) ~[kubernetes-client-3.1.12.fuse-740022-redhat-00001.jar!/:3.1.12.fuse-740022-redhat-00001]
	at io.fabric8.openshift.api.model.DoneableDeploymentConfig.done(DoneableDeploymentConfig.java:27) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
	at io.fabric8.openshift.api.model.DoneableDeploymentConfig.done(DoneableDeploymentConfig.java:6) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.patch(HasMetadataOperation.java:163) ~[kubernetes-client-3.1.12.fuse-740022-redhat-00001.jar!/:3.1.12.fuse-740022-redhat-00001]
	at io.fabric8.openshift.client.dsl.internal.DeploymentConfigOperationsImpl.patch(DeploymentConfigOperationsImpl.java:84) ~[openshift-client-3.1.12.fuse-740022-redhat-00001.jar!/:3.1.12.fuse-740022-redhat-00001]
	at io.fabric8.openshift.client.dsl.internal.DeploymentConfigOperationsImpl.patch(DeploymentConfigOperationsImpl.java:47) ~[openshift-client-3.1.12.fuse-740022-redhat-00001.jar!/:3.1.12.fuse-740022-redhat-00001]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$1.apply(HasMetadataOperation.java:60) ~[kubernetes-client-3.1.12.fuse-740022-redhat-00001.jar!/:3.1.12.fuse-740022-redhat-00001]
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$1.apply(HasMetadataOperation.java:50) ~[kubernetes-client-3.1.12.fuse-740022-redhat-00001.jar!/:3.1.12.fuse-740022-redhat-00001]
	at io.fabric8.openshift.api.model.DoneableDeploymentConfig.done(DoneableDeploymentConfig.java:27) ~[kubernetes-model-2.0.10.jar!/:2.0.10]
	at io.fabric8.openshift.client.dsl.internal.DeploymentConfigOperationsImpl.deployLatest(DeploymentConfigOperationsImpl.java:98) ~[openshift-client-3.1.12.fuse-740022-redhat-00001.jar!/:3.1.12.fuse-740022-redhat-00001]
	at io.fabric8.openshift.client.dsl.internal.DeploymentConfigOperationsImpl.deployLatest(DeploymentConfigOperationsImpl.java:89) ~[openshift-client-3.1.12.fuse-740022-redhat-00001.jar!/:3.1.12.fuse-740022-redhat-00001]
	at io.fabric8.openshift.client.dsl.internal.DeploymentConfigOperationsImpl.deployLatest(DeploymentConfigOperationsImpl.java:47) ~[openshift-client-3.1.12.fuse-740022-redhat-00001.jar!/:3.1.12.fuse-740022-redhat-00001]
	at io.syndesis.server.openshift.OpenShiftServiceImpl.deploy(OpenShiftServiceImpl.java:102) ~[server-openshift-1.7.13.fuse-740001-redhat-00002.jar!/:1.7.13.fuse-740001-redhat-00002]
	at io.syndesis.server.controller.integration.online.PublishHandler.deploy(PublishHandler.java:181) ~[server-controller-1.7.13.fuse-740001-redhat-00002.jar!/:1.7.13.fuse-740001-redhat-00002]
	at io.syndesis.server.controller.integration.online.PublishHandler$BuildStepOncePerformer.perform(PublishHandler.java:276) ~[server-controller-1.7.13.fuse-740001-redhat-00002.jar!/:1.7.13.fuse-740001-redhat-00002]
	at io.syndesis.server.controller.integration.online.PublishHandler.execute(PublishHandler.java:114) ~[server-controller-1.7.13.fuse-740001-redhat-00002.jar!/:1.7.13.fuse-740001-redhat-00002]
	at io.syndesis.server.controller.StateChangeHandler.execute(StateChangeHandler.java:33) [server-controller-1.7.13.fuse-740001-redhat-00002.jar!/:1.7.13.fuse-740001-redhat-00002]
	at io.syndesis.server.controller.integration.BaseIntegrationController.lambda$callStateChangeHandler$10(BaseIntegrationController.java:220) [server-controller-1.7.13.fuse-740001-redhat-00002.jar!/:1.7.13.fuse-740001-redhat-00002]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
2019-07-31 12:42:35.571  INFO [-,,,] 1 --- [tion Controller] i.s.s.c.i.BaseIntegrationController      : Integration i-Ll6Qo0le2jlAxwAme4-z : Setting status to Pending (Failure executing: PATCH at: https://kubernetes.default.svc/apis/apps.openshift.io/v1/namespaces/syndesis/deploymentconfigs/i-db-log. Message: This request caused apiserver to panic. Look in the logs for details.
.)

```

But the changes I did (I added a new string in the log step) were present - So I added both p1 and p2 because I don't know what it is trying to change

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11396**
