### ISSUE TITLE
[camel-k] Namespace parameter required when trying to publish integration

### ISSUE THREAD

**Issue by mmuzikar** [syndesisio/syndesis#6382]
See also **https://issues.jboss.org/browse/ENTESB-11383**

## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
When I try to publish an integration in syndesis which is using camel-k, I get this error message right after publishing: 
```
2019-08-15 10:51:46.854 ERROR [-,,,] 1 --- [tion Controller] i.s.s.c.i.BaseIntegrationController      : Error while processing integration status for integration i-LmJtuXIjG_aC1KZv6gsz:1
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/apis/camel.apache.org/v1alpha1/integrations/i-asdfsdaf . Message: Namespace parameter required.. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=Namespace parameter required., metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:472) ~[kubernetes-client-3.1.12.fuse-730022.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:411) ~[kubernetes-client-3.1.12.fuse-730022.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381) ~[kubernetes-client-3.1.12.fuse-730022.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344) ~[kubernetes-client-3.1.12.fuse-730022.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:313) ~[kubernetes-client-3.1.12.fuse-730022.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:296) ~[kubernetes-client-3.1.12.fuse-730022.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:780) ~[kubernetes-client-3.1.12.fuse-730022.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:196) ~[kubernetes-client-3.1.12.fuse-730022.jar!/:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:163) ~[kubernetes-client-3.1.12.fuse-730022.jar!/:na]
	at io.syndesis.server.openshift.OpenShiftServiceImpl.getCR(OpenShiftServiceImpl.java:583) ~[server-openshift-1.8-SNAPSHOT.jar!/:1.8-SNAPSHOT]
	at io.syndesis.server.controller.integration.camelk.BaseCamelKHandler.getCamelkIntegration(BaseCamelKHandler.java:40) ~[server-controller-1.8-SNAPSHOT.jar!/:1.8-SNAPSHOT]
	at io.syndesis.server.controller.integration.camelk.CamelKPublishHandler.execute(CamelKPublishHandler.java:120) ~[server-controller-1.8-SNAPSHOT.jar!/:1.8-SNAPSHOT]
	at io.syndesis.server.controller.StateChangeHandler.execute(StateChangeHandler.java:33) ~[server-controller-1.8-SNAPSHOT.jar!/:1.8-SNAPSHOT]
	at io.syndesis.server.controller.integration.BaseIntegrationController.lambda$callStateChangeHandler$10(BaseIntegrationController.java:220) ~[server-controller-1.8-SNAPSHOT.jar!/:1.8-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
```
I install syndesis with these commands:
```
syndesis install --setup --camel-k
syndesis install --camel-k 
syndesis kamel --activate
syndesis kamel --configure
syndesis kamel --sync-runtime
syndesis kamel --sync-lib
```
if that's of any help while solving this issue, also I have to manually scale down the operator and sometimes add the integration: camel-k into the syndesis-server config, but I think that's implied in the commands before and i just always forget to scale the operator down :D

**Comment by mmuzikar** [comment]
camel-k-operator log: 
[camel-k-operator-64f4c7594f-tdnbl.log](https://github.com/syndesisio/syndesis/files/3505285/camel-k-operator-64f4c7594f-tdnbl.log)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11383**
