### ISSUE TITLE
integration with DB connection fails to deploy

### ISSUE THREAD

**Issue by Stefan365** [syndesisio/syndesis#669]
If I create integration with DB connections 
(example, according to: https://drive.google.com/file/d/1eNO13gB4Q5i13SxkC1MFM8AT9vRxLIZm/view
or
https://drive.google.com/file/d/1A6LgMd4Y8SvYw_pjvE4GqlJpGVlZTto2/view)

Integration do not reach 'Active' status (status 'In progress' persists).

oc get pods:
```
skusobnaintegra-1-build       0/1       Completed          0          3m
skusobnaintegra-2-vpt3j       0/1       CrashLoopBackOff   4          2m
```

oc logs skusobnaintegra-1-build:
```
Receiving source from STDIN as archive ...
Pulling image "172.30.1.1:5000/syndesis-project-r/skusobnaintegra:latest" ...
pulling image error : Error: image syndesis-project-r/skusobnaintegra:latest not found

Starting S2I Java Build .....
S2I source build with plain binaries detected
Copying binaries from /tmp/src to /deployments ...
Checking for SpringBoot archive...
... done
 
Pushing image 172.30.1.1:5000/syndesis-project-r/skusobnaintegra:latest ...
Pushed 0/26 layers, 0% complete
Pushed 1/26 layers, 4% complete
Push successful
```

oc logs skusobnaintegra-2-vpt3j:
```
ERROR: Neither $JAVA_MAIN_CLASS nor $JAVA_APP_JAR is set and 0 found in /deployments (1 expected)
```

**Comment by dsimansk** [comment]
There one more interesting log message:
```
2017-12-08 12:39:40.617  INFO [-,,,] 1 --- [pool-3-thread-1] i.s.connector.catalog.ConnectorCatalog   : Downloading Maven GAV: io.syndesis:sql-start-connector:1.2-SNAPSHOT
2017-12-08 12:39:42.709  INFO [-,,,] 1 --- [pool-3-thread-1] i.s.c.integration.online.BaseHandler     : Integration [db-int]: Created project files and starting build
Exception in thread "pool-21-thread-1" java.lang.IllegalArgumentException: Cannot find endpoint with scheme sql-start-connector
	at org.apache.camel.catalog.AbstractCamelCatalog.doAsEndpointUri(AbstractCamelCatalog.java:879)
	at org.apache.camel.catalog.AbstractCamelCatalog.asEndpointUri(AbstractCamelCatalog.java:869)
	at io.syndesis.connector.catalog.ConnectorCatalog.buildEndpointUri(ConnectorCatalog.java:201)
	at io.syndesis.project.converter.visitor.EndpointStepVisitor.createEndpoint(EndpointStepVisitor.java:132)
	at io.syndesis.project.converter.visitor.EndpointStepVisitor.createEndpoint(EndpointStepVisitor.java:128)
	at io.syndesis.project.converter.visitor.EndpointStepVisitor.visit(EndpointStepVisitor.java:63)
	at io.syndesis.project.converter.DefaultProjectGenerator.visitStep(DefaultProjectGenerator.java:352)
	at io.syndesis.project.converter.DefaultProjectGenerator.generateFlow(DefaultProjectGenerator.java:339)
	at io.syndesis.project.converter.DefaultProjectGenerator.lambda$generateAddProjectTarEntries$1(DefaultProjectGenerator.java:191)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2017-12-08 12:41:13.989  INFO [-,,,] 1 --- [pool-3-thread-1] i.s.c.integration.online.BaseHandler     : Integration [db-int]: Starting deployment
2017-12-08 12:41:23.209  INFO [-,,,] 1 --- [pool-3-thread-1] i.s.c.integration.online.BaseHandler     : Integration [db-int]: Deployment done
2017-12-08 12:41:23.260  INFO [-,,,] 1 --- [pool-3-thread-1] i.s.c.integration.online.BaseHandler     : Integration [db-int]: Build started: false, isRunning: false, Deployment ready: false
2017-12-08 12:41:23.260  INFO [-,,,] 1 --- [pool-3-thread-1] i.s.c.integration.online.BaseHandler     : Integration [db-int]: [PENDING] [[build, deploy]]
2017-12-08 12:41:23.261  INFO [-,,,] 1 --- [pool-3-t
```

**Comment by zregvart** [comment]
Seems OK to me, perhaps database needs reloading, our schema migration is not as nice as it used to be.

https://github.com/syndesisio/syndesis/blob/50d529212b9add76746e28f22597e9d96c10396d/app/rest/dao/src/main/resources/io/syndesis/dao/deployment.json#L1221

https://github.com/syndesisio/syndesis/blob/50d529212b9add76746e28f22597e9d96c10396d/app/connectors/connectors/sql/sql-start-connector/src/main/resources/camel-connector.json#L8

**Comment by dsimansk** [comment]
Hmm, I can still reproduce this on a fresh Syndesis deployment.

**Comment by Stefan365** [comment]
@dsimansk me too. Still see that error.

**Comment by paoloantinori** [comment]
Seeing the same with images updated today.

**Comment by paoloantinori** [comment]
Checking in debug mode I can see this map while looking for value `sql-connector`:

```
0 = {HashMap$Node@17178} "salesforce-on-delete" -> "io.syndesis.connector.salesforce.SalesforceOnDeleteComponent"
1 = {HashMap$Node@17179} "aws-cw" -> "org.apache.camel.component.aws.cw.CwComponent"
2 = {HashMap$Node@17180} "direct-vm" -> "org.apache.camel.component.directvm.DirectVmComponent"
3 = {HashMap$Node@17181} "aws-swf" -> "org.apache.camel.component.aws.swf.SWFComponent"
4 = {HashMap$Node@17182} "validator" -> "org.apache.camel.component.validator.ValidatorComponent"
5 = {HashMap$Node@17183} "sjms" -> "org.apache.camel.component.sjms.SjmsComponent"
6 = {HashMap$Node@17184} "binding" -> "org.apache.camel.component.binding.BindingNameComponent"
7 = {HashMap$Node@17185} "language" -> "org.apache.camel.component.language.LanguageComponent"
8 = {HashMap$Node@17186} "salesforce-on-update" -> "io.syndesis.connector.salesforce.SalesforceOnUpdateComponent"
9 = {HashMap$Node@17187} "salesforce-get-sobject-with-id" -> "io.syndesis.connector.salesforce.SalesforceGetSObjectWithIdComponent"
10 = {HashMap$Node@17188} "aws-lambda" -> "org.apache.camel.component.aws.lambda.LambdaComponent"
11 = {HashMap$Node@17189} "salesforce" -> "org.apache.camel.component.salesforce.SalesforceComponent"
12 = {HashMap$Node@17190} "twitter" -> "org.apache.camel.component.twitter.TwitterComponent"
13 = {HashMap$Node@17191} "ref" -> "org.apache.camel.component.ref.RefComponent"
14 = {HashMap$Node@17192} "aws-ddbstream" -> "org.apache.camel.component.aws.ddbstream.DdbStreamComponent"
15 = {HashMap$Node@17193} "stub" -> "org.apache.camel.component.stub.StubComponent"
16 = {HashMap$Node@17194} "aws-kinesis" -> "org.apache.camel.component.aws.kinesis.KinesisComponent"
17 = {HashMap$Node@17195} "twitter-mention-connector" -> "io.syndesis.connector.twitter.TwitterMentionComponent"
18 = {HashMap$Node@17196} "bean" -> "org.apache.camel.component.bean.BeanComponent"
19 = {HashMap$Node@17197} "aws-sns" -> "org.apache.camel.component.aws.sns.SnsComponent"
20 = {HashMap$Node@17198} "twitter-directmessage" -> "org.apache.camel.component.twitter.directmessage.TwitterDirectMessageComponent"
21 = {HashMap$Node@17199} "twitter-streaming" -> "org.apache.camel.component.twitter.streaming.TwitterStreamingComponent"
22 = {HashMap$Node@17200} "test" -> "org.apache.camel.component.test.TestComponent"
23 = {HashMap$Node@17201} "aws-ddb" -> "org.apache.camel.component.aws.ddb.DdbComponent"
24 = {HashMap$Node@17202} "aws-ses" -> "org.apache.camel.component.aws.ses.SesComponent"
25 = {HashMap$Node@17203} "twitter-search" -> "org.apache.camel.component.twitter.search.TwitterSearchComponent"
26 = {HashMap$Node@17204} "aws-sqs" -> "org.apache.camel.component.aws.sqs.SqsComponent"
27 = {HashMap$Node@17205} "aws-ec2" -> "org.apache.camel.component.aws.ec2.EC2Component"
28 = {HashMap$Node@17206} "vm" -> "org.apache.camel.component.vm.VmComponent"
29 = {HashMap$Node@17207} "aws-s3" -> "org.apache.camel.component.aws.s3.S3Component"
30 = {HashMap$Node@17208} "mock" -> "org.apache.camel.component.mock.MockComponent"
31 = {HashMap$Node@17209} "salesforce-create-sobject" -> "io.syndesis.connector.salesforce.SalesforceCreateSObjectComponent"
32 = {HashMap$Node@17210} "activemq-request" -> "io.syndesis.connector.jms.ActiveMQRequestComponent"
33 = {HashMap$Node@17211} "aws-s3-copy-object-connector" -> "io.syndesis.s3.copy.S3CopyObjectConnectorComponent"
34 = {HashMap$Node@17212} "browse" -> "org.apache.camel.component.browse.BrowseComponent"
35 = {HashMap$Node@17213} "twitter-timeline" -> "org.apache.camel.component.twitter.timeline.TwitterTimelineComponent"
36 = {HashMap$Node@17214} "salesforce-upsert-sobject" -> "io.syndesis.connector.salesforce.SalesforceUpsertSObjectComponent"
37 = {HashMap$Node@17215} "log" -> "org.apache.camel.component.log.LogComponent"
38 = {HashMap$Node@17216} "twitter-search-connector" -> "io.syndesis.search.TwitterSearchComponent"
39 = {HashMap$Node@17217} "direct" -> "org.apache.camel.component.direct.DirectComponent"
40 = {HashMap$Node@17218} "aws-kinesis-firehose" -> "org.apache.camel.component.aws.firehose.KinesisFirehoseComponent"
41 = {HashMap$Node@17219} "salesforce-update-sobject" -> "io.syndesis.connector.salesforce.SalesforceUpdateSObjectComponent"
42 = {HashMap$Node@17220} "activemq-subscribe" -> "io.syndesis.connector.jms.ActiveMQSubscribeComponent"
43 = {HashMap$Node@17221} "spring-event" -> "org.apache.camel.component.event.EventComponent"
44 = {HashMap$Node@17222} "sql" -> "org.apache.camel.component.sql.SqlComponent"
45 = {HashMap$Node@17223} "scheduler" -> "org.apache.camel.component.scheduler.SchedulerComponent"
46 = {HashMap$Node@17224} "timer" -> "org.apache.camel.component.timer.TimerComponent"
47 = {HashMap$Node@17225} "file" -> "org.apache.camel.component.file.FileComponent"
48 = {HashMap$Node@17226} "salesforce-on-create" -> "io.syndesis.connector.salesforce.SalesforceOnCreateComponent"
49 = {HashMap$Node@17227} "sql-stored-connector" -> "io.syndesis.connector.sql.stored.SqlStoredConnectorComponent"
50 = {HashMap$Node@17228} "aws-sdb" -> "org.apache.camel.component.aws.sdb.SdbComponent"
51 = {HashMap$Node@17229} "sjms-batch" -> "org.apache.camel.component.sjms.batch.SjmsBatchComponent"
52 = {HashMap$Node@17230} "salesforce-delete-sobject-with-id" -> "io.syndesis.connector.salesforce.SalesforceDeleteSObjectWithIdComponent"
53 = {HashMap$Node@17231} "class" -> "org.apache.camel.component.beanclass.ClassComponent"
54 = {HashMap$Node@17232} "aws-s3-get-object-connector" -> "io.syndesis.s3.get.S3GetObjectConnectorComponent"
55 = {HashMap$Node@17233} "rest" -> "org.apache.camel.component.rest.RestComponent"
56 = {HashMap$Node@17234} "dataformat" -> "org.apache.camel.component.dataformat.DataFormatComponent"
57 = {HashMap$Node@17235} "salesforce-delete-sobject" -> "io.syndesis.connector.salesforce.SalesforceDeleteSObjectComponent"
58 = {HashMap$Node@17236} "aws-s3-polling-bucket-connector" -> "io.syndesis.s3.polling.S3PollingBucketConnectorComponent"
59 = {HashMap$Node@17237} "salesforce-get-sobject" -> "io.syndesis.connector.salesforce.SalesforceGetSObjectComponent"
60 = {HashMap$Node@17238} "activemq-publish" -> "io.syndesis.connector.jms.ActiveMQPublishComponent"
61 = {HashMap$Node@17239} "rest-api" -> "org.apache.camel.component.rest.RestApiComponent"
62 = {HashMap$Node@17240} "seda" -> "org.apache.camel.component.seda.SedaComponent"
63 = {HashMap$Node@17241} "xslt" -> "org.apache.camel.component.xslt.XsltComponent"
64 = {HashMap$Node@17242} "sql-stored" -> "org.apache.camel.component.sql.stored.SqlStoredComponent"
65 = {HashMap$Node@17243} "controlbus" -> "org.apache.camel.component.controlbus.ControlBusComponent"
66 = {HashMap$Node@17244} "dataset" -> "org.apache.camel.component.dataset.DataSetComponent"
67 = {HashMap$Node@17245} "properties" -> "org.apache.camel.component.properties.PropertiesComponent"
```

at this stage:

```
	  at org.apache.camel.catalog.CamelCatalogJSonSchemaResolver.getComponentJSonSchema(CamelCatalogJSonSchemaResolver.java:50)
	  at org.apache.camel.catalog.AbstractCamelCatalog.doAsEndpointUri(AbstractCamelCatalog.java:877)
	  at org.apache.camel.catalog.AbstractCamelCatalog.asEndpointUri(AbstractCamelCatalog.java:869)
	  at io.syndesis.connector.catalog.ConnectorCatalog.buildEndpointUri(ConnectorCatalog.java:201)
	  at io.syndesis.project.converter.visitor.EndpointStepVisitor.createEndpoint(EndpointStepVisitor.java:131)
	  at io.syndesis.project.converter.visitor.EndpointStepVisitor.createEndpoint(EndpointStepVisitor.java:127)
	  at io.syndesis.project.converter.visitor.EndpointStepVisitor.visit(EndpointStepVisitor.java:62)
	  at io.syndesis.project.converter.DefaultProjectGenerator.visitStep(DefaultProjectGenerator.java:352)
	  at io.syndesis.project.converter.DefaultProjectGenerator.generateFlow(DefaultProjectGenerator.java:339)
	  at io.syndesis.project.converter.DefaultProjectGenerator.lambda$generateAddProjectTarEntries$1(DefaultProjectGenerator.java:191)
	  at io.syndesis.project.converter.DefaultProjectGenerator$$Lambda$250.84074671.run(Unknown Source:-1)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
```

**Comment by KurtStam** [comment]
@paoloantinori the `sql` key would be the camel component. I don't see any of our database connectors in this list. Do you know how this list is populated?

**Comment by zregvart** [comment]
Wrong GAV so it silently isn't added?

**Comment by KurtStam** [comment]
@zregvart do we release the snapshots to maven central? The GAV is:
"camelConnectorGAV": "io.syndesis:sql-connector:@syndesis.version@",

**Comment by paoloantinori** [comment]
I can see in debug that that catalog is populated here:

```
io.syndesis.connector.catalog.ConnectorCatalog#prefetchConnectors
```
Looking for `/META-INF/camel/camel-meta.json` that lives at runtime here: `jar:file:/deployments/runtime.jar!/META-INF/camel/camel-meta.json`  

And that file, in my understanding is generated by `syndesis-build-helper-maven-plugin` invoked here: `syndesis/app/rest/runtime/pom.xml`

And I think, the problem is that only 

```
            <groupId>io.syndesis</groupId>
            <artifactId>sql-stored-connector</artifactId>
```
is listed, and it should also contain

```
            <groupId>io.syndesis</groupId>
            <artifactId>sql-connector</artifactId>
```


https://github.com/syndesisio/syndesis/blob/master/app/rest/runtime/pom.xml#L177-L182

**Comment by KurtStam** [comment]
@paoloantinori can you double check this fixes things, I added you as reviewer of the PR too.

**Comment by paoloantinori** [comment]
Let me fetch and deploy locally to save from any possible further issue.

**Comment by lburgazzoli** [comment]
btw, if the download fails, the MavenArtifactProvider fails silently:

https://github.com/apache/camel/blob/master/platforms/camel-catalog-maven/src/main/java/org/apache/camel/catalog/maven/DefaultMavenArtifactProvider.java#L108-L112

**Comment by KurtStam** [comment]
@lburgazzoli I opened https://github.com/syndesisio/syndesis/issues/751 for the issue you just brought up.

**Comment by paoloantinori** [comment]
It seems that being a `SNAPSHOT` artifact is still a blocking problem to use the connector:

```
myproject/paolo-1-build[sti-build]: [ERROR] Failed to execute goal on project project: Could not resolve dependencies for project io.syndesis.integrations:project:jar:0.1-SNAPSHOT: The following artifacts could not be resolved: io.syndesis:sql-connector:jar:1.2-SNAPSHOT, io.syndesis.integration-runtime:model:jar:1.2-SNAPSHOT, io.syndesis.integration-runtime:runtime:jar:1.2-SNAPSHOT: Could not find artifact io.syndesis:sql-connector:jar:1.2-SNAPSHOT in 01_maven_central (https://repo1.maven.org/maven2) -> [Help 1]
myproject/paolo-1-build[sti-build]: org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project project: Could not resolve dependencies for project io.syndesis.integrations:project:jar:0.1-SNAPSHOT: The following artifacts could not be resolved: io.syndesis:sql-connector:jar:1.2-SNAPSHOT, io.syndesis.integration-runtime:model:jar:1.2-SNAPSHOT, io.syndesis.integration-runtime:runtime:jar:1.2-SNAPSHOT: Could not find artifact io.syndesis:sql-connector:jar:1.2-SNAPSHOT in 01_maven_central (https://repo1.maven.org/maven2)
myproject/paolo-1-build[sti-build]: at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
myproject/paolo-1-build[sti-build]: at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
myproject/paolo-1-build[sti-build]: at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:257)
myproject/paolo-1-build[sti-build]: at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
myproject/paolo-1-build[sti-build]: at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
myproject/paolo-1-build[sti-build]: at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
myproject/paolo-1-build[sti-build]: at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
myproject/paolo-1-build[sti-build]: at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
myproject/paolo-1-build[sti-build]: at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
myproject/paolo-1-build[sti-build]: at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
myproject/paolo-1-build[sti-build]: at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
myproject/paolo-1-build[sti-build]: at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
myproject/paolo-1-build[sti-build]: at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
myproject/paolo-1-build[sti-build]: at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
myproject/paolo-1-build[sti-build]: at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
myproject/paolo-1-build[sti-build]: at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
myproject/paolo-1-build[sti-build]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
myproject/paolo-1-build[sti-build]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
myproject/paolo-1-build[sti-build]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
myproject/paolo-1-build[sti-build]: at java.lang.reflect.Method.invoke(Method.java:498)
myproject/paolo-1-build[sti-build]: at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
myproject/paolo-1-build[sti-build]: at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
myproject/paolo-1-build[sti-build]: at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
myproject/paolo-1-build[sti-build]: at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
myproject/paolo-1-build[sti-build]: Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project io.syndesis.integrations:project:jar:0.1-SNAPSHOT: The following artifacts could not be resolved: io.syndesis:sql-connector:jar:1.2-SNAPSHOT, io.syndesis.integration-runtime:model:jar:1.2-SNAPSHOT, io.syndesis.integration-runtime:runtime:jar:1.2-SNAPSHOT: Could not find artifact io.syndesis:sql-connector:jar:1.2-SNAPSHOT in 01_maven_central (https://repo1.maven.org/maven2)
myproject/paolo-1-build[sti-build]: at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
myproject/paolo-1-build[sti-build]: at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
myproject/paolo-1-build[sti-build]: ... 23 more
myproject/paolo-1-build[sti-build]: Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: io.syndesis:sql-connector:jar:1.2-SNAPSHOT, io.syndesis.integration-runtime:model:jar:1.2-SNAPSHOT, io.syndesis.integration-runtime:runtime:jar:1.2-SNAPSHOT: Could not find artifact io.syndesis:sql-connector:jar:1.2-SNAPSHOT in 01_maven_central (https://repo1.maven.org/maven2)
myproject/paolo-1-build[sti-build]: at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
myproject/paolo-1-build[sti-build]: at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
myproject/paolo-1-build[sti-build]: ... 24 more
myproject/paolo-1-build[sti-build]: Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: io.syndesis:sql-connector:jar:1.2-SNAPSHOT, io.syndesis.integration-runtime:model:jar:1.2-SNAPSHOT, io.syndesis.integration-runtime:runtime:jar:1.2-SNAPSHOT: Could not find artifact io.syndesis:sql-connector:jar:1.2-SNAPSHOT in 01_maven_central (https://repo1.maven.org/maven2)
myproject/paolo-1-build[sti-build]: at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
myproject/paolo-1-build[sti-build]: at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
myproject/paolo-1-build[sti-build]: at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
myproject/paolo-1-build[sti-build]: ... 25 more
myproject/paolo-1-build[sti-build]: Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.syndesis:sql-connector:jar:1.2-SNAPSHOT in 01_maven_central (https://repo1.maven.org/maven2)
myproject/paolo-1-build[sti-build]: at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
myproject/paolo-1-build[sti-build]: at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
myproject/paolo-1-build[sti-build]: at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
myproject/paolo-1-build[sti-build]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
myproject/paolo-1-build[sti-build]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
myproject/paolo-1-build[sti-build]: at java.lang.Thread.run(Thread.java:748)
myproject/paolo-1-build[sti-build]: [ERROR]
myproject/paolo-1-build[sti-build]: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
myproject/paolo-1-build[sti-build]: [ERROR]
myproject/paolo-1-build[sti-build]: [ERROR] For more information about the errors and possible solutions, please read the following articles:
myproject/paolo-1-build[sti-build]: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
myproject/paolo-1-build[sti-build]: Aborting due to error code 1 for Maven build
myproject/paolo-1-build[sti-build]: assemble failed with rc=1
```

**Comment by KurtStam** [comment]
@rhuss How are SNAPSHOTS supposed to work in the mono repo?

**Comment by rhuss** [comment]
Yes, when the s2i image is deployed properly which contains the snapshots.

So you should build the s2i image, too and update it in your installation.

**Comment by rhuss** [comment]
just call 'syndesis -m s2i --openshift --flash' and the S2I image, populated with the latest snapshot versions will be created.

**Comment by rhuss** [comment]
however the s2i image will contain only connectors which are also configured in deployment.json

https://github.com/syndesisio/syndesis/blob/9c51ce8ed5cf19e24c2be24747db7534ee2f6b95/app/rest/syndesis-builder-image-generator/src/main/java/io/syndesis/image/Application.java#L88

**Comment by paoloantinori** [comment]
Sorry but I cannot test this. I have not been able to find a way for the build image to find `io.syndesis:sql-connector:jar:1.2-SNAPSHOT` . @rhuss method doesn't work for me

**Comment by paoloantinori** [comment]
I might have done some progress. Now I have no longer an error reporting missing sql-connector artifact but the build pod stays in `paolo-1-build                 1/1	Running     0          11m` state.

```
myproject/syndesis-rest-2-vgjgh[syndesis-rest]: 2017-12-14 19:06:13.124  INFO [-,,,] 1 --- [pool-4-thread-1] i.s.c.integration.IntegrationController  : Integration -L0LOu1dtKOnBbjtz7ZG : Desired status "Activated" != current status "Pending" --> calling status change handler
myproject/syndesis-rest-2-vgjgh[syndesis-rest]: 2017-12-14 19:06:13.124  INFO [-,,,] 1 --- [pool-3-thread-1] i.s.c.integration.IntegrationController  : Integration -L0LOu1dtKOnBbjtz7ZG : Start processing integration with ActivateHandler
myproject/syndesis-rest-2-vgjgh[syndesis-rest]: 2017-12-14 19:06:13.217  INFO [-,,,] 1 --- [pool-3-thread-1] i.s.c.integration.online.BaseHandler     : Integration [paolo]: Build started: true, isRunning: false, Deployment ready: false
myproject/syndesis-rest-2-vgjgh[syndesis-rest]: 2017-12-14 19:06:13.218  INFO [-,,,] 1 --- [pool-3-thread-1] i.s.c.integration.online.BaseHandler     : Integration [paolo]: Steps performed so far: [build, deploy]
myproject/syndesis-rest-2-vgjgh[syndesis-rest]: 2017-12-14 19:06:13.239  INFO [-,,,] 1 --- [pool-3-thread-1] i.s.c.integration.online.BaseHandler     : Integration [paolo]: Skipped step build because already performed
myproject/syndesis-rest-2-vgjgh[syndesis-rest]: 2017-12-14 19:06:13.241  INFO [-,,,] 1 --- [pool-3-thread-1] i.s.c.integration.online.BaseHandler     : Integration [paolo]: Skipped step deploy because already performed
myproject/syndesis-rest-2-vgjgh[syndesis-rest]: 2017-12-14 19:06:13.269  INFO [-,,,] 1 --- [pool-3-thread-1] i.s.c.integration.online.BaseHandler     : Integration [paolo]: Build started: true, isRunning: false, Deployment ready: false
myproject/syndesis-rest-2-vgjgh[syndesis-rest]: 2017-12-14 19:06:13.270  INFO [-,,,] 1 --- [pool-3-thread-1] i.s.c.integration.online.BaseHandler     : Integration [paolo]: [PENDING] [[build, deploy]]
myproject/syndesis-rest-2-vgjgh[syndesis-rest]: 2017-12-14 19:06:13.272  INFO [-,,,] 1 --- [pool-3-thread-1] i.s.c.integration.IntegrationController  : Integration -L0LOu1dtKOnBbjtz7ZG : Setting status to Pending
```

**Comment by KurtStam** [comment]
It deploys ok for me now. Please reopen if this is still an issue.
