### ISSUE TITLE
Unable to re-generate operator

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#7247]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

When running:

```sh
$ operator-sdk version
$ operator-sdk version: "v0.11.0", commit: "39c65c36159a9c249e5f3c178205cc6e86c16f8d", go version: "go1.12.7 linux/amd64"
$ go version
$ go version go1.13.4 linux/amd64
$ GO111MODULE=on operator-sdk generate k8s
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [syndesis:[v1alpha1], ] 
F1127 11:13:27.326492  150370 deepcopy.go:885] Hit an unsupported type invalid type for invalid type, from github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1alpha1.Syndesis
goroutine 1 [running]:
k8s.io/klog.stacks(0xc0007e6800, 0xc000058360, 0xbf, 0x10f)
	pkg/mod/k8s.io/klog@v0.3.3/klog.go:855 +0xb1
k8s.io/klog.(*loggingT).output(0x3707c20, 0xc000000003, 0xc0005038f0, 0x3511554, 0xb, 0x375, 0x0)
	pkg/mod/k8s.io/klog@v0.3.3/klog.go:806 +0x2d9
k8s.io/klog.(*loggingT).printf(0x3707c20, 0x3, 0x1f45d95, 0x2a, 0xc00065ee80, 0x3, 0x3)
	pkg/mod/k8s.io/klog@v0.3.3/klog.go:705 +0x14e
k8s.io/klog.Fatalf(...)
	pkg/mod/k8s.io/klog@v0.3.3/klog.go:1256
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).doStruct(0xc0003b4d80, 0xc00025cfd0, 0xc000549860)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/examples/deepcopy-gen/generators/deepcopy.go:885 +0x7bf
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).generateFor(0xc0003b4d80, 0xc00025cfd0, 0xc000549860)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/examples/deepcopy-gen/generators/deepcopy.go:695 +0xc5
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).GenerateType(0xc0003b4d80, 0xc000383da0, 0xc00025cfd0, 0x22483e0, 0xc0006e81e0, 0x0, 0x0)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/examples/deepcopy-gen/generators/deepcopy.go:608 +0xe86
k8s.io/gengo/generator.(*Context).executeBody(0xc000383da0, 0x2244f80, 0xc0005507f0, 0x22c3a00, 0xc0003b4d80, 0x60, 0x10)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/generator/execute.go:304 +0x11d
k8s.io/gengo/generator.(*Context).ExecutePackage(0xc000383aa0, 0xc000260c60, 0x15, 0x229a1a0, 0xc0003b4b80, 0x0, 0x0)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/generator/execute.go:265 +0xbf7
k8s.io/gengo/generator.(*Context).ExecutePackages(0xc000383aa0, 0xc000260c60, 0x15, 0xc00022baf0, 0x1, 0x1, 0x0, 0xc000260cc0)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/generator/execute.go:51 +0xc5
k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc0005ee640, 0xc00065f808, 0x1ee7c15, 0x6, 0x1fecba0, 0xc000260c40, 0x1c)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/args/args.go:194 +0x2d7
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.deepcopyGen(0xc0004d6350, 0xe, 0xc0001cb770, 0x1, 0x1, 0x18, 0xc00065f9a8)
	/Users/haseeb/work/module-projects/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:95 +0x4d2
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.K8sCodegen.func1(0xc0004d6350, 0xe, 0xc0004d6350, 0xe)
	/Users/haseeb/work/module-projects/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:54 +0x50
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.generateWithHeaderFile(0xc0001f3f20, 0x0, 0x0)
	/Users/haseeb/work/module-projects/operator-sdk/cmd/operator-sdk/internal/genutil/genutil.go:46 +0x178
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.K8sCodegen(0xc00030b680, 0x0)
	/Users/haseeb/work/module-projects/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:55 +0x4c0
github.com/operator-framework/operator-sdk/cmd/operator-sdk/generate.k8sFunc(0xc00030b680, 0x372b820, 0x0, 0x0, 0x0, 0x0)
	/Users/haseeb/work/module-projects/operator-sdk/cmd/operator-sdk/generate/k8s.go:56 +0x156
github.com/spf13/cobra.(*Command).execute(0xc00030b680, 0x372b820, 0x0, 0x0, 0xc00030b680, 0x372b820)
	pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc000417180, 0x2249c20, 0xc00026f800, 0x0)
	pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/Users/haseeb/work/module-projects/operator-sdk/cmd/operator-sdk/main.go:85 +0x50f
```

**Comment by lgarciaaco** [comment]
@zregvart I can't reproduce this

```
$ operator-sdk version
operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.3 linux/amd64"
$ GO111MODULE=on operator-sdk generate k8s
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [syndesis:[v1alpha1], ] 
INFO[0004] Code-generation complete.                    
```

**Comment by zregvart** [comment]
Let me try with newer operator-sdk, are we bumping the operator-sdk version to 0.12.0 then? Will require a [newer go version](https://github.com/operator-framework/operator-sdk/releases/tag/v0.12.0) (1.13).

This looks quite fishy, not sure what's that about:

https://github.com/syndesisio/syndesis/blob/aeb4da759a7a53cc9a072513de50d5b094d61ab2/install/operator/go.mod#L16

**Comment by zregvart** [comment]
I've downloaded the new operator-sdk version, same issue on my end, should I nuke something?

```
$ go version
go version go1.13.4 linux/amd64
$ cd $HOME/go/src/github.com/syndesisio/syndesis/install/operator/
$ ~/Downloads/operator-sdk-v0.12.0-x86_64-linux-gnu version
operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.3 linux/amd64"
$ GO111MODULE=on ~/Downloads/operator-sdk-v0.12.0-x86_64-linux-gnu generate k8s
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [syndesis:[v1alpha1], ] 
F1203 14:04:37.027493  616924 deepcopy.go:885] Hit an unsupported type invalid type for invalid type, from github.com/syndesisio/syndesis/install/operator/pkg/apis/syndesis/v1alpha1.Syndesis
goroutine 1 [running]:
k8s.io/klog.stacks(0xc0007f2900, 0xc000064480, 0xbf, 0x10f)
	/home/joe/go/pkg/mod/k8s.io/klog@v0.3.3/klog.go:855 +0xb8
k8s.io/klog.(*loggingT).output(0x335c940, 0xc000000003, 0xc0005f8380, 0x3146640, 0xb, 0x375, 0x0)
	/home/joe/go/pkg/mod/k8s.io/klog@v0.3.3/klog.go:806 +0x351
k8s.io/klog.(*loggingT).printf(0x335c940, 0x3, 0x1ee9b04, 0x2a, 0xc00075aed8, 0x3, 0x3)
	/home/joe/go/pkg/mod/k8s.io/klog@v0.3.3/klog.go:705 +0x14b
k8s.io/klog.Fatalf(...)
	/home/joe/go/pkg/mod/k8s.io/klog@v0.3.3/klog.go:1256
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).doStruct(0xc0002e5600, 0xc000541b80, 0xc0001002d0)
	/home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/examples/deepcopy-gen/generators/deepcopy.go:885 +0x7bd
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).generateFor(0xc0002e5600, 0xc000541b80, 0xc0001002d0)
	/home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/examples/deepcopy-gen/generators/deepcopy.go:695 +0xc5
k8s.io/gengo/examples/deepcopy-gen/generators.(*genDeepCopy).GenerateType(0xc0002e5600, 0xc0005f8310, 0xc000541b80, 0x21b7320, 0xc0005ad120, 0x0, 0x0)
	/home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/examples/deepcopy-gen/generators/deepcopy.go:608 +0xe98
k8s.io/gengo/generator.(*Context).executeBody(0xc0005f8310, 0x21b42a0, 0xc0001661b0, 0x222f9c0, 0xc0002e5600, 0x70, 0xc00075b288)
	/home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/generator/execute.go:306 +0x11c
k8s.io/gengo/generator.(*Context).ExecutePackage(0xc0005f81c0, 0xc000558260, 0x15, 0x2216ba0, 0xc00072def0, 0x0, 0x0)
	/home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/generator/execute.go:267 +0xb25
k8s.io/gengo/generator.(*Context).ExecutePackages(0xc0005f81c0, 0xc000558260, 0x15, 0xc0004aa820, 0x1, 0x1, 0x0, 0x30)
	/home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/generator/execute.go:51 +0xbf
k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc000762000, 0xc00075b7b0, 0x1e886d7, 0x6, 0x1f94440, 0xc000558240, 0x1c)
	/home/joe/go/pkg/mod/k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f/args/args.go:207 +0x1eb
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.deepcopyGen(0xc0000e10e0, 0xe, 0xc00068c0b0, 0x1, 0x1, 0x0, 0xc0000e4040)
	/home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:95 +0x4d9
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.K8sCodegen.func1(0xc0000e10e0, 0xe, 0x0, 0x0)
	/home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:54 +0x50
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.generateWithHeaderFile(0xc00075bc00, 0x0, 0x0)
	/home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/genutil.go:46 +0x175
github.com/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil.K8sCodegen(0xc000638780, 0x0)
	/home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/internal/genutil/k8s.go:55 +0x48d
github.com/operator-framework/operator-sdk/cmd/operator-sdk/generate.k8sFunc(0xc000638780, 0x33841d8, 0x0, 0x0, 0x0, 0x0)
	/home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/generate/k8s.go:56 +0x64
github.com/spf13/cobra.(*Command).execute(0xc000638780, 0x33841d8, 0x0, 0x0, 0xc000638780, 0x33841d8)
	/home/joe/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000636000, 0x21b8d40, 0xc000721600, 0x0)
	/home/joe/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/joe/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/joe/projects/work/operator-framework/operator-sdk/cmd/operator-sdk/main.go:84 +0x584
```

**Comment by lgarciaaco** [comment]
> Let me try with newer operator-sdk, are we bumping the operator-sdk version to 0.12.0 then? Will require a [newer go version](https://github.com/operator-framework/operator-sdk/releases/tag/v0.12.0) (1.13).
> 
> This looks quite fishy, not sure what's that about:
> 
> https://github.com/syndesisio/syndesis/blob/aeb4da759a7a53cc9a072513de50d5b094d61ab2/install/operator/go.mod#L16

I tried that but unfortunately we can't :(. 

We have a chicken egg dependency problem.  `operator-sdk` 0.12.0 depends on `kubernetes 1.15.4`m but we can't upgrade because k8s.io/apimachinery in any version depends on `kubernetes 1.13`. So if you try https://github.com/syndesisio/syndesis/pull/7306 where I upgraded kubernetes to 1.16.3 you get:
```
[lgarciaa@lgarciaa operator]$ ./build.sh --operator-build go --image-build skip --souce-gen skip
======================================================
Building executable with go tooling
======================================================
generating sources
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [syndesis:[v1alpha1], ] 
INFO[0005] Code-generation complete.                    
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [syndesis:[v1alpha1], ] 
INFO[0005] Created deploy/crds/syndesis.io_syndeses_crd.yaml 
INFO[0005] Created deploy/crds/syndesis.io_syndeses_crd.yaml 
INFO[0005] Code-generation complete.                    
# sigs.k8s.io/controller-runtime/pkg/client/apiutil
../../../../../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.1.12/pkg/client/apiutil/apimachinery.go:69:29: undefined: serializer.DirectCodecFactory
pkg/generator/generator.go:2: running "go": exit status 2
```
Here is the upstream issue https://github.com/tektoncd/pipeline/issues/1561

I think we wait for this to be solved?

**Comment by lgarciaaco** [comment]
> I've downloaded the new operator-sdk version, same issue on my end, should I nuke something?
> 
I don't think so, but I also don't know what it could be.

@chirino does it sound familiar?

**Comment by claudio4j** [comment]
I was able to run on my environment.
```
$ operator-sdk version
operator-sdk version: "v0.15.2", commit: "ffaf278993c8fcb00c6f527c9f20091eb8dd3352", go version: "go1.13.3 linux/amd64"

$ go version
go version go1.14.2 linux/amd64

$ GO111MODULE=on operator-sdk generate k8s
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [syndesis:[v1alpha1 v1beta1], ] 
INFO[0010] Code-generation complete. 
```

Is this an issue yet ?
