### ISSUE TITLE
Nightly integration tests failing

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#7301]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Looks like the nightly integration tests [are failing](https://circleci.com/gh/syndesisio/syndesis/191585).

```
waitForIntegrationToBeHealthy - io.syndesis.test.itest.gmail.WebhookToGMail_IT

com.consol.citrus.exceptions.TestCaseFailedException: Failed to check Http condition - request url 'http://localhost:32816/health' did not return expected status '200'
	at io.syndesis.test.itest.gmail.WebhookToGMail_IT.waitForIntegrationToBeHealthy(WebhookToGMail_IT.java:51)
Caused by: com.consol.citrus.exceptions.CitrusRuntimeException: Failed to check Http condition - request url 'http://localhost:32816/health' did not return expected status '200'
	at io.syndesis.test.itest.gmail.WebhookToGMail_IT.waitForIntegrationToBeHealthy(WebhookToGMail_IT.java:51)
```

And

```
waitForIntegrationToBeHealthy - io.syndesis.test.itest.googlecalendar.WebhookToGoogleCalendar_IT

com.consol.citrus.exceptions.TestCaseFailedException: Failed to check Http condition - request url 'http://localhost:32799/health' did not return expected status '200'
	at io.syndesis.test.itest.googlecalendar.WebhookToGoogleCalendar_IT.waitForIntegrationToBeHealthy(WebhookToGoogleCalendar_IT.java:52)
Caused by: com.consol.citrus.exceptions.CitrusRuntimeException: Failed to check Http condition - request url 'http://localhost:32799/health' did not return expected status '200'
	at io.syndesis.test.itest.googlecalendar.WebhookToGoogleCalendar_IT.waitForIntegrationToBeHealthy(WebhookToGoogleCalendar_IT.java:52)
```

They are passing locally (on my machine :smirk_cat:) and [the logs](https://191585-105563335-gh.circle-artifacts.com/0/home/circleci/logs/test_log.txt) don't contain any errors. It might be an issue in exporting port.

**Comment by zregvart** [comment]
I think this was fixed.
