### ISSUE TITLE
Rest can't create BC after kubernetes-client upgrade

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#732]
Dragons have been deployed upon us.

@paoloantinori you might want to look at this one. Caused by https://github.com/syndesisio/syndesis/pull/711.

```

2017-12-13 07:48:08.692 ERROR [-,,,] 1 --- [pool-3-thread-1] i.s.c.integration.IntegrationController  : Error while processing integration status for integration -L0Dq4Dr3bq905vqX1_Y
--
  |  
  | io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://openshift.default.svc/apis/build.openshift.io/v1/namespaces/syndesis/builds?labelSelector=openshift.io/build-config.name%3Ddb-int&fieldSelector=status%3DRunning. Message: No field label conversion function found for version: build.openshift.io/v1. Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=No field label conversion function found for version: build.openshift.io/v1, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470) ~[kubernetes-client-3.1.1.jar!/:na]
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409) ~[kubernetes-client-3.1.1.jar!/:na]
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379) ~[kubernetes-client-3.1.1.jar!/:na]
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343) ~[kubernetes-client-3.1.1.jar!/:na]
  | at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327) ~[kubernetes-client-3.1.1.jar!/:na]
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:605) ~[kubernetes-client-3.1.1.jar!/:na]
  | at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70) ~[kubernetes-client-3.1.1.jar!/:na]
  | at io.syndesis.openshift.OpenShiftServiceImpl.isBuildStarted(OpenShiftServiceImpl.java:143) ~[openshift-1.2-SNAPSHOT.jar!/:1.2-SNAPSHOT]
  | at io.syndesis.controllers.integration.online.ActivateHandler.isBuildStarted(ActivateHandler.java:151) ~[controllers-1.2-SNAPSHOT.jar!/:1.2-SNAPSHOT]
  | at io.syndesis.controllers.integration.online.ActivateHandler.execute(ActivateHandler.java:93) ~[controllers-1.2-SNAPSHOT.jar!/:1.2-SNAPSHOT]
  | at io.syndesis.controllers.integration.IntegrationController.lambda$callStatusChangeHandler$10(IntegrationController.java:175) ~[controllers-1.2-SNAPSHOT.jar!/:1.2-SNAPSHOT]
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
  | at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]


```

**Comment by paoloantinori** [comment]
Sure! I'm checking it!

**Comment by paoloantinori** [comment]
Hi @dsimansk  what's the source of that portion of log? Do the error locally?

**Comment by dsimansk** [comment]
@paoloantinori just create any integration, e.g. Db->Db and publish it. `ActivationHandler` is checking with `isBuildStarted` [method](https://github.com/rhuss/syndesis/blob/9c51ce8ed5cf19e24c2be24747db7534ee2f6b95/app/rest/openshift/src/main/java/io/syndesis/openshift/OpenShiftServiceImpl.java#L140-L143).

But you should get in touch with @iocanel that already started to investigate also.

**Comment by paoloantinori** [comment]
So, a verified way to fix the problem is to use OpenShift 3.7.

3.6.1 should be good enough, but it doesn't work on Minishift due to https://github.com/minishift/minishift/issues/1841

cc @rhuss

**Comment by jimmidyson** [comment]
Any news on this? Is this still causing issues?

**Comment by paoloantinori** [comment]
I'm currently working on 3.7.0 support.

**Comment by jimmidyson** [comment]
So this isn't an issue with our current deployment target though right so doesn't affect TP3? Can this be deferred to TP4?

**Comment by dsimansk** [comment]
@jimmidyson imho we should close it to prevent any confusion. Version upgrade that caused this issue was reverted. There's no need to keep it for TP4 I guess.

**Comment by jimmidyson** [comment]
Agreed.
