### ISSUE TITLE
The Integration generated by Unit Test Case can not start

### ISSUE THREAD

**Issue by ashenp** [syndesisio/syndesis#7384]
##  The Integration generated by Unit Test Case can not start
<pre><code>
[×] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[√] Bug report  
[x] Documentation issue or request
</code></pre>

## Description
I run the Junit test function:
testGenerateApplicationWithRestDSL in ProjectGeneratorTest
and get a spring boot application structure in my desk
but when I run the Application I get an error saying:

```
org.apache.camel.RuntimeCamelException: org.apache.camel.FailedToCreateRouteException: Failed to create route route1: Route(route1)[[From[rest:get:/openapi.json?routeId=route1&de... because of Failed to resolve endpoint: servlet:///openapi.json?headerFilterStrategy=syndesisHeaderStrategy&httpMethodRestrict=GET due to: No bean could be found in the registry for: syndesisHeaderStrategy of type: org.apache.camel.spi.HeaderFilterStrategy
	at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1830) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.spring.SpringCamelContext.start(SpringCamelContext.java:136) ~[camel-spring-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.spring.SpringCamelContext.onApplicationEvent(SpringCamelContext.java:174) ~[camel-spring-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:399) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration.createChildManagementContext(EndpointWebMvcAutoConfiguration.java:193) ~[spring-boot-actuator-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration.afterSingletonsInstantiated(EndpointWebMvcAutoConfiguration.java:156) ~[spring-boot-actuator-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:781) ~[spring-beans-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.19.RELEASE.jar:4.3.19.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.16.RELEASE.jar:1.5.16.RELEASE]
	at io.syndesis.example.Application.main(Application.java:13) [classes/:na]
Caused by: org.apache.camel.FailedToCreateRouteException: Failed to create route route1: Route(route1)[[From[rest:get:/openapi.json?routeId=route1&de... because of Failed to resolve endpoint: servlet:///openapi.json?headerFilterStrategy=syndesisHeaderStrategy&httpMethodRestrict=GET due to: No bean could be found in the registry for: syndesisHeaderStrategy of type: org.apache.camel.spi.HeaderFilterStrategy
	at org.apache.camel.impl.RouteService.warmUp(RouteService.java:147) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.DefaultCamelContext.doWarmUpRoutes(DefaultCamelContext.java:3947) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.DefaultCamelContext.safelyStartRouteServices(DefaultCamelContext.java:3854) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRoutes(DefaultCamelContext.java:3640) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3492) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:209) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3251) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3247) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3270) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3247) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:3163) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.spring.SpringCamelContext.start(SpringCamelContext.java:133) ~[camel-spring-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	... 23 common frames omitted
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: servlet:///openapi.json?headerFilterStrategy=syndesisHeaderStrategy&httpMethodRestrict=GET due to: No bean could be found in the registry for: syndesisHeaderStrategy of type: org.apache.camel.spi.HeaderFilterStrategy
	at org.apache.camel.impl.DefaultCamelContext.getEndpoint(DefaultCamelContext.java:758) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.DefaultCamelContext.getEndpoint(DefaultCamelContext.java:771) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.component.servlet.ServletComponent.doCreateConsumer(ServletComponent.java:296) ~[camel-servlet-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.component.servlet.ServletComponent.createConsumer(ServletComponent.java:228) ~[camel-servlet-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.component.rest.RestEndpoint.createConsumer(RestEndpoint.java:517) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.EventDrivenConsumerRoute.addServices(EventDrivenConsumerRoute.java:69) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.DefaultRoute.onStartingServices(DefaultRoute.java:103) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.RouteService.doWarmUp(RouteService.java:172) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.RouteService.warmUp(RouteService.java:145) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	... 35 common frames omitted
Caused by: org.apache.camel.NoSuchBeanException: No bean could be found in the registry for: syndesisHeaderStrategy of type: org.apache.camel.spi.HeaderFilterStrategy
	at org.apache.camel.util.CamelContextHelper.mandatoryLookupAndConvert(CamelContextHelper.java:201) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.util.EndpointHelper.resolveReferenceParameter(EndpointHelper.java:324) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.util.EndpointHelper.resolveReferenceParameter(EndpointHelper.java:306) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.DefaultComponent.resolveAndRemoveReferenceParameter(DefaultComponent.java:429) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.DefaultComponent.resolveAndRemoveReferenceParameter(DefaultComponent.java:408) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.component.servlet.ServletComponent.createEndpoint(ServletComponent.java:69) ~[camel-servlet-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.DefaultComponent.createEndpoint(DefaultComponent.java:130) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	at org.apache.camel.impl.DefaultCamelContext.getEndpoint(DefaultCamelContext.java:711) ~[camel-core-2.21.0.fuse-750029.jar:2.21.0.fuse-750029]
	... 43 common frames omitted

```

Is it a bug or I just did the wrong way?
Please help my with this issue, thanks very much

**Comment by zregvart** [comment]
I can see that in one of the recent builds [on CircleCI](https://app.circleci.com/jobs/github/syndesisio/syndesis/200268/parallel-runs/0/steps/0-104) that test was run without issues:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.syndesis.integration.project.generator.ProjectGeneratorHelperTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.352 s - in io.syndesis.integration.project.generator.ProjectGeneratorHelperTest
[INFO] Running io.syndesis.integration.project.generator.ProjectGeneratorTest
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.938 s - in io.syndesis.integration.project.generator.ProjectGeneratorTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0
```

Should be defined via this (in Spring Boot runtime):

https://github.com/syndesisio/syndesis/blob/d8ca3296aa54a712b1cd68cbba32637ebc796a99/app/integration/runtime-springboot/src/main/java/io/syndesis/integration/runtime/sb/SyndesisHttpConfiguration.java#L86-L90

**Comment by ashenp** [comment]
Yes, I can run all tests perfectly too.
I mean I guess the  in the test function finally generates a spring boot application strucrure and I found it in my desk.
But when I opened the directory and run the application I got this error message, the generated application can not run successfully.

**Comment by zregvart** [comment]
I guess the test wasn't built with that in mind, the test AFAIK doesn't run the generated application, just checks that there are bits in place. And adding in that `HeaderFilterStrategy` is conditional on having one of the HTTP-related connectors as dependencies, so I guess the generated project doesn't have those.

**Comment by ashenp** [comment]
Alright, So the purpose of the test is just to verify whether the files is right without caring whether the application could run?
But I find that  in the default template file "RestRouteConfiguration.java.mustache" for generating new project, the syndesisHeaderStrategy is setted to the rest endpointProperty by default. Mapping the "/" path.

**Comment by zregvart** [comment]
> Alright, So the purpose of the test is just to verify whether the files is right without caring whether the application could run?

Yeah, I think the trade-off in running the generated integration project would take too long to run. And we have a number of tests in the [integration test suite](https://github.com/syndesisio/syndesis/tree/175355f1a201e170e6a9ccbb64c16f93eaad5c73/app/test/integration-test) that already check if the generated integration project can be run.

> But I find that in the default template file "RestRouteConfiguration.java.mustache" for generating new project, the syndesisHeaderStrategy is setted to the rest endpointProperty by default. Mapping the "/" path.

Not all integration projects include the `RestRouteConfiguration.java` only those that pass these conditions:

https://github.com/syndesisio/syndesis/blob/7ed2d49a39305fb7ecc77215d2a9a9d6d726d6a7/app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java#L364-L379

And it's the same set of circumstances that leads to the inclusion of the `syndesisHeaderStrategy` bean.

**Comment by zregvart** [comment]
I think this is now resolved (explained). @ashenp feel free to reopen if you think it's not.

**Comment by ashenp** [comment]
Yes, Thank you for your help and patience :)
