### ISSUE TITLE
Failing to run the latest images

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#7556]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

For example when trying to run the meta image:

```
docker run -it --rm docker.io/syndesis/syndesis-meta:latest
Unable to find image 'syndesis/syndesis-meta:latest' locally
latest: Pulling from syndesis/syndesis-meta
ac9208207ada: Pull complete 
1e29086cad24: Pull complete 
76dcefade05b: Pull complete 
543dfa680296: Pull complete 
38c5929163cd: Pull complete 
fa6b7b77c257: Pull complete 
128401db1475: Pull complete 
17f76aceb40a: Pull complete 
d0e3405f2c1f: Pull complete 
fecf74506960: Pull complete 
Digest: sha256:790de0f6b1604640d95253e2e1dea8da91fe7f062cb18054edb2ec2fe92f29d0
Status: Downloaded newer image for syndesis/syndesis-meta:latest
No extensions found
No extensions found
exec java -javaagent:/opt/agent-bond/agent-bond.jar=jolokia{{host=0.0.0.0}},jmx_exporter{{9779:/opt/agent-bond/jmx_exporter_config.yml}} -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/meta-2.0-SNAPSHOT.jar
I> No access restrictor found, access to any MBean is allowed
Jolokia: Agent started with URL http://172.17.0.2:8778/jolokia/
      _______.                 _               _
    /       |                 | |             (_)
   |   (----`_   _  ____    _ | |  ____   ___  _   ___
    \   \   | | | ||  _ \  / || | / _  ) /___)| | /___)
.----)   |  | |_| || | | |( (_| |( (/ / |___ || ||___ |
|_______/    \__  ||_| |_| \____| \____)(___/ |_|(___/
============ (____/ ===================================
:: Meta :: v2.0-SNAPSHOT


2020-01-13 11:32:51.229  INFO 1 --- [           main] io.syndesis.connector.meta.Application   : Starting Application v2.0-SNAPSHOT on f912908a61b0 with PID 1 (/deployments/meta-2.0-SNAPSHOT.jar started by jboss in /deployments)
2020-01-13 11:32:51.234  INFO 1 --- [           main] io.syndesis.connector.meta.Application   : No active profile set, falling back to default profiles: default
2020-01-13 11:32:53.020  INFO 1 --- [           main] j.r.s.ResteasyEmbeddedServletInitializer : Finding JAX-RS Application classes
2020-01-13 11:32:53.022  INFO 1 --- [           main] j.r.s.ResteasyEmbeddedServletInitializer : Property resteasy.jaxrs.app.registration has not been set, JAX-RS Application classes registration is being set to AUTO
2020-01-13 11:32:53.024  INFO 1 --- [           main] j.r.s.ResteasyEmbeddedServletInitializer : Searching for JAX-RS Application Spring beans
2020-01-13 11:32:53.057  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'v1' defined in URL [jar:file:/deployments/meta-2.0-SNAPSHOT.jar!/BOOT-INF/classes!/io/syndesis/connector/meta/v1/V1.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.syndesis.connector.meta.v1.V1]: Constructor threw exception; nested exception is java.lang.IllegalStateException: zip file closed
2020-01-13 11:32:53.077  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-01-13 11:32:53.085 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'v1' defined in URL [jar:file:/deployments/meta-2.0-SNAPSHOT.jar!/BOOT-INF/classes!/io/syndesis/connector/meta/v1/V1.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.syndesis.connector.meta.v1.V1]: Constructor threw exception; nested exception is java.lang.IllegalStateException: zip file closed
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1303) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1197) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:606) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.jboss.resteasy.springboot.ResteasyEmbeddedServletInitializer.findJaxrsApplicationBeans(ResteasyEmbeddedServletInitializer.java:140) ~[resteasy-spring-boot-starter-2.0.1.Final.jar!/:2.0.1.Final]
	at org.jboss.resteasy.springboot.ResteasyEmbeddedServletInitializer.findJaxrsApplications(ResteasyEmbeddedServletInitializer.java:83) ~[resteasy-spring-boot-starter-2.0.1.Final.jar!/:2.0.1.Final]
	at org.jboss.resteasy.springboot.ResteasyEmbeddedServletInitializer.postProcessBeanFactory(ResteasyEmbeddedServletInitializer.java:249) ~[resteasy-spring-boot-starter-2.0.1.Final.jar!/:2.0.1.Final]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:286) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:181) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at io.syndesis.connector.meta.Application.main(Application.java:42) [classes!/:2.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47) [meta-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:86) [meta-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [meta-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:577) [meta-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.syndesis.connector.meta.v1.V1]: Constructor threw exception; nested exception is java.lang.IllegalStateException: zip file closed
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:184) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1295) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	... 30 common frames omitted
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[na:1.8.0_201]
	at java.util.zip.ZipFile.access$200(ZipFile.java:60) ~[na:1.8.0_201]
	at java.util.zip.ZipFile$ZipEntryIterator.<init>(ZipFile.java:499) ~[na:1.8.0_201]
	at java.util.zip.ZipFile.entries(ZipFile.java:552) ~[na:1.8.0_201]
	at java.util.jar.JarFile.access$001(JarFile.java:71) ~[na:1.8.0_201]
	at java.util.jar.JarFile$JarEntryIterator.<init>(JarFile.java:250) ~[na:1.8.0_201]
	at java.util.jar.JarFile$JarEntryIterator.<init>(JarFile.java:247) ~[na:1.8.0_201]
	at java.util.jar.JarFile.stream(JarFile.java:279) ~[na:1.8.0_201]
	at org.reflections.vfs.ZipDir.lambda$getFiles$2(ZipDir.java:21) ~[reflections-0.9.12.jar!/:na]
	at org.reflections.Reflections.scan(Reflections.java:260) ~[reflections-0.9.12.jar!/:na]
	at org.reflections.Reflections.scan(Reflections.java:216) ~[reflections-0.9.12.jar!/:na]
	at org.reflections.Reflections.<init>(Reflections.java:137) ~[reflections-0.9.12.jar!/:na]
	at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:288) ~[swagger-jaxrs-1.6.0.jar!/:1.6.0]
	at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:250) ~[swagger-jaxrs-1.6.0.jar!/:1.6.0]
	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:231) ~[swagger-jaxrs-1.6.0.jar!/:1.6.0]
	at io.syndesis.connector.meta.v1.V1.<init>(V1.java:39) ~[classes!/:2.0-SNAPSHOT]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_201]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	... 32 common frames omitted
```

**Comment by zregvart** [comment]
One solution that I've found is to upgrade swagger-core to latest (2.1.1) for this I've created [a pull request](https://github.com/atlasmap/atlasmap/pull/1672) in Atlasmap, as otherwise we would end up with a dependency issue in Syndesis due to different versions of swagger-core in Syndesis vs Atlasmap.

In the interim I'm trying to find a quick fix/workaround for this that doesn't involve upgrading the swagger-core.

**Comment by zregvart** [comment]
Workaround is in effect, we're missing the swagger-core upgrade.

**Comment by claudio4j** [comment]
Can this be closed ? `docker run -it --rm docker.io/syndesis/syndesis-meta:latest` runs with no issues and there is no report of latest images from dockerhub failing to run.
