### ISSUE TITLE
IndexOutOfBoundException when trying to save Dat Virt ddl request

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis#7832]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Server error reported in UI when clicking on "Save" of the datavirtualization using master.
in syndesis-dv pod, there is this stack:
```

09:58:28.138 [http-nio-8080-exec-2] INFO  o.teiid.RUNTIME.VDBLifeCycleListener - TEIID40003 VDB -mydatavirtvdb.1 is set to ACTIVE
--
  | 09:59:23.473 [http-nio-8080-exec-5] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/dv] threw exception [Request processing failed; nested exception is java.lang.IndexOutOfBoundsException: Index: 2, Size: 2] with root cause
  | java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
  | at java.util.ArrayList.rangeCheck(ArrayList.java:657)
  | at java.util.ArrayList.get(ArrayList.java:433)
  | at org.teiid.query.metadata.MetadataValidator.determineDependencies(MetadataValidator.java:867)
  | at org.teiid.query.metadata.MetadataValidator.determineDependencies(MetadataValidator.java:811)
  | at org.teiid.query.metadata.MetadataValidator.validate(MetadataValidator.java:718)
  | at io.syndesis.dv.metadata.internal.DefaultMetadataInstance.validate(DefaultMetadataInstance.java:556)
  | at io.syndesis.dv.metadata.internal.DefaultMetadataInstance$TeiidVdbImpl.validate(DefaultMetadataInstance.java:179)
  | at io.syndesis.dv.server.endpoint.EditorService.validateViewDefinition(EditorService.java:172)
  | at io.syndesis.dv.server.endpoint.EditorService.upsertViewDefinition(EditorService.java:128)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
  | at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
  | at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
  | at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
  | at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
  | at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
  | at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
  | at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
  | at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
  | at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:919)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:663)
  | at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at io.opentracing.contrib.web.servlet.filter.TracingFilter.doFilter(TracingFilter.java:174)
  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
  | at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
  | at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
  | at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
  | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
  | at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
  | at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
  | at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
  | at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
  | at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  | at java.lang.Thread.run(Thread.java:748)

```

![Screenshot from 2020-02-06 11-02-19](https://user-images.githubusercontent.com/1105127/73926613-2dfa5780-48d0-11ea-83cf-c1d38ae89b5f.png)

**Comment by apupier** [comment]
it comes from an invalid request:
```
CREATE VIEW myview (
  first_name, last_name, company, lead_source, create_date
  /*,id, wine, price, "year", gws, ci, nbj, productcode, pricebookentryid*/
) AS 
  SELECT 
    t1.first_name, t1.last_name, t1.company
    /*,t2.id, t2.wine, t2.price, t2."year", t2.gws, t2.ci, t2.nbj, t2.productcode, t2.pricebookentryid*/
  FROM 
    PostgresDB.contact AS t1
    /*,*/
```
ther eis not the same number of elements in the view and select list

**Comment by shawkins** [comment]
Captured upstream as https://issues.redhat.com/browse/TEIID-5901

**Comment by shawkins** [comment]
Resolved upstream.
