### ISSUE TITLE
Invoke SQL on start position throws mapping error

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#791]
When I try simple SQL integration, there is a mapping exception thrown. The same integration works fine with `Periodic Invoke SQL`.

Cc @KurtStam 

```
---
flows:
- steps:
  - kind: endpoint
    uri: sql-connector:SELECT * FROM CONTACT
  - kind: endpoint
    uri: atlas:mapping-step-2.json
  - kind: endpoint
    uri: sql-stored-connector:add_lead(VARCHAR ${body[first_and_last_name]}, VARCHAR ${body[company]}, VARCHAR ${body[phone]}, VARCHAR ${body[email]}, VARCHAR ${body[lead_source]}, VARCHAR ${body[lead_status]}, VARCHAR ${body[rating]})

```

```
017-12-15 11:02:13.870 ERROR 1 --- [0FROM%20CONTACT] o.a.camel.processor.DefaultErrorHandler  : Failed delivery for (MessageId: ID-db-to-db-2-b62q7-1513335506727-0-848 on ExchangeId: ID-db-to-db-2-b62q7-1513335506727-0-847). Exhausted after delivery attempt: 1 caught: io.atlasmap.api.AtlasException: Incompatible Source Document '{first_name=Joe, last_name=Jackson, company=Red Hat, lead_source=db, create_date=2017-12-13}'

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[flow1             ] [flow1             ] [sql-sql-connector-component://SELECT%20*%20FROM%20CONTACT                     ] [         1]
[flow1             ] [to1               ] [atlas:mapping-step-2.json                                                     ] [         0]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------

io.atlasmap.api.AtlasException: Incompatible Source Document '{first_name=Joe, last_name=Jackson, company=Red Hat, lead_source=db, create_date=2017-12-13}'
	at io.atlasmap.json.module.JsonModule.processPreSourceExecution(JsonModule.java:81) ~[atlas-json-module-1.32.1.jar!/:1.32.1]
	at io.atlasmap.core.DefaultAtlasContext.process(DefaultAtlasContext.java:235) ~[atlas-core-1.32.1.jar!/:1.32.1]
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:222) ~[camel-atlasmap-1.32.1.jar!/:na]
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.sql.SqlConsumer.processBatch(SqlConsumer.java:233) [camel-sql-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.sql.SqlConsumer$1.doInPreparedStatement(SqlConsumer.java:153) [camel-sql-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.sql.SqlConsumer$1.doInPreparedStatement(SqlConsumer.java:112) [camel-sql-2.20.1.jar!/:2.20.1]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633) [spring-jdbc-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:662) [spring-jdbc-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.apache.camel.component.sql.SqlConsumer.poll(SqlConsumer.java:168) [camel-sql-2.20.1.jar!/:2.20.1]
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101) [camel-core-2.20.1.jar!/:2.20.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_141]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_141]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_141]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_141]
```

**Comment by KurtStam** [comment]
@dsimansk You should not be able to pick the sql-connector as a start connection, you should only have the option to pick the periodic one at the start. I'm going to close this one as a duplicate/result of https://github.com/syndesisio/syndesis/issues/253
