### ISSUE TITLE
Integration fails to start: prometheus config cannot be found

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#8034]
```
Starting the Java application using /opt/run-java/run-java.sh ...
exec java -javaagent:/opt/jolokia/jolokia.jar=config=/opt/jolokia/etc/jolokia.properties -javaagent:/opt/prometheus/jmx_prometheus_javaagent.jar=9779:/tmp/src/prometheus-config.yml -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/project-0.1-SNAPSHOT.jar
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.io.FileNotFoundException: /tmp/src/prometheus-config.yml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<init>(JmxCollector.java:74)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:47)
	... 6 more
FATAL ERROR in native method: processing of -javaagent failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc35d30aa47, pid=1, tid=0x00007fc35e0fb700
#
# JRE version: OpenJDK Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x37a47]  abort+0x297
#
# Core dump written. Default location: /deployments/core or core.1
#

```

Import the Task-API_export.zip (https://github.com/syndesisio/syndesis-quickstarts/raw/master/api-provider/TaskAPI-export.zip) and edit and start it.

**Comment by zregvart** [comment]
Seems to relate to #4867.

That file should be added here:

https://github.com/syndesisio/syndesis/blob/96cd2c58d9dd75e53bf76a8617565c2c93ab115a/app/integration/project-generator/src/main/java/io/syndesis/integration/project/generator/ProjectGenerator.java#L301

**Comment by KurtStam** [comment]
Turn out this is caused by a missing class due to the following exclusion:
https://github.com/syndesisio/syndesis/blob/master/app/server/controller/pom.xml#L70-L76
There really should be a an ERROR in the logs at least. This is related to
https://issues.redhat.com/browse/ENTESB-13085

I will fix and add an integration test
