### ISSUE TITLE
NPE at save of new API Client Connector

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#8038]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

Using this OpenAPI specification:

https://api.apis.guru/v2/specs/googleapis.com/dfareporting/v3.3/openapi.json

to create an API Client Connector and clicking Save leads to a NullPointerException in the syndesis-server:

```
java.lang.NullPointerException: null
	at io.syndesis.server.api.generator.openapi.OpenApiParameterGenerator.createPropertyFromParameter(OpenApiParameterGenerator.java:86) ~[server-api-generator-2.0-SNAPSHOT.jar!/:2.0-SNAPSHOT]
	at io.syndesis.server.api.generator.openapi.v3.Oas30ParameterGenerator.lambda$createConfigurationProperties$1(Oas30ParameterGenerator.java:49) ~[server-api-generator-2.0-SNAPSHOT.jar!/:2.0-SNAPSHOT]
	at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_181]
	at io.syndesis.server.api.generator.openapi.v3.Oas30ParameterGenerator.lambda$createConfigurationProperties$2(Oas30ParameterGenerator.java:49) ~[server-api-generator-2.0-SNAPSHOT.jar!/:2.0-SNAPSHOT]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_181]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_181]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_181]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_181]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_181]
	at io.syndesis.server.api.generator.openapi.v3.Oas30ParameterGenerator.createConfigurationProperties(Oas30ParameterGenerator.java:47) ~[server-api-generator-2.0-SNAPSHOT.jar!/:2.0-SNAPSHOT]
	at io.syndesis.server.api.generator.openapi.v3.Oas30ParameterGenerator.createConfigurationProperties(Oas30ParameterGenerator.java:33) ~[server-api-generator-2.0-SNAPSHOT.jar!/:2.0-SNAPSHOT]
	at io.syndesis.server.api.generator.openapi.OpenApiParameterGenerator.addGlobalParameters(OpenApiParameterGenerator.java:45) ~[server-api-generator-2.0-SNAPSHOT.jar!/:2.0-SNAPSHOT]
	at io.syndesis.server.api.generator.openapi.OpenApiConnectorGenerator.addGlobalParameters(OpenApiConnectorGenerator.java:318) ~[server-api-generator-2.0-SNAPSHOT.jar!/:2.0-SNAPSHOT]
	at io.syndesis.server.api.generator.openapi.OpenApiConnectorGenerator.configureConnector(OpenApiConnectorGenerator.java:217) ~[server-api-generator-2.0-SNAPSHOT.jar!/:2.0-SNAPSHOT]
	at io.syndesis.server.api.generator.openapi.OpenApiConnectorGenerator.generate(OpenApiConnectorGenerator.java:92) ~[server-api-generator-2.0-SNAPSHOT.jar!/:2.0-SNAPSHOT]
	at io.syndesis.server.endpoint.v1.handler.connection.CustomConnectorHandler.lambda$create$1(CustomConnectorHandler.java:94) ~[server-endpoint-2.0-SNAPSHOT.jar!/:2.0-SNAPSHOT]
	at io.syndesis.server.endpoint.v1.handler.connection.BaseConnectorGeneratorHandler.withGeneratorAndTemplate(BaseConnectorGeneratorHandler.java:49) ~[server-endpoint-2.0-SNAPSHOT.jar!/:2.0-SNAPSHOT]
	at io.syndesis.server.endpoint.v1.handler.connection.CustomConnectorHandler.create(CustomConnectorHandler.java:93) ~[server-endpoint-2.0-SNAPSHOT.jar!/:2.0-SNAPSHOT]
```

This is the request:

```http
POST /api/v1/connectors/custom HTTP/1.1
Accept: application/json,text/plain,*/*
Content-Type: multipart/form-data; boundary=---------------------------9473194471271227221609302841
```

And the response:
```http
HTTP/1.1 500 Internal Server Error
Cache-Control: no-cache, no-store, max-age=0, must-revalidate, proxy-revalidate, s-maxage=0
Content-Length: 133
Content-Type: application/json
Date: Thu, 05 Mar 2020 09:45:41 GMT
Gap-Auth: zregvart@cluster.local
Gap-Upstream-Address: syndesis-server
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Syndesis-Xsrf-Token: awesome
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block

{"errorCode":500,"userMsg":"Please contact the administrator and file a bug report","developerMsg":"Internal Server Exception. null"}
```

**Comment by zregvart** [comment]
Seems that we're relying on the Parameter object having the [`required` field](http://spec.openapis.org/oas/v3.0.3#fixed-fields-9) present. The only situation where it must be specified is for the path parameters. We can default to `false` if it's not present.

**Comment by zregvart** [comment]
As a workaround setting the `required` to `false` in the OpenAPI document should help.
