### ISSUE TITLE
Cannot build the ReactUI

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis#8150]
The dailybuild  on March 25 fails to build the UI React:

[INFO] Server :: Builder :: Image Generator ............... SUCCESS [  9.996 s] 
[INFO] S2I ................................................ SUCCESS [ 42.997 s] 
[INFO] Meta ............................................... SUCCESS [ 23.636 s] 
[INFO] UI React ........................................... FAILURE [20:33 min]

**Comment by KurtStam** [comment]
March 28 adds a bit more detail:

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.1:yarn (yarn-test) on project ui-react: Failed to run task: 'yarn test' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1] 
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.1:yarn (yarn-test) on project ui-react: Failed to run task 
- show quoted text -
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task 
    at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:100) 
- show quoted text -
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'yarn test' failed. 
    at com.github.eirslett.maven.plugins.frontend.lib.YarnTaskExecutor.execute (YarnTaskExecutor.java:64) 
    at com.github.eirslett.maven.plugins.frontend.mojo.YarnMojo.execute (YarnMojo.java:65) 
    at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:94) 
- show quoted text -
Caused by: com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutionException: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) 
    at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.execute (ProcessExecutor.java:82) 
    at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.executeAndRedirectOutput (ProcessExecutor.java:64) 
    at com.github.eirslett.maven.plugins.frontend.lib.YarnExecutor.executeAndRedirectOutput (YarnExecutor.java:28) 
    at com.github.eirslett.maven.plugins.frontend.lib.YarnTaskExecutor.execute (YarnTaskExecutor.java:58) 
    at com.github.eirslett.maven.plugins.frontend.mojo.YarnMojo.execute (YarnMojo.java:65) 
    at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:94) 
- show quoted text -
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) 
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404) 
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166) 
    at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.execute (ProcessExecutor.java:74) 
    at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.executeAndRedirectOutput (ProcessExecutor.java:64) 
    at com.github.eirslett.maven.plugins.frontend.lib.YarnExecutor.executeAndRedirectOutput (YarnExecutor.java:28) 
    at com.github.eirslett.maven.plugins.frontend.lib.YarnTaskExecutor.execute (YarnTaskExecutor.java:58) 
    at com.github.eirslett.maven.plugins.frontend.mojo.YarnMojo.execute (YarnMojo.java:65) 
    at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:94) 
- show quoted text -

**Comment by KurtStam** [comment]
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] 
[INFO] lerna ERR! yarn run test --coverage --color --runInBand stderr:
[INFO]  FAIL  src/app/App.test.tsx
[INFO]   ● Test suite failed to run
[INFO] 
[INFO]     Cannot find module '/mnt/hudson_workspace/workspace/syndesis-release-daily/app/ui-react/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/interopRequireWildcard' from 'App.test.tsx'
[INFO] 
[INFO]       4 | import { MemoryRouter } from 'react-router';
[INFO]       5 | import { App } from './App';
[INFO]     > 6 | import i18n from '../i18n';
[INFO]         |                               ^
[INFO]       7 | 
[INFO]       8 | jest.unmock('./App');
[INFO]       9 | jest.mock('./WithConfig');
[INFO] 
[INFO]       at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:259:17)
[INFO]       at Object.<anonymous> (src/app/App.test.tsx:6:31)
[INFO] 
[INFO] Test Suites: 1 failed, 1 total
[INFO] Tests:       0 total
[INFO] Snapshots:   0 total
[INFO] Time:        8.553s
[INFO] Ran all test suites.
[INFO] error Command failed with exit code 1.
[INFO] 
[INFO] lerna ERR! yarn run test --coverage --color --runInBand exited 1 in '@syndesis/syndesis'
[INFO] error Command failed with exit code 1.
[INFO] ERROR: "test:jest" exited with 1.
[INFO] error Command failed with exit code 1.

**Comment by zregvart** [comment]
Fixed with #8156? Can you check on your end @KurtStam?

**Comment by gashcrumb** [comment]
New error:

![image](https://user-images.githubusercontent.com/351660/78028088-6e081480-732c-11ea-8693-242872b40236.png)

**Comment by KurtStam** [comment]
Unfortunately the error changed

12:15:03 [INFO] --------------------------------------------------------|----------|----------|----------|----------|-------------------|
12:15:03 [INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
12:15:03 [INFO] 
12:15:03 [INFO] lerna ERR! yarn run test --coverage --color --runInBand stderr:
12:15:03 [INFO]  FAIL  src/app/App.test.tsx
12:15:03 [INFO]   ● Test suite failed to run
12:15:03 [INFO] 
12:15:03 [INFO]     Cannot find module '/mnt/hudson_workspace/workspace/syndesis-release-daily/app/ui-react/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/interopRequireWildcard' from 'App.tsx'
12:15:03 [INFO] 
12:15:03 [INFO]     However, Jest was able to find:
12:15:03 [INFO]     	'./App.css'
12:15:03 [INFO]     	'./App.test.tsx'
12:15:03 [INFO]     	'./App.tsx'
12:15:03 [INFO] 
12:15:03 [INFO]     You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'].
12:15:03 [INFO] 
12:15:03 [INFO]     See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string
12:15:03 [INFO] 
12:15:03 [INFO] 
12:15:03 [INFO] 
12:15:03 [INFO]       at Resolver.resolveModule (../node_modules/jest-resolve/build/index.js:259:17)
12:15:03 [INFO]       at Object.<anonymous> (src/app/App.tsx:369:31)
12:15:03 [INFO]       at Object.<anonymous> (src/app/App.test.tsx:4:1)
12:15:03 [INFO] 
12:15:03 [INFO] Test Suites: 1 failed, 1 total
12:15:03 [INFO] Tests:       0 total
12:15:03 [INFO] Snapshots:   0 total
12:15:03 [INFO] Time:        10.323s
12:15:03 [INFO] Ran all test suites.
12:15:03 [INFO] error Command failed with exit code 1.
12:15:03 [INFO] 
12:15:03 [INFO] lerna ERR! yarn run test --coverage --color --runInBand exited 1 in '@syndesis/syndesis'
12:15:03 [INFO] error Command failed with exit code 1.
12:15:03 [INFO] ERROR: "test:jest" exited with 1.
12:15:03 [INFO] error Command failed with exit code 1.

**Comment by KurtStam** [comment]
and the path:

Cannot find module '/mnt/hudson_workspace/workspace/syndesis-release-daily/app/ui-react/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/interopRequireWildcard'

is indeed none existing on the build server
