### ISSUE TITLE
failed[integration-test]: TodoOpenApiV3_IT

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#8215]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

TodoOpenApiV3_IT is failing on master. Here is what I see in the logs when running the test locally:

```
07:15:38.496 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: io.syndesis.common.util.SyndesisConnectorException: SQL SELECT did not SELECT any records
07:15:38.496 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at io.syndesis.connector.sql.customizer.SqlConnectorCustomizer.doAfterProducer(SqlConnectorCustomizer.java:124) ~[connector-sql-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
07:15:38.497 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:67) ~[camel-support-3.1.0.jar:3.1.0]
07:15:38.497 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.processor.Pipeline$PipelineTask.run(Pipeline.java:90) ~[camel-base-3.1.0.jar:3.1.0]
07:15:38.503 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:153) [camel-base-3.1.0.jar:3.1.0]
07:15:38.503 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:60) [camel-base-3.1.0.jar:3.1.0]
07:15:38.503 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.processor.Pipeline.process(Pipeline.java:147) [camel-base-3.1.0.jar:3.1.0]
07:15:38.503 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:286) [camel-base-3.1.0.jar:3.1.0]
07:15:38.503 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:84) [camel-base-3.1.0.jar:3.1.0]
07:15:38.503 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:40) [camel-support-3.1.0.jar:3.1.0]
07:15:38.503 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.http.common.CamelServlet.doService(CamelServlet.java:214) [camel-http-common-3.1.0.jar:3.1.0]
07:15:38.503 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.http.common.CamelServlet.service(CamelServlet.java:80) [camel-http-common-3.1.0.jar:3.1.0]
07:15:38.503 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) [jakarta.servlet-api-4.0.3.jar:4.0.3]
```

and following from that:

```
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 2020-04-07 07:15:38.516 ERROR 39 --- [  XNIO-1 task-4] o.a.c.p.FatalFallbackErrorHandler        : \--> New exception on exchangeId: i-M4IUdhsdN6XC32grz8uz
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: java.lang.NullPointerException: null
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at io.syndesis.connector.support.processor.ErrorMapper.matchByException(ErrorMapper.java:82) ~[connector-support-processor-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at io.syndesis.connector.support.processor.ErrorMapper.mapError(ErrorMapper.java:62) ~[connector-support-processor-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at io.syndesis.connector.apiprovider.ApiProviderOnExceptionHandler.process(ApiProviderOnExceptionHandler.java:42) ~[connector-api-provider-2.0-SNAPSHOT.jar:2.0-SNAPSHOT]
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.support.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:64) ~[camel-support-3.1.0.jar:3.1.0]
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.support.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:93) ~[camel-support-3.1.0.jar:3.1.0]
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:286) [camel-base-3.1.0.jar:3.1.0]
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.processor.FatalFallbackErrorHandler.process(FatalFallbackErrorHandler.java:82) ~[camel-base-3.1.0.jar:3.1.0]
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.deliverToFailureProcessor(RedeliveryErrorHandler.java:1050) ~[camel-base-3.1.0.jar:3.1.0]
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:640) ~[camel-base-3.1.0.jar:3.1.0]
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:153) [camel-base-3.1.0.jar:3.1.0]
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:60) [camel-base-3.1.0.jar:3.1.0]
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.processor.Pipeline.process(Pipeline.java:147) [camel-base-3.1.0.jar:3.1.0]
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:286) [camel-base-3.1.0.jar:3.1.0]
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:84) [camel-base-3.1.0.jar:3.1.0]
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:40) [camel-support-3.1.0.jar:3.1.0]
07:15:38.505 [ream-1082378213] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.apache.camel.http.common.CamelServlet.doService(CamelServlet.java:214) [camel-http-common-3.1.0.jar:3.1.0]
```

**Comment by KurtStam** [comment]
I will take a look at this one

**Comment by christophd** [comment]
@KurtStam awesome, thanks!

**Comment by KurtStam** [comment]
The exception is pushed into a property now and exchange.getException() is null
