### ISSUE TITLE
failed[integration-test]: SendMail_IT

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#8216]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

SendMail_IT is failing on master with following error:

```
07:16:05.230 [cTaskExecutor-1] DEBUG Logger.Message_IN              - HTTP/1.1 500 INTERNAL_SERVER_ERROR Internal Server Error
Connection:keep-alive
Transfer-Encoding:chunked
Content-Type:text/plain;charset=ISO-8859-1
Date:Tue, 07 Apr 2020 07:16:05 GMT

io.atlasmap.api.AtlasException: Errors: [Cannot read a field '/mail' of JSON document '-LhL23Q971G_Hn4CaeFQ', document is null: docId='-LhL23Q971G_Hn4CaeFQ', path='/mail'], 
	at org.apache.camel.component.atlasmap.AtlasEndpoint.onExchange(AtlasEndpoint.java:262)
	at org.apache.camel.support.ProcessorEndpoint$1.process(ProcessorEndpoint.java:63)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:67)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:174)
	at org.apache.camel.support.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:93)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:396)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:153)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:60)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:147)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:84)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:40)
	at org.apache.camel.http.common.CamelServlet.doService(CamelServlet.java:214)
	at org.apache.camel.http.common.CamelServlet.service(CamelServlet.java:80)
```

**Comment by christophd** [comment]
Yesterday's nightly build had no errors for SendMail_IT! @Delawen is this one fixed?

**Comment by Delawen** [comment]
Yes! With the atlasmap update. Good :)
