### ISSUE TITLE
failed[integration-test]: TimerToLog_IT

### ISSUE THREAD

**Issue by christophd** [syndesisio/syndesis#8217]
## This is a...

<pre><code>
[ ] Feature request
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

TimerToLog_IT test fails on master with:

```
07:12:34.530 [ool-28-thread-1] ERROR ect.generator.ProjectGenerator - Exception while creating runtime build tar for deployment null : java.lang.NullPointerException
java.lang.NullPointerException: null
	at io.syndesis.common.util.Names.sanitize(Names.java:54)
	at io.syndesis.integration.project.generator.ProjectGenerator.lambda$generateAddProjectTarEntries$2(ProjectGenerator.java:306)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This leads to:

```
07:12:50.639 [tream-584677462] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.opentracing.contrib.spring.web.starter.ServerTracingAutoConfiguration': Unsatisfied dependency expressed through field 'skipPattern'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'skipPattern' defined in class path resource [io/opentracing/contrib/spring/web/starter/SkipPatternAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.regex.Pattern]: Factory method 'skipPattern' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'routeControllerEndpoint' defined in class path resource [org/apache/camel/spring/boot/actuate/endpoint/CamelRouteControllerEndpointAutoConfiguration.class]: Unsatisfied dependency expressed through method 'routeControllerEndpoint' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'camelContext' defined in class path resource [org/apache/camel/spring/boot/CamelAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.camel.CamelContext]: Factory method 'camelContext' threw exception; nested exception is java.lang.IllegalArgumentException: CamelContext name  must be specified and not empty
07:12:50.640 [tream-584677462] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
07:12:50.640 [tream-584677462] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) ~[spring-context-5.2.3.RELEASE.jar:5.2.3.RELEASE]
07:12:50.640 [tream-584677462] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
07:12:50.640 [tream-584677462] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
07:12:50.640 [tream-584677462] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
07:12:50.640 [tream-584677462] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
07:12:50.640 [tream-584677462] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
07:12:50.640 [tream-584677462] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
07:12:50.640 [tream-584677462] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at io.syndesis.example.Application.main(Application.java:13) [classes/:na]
07:12:50.640 [tream-584677462] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: Caused by: java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.opentracing.contrib.spring.web.starter.ServerTracingAutoConfiguration': Unsatisfied dependency expressed through field 'skipPattern'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'skipPattern' defined in class path resource [io/opentracing/contrib/spring/web/starter/SkipPatternAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.regex.Pattern]: Factory method 'skipPattern' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'routeControllerEndpoint' defined in class path resource [org/apache/camel/spring/boot/actuate/endpoint/CamelRouteControllerEndpointAutoConfiguration.class]: Unsatisfied dependency expressed through method 'routeControllerEndpoint' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'camelContext' defined in class path resource [org/apache/camel/spring/boot/CamelAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.camel.CamelContext]: Factory method 'camelContext' threw exception; nested exception is java.lang.IllegalArgumentException: CamelContext name  must be specified and not empty
07:12:50.640 [tream-584677462] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:254) ~[undertow-servlet-2.0.29.Final.jar:2.0.29.Final]
07:12:50.640 [tream-584677462] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.createDeploymentManager(UndertowServletWebServerFactory.java:292) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
07:12:50.640 [tream-584677462] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.getWebServer(UndertowServletWebServerFactory.java:218) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
07:12:50.641 [tream-584677462] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
07:12:50.641 [tream-584677462] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153) ~[spring-boot-2.2.4.RELEASE.jar:2.2.4.RELEASE]
07:12:50.641 [tream-584677462] INFO  INTEGRATION_RUNTIME_CONTAINER  - STDOUT: 	... 8 common frames omitted
```

**Comment by christophd** [comment]
@Delawen I saw you working on this one. Is it fixed already?

**Comment by Delawen** [comment]
I think so, I don't have errors anymore. But I don't remember having that null pointer.

**Comment by christophd** [comment]
@Delawen yeah I think the errors mentioned here have been follow up errors and got fixed with what you have done on the quartz dependency.

The last nightly build also did not report any failures on this one anymore so I think we can close.
