### ISSUE TITLE
Fix flaky MongoDB

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#8244]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

As seen [on build](https://circleci.com/gh/syndesisio/syndesis/296643) for a change unrelated to mongodb.

```
java.lang.AssertionError: mock://result Received message count. Expected: <1> but was: <2>
	at io.syndesis.connector.mongo.MongoDBConnectorCappedCollectionConsumerTest.mongoTest(MongoDBConnectorCappedCollectionConsumerTest.java:88)
	at io.syndesis.connector.mongo.MongoDBConnectorCappedCollectionConsumerTest.repeatedMongoTest(MongoDBConnectorCappedCollectionConsumerTest.java:98)
```

**Comment by KurtStam** [comment]
Sounds like this? https://github.com/syndesisio/syndesis/issues/8149

**Comment by zregvart** [comment]
Guess it wasn't fixed.
