### ISSUE TITLE
[REST Swagger] Verification process missing

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#8609]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
While working on #7466 I realized the validation process for Swagger connections is missing producing the following error on `meta`:
```
2020-06-01 08:29:36.342  WARN 1 --- [  XNIO-1 task-1] i.s.connector.meta.v1.VerifierEndpoint   : No factory finder of type: io.syndesis.connector.support.verifier.api.Verifier for id: i-M8PdK9xYED-7ijVaUwYz
org.apache.camel.RuntimeCamelException: java.lang.NullPointerException
	at org.apache.camel.support.ObjectHelper.newInstance(ObjectHelper.java:224) ~[camel-support-3.1.0.jar!/:3.1.0]
...
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.lang.NullPointerException: null
	at org.apache.camel.support.ObjectHelper.newInstance(ObjectHelper.java:222) ~[camel-support-3.1.0.jar!/:3.1.0]
	... 86 common frames omitted
```

**Comment by dhirajsb** [comment]
It should pass along the `connectorGroupId`for verification. Soap client connectors also need this feature.

**Comment by squakez** [comment]
Thanks @dhirajsb. I see this parameter is belonging to `ConnectorTemplate` and it is different that `Connector.id`. I wasn't either able to find a way to relate the `ConnectorTemplate` to `Connector`, so, unless there is already a way to do it, we must correlate the 2 entities.
