### ISSUE TITLE
[Camel K] BodyLogger not found when using log step

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#8845]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Using a `log` step with body is resulting in a failure due to:
```
2020-07-27 08:22:50.468 [32mINFO [m [main] AbstractCamelContext - Apache Camel 3.3.0 (CamelContext: camel-k) started in 0.234 seconds
{"exchange":"ID-i-dsadsaasd-fcf78dc68-cdvrh-1595838170456-0-2","status":"begin"}
2020-07-27 08:22:51.522 [32mINFO [m [Camel (camel-k) thread #2 - timer://syndesis-timer] -MDEMQfi9l-t18oW3RA6 - Body: [] 
2020-07-27 08:22:51.526 [1;31mERROR[m [Camel (camel-k) thread #2 - timer://syndesis-timer] DefaultErrorHandler - Failed delivery for (MessageId: ID-i-dsadsaasd-fcf78dc68-cdvrh-1595838170456-0-2 on ExchangeId: ID-i-dsadsaasd-fcf78dc68-cdvrh-1595838170456-0-2). Exhausted after delivery attempt: 1 caught: org.apache.camel.NoSuchBeanException: No bean could be found in the registry for: bodyLogger

Message History (complete message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[-MDEMQfi9l-t18oW3R] [-MDEMQfi9l-t18oW3R] [from[timer://syndesis-timer?period=60000]                                     ] [        61]
	...
[-MDEMQfi9l-t18oW3R] [log1              ] [log                                                                           ] [         0]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
org.apache.camel.NoSuchBeanException: No bean could be found in the registry for: bodyLogger
	at org.apache.camel.component.bean.RegistryBean.getBean(RegistryBean.java:92) ~[org.apache.camel.camel-bean-3.3.0.jar:3.3.0]
	at org.apache.camel.component.bean.AbstractBeanProcessor.process(AbstractBeanProcessor.java:76) ~[org.apache.camel.camel-bean-3.3.0.jar:3.3.0]
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:83) ~[org.apache.camel.camel-base-3.3.0.jar:3.3.0]
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:40) ~[org.apache.camel.camel-support-3.3.0.jar:3.3.0]
	at org.apache.camel.language.bean.BeanExpression.invokeBean(BeanExpression.java:327) ~[org.apache.camel.camel-bean-3.3.0.jar:3.3.0]
	at org.apache.camel.language.bean.BeanExpression.evaluate(BeanExpression.java:174) ~[org.apache.camel.camel-bean-3.3.0.jar:3.3.0]
	at org.apache.camel.language.bean.BeanExpression.evaluate(BeanExpression.java:186) ~[org.apache.camel.camel-bean-3.3.0.jar:3.3.0]
	at org.apache.camel.support.builder.ExpressionBuilder$55.evaluate(ExpressionBuilder.java:1522) ~[org.apache.camel.camel-support-3.3.0.jar:3.3.0]
	at org.apache.camel.support.ExpressionAdapter.evaluate(ExpressionAdapter.java:36) ~[org.apache.camel.camel-support-3.3.0.jar:3.3.0]
	at org.apache.camel.support.builder.ExpressionBuilder$50.evaluate(ExpressionBuilder.java:1417) ~[org.apache.camel.camel-support-3.3.0.jar:3.3.0]
	at org.apache.camel.support.ExpressionAdapter.evaluate(ExpressionAdapter.java:36) ~[org.apache.camel.camel-support-3.3.0.jar:3.3.0]
	at org.apache.camel.processor.LogProcessor.process(LogProcessor.java:59) ~[org.apache.camel.camel-base-3.3.0.jar:3.3.0]
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:395) [org.apache.camel.camel-base-3.3.0.jar:3.3.0]
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:148) [org.apache.camel.camel-base-3.3.0.jar:3.3.0]
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:60) [org.apache.camel.camel-base-3.3.0.jar:3.3.0]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:147) [org.apache.camel.camel-base-3.3.0.jar:3.3.0]
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:198) [org.apache.camel.camel-timer-3.3.0.jar:3.3.0]
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:78) [org.apache.camel.camel-timer-3.3.0.jar:3.3.0]
	at java.util.TimerThread.mainLoop(Timer.java:556) [?:?]
	at java.util.TimerThread.run(Timer.java:506) [?:?]
{"exchange":"ID-i-dsadsaasd-fcf78dc68-cdvrh-1595838170456-0-2","status":"done","failed":true}
```
Apparently there is some failure in the way the registry is managed since Camel 3.3/CamelK runtime 1.3.0.

**Comment by squakez** [comment]
It is missing the proper tracing initialization at integration startup:
```
2020-07-27 09:43:10.615 [32mINFO [m [main] IntegrationRouteLoader - Loading tracer from Camel RuntimeRegistry.
2020-07-27 09:43:10.616 [32mINFO [m [main] IntegrationRouteLoader - No tracer found
```

**Comment by squakez** [comment]
Fixed by applying proper server-config values:
```
controllers:
  integration: camel-k
  camelk:
    customizers:
    - metadata
    - logging
    - syndesis
```
