### ISSUE TITLE
[Camel K] Servlet based connectors integration failure

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#8850]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description
Missing dependencies when building an integration with certain connectors.

### Webhook to log
```
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.apache.camel.k:camel-k-runtime-servlet:jar is missing. @ line 53, column 17
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.apache.camel.k.integration:camel-k-integration:1.0.1 (/tmp/builder-012444453/maven/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.apache.camel.k:camel-k-runtime-servlet:jar is missing. @ line 53, column 17
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
{"level":"info","ts":1595842104.5530808,"logger":"camel-k.builder","msg":"step failed with error: failure while determining classpath: exit status 1","step":"github.com/apache/camel-k/pkg/builder/runtime/ComputeDependencies","phase":20,"name":"kit-bsf9s8a02f2i8o4v5vfg","task":"builder"}
{"level":"info","ts":1595842104.5531127,"logger":"camel-k.builder","msg":"dependencies: [bom:io.syndesis.integration/integration-bom-camel-k/pom/2.0-SNAPSHOT mvn:io.prometheus.jmx/jmx_prometheus_javaagent:0.3.1 mvn:io.syndesis.connector/connector-webhook mvn:io.syndesis.integration/integration-runtime-camelk mvn:org.apache.camel.k/camel-k-runtime-main mvn:org.apache.camel.k/camel-k-runtime-servlet mvn:org.apache.camel/camel-base64 mvn:org.apache.camel/camel-management mvn:org.jolokia/jolokia-jvm:jar:agent:1.6.2]"}
```

**Comment by squakez** [comment]
May be fixed via #8884

**Comment by squakez** [comment]
The dependency issue seems fixed by #8884, but a new error is thrown:
```
2020-08-10 08:51:52.946 [32mINFO [m [main] LRUCacheFactory - Detected and using LRUCacheFactory: camel-caffeine-lrucache
2020-08-10 08:51:53.141 [32mINFO [m [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.ContextConfigurer@1522d8a0
2020-08-10 08:51:53.143 [32mINFO [m [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.RoutesConfigurer@3381b4fc
2020-08-10 08:51:53.143 [32mINFO [m [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.PropertiesConfigurer@aeab9a1
2020-08-10 08:51:53.162 [32mINFO [m [main] ApplicationRuntime - Listener org.apache.camel.k.listener.PropertiesConfigurer@aeab9a1 executed in phase ConfigureProperties
2020-08-10 08:51:53.169 [32mINFO [m [main] RuntimeSupport - Looking up loader for language: syndesis
2020-08-10 08:51:53.172 [32mINFO [m [main] RuntimeSupport - Found loader io.syndesis.integration.runtime.camelk.IntegrationRouteLoader@a776e for language syndesis from service definition
2020-08-10 08:51:53.172 [32mINFO [m [main] IntegrationRouteLoader - Loading ActivityTracker from Camel RuntimeRegistry.
2020-08-10 08:51:53.173 [32mINFO [m [main] IntegrationRouteLoader - ActivityTracker not provided or not found in Camel RuntimeRegistry, using new instance of ActivityTracker.SysOut() .
2020-08-10 08:51:53.173 [32mINFO [m [main] IntegrationRouteLoader - Loading IntegrationStepHandlers with ServiceLoader.
2020-08-10 08:51:53.366 [32mINFO [m [main] IntegrationRouteLoader - 13 IntegrationStepHandlers loaded.
2020-08-10 08:51:53.366 [32mINFO [m [main] IntegrationRouteLoader - Loading tracer from Camel RuntimeRegistry.
2020-08-10 08:51:53.366 [32mINFO [m [main] IntegrationRouteLoader - No tracer found.
2020-08-10 08:51:53.381 [32mINFO [m [main] RoutesConfigurer - Loading routes from: file:/etc/camel/sources/i-source-000/i-memy6xcdxdyq9mhuuk4z?language=syndesis
2020-08-10 08:51:53.381 [32mINFO [m [main] ApplicationRuntime - Listener org.apache.camel.k.listener.RoutesConfigurer@3381b4fc executed in phase ConfigureRoutes
Exception in thread "main" org.apache.camel.PropertyBindingException: Error binding property (camel.rest.endpointProperty.headerFilterStrategy=syndesisHeaderStrategy) with name: endpointProperty.headerFilterStrategy on bean: org.apache.camel.spi.RestConfiguration@1a15b789 with value: syndesisHeaderStrategy
	at org.apache.camel.main.BaseMainSupport.setPropertiesOnTarget(BaseMainSupport.java:182)
	at org.apache.camel.main.BaseMainSupport.doConfigureCamelContextFromMainConfiguration(BaseMainSupport.java:787)
	at org.apache.camel.main.BaseMainSupport.autoconfigure(BaseMainSupport.java:507)
	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:570)
	at org.apache.camel.main.BaseMainSupport.initCamelContext(BaseMainSupport.java:379)
	at org.apache.camel.k.main.ApplicationRuntime$MainAdapter.doInit(ApplicationRuntime.java:197)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
	at org.apache.camel.main.MainSupport.run(MainSupport.java:79)
	at org.apache.camel.k.main.ApplicationRuntime.run(ApplicationRuntime.java:70)
	at org.apache.camel.k.main.Application.main(Application.java:42)
```

**Comment by squakez** [comment]
The error is apparently caused by the fact that when the `ApplicationRuntime` tries to bind `syndesisHeaderStrategy`, this is not yet present in the registry.

**Comment by squakez** [comment]
Should be fixed by 248e26818ac81e63d13b35633668873eca084bef

**Comment by squakez** [comment]
Now a new error is thrown:
```
Exception in thread "main" java.lang.RuntimeException: Error creating instance for customizer: health
```

**Comment by squakez** [comment]
Solved the health customized error by setting proper configuration. The problem is however the fact that camel k runtime is not providing a servlet engine out of the box. In order to fix this we either have to provide a servlet engine to the integration, or rewrite the connectors using a servlet to use `platform-http` which is the choice preferred in camel k runtime.
