### ISSUE TITLE
DB connector: SQL invoke with named parameter throws exception

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis#910]
For the following integration
```
---
flows:
- steps:
  - kind: endpoint
    uri: sql-start-connector-1
    properties:
      query: SELECT * FROM CONTACT
      schedulerPeriod: "5000"
  - kind: endpoint
    uri: atlas:mapping-step-2.json
  - kind: endpoint
    uri: sql-connector-3
    properties:
      query: INSERT INTO TODO (task) VALUES (:#task)
```

```
2018-01-04 09:57:26.218 ERROR 1 --- [ector-component] o.a.camel.processor.DefaultErrorHandler  : Failed delivery for (MessageId: ID-crud1-read-update-e2e-6-v6zhg-1515059641988-0-164 on ExchangeId: ID-crud1-read-update-e2e-6-v6zhg-1515059641988-0-163). Exhausted after delivery attempt: 1 caught: org.apache.camel.RuntimeExchangeException: Cannot find key [task] in message body or headers to use when setting named parameter in query [INSERT INTO TODO (task) VALUES (:?task)] on the exchange: Exchange[ID-crud1-read-update-e2e-6-v6zhg-1515059641988-0-163]

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[flow1             ] [flow1             ] [timer://sql-sql-start-connector-component?period=5000                         ] [        11]
[flow1             ] [to1               ] [atlas:mapping-step-2.json                                                     ] [         1]
[flow1             ] [to2               ] [sql-connector-3?query=INSERT+INTO+TODO+%28task%29+VALUES+%28%3A%23task%29     ] [         9]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------

org.apache.camel.RuntimeExchangeException: Cannot find key [task] in message body or headers to use when setting named parameter in query [INSERT INTO TODO (task) VALUES (:?task)] on the exchange: Exchange[ID-crud1-read-update-e2e-6-v6zhg-1515059641988-0-163]
	at org.apache.camel.component.sql.DefaultSqlPrepareStatementStrategy$PopulateIterator.next(DefaultSqlPrepareStatementStrategy.java:280) ~[camel-sql-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.sql.DefaultSqlPrepareStatementStrategy.populateStatement(DefaultSqlPrepareStatementStrategy.java:130) ~[camel-sql-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.sql.SqlProducer$2.doInPreparedStatement(SqlProducer.java:146) ~[camel-sql-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.sql.SqlProducer$2.doInPreparedStatement(SqlProducer.java:116) ~[camel-sql-2.20.1.jar!/:2.20.1]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633) ~[spring-jdbc-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.apache.camel.component.sql.SqlProducer.process(SqlProducer.java:116) ~[camel-sql-2.20.1.jar!/:2.20.1]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.connector.ConnectorProducer.process(ConnectorProducer.java:45) ~[camel-connector-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:148) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548) ~[camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:701) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:624) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:248) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Splitter.process(Splitter.java:114) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:138) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:101) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:197) [camel-core-2.20.1.jar!/:2.20.1]
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:79) [camel-core-2.20.1.jar!/:2.20.1]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_141]
	at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_141]

2018-01-04 09:57:26.219
```

**Comment by KurtStam** [comment]
@dsimansk Can you add a screenshot of the data mapping?

**Comment by KurtStam** [comment]
OK the workaround is to use capitals for INSERT INTO TODO (TASK) VALUES (:#TASK). Will work on a fix.

**Comment by KurtStam** [comment]
Fixed.
