### ISSUE TITLE
Build fails on S2I module

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis#932]
This worked fine a few days ago not sure what happened, but running:

```
 ./tools/bin/syndesis build --flash
```

yeilds a failure in the S2I module:

```
[INFO] --- exec-maven-plugin:1.2.1:exec (syndesis-builder-image-generator) @ s2i ---

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.8.RELEASE)

Jan 05, 2018 9:58:41 AM org.springframework.boot.StartupInfoLogger logStarting
INFO: Starting Application v1.2-SNAPSHOT on kolossus.gashcrumb.homelinux.org with PID 20043 (/home/gashcrumb/Source/syn
desis/app/s2i/target/syndesis-builder-image-generator.jar started by gashcrumb in /home/gashcrumb/Source/syndesis/app/s
2i)
Jan 05, 2018 9:58:41 AM org.springframework.boot.SpringApplication logStartupProfileInfo
INFO: No active profile set, falling back to default profiles: default
Jan 05, 2018 9:58:41 AM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@75828a0f: startup date [Fri
Jan 05 09:58:41 EST 2018]; root of context hierarchy
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jan 05, 2018 9:58:42 AM org.springframework.jmx.export.MBeanExporter afterSingletonsInstantiated
INFO: Registering beans for JMX exposure on startup
To: /home/gashcrumb/Source/syndesis/app/s2i/target/generated-sources/docker/m2/project
Jan 05, 2018 9:58:42 AM org.springframework.boot.autoconfigure.logging.AutoConfigurationReportLoggingInitializer logAut
oConfigurationReport
INFO:

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enable
d.
Jan 05, 2018 9:58:42 AM org.springframework.boot.SpringApplication reportFailure
SEVERE: Application startup failed
java.lang.NoSuchMethodError: io.syndesis.model.connection.Connection$Builder.build()Lio/syndesis/model/connection/Immut
ableConnection;
        at io.syndesis.image.Application.generateIntegrationProject(Application.java:105)
        at io.syndesis.image.Application.run(Application.java:77)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:723)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:713)
        at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
        at io.syndesis.image.Application.main(Application.java:69)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

Jan 05, 2018 9:58:42 AM org.springframework.context.support.AbstractApplicationContext doClose
INFO: Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@75828a0f: startup date [Fri Jan
 05 09:58:41 EST 2018]; root of context hierarchy
Jan 05, 2018 9:58:42 AM org.springframework.jmx.export.MBeanExporter destroy
INFO: Unregistering JMX-exposed beans on shutdown
```

**Comment by gashcrumb** [comment]
@seanforyou23 FYI assuming you're also still hitting this...

**Comment by gashcrumb** [comment]
@jimmidyson any ideas?

**Comment by jimmidyson** [comment]
I hit a different error:

```
Error extracting plugin descriptor: 'Goal: help already exists in the plugin descriptor for prefix: syndesis-build-helper
[ERROR] Existing implementation is: io.syndesis.maven.HelpMojo
[ERROR] Conflicting implementation is: HelpMojo'
```

**Comment by zregvart** [comment]
@gashcrumb are you sure that you don't have the IDE compiling in parallel with the Maven build from CLI?

**Comment by oscerd** [comment]
I hit the same issue.

**Comment by zregvart** [comment]
Actually me to 😕. Seems that adding `-c` (for clean build) on syndesis CLI (full command `syndesis build --images --docker -f -c`) helped on my end.

**Comment by oscerd** [comment]
For the moment, maybe we can force the -c to be always set

**Comment by gashcrumb** [comment]
Stale
