### ISSUE TITLE
FHIR connector test failures

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis#9504]
## This is a...

<pre><code>
[ ] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Documentation issue or request
</code></pre>

## Description

```
[INFO] Running io.syndesis.connector.fhir.FhirPatchWithBodyTest
Error:  Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.388 s <<< FAILURE! - in io.syndesis.connector.fhir.FhirPatchWithBodyTest
Error:  io.syndesis.connector.fhir.FhirPatchWithBodyTest.shouldPatchWithBodyTest  Time elapsed: 0.163 s  <<< ERROR!
org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[ID-fv-az209-794-1618574321447-18-1]
	at io.syndesis.connector.fhir.FhirPatchWithBodyTest.shouldPatchWithBodyTest(FhirPatchWithBodyTest.java:46)
Caused by: org.apache.camel.RuntimeCamelException: 
Error invoking patchById with {stringId=Patient/1, patchBody=[{"op":"replace","path":"active","value":true}], extraParameters={}, preferReturn=null}: HTTP 404 Not Found: 
                                               Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
PATCH                                                      | PATCH
/Patient/1?_format=xml                                     | /Patient/1                                          <<<<< URL does not match
                                                           |
                                                           |
-----------------------------------------------------------------------------------------------------------------------

Caused by: ca.uhn.fhir.rest.server.exceptions.ResourceNotFoundException: 
HTTP 404 Not Found: 
                                               Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
PATCH                                                      | PATCH
/Patient/1?_format=xml                                     | /Patient/1                                          <<<<< URL does not match
                                                           |
                                                           |
-----------------------------------------------------------------------------------------------------------------------


Error:  io.syndesis.connector.fhir.FhirPatchWithBodyTest.shouldPatchWithBodyWithoutOpTest  Time elapsed: 0.212 s  <<< ERROR!
org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[ID-fv-az209-794-1618574321447-19-1]
	at io.syndesis.connector.fhir.FhirPatchWithBodyTest.shouldPatchWithBodyWithoutOpTest(FhirPatchWithBodyTest.java:54)
Caused by: org.apache.camel.RuntimeCamelException: 
Error invoking patchById with {stringId=Patient/1, patchBody=[{"path":"active","value":true,"op":"replace"}], extraParameters={}, preferReturn=null}: HTTP 404 Not Found: 
                                               Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
PATCH                                                      | PATCH
/Patient/1?_format=xml                                     | /Patient/1                                          <<<<< URL does not match
                                                           |
                                                           |
-----------------------------------------------------------------------------------------------------------------------

Caused by: ca.uhn.fhir.rest.server.exceptions.ResourceNotFoundException: 
HTTP 404 Not Found: 
                                               Request was not matched
                                               =======================

-----------------------------------------------------------------------------------------------------------------------
| Closest stub                                             | Request                                                  |
-----------------------------------------------------------------------------------------------------------------------
                                                           |
PATCH                                                      | PATCH
/Patient/1?_format=xml                                     | /Patient/1                                          <<<<< URL does not match
                                                           |
                                                           |
-----------------------------------------------------------------------------------------------------------------------
```

cc @rkorytkowski

**Comment by zregvart** [comment]
Resolved via #9524
